In [1]:
import json
import pandas as pd
import glob
import numpy as np
import driver
from tqdm.notebook import tqdm

## Initial Files

In [2]:
# query_df = pd.DataFrame()
# # query_actions_df = pd.DataFrame() 
# query_corrections_df = pd.DataFrame()
# serp_df = pd.DataFrame()
# clicked_results_df = pd.DataFrame()
# viewed_results_df = pd.DataFrame()
# explored_pages_df = pd.DataFrame()
# part_answer_df = pd.DataFrame()
final_answer_df = pd.DataFrame()

for file_name in tqdm(glob.glob("Data/3rd/*_FULL.log"), total=len(glob.glob("Data/3rd/*_FULL.log"))):
    # print(file_name)
    with open(file_name, 'r') as f:
        result = [json.loads(x) for x in f.readlines()]
    
    # # queries
    # query_temp_df = driver.get_queries(result)
    # query_df = pd.concat([query_df, query_temp_df], ignore_index=True)

    # # # query actions
    # # query_actions_temp_df = driver.get_query_actions(result)
    # # query_actions_df = pd.concat([query_actions_df, query_actions_temp_df], ignore_index=True)

    # # query corrections
    # query_corrections_temp_df = driver.get_query_corrections(result)
    # query_corrections_df = pd.concat([query_corrections_df, query_corrections_temp_df], ignore_index=True)

    # # SERPs generated
    # serp_temp_df = driver.get_generated_serps(result)
    # serp_df = pd.concat([serp_df, serp_temp_df], ignore_index=True)

    # # Clicked results
    # clicked_results_temp_df = driver.get_clicked_results(result)
    # clicked_results_df = pd.concat([clicked_results_df, clicked_results_temp_df], ignore_index=True)

    # # Explored pages
    # explored_pages_temp_df = driver.get_explored_web_pages(result)
    # explored_pages_df = pd.concat([explored_pages_df, explored_pages_temp_df], ignore_index=True)

    # # Viewed results
    # viewed_results_temp_df = driver.get_viewed_results(result) 
    # viewed_results_df = pd.concat([viewed_results_df, viewed_results_temp_df], ignore_index=True)

    # # Part answers
    # part_answer_temp_df = driver.get_partial_answers(result)
    # part_answer_df = pd.concat([part_answer_temp_df, part_answer_df])

    # final answers
    final_answer_temp_df = driver.get_final_answers(result)
    final_answer_df = pd.concat([final_answer_df, final_answer_temp_df], ignore_index=True)

for file_name in tqdm(glob.glob("Data/4th/*_FULL.log"), total=(len(glob.glob("Data/4th/*_FULL.log")))):
    # print(file_name)
    with open(file_name, 'r') as f:
        result = [json.loads(x) for x in f.readlines()]
    
    # # queries
    # query_temp_df = driver.get_queries(result)
    # query_df = pd.concat([query_df, query_temp_df], ignore_index=True)

    # # # query actions
    # # query_actions_temp_df = driver.get_query_actions(result)
    # # query_actions_df = pd.concat([query_actions_df, query_actions_temp_df], ignore_index=True)

    # # query corrections
    # query_corrections_temp_df = driver.get_query_corrections(result)
    # query_corrections_df = pd.concat([query_corrections_df, query_corrections_temp_df], ignore_index=True)

    # # SERPs generated
    # serp_temp_df = driver.get_generated_serps(result)
    # serp_df = pd.concat([serp_df, serp_temp_df], ignore_index=True)

    # # Clicked results
    # clicked_results_temp_df = driver.get_clicked_results(result)
    # clicked_results_df = pd.concat([clicked_results_df, clicked_results_temp_df], ignore_index=True)

    # # Explored pages
    # explored_pages_temp_df = driver.get_explored_web_pages(result)
    # explored_pages_df = pd.concat([explored_pages_df, explored_pages_temp_df], ignore_index=True)

    # # Viewed results
    # viewed_results_temp_df = driver.get_viewed_results(result) 
    # viewed_results_df = pd.concat([viewed_results_df, viewed_results_temp_df], ignore_index=True)

    # # Part answers
    # part_answer_temp_df = driver.get_partial_answers(result)
    # part_answer_df = pd.concat([part_answer_temp_df, part_answer_df])

    # final answers
    final_answer_temp_df = driver.get_final_answers(result)
    final_answer_df = pd.concat([final_answer_df, final_answer_temp_df], ignore_index=True)

# reordering all dataframes uid, topic_number, and timestamp
# query_df = query_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
# # query_actions_df = query_actions_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
# query_corrections_df = query_corrections_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
# serp_df = serp_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
# clicked_results_df = clicked_results_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
# explored_pages_df = explored_pages_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
# viewed_results_df = viewed_results_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
# part_answer_df = part_answer_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
final_answer_df = final_answer_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)


# ## assigning qid
# query_df["qid"] = ["q"+str(i) for i in range(1, len(query_df)+1)]
# query_df = query_df[["uid", "topic_number", "qid", "query", "source", "timestamp"]]

# ## assigning serp id
# serp_num = 0
# serp_id_list = []

# for _, row in serp_df.iterrows():
#     if row["rank"]==1 or pd.isna(row["rank"]):
#         serp_num += 1
#     serp_id_list.append("serp"+str(serp_num))

# serp_df["serp_id"] = serp_id_list
# serp_df = serp_df[["uid", "topic_number", "query", "serp_id", "url", "title", "snippet", "rank", "timestamp"]]

# ## removing duplicates
# final_answer_df = final_answer_df.drop_duplicates(ignore_index=True)

# # saving initial files
# query_df.to_csv("Data/query_df.csv", index=False, econding="utf8")
# query_corrections_df.to_csv("Data/query_corrections.csv", index=False, encoding="utf8")

# serp_df.to_csv("Data/logs_compiled.csv", index=False, encoding="utf8")
# clicked_results_df.to_csv("Data/clicked_results_df.csv", index=False, encoding="utf8")
# viewed_results_df.to_csv("Data/viewed_results_df.csv", index=False, encoding="utf8")
# explored_pages_df.to_csv("Data/explored_pages_df.csv", index=False, encoding="utf8")

# part_answer_df.to_csv("Data/part_answers_df.csv", index=False, encoding="utf8")
final_answer_df.to_csv("Data/final_answer_df.csv", index=False, encoding="utf8")

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

## query formulation

In [ ]:
import pandas as pd

query_df = pd.read_csv("Data/query_df.csv")
serp_df = pd.read_csv("Data/logs_compiled.csv")

query_df.head()

,uid,topic_number,qid,query,source,timestamp
0,1,g3t3,q1,Quali sono i cinque animali tipici dell india,UserFormulated,2026-05-19 14:51:26.583
1,1,g3t2,q2,Quale è il nome del simbolo al centro della ba...,UserFormulated,2026-05-19 15:02:41.120
2,1,g3t1,q3,Fiume sacro degli indiani,UserFormulated,2026-05-19 15:08:39.525
3,2,g3t3,q4,Quali sono i animali dall'India,UserFormulated,2026-05-19 14:50:22.081
4,2,g3t3,q5,Quali sono i 5 animali tipici dall'India,UserFormulated,2026-05-19 14:51:20.189

In [ ]:
len(query_df)

118

In [ ]:
serp_df.head()

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
0,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:51:27.687
1,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,2026-05-19 14:51:27.688
2,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.storicang.it/a/civilta-dellindo-i-...,"La civiltà dell'Indo, i misteri di un popolo d...","\n Jun 5, 2023 ... Sono note cinque m...",3.0,2026-05-19 14:51:27.689
3,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... Chi sono, da dove ...",4.0,2026-05-19 14:51:27.690
4,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/comportamento/feste...,Festa della mamma: come si festeggia nel resto...,\n Il dolce tipico per celebrare ques...,5.0,2026-05-19 14:51:27.691

In [ ]:
temp_df = serp_df.loc[(serp_df["rank"]==1) | (pd.isna(serp_df["rank"]))] # get one result (either rank 1 or None) of each generated serp
len(temp_df)

118

In [ ]:
associated_query_ids = []

for _, row in temp_df.iterrows():
    associated_query = query_df.loc[
        (query_df["uid"]==row["uid"]) 
        & (query_df["topic_number"]==row["topic_number"]) 
        & (query_df["query"]==row["query"]) 
        & (query_df["timestamp"]<row["timestamp"])
    ]

    if len(associated_query) == 0:
        print("No query found for serp id: ", row["serp_id"], "; uid: ", row["uid"], "; query: ", row["query"], "; time: ", row["timestamp"])
        # associated_query = query_df.loc[
        #     (query_df["uid"]==row["uid"]) 
        #     & (query_df["topic_number"]==row["topic_number"]) 
        #     # & (query_df["query"]==row["query"]) 
        #     & (query_df["timestamp"]<row["timestamp"])
        # ]
        # print("Matching based on uid and topic number (w/o query match) led to ", len(associated_query), " matches.\n")
        associated_query_ids.append(None)

    elif len(associated_query) > 1:
        # print("multiple queries found: ", row["serp_id"], row["uid"], row["timestamp"])
        time_diff = np.inf
        for _, query in associated_query.iterrows():
            # print(query)
            time_diff_compute = row["timestamp"] - query["timestamp"]
            if time_diff >= time_diff_compute.total_seconds():
                correct_query = query
                time_diff = time_diff_compute.total_seconds()
        # print("query chosen for ", row["serp_id"], "query: ", query["query"], "; timestamp: ", query["timestamp"])
        associated_query_ids.append(correct_query["qid"])
    else:
        associated_query_ids.append(associated_query["qid"].values[0])

temp_df["qid"] = associated_query_ids

C:\Users\hrishitachakra\AppData\Local\Temp\ipykernel_5828\1166631844.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df["qid"] = associated_query_ids

In [ ]:
temp_df.loc[temp_df["uid"]==8]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,qid
308,8,g3t3,Quali sono i,serp43,https://www.focusjunior.it/scienza/ambiente/vu...,"Quali sono i vulcani attivi in Italia? I ""magn...",\n In Italia esistono almeno 10 vulca...,1.0,2026-05-19 14:49:49.307,q43
318,8,g3t3,Quali sono 5 animali dell India,serp44,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:51:12.191,q44
328,8,g3t3,Quali sono 5 animali dell India,serp45,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:53:54.964,q45
338,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp46,None,None,None,NaN,2026-05-19 15:04:52.511,q46
339,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp47,None,None,None,NaN,2026-05-19 15:05:05.152,q47
340,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp48,None,None,None,NaN,2026-05-19 15:08:36.757,q48
341,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp49,None,None,None,NaN,2026-05-19 15:09:48.390,q49
342,8,g3t2,centro bandiera india simbolo,serp50,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 15:11:41.365,q50
352,8,g3t2,Bandira india simbolo,serp51,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 15:14:07.992,q51
362,8,g3t1,Fiume sacro India,serp52,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Secondo gli indù questo fiume è sa...,1.0,2026-05-19 15:16:03.549,q52
372,8,g3t1,Fiume sacro India,serp53,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Secondo gli indù questo fiume è sa...,1.0,2026-05-19 15:16:18.583,q53

In [ ]:
query_df["serp_id"] = [temp_df.loc[temp_df["qid"]==qid]["serp_id"].values[0] for qid in query_df["qid"]]
query_df = query_df[["uid", "topic_number", "qid", "query", "source", "serp_id", "timestamp"]]
query_df.to_csv("Data/query_df.csv", index=False, encoding='utf8')

In [ ]:
query_df.head()

,uid,topic_number,qid,query,source,serp_id,timestamp
0,1,g3t3,q1,Quali sono i cinque animali tipici dell india,UserFormulated,serp1,2026-05-19 14:51:26.583
1,1,g3t2,q2,Quale è il nome del simbolo al centro della ba...,UserFormulated,serp2,2026-05-19 15:02:41.120
2,1,g3t1,q3,Fiume sacro degli indiani,UserFormulated,serp3,2026-05-19 15:08:39.525
3,2,g3t3,q4,Quali sono i animali dall'India,UserFormulated,serp4,2026-05-19 14:50:22.081
4,2,g3t3,q5,Quali sono i 5 animali tipici dall'India,UserFormulated,serp5,2026-05-19 14:51:20.189

In [ ]:
serp_df.loc[serp_df["rank"].isna()]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
165,5,g3t1,come si chiama il fiume sacro agli indianischen,serp20,None,None,None,NaN,2026-05-19 14:52:35.518
166,5,g3t1,come si chiama il fiume sacro agli indianischen,serp21,None,None,None,NaN,2026-05-19 14:52:46.904
181,5,g3t3,Qali sono 5 animali tipici dell india,serp24,None,None,None,NaN,2026-05-19 15:01:44.186
182,5,g3t3,Qali sono 5 animali tipici dell india,serp25,None,None,None,NaN,2026-05-19 15:01:47.876
183,5,g3t3,Qali sono 5 animali tipici dell india,serp26,None,None,None,NaN,2026-05-19 15:01:58.337
204,5,g3t2,Qal e il,serp29,None,None,None,NaN,2026-05-19 15:15:44.081
338,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp46,None,None,None,NaN,2026-05-19 15:04:52.511
339,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp47,None,None,None,NaN,2026-05-19 15:05:05.152
340,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp48,None,None,None,NaN,2026-05-19 15:08:36.757
341,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp49,None,None,None,NaN,2026-05-19 15:09:48.390
414,9,g4t3,3 galassie oly,serp58,None,None,None,NaN,2026-05-19 11:09:41.822
582,12,g4t3,3 galassie olt4e la nostra,serp76,None,None,None,NaN,2026-05-19 11:16:50.790
583,12,g4t3,3 galassie olt4e la nostra,serp77,None,None,None,NaN,2026-05-19 11:16:54.735
749,15,g4t3,qualifiche f1,serp94,None,None,None,NaN,2026-05-19 10:55:32.846
781,15,g4t3,Nomi di alre galassie,serp98,None,None,None,NaN,2026-05-19 11:06:11.428

In [ ]:
relevance = pd.read_csv("Data/relevance.csv")
relevance.loc[relevance["topic_number"]=="g3t2"]

,topic_number,topic,doc,relevance
14,g3t2,Bandiera India simbolo,https://liceoberchet.edu.it/ricerche/geo4d_03/...,1
15,g3t2,Bandiera India simbolo,https://www.wisdomlib.org/it/concept/dharmacakra,1
16,g3t2,Bandiera India simbolo,https://www.bandiere-nazionali.com/bandiera-in...,1
17,g3t2,Bandiera India simbolo,https://www.wisdomlib.org/it/concept/ashoka,1
18,g3t2,Bandiera India simbolo,https://www.fuorimag.it/la-bandiera-dellindia/,1
19,g3t2,Bandiera India simbolo,https://flags-world.com/it/bandiera-india-colo...,1
20,g3t2,Bandiera India simbolo,https://sullestradedelmondo.it/bandiera-indiana/,1
21,g3t2,Bandiera India simbolo,https://mastroviaggiatore.it/saree/blog/lindia...,1
22,g3t2,Bandiera India simbolo,https://isha.sadhguru.org/mahashivratri/it/shi...,1
23,g3t2,Bandiera India simbolo,https://www.bandiere-mondo.it/india,1
24,g3t2,Bandiera India simbolo,https://it.gov-civ-guarda.pt/flag-india,1
25,g3t2,Bandiera India simbolo,https://it.indiamap360.com/mappa-della-bandier...,1
26,g3t2,Bandiera India simbolo,https://www.ilsaperestorico.it/ashoka-asoka-il...,1
27,g3t2,Bandiera India simbolo,https://old.icsestopascoli.edu.it/wp-content/u...,1
28,g3t2,Bandiera India simbolo,https://www.media.inaf.it/2013/04/04/smc-wing-...,1
29,g3t2,Bandiera India simbolo,https://www.skuola.net/geografia-medie/india-d...,1
30,g3t2,Bandiera India simbolo,https://dinolingo.com/it/hindi-culture-hindi-c...,1

In [105]:
import pandas as pd

serp_df = pd.read_csv("Data/logs_compiled.csv")
relevance = pd.read_csv("Data/relevance.csv")
relevance_score = []

for _, row in serp_df.iterrows():
    relevant_docs = relevance.loc[relevance["topic_number"]==row["topic_number"]]["doc"].tolist()
    if row["url"] in relevant_docs:
        relevance_score.append(1)
    else:
        relevance_score.append(0)

serp_df["relevance_score"] = relevance_score
serp_df.to_csv("Data/logs_compiled.csv", index=False, encoding="utf8")

In [118]:
temp = serp_df.loc[(serp_df["rank"]<=10)|(pd.isna(serp_df["rank"]))].groupby(["serp_id"])["relevance_score"].sum()/10
df = pd.DataFrame(temp).reset_index()
df.columns = ["serp_id", "precision@10"]
df["query"] = [serp_df.loc[serp_df["serp_id"]==serp_id]["query"].values[0] for serp_id in df["serp_id"]]
df["topic_number"] = [serp_df.loc[serp_df["serp_id"]==serp_id]["topic_number"].values[0] for serp_id in df["serp_id"]]
df["uid"] = [serp_df.loc[serp_df["serp_id"]==serp_id]["uid"].values[0] for serp_id in df["serp_id"]]
df = df[["uid", "topic_number", "serp_id", "query", "precision@10"]]
df = df.sort_values(by=["uid"]).reset_index(drop=True)
df = df[["uid","topic_number","query","serp_id", "precision@10"]]
df.to_csv("Data/query_formulation_df.csv", index=False, encoding='utf8')

In [119]:
df

,uid,topic_number,query,serp_id,precision@10
0,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,0.2
1,1,g3t2,Quale è il nome del simbolo al centro della ba...,serp2,0.1
2,1,g3t1,Fiume sacro degli indiani,serp3,0.4
3,2,g3t3,Quali sono i animali dall'India,serp4,0.7
4,2,g3t3,Quali sono i 5 animali tipici dall'India,serp5,0.2
...,...,...,...,...,...
113,18,g3t3,Quali sono i cinque tipici animali dell l india,serp114,0.2
114,18,g3t3,Quali sono i 5 cinque tipici animali dell l i...,serp115,0.1
115,18,g3t2,Simbolo della bandiera dell'india,serp117,0.9
116,18,g3t2,Quale il nome del simbolo al centro della band...,serp116,0.4
117,18,g3t1,Come si chiama il fiume sacro degli indiani,serp118,0.4

## results navigation

In [1]:
import pandas as pd

serp_df = pd.read_csv("Data/logs_compiled.csv")
serp_df.head()

,uid,topic_number,qid,query,serp_id,url,title,snippet,rank,relevance_score,click_count,timestamp
0,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,1,2,2026-05-19 14:51:27.687
1,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,1,0,2026-05-19 14:51:27.688
2,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://www.storicang.it/a/civilta-dellindo-i-...,"La civiltà dell'Indo, i misteri di un popolo d...","\n Jun 5, 2023 ... Sono note cinque m...",3.0,0,0,2026-05-19 14:51:27.689
3,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... Chi sono, da dove ...",4.0,0,0,2026-05-19 14:51:27.690
4,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/comportamento/feste...,Festa della mamma: come si festeggia nel resto...,\n Il dolce tipico per celebrare ques...,5.0,0,0,2026-05-19 14:51:27.691

### clicked results

In [ ]:
import pandas as pd

clicked_results = pd.read_csv("Data/clicked_results_df.csv")
clicked_results_df.head(40)

,uid,topic_number,query,url,rank,timestamp
0,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:43.444
1,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:53:19.408
2,1,g3t2,Quale è il nome del simbolo al centro della ba...,https://it.gov-civ-guarda.pt/flag-india,1,2026-05-19 15:02:48.776
3,1,g3t1,Fiume sacro degli indiani,https://www.consciousjourneys.com/it/approfond...,2,2026-05-19 15:08:58.405
4,2,g3t3,Quali sono i 5 animali tipici dall'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:52:53.759
5,2,g3t2,Qual è il nome del simbolo al centro della b...,https://sullestradedelmondo.it/bandiera-indiana/,3,2026-05-19 15:09:25.575
6,2,g3t1,Come si chiama il fiume sacro agli indiani,https://www.consciousjourneys.com/it/approfond...,1,2026-05-19 15:14:18.095
7,3,g3t3,Quali sono 5 animali tipici dell'india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:56:28.100
8,3,g3t2,Quale il nome del simbolo al centro della band...,https://mastroviaggiatore.it/saree/blog/lindia...,1,2026-05-19 15:05:39.212
9,3,g3t2,Quale il nome del simbolo al centro della band...,https://it.gov-civ-guarda.pt/flag-india,3,2026-05-19 15:06:00.133
10,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://it.gov-civ-guarda.pt/flag-india,7,2026-05-19 14:55:47.060
11,4,g3t2,Quale il simbolo dell'India,https://liceoberchet.edu.it/ricerche/geo4d_03/...,1,2026-05-19 15:06:06.889
12,4,g3t2,Quale il simbolo dell'India,https://www.focus.it/ambiente/animali/8-cose-c...,2,2026-05-19 15:06:28.655
13,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:36.085
14,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:49.996
15,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:11:04.292
16,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:12:03.487
17,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:14:14.237
18,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:17:21.809
19,4,g3t1,Fiume sacro indiano,https://www.goasia.it/la-religione-gange-fiume...,1,2026-05-19 15:20:26.846
20,5,g3t3,Quali sono 5 animali tipici dell india,https://www.terreincognitemagazine.it/natura-s...,2,2026-05-19 15:08:18.588
21,5,g3t2,Qual eil simbolo della bandiera india,https://sullestradedelmondo.it/bandiera-indiana/,1,2026-05-19 15:19:29.861
22,6,g3t3,Quali sono 5 animali tipici dell'india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:56:05.417
23,6,g3t2,Quale il simbolo al centro della bandiera dell...,https://www.skuola.net/geografia-medie/india-d...,1,2026-05-19 15:08:05.059
24,6,g3t2,Simbolo andiera India,https://www.bandiere-nazionali.com/bandiera-in...,3,2026-05-19 15:11:31.642
25,6,g3t2,Simbolo andiera India,https://sullestradedelmondo.it/bandiera-indiana/,4,2026-05-19 15:13:24.460
26,8,g3t3,Quali sono 5 animali dell India,https://www.focusjunior.it/scuola/geografia/le...,5,2026-05-19 14:51:21.199
27,8,g3t3,Quali sono 5 animali dell India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:42.534
28,8,g3t3,Quali sono 5 animali dell India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:52:02.269
29,8,g3t3,Quali sono 5 animali dell India,https://animalia.bio/it/india-animals,4,2026-05-19 14:54:13.476
30,8,g3t3,Quali sono 5 animali dell India,https://animalia.bio/it/india-animals,4,2026-05-19 14:55:56.413
31,8,g3t2,centro bandiera india simbolo,https://www.bandiere-nazionali.com/bandiera-in...,2,2026-05-19 15:11:51.878
32,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.focusjunior.it/scienza/spazio/laik...,2,2026-05-19 10:43:58.958
33,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.nationalgeographic.it/spazio/2021/...,3,2026-05-19 10:44:41.360
34,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.focusjunior.it/scienza/spazio/stel...,6,2026-05-19 10:45:32.387
35,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.storicang.it/foto-del-giorno/laika...,1,2026-05-19 10:46:16.185
36,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.focusjunior.it/scienza/spazio/laik...,2,2026-05-19 10:46:57.627
37,9,g4t1,Come si chiamano i satteliti maggiori di Giove,https://www.astronomitaly.com/blog/astronomy-p...,1,2026-05-19 10:52:26.337
38,9,g4t1,Come si chiamano i satteliti maggiori di Giove,https://starwalk.space/it/news/jupiter-galilea...,2,2026-05-19 10:53:18.182
39,9,g4t1,Come si chiamano i satteliti maggiori di Giove,https://edu.inaf.it/astrofoto/giove-satelliti-...,3,2026-05-19 10:53:42.819

In [ ]:
clicked_results_df.dtypes

uid                      Int64
topic_number            object
query                   object
url                     object
rank                     Int64
timestamp       datetime64[ns]
dtype: object

In [ ]:
## linking clicks to which SERP the click took place in

serp_df = pd.read_csv("Data/logs_compiled.csv")
associated_serp_ids = []

for _, row in clicked_results_df.iterrows():
    associated_serp = serp_df.loc[
        (serp_df["uid"]==row["uid"]) 
        & (serp_df["topic_number"]==row["topic_number"]) 
        & (serp_df["query"]==row["query"]) 
        & (serp_df["url"]==row["url"]) 
        & (serp_df["rank"]==row["rank"]) 
        & (serp_df["timestamp"]<row["timestamp"])
    ]

    if len(associated_serp) == 0:
        print(row)
        associated_serp_ids.append(None)

    elif len(associated_serp) > 1:
        # print(associated_serp)
        time_diff = np.inf
        for _, serp in associated_serp.iterrows():
            # print(serp)
            time_diff_compute = row["timestamp"] - serp["timestamp"]
            if time_diff >= time_diff_compute.total_seconds():
                correct_serp = serp["serp_id"]
                time_diff = time_diff_compute.total_seconds()
        associated_serp_ids.append(correct_serp)
    else:
        associated_serp_ids.append(associated_serp["serp_id"].values[0])

clicked_results_df["serp_id"] = associated_serp_ids

In [ ]:
clicked_results_df.loc[(clicked_results_df["uid"]==4)&(clicked_results_df["topic_number"]=="g3t2")&(clicked_results_df["query"]=="Che cosa rappresenta l'imagine del simbolo banderia dell'India")&(clicked_results_df["rank"]==2)]

,uid,topic_number,query,url,rank,timestamp,serp_id
15,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:11:04.292,serp14
16,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:12:03.487,serp14

In [ ]:
clicked_results_df.loc[pd.isna(clicked_results_df["serp_id"])]

Empty DataFrame
Columns: [uid, topic_number, query, url, rank, timestamp, serp_id]
Index: []

In [ ]:
clicked_results_df.loc[clicked_results_df["timestamp"]=="2026-05-19 10:46:51.654"]

,uid,topic_number,query,url,rank,timestamp,serp_id
123,15,g4t2,Qual è stato il primo animale nello spazio e c...,https://www.storicang.it/foto-del-giorno/laika...,1,2026-05-19 10:46:51.654,serp92

In [ ]:
clicked_results_df.loc[clicked_results_df["timestamp"]=="2026-05-19 10:51:16.099"]

,uid,topic_number,query,url,rank,timestamp,serp_id
124,15,g4t2,Qual è stato il primo animale nello spazio e c...,https://www.storicang.it/foto-del-giorno/laika...,1,2026-05-19 10:51:16.099,serp93

In [ ]:
clicked_results_df.head(20)

,uid,topic_number,query,url,rank,timestamp,serp_id
0,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:43.444,serp1
1,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:53:19.408,serp1
2,1,g3t2,Quale è il nome del simbolo al centro della ba...,https://it.gov-civ-guarda.pt/flag-india,1,2026-05-19 15:02:48.776,serp2
3,1,g3t1,Fiume sacro degli indiani,https://www.consciousjourneys.com/it/approfond...,2,2026-05-19 15:08:58.405,serp3
4,2,g3t3,Quali sono i 5 animali tipici dall'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:52:53.759,serp5
5,2,g3t2,Qual è il nome del simbolo al centro della b...,https://sullestradedelmondo.it/bandiera-indiana/,3,2026-05-19 15:09:25.575,serp7
6,2,g3t1,Come si chiama il fiume sacro agli indiani,https://www.consciousjourneys.com/it/approfond...,1,2026-05-19 15:14:18.095,serp8
7,3,g3t3,Quali sono 5 animali tipici dell'india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:56:28.100,serp10
8,3,g3t2,Quale il nome del simbolo al centro della band...,https://mastroviaggiatore.it/saree/blog/lindia...,1,2026-05-19 15:05:39.212,serp11
9,3,g3t2,Quale il nome del simbolo al centro della band...,https://it.gov-civ-guarda.pt/flag-india,3,2026-05-19 15:06:00.133,serp11
10,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://it.gov-civ-guarda.pt/flag-india,7,2026-05-19 14:55:47.060,serp13
11,4,g3t2,Quale il simbolo dell'India,https://liceoberchet.edu.it/ricerche/geo4d_03/...,1,2026-05-19 15:06:06.889,serp16
12,4,g3t2,Quale il simbolo dell'India,https://www.focus.it/ambiente/animali/8-cose-c...,2,2026-05-19 15:06:28.655,serp16
13,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:36.085,serp16
14,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:49.996,serp16
15,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:11:04.292,serp14
16,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:12:03.487,serp14
17,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:14:14.237,serp17
18,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:17:21.809,serp17
19,4,g3t1,Fiume sacro indiano,https://www.goasia.it/la-religione-gange-fiume...,1,2026-05-19 15:20:26.846,serp18

In [ ]:
clicked_results_df.to_csv("Data/clicked_results_df.csv", index=False, encoding='utf8')

### viewed results

In [ ]:
## linking snippets viewed with which SERP the snippets belong to

serp_df = pd.read_csv("Data/logs_compiled.csv")
serp_df["timestamp"] = pd.to_datetime(serp_df["timestamp"])
viewed_results_df = pd.read_csv("Data/viewed_results_df.csv")
viewed_results_df["timestamp"] = pd.to_datetime(viewed_results_df["timestamp"])

associated_serp_ids = []

for _, row in tqdm(viewed_results_df.iterrows(), total=len(viewed_results_df)):
    associated_serp = serp_df.loc[
        (serp_df["uid"]==row["uid"]) 
        & (serp_df["topic_number"]==row["topic_number"]) 
        & (serp_df["query"]==row["query"]) 
        & (serp_df["url"]==row["url"]) 
        & (serp_df["rank"]==row["rank"]) 
        & (serp_df["timestamp"]<row["timestamp"])
    ]

    if len(associated_serp) == 0:
        print(row)
        associated_serp_ids.append(None)

    elif len(associated_serp) > 1:
        # print(associated_serp)
        time_diff = np.inf
        for _, serp in associated_serp.iterrows():
            # print(serp)
            time_diff_compute = row["timestamp"] - serp["timestamp"]
            if time_diff >= time_diff_compute.total_seconds():
                correct_serp = serp["serp_id"]
                time_diff = time_diff_compute.total_seconds()
        associated_serp_ids.append(correct_serp)
    else:
        associated_serp_ids.append(associated_serp["serp_id"].values[0])

viewed_results_df["serp_id"] = associated_serp_ids

  0%|          | 0/3084 [00:00<?, ?it/s]

In [ ]:
import pandas as pd

click_df = pd.read_csv("Data/clicked_results_df.csv")
click_df["timestamp"] = pd.to_datetime(click_df["timestamp"])
view_df = pd.read_csv("Data/viewed_results_df.csv")
view_df["timestamp"] = pd.to_datetime(view_df["timestamp"])

for serp_id in click_df["serp_id"].unique():
    clicks = click_df.loc[click_df["serp_id"]==serp_id].sort_values(by='timestamp', ascending=False)

    for _, click in clicks.iterrows():
        views = view_df.loc[(view_df["serp_id"]==click["serp_id"])&(view_df["timestamp"]<click["timestamp"])]
        for idx, view in views.iterrows():
            view_df.loc[idx, ["associated_click_timestamp"]] = click["timestamp"]

In [9]:
view_df["serp_id"].unique()

array(['serp1', 'serp2', 'serp3', 'serp4', 'serp5', 'serp6', 'serp7',
       'serp8', 'serp9', 'serp10', 'serp11', 'serp12', 'serp13', 'serp14',
       'serp15', 'serp16', 'serp17', 'serp18', 'serp19', 'serp22',
       'serp23', 'serp27', 'serp28', 'serp30', 'serp31', 'serp32',
       'serp33', 'serp34', 'serp36', 'serp37', 'serp38', 'serp39',
       'serp40', 'serp41', 'serp42', 'serp43', 'serp44', 'serp45',
       'serp50', 'serp51', 'serp52', 'serp53', 'serp54', 'serp55',
       'serp56', 'serp57', 'serp59', 'serp60', 'serp61', 'serp62',
       'serp63', 'serp64', 'serp65', 'serp66', 'serp67', 'serp68',
       'serp69', 'serp70', 'serp71', 'serp72', 'serp73', 'serp74',
       'serp75', 'serp78', 'serp79', 'serp80', 'serp81', 'serp82',
       'serp83', 'serp84', 'serp85', 'serp86', 'serp87', 'serp88',
       'serp89', 'serp90', 'serp91', 'serp92', 'serp93', 'serp95',
       'serp96', 'serp97', 'serp99', 'serp100', 'serp101', 'serp102',
       'serp103', 'serp104', 'serp105', 'serp106', 'serp107', 'serp108',
       'serp109', 'serp110', 'serp111', 'serp112', 'serp113', 'serp114',
       'serp115', 'serp116', 'serp117', 'serp118'], dtype=object)

In [13]:
view_df.loc[view_df["serp_id"]=="serp117"]

,uid,topic_number,query,url,rank,viewType,viewDurationInSeconds,timestamp,serp_id,associated_click_timestamp
3054,18,g3t2,Simbolo della bandiera dell'india,https://sullestradedelmondo.it/bandiera-indiana/,1,resultExposureStarted,NaN,2026-05-19 15:13:43.673,serp117,2026-05-19 15:14:24.499
3055,18,g3t2,Simbolo della bandiera dell'india,https://mastroviaggiatore.it/saree/blog/lindia...,2,resultExposureStarted,NaN,2026-05-19 15:13:43.677,serp117,2026-05-19 15:14:24.499
3056,18,g3t2,Simbolo della bandiera dell'india,https://www.bandiere-nazionali.com/bandiera-in...,3,resultExposureStarted,NaN,2026-05-19 15:13:49.313,serp117,2026-05-19 15:14:24.499
3057,18,g3t2,Simbolo della bandiera dell'india,https://liceoberchet.edu.it/ricerche/geo4d_03/...,4,resultExposureStarted,NaN,2026-05-19 15:13:54.297,serp117,2026-05-19 15:14:24.499
3058,18,g3t2,Simbolo della bandiera dell'india,https://sullestradedelmondo.it/bandiera-indiana/,1,resultExposureEnded,28.591,2026-05-19 15:14:12.013,serp117,2026-05-19 15:14:24.499
3059,18,g3t2,Simbolo della bandiera dell'india,https://www.skuola.net/geografia-medie/india-d...,5,resultExposureStarted,NaN,2026-05-19 15:14:12.271,serp117,2026-05-19 15:14:24.499
3060,18,g3t2,Simbolo della bandiera dell'india,https://mastroviaggiatore.it/saree/blog/lindia...,2,resultExposureEnded,31.840,2026-05-19 15:14:15.262,serp117,2026-05-19 15:14:24.499
3061,18,g3t2,Simbolo della bandiera dell'india,https://it.gov-civ-guarda.pt/flag-india,6,resultExposureStarted,NaN,2026-05-19 15:14:15.543,serp117,2026-05-19 15:14:24.499
3062,18,g3t2,Simbolo della bandiera dell'india,https://www.bandiere-nazionali.com/bandiera-in...,3,resultExposureEnded,26.771,2026-05-19 15:14:15.833,serp117,2026-05-19 15:14:24.499
3063,18,g3t2,Simbolo della bandiera dell'india,https://liceoberchet.edu.it/ricerche/geo4d_03/...,4,resultExposureEnded,22.054,2026-05-19 15:14:16.100,serp117,2026-05-19 15:14:24.499
3064,18,g3t2,Simbolo della bandiera dell'india,https://www.focus.it/ambiente/animali/8-cose-c...,7,resultExposureStarted,NaN,2026-05-19 15:14:16.110,serp117,2026-05-19 15:14:24.499
3065,18,g3t2,Simbolo della bandiera dell'india,https://flags-world.com/it/bandiera-india-colo...,8,resultExposureStarted,NaN,2026-05-19 15:14:16.382,serp117,2026-05-19 15:14:24.499
3066,18,g3t2,Simbolo della bandiera dell'india,https://flags-world.com/it/bandiera-india-colo...,8,resultExposureEnded,2.859,2026-05-19 15:14:18.991,serp117,2026-05-19 15:14:24.499
3067,18,g3t2,Simbolo della bandiera dell'india,https://www.focus.it/ambiente/animali/8-cose-c...,7,resultExposureEnded,3.299,2026-05-19 15:14:19.158,serp117,2026-05-19 15:14:24.499
3068,18,g3t2,Simbolo della bandiera dell'india,https://liceoberchet.edu.it/ricerche/geo4d_03/...,4,resultExposureStarted,NaN,2026-05-19 15:14:19.276,serp117,2026-05-19 15:14:24.499
3069,18,g3t2,Simbolo della bandiera dell'india,https://www.bandiere-nazionali.com/bandiera-in...,3,resultExposureStarted,NaN,2026-05-19 15:14:19.456,serp117,2026-05-19 15:14:24.499
3070,18,g3t2,Simbolo della bandiera dell'india,https://www.bandiere-nazionali.com/bandiera-in...,3,resultExposureEnded,0.590,2026-05-19 15:14:19.795,serp117,2026-05-19 15:14:24.499
3071,18,g3t2,Simbolo della bandiera dell'india,https://www.focus.it/ambiente/animali/8-cose-c...,7,resultExposureStarted,NaN,2026-05-19 15:14:20.051,serp117,2026-05-19 15:14:24.499
3072,18,g3t2,Simbolo della bandiera dell'india,https://www.focus.it/ambiente/animali/8-cose-c...,7,resultExposureEnded,3.732,2026-05-19 15:14:23.532,serp117,2026-05-19 15:14:24.499
3073,18,g3t2,Simbolo della bandiera dell'india,https://it.gov-civ-guarda.pt/flag-india,6,resultExposureEnded,9.201,2026-05-19 15:14:24.494,serp117,2026-05-19 15:14:24.499
3074,18,g3t2,Simbolo della bandiera dell'india,https://www.skuola.net/geografia-medie/india-d...,5,resultExposureEnded,12.476,2026-05-19 15:14:24.496,serp117,2026-05-19 15:14:24.499
3075,18,g3t2,Simbolo della bandiera dell'india,https://liceoberchet.edu.it/ricerche/geo4d_03/...,4,resultExposureEnded,5.473,2026-05-19 15:14:24.497,serp117,2026-05-19 15:14:24.499

In [14]:
view_df.to_csv("Data/viewed_results_df.csv", index=False, encoding="utf8")

In [ ]:
viewed_results_df.loc[(viewed_results_df["uid"]==4)&(viewed_results_df["topic_number"]=="g3t2")&(viewed_results_df["query"]=="Che cosa rappresenta l'imagine del simbolo banderia dell'India")&(viewed_results_df["rank"]==2)]

,uid,topic_number,query,url,rank,viewType,viewDurationInSeconds,timestamp,serp_id
149,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,NaN,2026-05-19 14:54:59.696,serp13
154,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,37.873,2026-05-19 14:55:37.301,serp13
165,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,NaN,2026-05-19 14:58:09.379,serp13
169,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,5.019,2026-05-19 14:58:14.141,serp13
197,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,NaN,2026-05-19 14:58:46.706,serp13
213,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,49.223,2026-05-19 14:59:35.679,serp13
217,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,NaN,2026-05-19 14:59:37.452,serp14
219,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,4.989,2026-05-19 14:59:42.185,serp14
327,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,NaN,2026-05-19 15:10:33.828,serp14
328,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,30.716,2026-05-19 15:11:04.278,serp14
331,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,NaN,2026-05-19 15:11:53.293,serp14
332,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,10.445,2026-05-19 15:12:03.475,serp14

In [ ]:
viewed_results_df.loc[pd.isna(viewed_results_df["serp_id"])]

Empty DataFrame
Columns: [uid, topic_number, query, url, rank, viewType, viewDurationInSeconds, timestamp, serp_id]
Index: []

In [ ]:
viewed_results_df.to_csv("Data/viewed_results_df.csv", index=False, encoding='utf8')

### SERP pages

In [2]:
import pandas as pd

clicked_results_df = pd.read_csv("Data/clicked_results_df.csv")
serp_df = pd.read_csv("Data/logs_compiled.csv")
serp_df["timestamp"] = pd.to_datetime(serp_df["timestamp"])

df = pd.DataFrame(clicked_results_df.groupby(["uid", "topic_number", "serp_id"])["url"].value_counts()).reset_index()

click_count = []

for _, row in serp_df.iterrows():
    serp_row = df.loc[(df["uid"]==row["uid"])&(df["topic_number"]==row["topic_number"])&(df["serp_id"]==row["serp_id"])&(df["url"]==row["url"])]
    if len(serp_row) > 1:
        print(row, serp_row)
    elif len(serp_row) == 0:
        click_count.append(0)
    else:
        click_count.append(serp_row["count"].values[0])

serp_df["click_count"] = click_count

In [3]:
serp_df.head()

,uid,topic_number,qid,query,serp_id,url,title,snippet,rank,relevance_score,click_count,timestamp
0,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,1,2,2026-05-19 14:51:27.687
1,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,1,0,2026-05-19 14:51:27.688
2,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://www.storicang.it/a/civilta-dellindo-i-...,"La civiltà dell'Indo, i misteri di un popolo d...","\n Jun 5, 2023 ... Sono note cinque m...",3.0,0,0,2026-05-19 14:51:27.689
3,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... Chi sono, da dove ...",4.0,0,0,2026-05-19 14:51:27.690
4,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/comportamento/feste...,Festa della mamma: come si festeggia nel resto...,\n Il dolce tipico per celebrare ques...,5.0,0,0,2026-05-19 14:51:27.691

In [29]:
serp_df.sample(10)

,uid,topic_number,qid,query,serp_id,url,title,snippet,rank,relevance_score,click_count,timestamp
660,14,g4t3,q86,Gli altri nomi delle galassie,serp86,https://www.focusjunior.it/news/la-superluna-d...,"La Superluna di ottobre 2024, la più luminosa ...","\n Oct 17, 2024 ... Altri nomi con cu...",12.0,0,0,2026-05-19 10:58:19.267
688,14,g4t2,q88,"Come si chia,",serp88,https://www.focusjunior.it/news/marciapiedi-pu...,Marciapiedi puliti: uniti contro la sporcizia ...,"\n Apr 19, 2023 ... I marciapiedi pul...",10.0,0,0,2026-05-19 11:08:05.000
591,12,g4t3,q78,3 galassie oltre alla nostra,serp78,https://www.focusjunior.it/content/uploads/sit...,"SP ""Aldo Moro"" - Focus Junior","\n May 30, 2016 ... 3. Una donna tra ...",8.0,0,0,2026-05-19 11:17:33.624
91,4,g3t2,q13,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focusjunior.it/scuola/geografia/10...,10 cose che (forse) non sai sull'Europa - Focu...,"\n Dal nome, alla bandiera passando p...",6.0,0,0,2026-05-19 14:54:59.396
348,8,g3t2,q50,centro bandiera india simbolo,serp50,https://www.focus.it/ambiente/animali/8-cose-c...,8 cose che (forse) non sai sulle vacche sacre ...,"\n Mar 31, 2019 ... Ma attenzione: gl...",7.0,0,0,2026-05-19 15:11:41.377
732,15,g4t2,q92,Qual è stato il primo animale nello spazio e c...,serp92,https://www.focusjunior.it/tecnologia/tecnolog...,Tecnologia: il primo Smartphone della storia -...,"\n Jun 4, 2015 ... Si chiama SIMON ed...",4.0,0,0,2026-05-19 10:46:44.792
333,8,g3t3,q45,Quali sono 5 animali dell India,serp45,https://www.goasia.it/geografia-natura-e-clima...,"Geografia, natura e clima dell'India - Go Asia",\n Molteplici varietà di animali sono...,6.0,1,0,2026-05-19 14:53:54.972
58,3,g3t1,q9,come si chiama il fiume sacro agli indiani,serp9,https://www.consciousjourneys.com/it/approfond...,"Gange, il fiume sacro agli indù e alla popolaz...","\n È altresì importante per la pesca,...",1.0,1,0,2026-05-19 14:50:11.779
784,15,g4t3,q99,Nomi di altre galassie,serp99,https://www.latorredelsole.it/2025/09/05/m-31-...,M 31 – Galassia di Andromeda - La Torre del Sole,"\n Sep 5, 2025 ... La Galassia di And...",3.0,1,3,2026-05-19 11:06:18.433
661,14,g4t3,q86,Gli altri nomi delle galassie,serp86,https://www.focusjunior.it/scienza/spazio/mari...,Mari spaziali: come sono gli oceani sugli altr...,\n ... delle comete si sciogliesse in...,13.0,0,0,2026-05-19 10:58:19.273

In [ ]:
query_df = pd.read_csv("Data/query_formulation_df.csv")
serp_df["qid"] = [query_df.loc[query_df["serp_id"]==serp_id]["qid"].values[0] for serp_id in serp_df["serp_id"]]
serp_df = serp_df[["uid", "topic_number", "qid", "query", "serp_id", "url", "title", "snippet", "rank", "relevance_score", "click_count", "timestamp"]]
serp_df = serp_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)

In [7]:
serp_df.head()

,uid,topic_number,qid,query,serp_id,url,title,snippet,rank,relevance_score,click_count,timestamp
0,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,1,2,2026-05-19 14:51:27.687
1,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,1,0,2026-05-19 14:51:27.688
2,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://www.storicang.it/a/civilta-dellindo-i-...,"La civiltà dell'Indo, i misteri di un popolo d...","\n Jun 5, 2023 ... Sono note cinque m...",3.0,0,0,2026-05-19 14:51:27.689
3,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... Chi sono, da dove ...",4.0,0,0,2026-05-19 14:51:27.690
4,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/comportamento/feste...,Festa della mamma: come si festeggia nel resto...,\n Il dolce tipico per celebrare ques...,5.0,0,0,2026-05-19 14:51:27.691

In [8]:
cleaned_serp_df = serp_df.dropna(subset=["rank"])
cleaned_serp_df["rank"] = cleaned_serp_df["rank"].astype(int)

C:\Users\hrishitachakra\AppData\Local\Temp\ipykernel_38884\193022930.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_serp_df["rank"] = cleaned_serp_df["rank"].astype(int)

In [9]:
len(serp_df), len(cleaned_serp_df)

(945, 930)

In [10]:
len(serp_df["serp_id"].unique()), len(cleaned_serp_df["serp_id"].unique())

(118, 103)

In [11]:
serp_df.to_csv("Data/logs_compiled.csv", index=False, encoding='utf8')
cleaned_serp_df.to_csv("Data/results_navigation.csv", index=False, encoding='utf8') # removes queries which did not yield any results

In [12]:
serp_df.loc[serp_df["serp_id"]=="serp119"]

Empty DataFrame
Columns: [uid, topic_number, qid, query, serp_id, url, title, snippet, rank, relevance_score, click_count, timestamp]
Index: []

### Explored pages

In [ ]:
clicked_results_df = pd.read_csv("Data/clicked_results_df.csv")
clicked_results_df["timestamp"] = pd.to_datetime(clicked_results_df["timestamp"])

explored_pages_df = pd.read_csv("Data/explored_pages_df.csv")
explored_pages_df["timestamp"] = pd.to_datetime(explored_pages_df["timestamp"])

associated_click_time = []

for _, row in tqdm(explored_pages_df.iterrows(), total=len(explored_pages_df)):
    associated_clicks = clicked_results_df.loc[
        (clicked_results_df["uid"]==row["uid"]) 
        & (clicked_results_df["topic_number"]==row["topic_number"]) 
        & (clicked_results_df["url"]==row["url"]) 
        & (clicked_results_df["timestamp"]<row["timestamp"])
    ]

    # print(len(associated_clicks))

    if len(associated_clicks) == 0:
        print("couldn't find associated click: ", row)
        associated_click_time.append(None)

    elif len(associated_clicks) > 1:
        # print("found multiple clicks: ", associated_clicks)
        time_diff = np.inf
        for _, click in associated_clicks.iterrows():
            # print(serp)
            time_diff_compute = row["timestamp"] - click["timestamp"]
            if time_diff >= time_diff_compute.total_seconds():
                correct_click_time = click["timestamp"]
                time_diff = time_diff_compute.total_seconds()
        associated_click_time.append(correct_click_time)
    else:
        associated_click_time.append(associated_clicks["timestamp"].values[0])

explored_pages_df["click_time"] = associated_click_time

  0%|          | 0/332 [00:00<?, ?it/s]

In [ ]:
click_rank = []
serp_id = []
for _, row in explored_pages_df.iterrows():
    clicked_result = click_df.loc[(click_df["uid"]==row["uid"]) & (click_df["timestamp"]==row["click_time"])]
    serp_id.append(clicked_result["serp_id"].values[0])
    click_rank.append(clicked_result["rank"].values[0])

explored_pages_df["serp_id"] = serp_id
explored_pages_df["click_rank"] = click_rank
explored_pages_df.to_csv("Data/explored_pages.csv", index=False, encoding="utf8")
explored_pages_df

In [ ]:
serp = pd.read_csv("Data/results_navigation.csv")
rel_score = []

for _, row in explored_pages_df.iterrows():
    serp_result = serp.loc[(serp["serp_id"]==row["serp_id"]) & (serp["url"]==row["url"])]
    rel_score.append(serp_result["relevance_score"].values[0])

explored_pages_df["relevance_score"] = rel_score
explored_pages_df.to_csv("Data/explored_pages.csv", index=False, encoding="utf8")
explored_pages_df.head()

In [ ]:
explored_pages_df.loc[pd.isna(explored_pages_df["click_time"])]

Empty DataFrame
Columns: [uid, topic_number, url, exploreType, viewDurationInSeconds, timestamp, click_time]
Index: []

In [ ]:
explored_pages_df.to_csv("Data/explored_pages.csv", index=False, encoding="utf8")

In [ ]:
page_count = pd.DataFrame(explored_pages_df["click_time"].value_counts()).reset_index()
page_count.loc[page_count["count"]!=2]

Empty DataFrame
Columns: [click_time, count]
Index: []

In [ ]:
print(len(clicked_results_df), len(explored_pages_df)/2)

166 166.0

### Navigation quality

In [13]:
import pandas as pd

navigation_quality = []
results_navigation = pd.read_csv("Data/results_navigation.csv")
results_navigation["timestamp"] = pd.to_datetime(results_navigation["timestamp"])

click_df = pd.read_csv("Data/clicked_results_df.csv")
click_df["timestamp"] = pd.to_datetime(click_df["timestamp"])

for serp_id in results_navigation["serp_id"].unique():
    serp = results_navigation.loc[results_navigation["serp_id"]==serp_id]
    clicked_results = click_df.loc[click_df["serp_id"]==serp_id]

    uid = serp["uid"].values[0]
    topic_number = serp["topic_number"].values[0]
    qid = serp["qid"].values[0]
    query = serp["query"].values[0]
    total_clicks = serp["click_count"].sum()

    if total_clicks == 0:
        click_accuracy = None
        if sum(serp["relevance_score"]) == 0: # no relevant resources in the SERP
            effective_navigation = 1
        elif sum(serp["relevance_score"]) > 0: # there are relevant resources in the SERP
            effective_navigation = 0
    else:
        clicked_resources = 0
        positive_clicks = 0
        for _, result in serp.loc[serp["click_count"]>0].iterrows(): # serp results that were clicked
            clicked_resources += 1
            if result["relevance_score"] == 1:
                positive_clicks += 1
        click_accuracy = round(positive_clicks/clicked_resources,2)
        effective_navigation = int(click_accuracy >= 0.80)

    repetitions = total_clicks - len(clicked_results["rank"].unique())
    last_relevant_timestamp = serp["timestamp"].values[0]
    found_a_relevant_click = 0
    for _, click in clicked_results.iterrows():
        relevance = serp.loc[(serp["url"]==click["url"]) & (serp["rank"]==click["rank"])]["relevance_score"].values[0]
        if relevance == 1:
            found_a_relevant_click = 1
            last_relevant_timestamp = click["timestamp"]

    tail = len(clicked_results.loc[clicked_results["timestamp"]>last_relevant_timestamp])

    if found_a_relevant_click == 0:
            last_relevant_timestamp = None

    # if total_clicks > 0:
    #     nav_eff = (total_clicks - repetitions - tail)/total_clicks
    # else:
    #      nav_eff = None

    navigation_quality.append([uid, topic_number, qid, query, serp_id, total_clicks, repetitions, tail, last_relevant_timestamp, click_accuracy, effective_navigation])

navigation_quality_df = pd.DataFrame(navigation_quality, columns = ["uid", "topic_number", "qid", "query", "serp_id", "total_clicks", "repetitions", "tail", "last_relevant_timestamp", "click_accuracy", "effective_navigation"])
navigation_quality_df.to_csv("Data/navigation_quality.csv", index=False, encoding="utf8")
navigation_quality_df.head(10)

,uid,topic_number,qid,query,serp_id,total_clicks,repetitions,tail,last_relevant_timestamp,click_accuracy,effective_navigation
0,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,2,1,0,2026-05-19 14:53:19.408,1.0,1
1,1,g3t2,q2,Quale è il nome del simbolo al centro della ba...,serp2,1,0,0,2026-05-19 15:02:48.776,1.0,1
2,1,g3t1,q3,Fiume sacro degli indiani,serp3,1,0,0,2026-05-19 15:08:58.405,1.0,1
3,2,g3t3,q4,Quali sono i animali dall'India,serp4,0,0,0,NaT,NaN,0
4,2,g3t3,q5,Quali sono i 5 animali tipici dall'India,serp5,1,0,0,2026-05-19 14:52:53.759,1.0,1
5,2,g3t2,q6,Qual è il nome del simbolo al centro della ban...,serp6,0,0,0,NaT,NaN,0
6,2,g3t2,q7,Qual è il nome del simbolo al centro della b...,serp7,1,0,0,2026-05-19 15:09:25.575,1.0,1
7,2,g3t1,q8,Come si chiama il fiume sacro agli indiani,serp8,1,0,0,2026-05-19 15:14:18.095,1.0,1
8,3,g3t1,q9,come si chiama il fiume sacro agli indiani,serp9,0,0,0,NaT,NaN,0
9,3,g3t3,q10,Quali sono 5 animali tipici dell'india,serp10,1,0,0,2026-05-19 14:56:28.100,1.0,1

In [15]:
results_navigation.loc[results_navigation["serp_id"]=="serp4"]

,uid,topic_number,qid,query,serp_id,url,title,snippet,rank,relevance_score,click_count,timestamp
19,2,g3t3,q4,Quali sono i animali dall'India,serp4,https://www.focusjunior.it/scuola/storia/il-pi...,Chi ha inventato il pigiama? - FocusJunior.it,\n Ma quali sono le sue origini? DAL ...,1,0,0,2026-05-19 14:50:23.230
20,2,g3t3,q4,Quali sono i animali dall'India,serp4,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... Finalmente la tig...",2,1,0,2026-05-19 14:50:23.232
21,2,g3t3,q4,Quali sono i animali dall'India,serp4,https://www.focus.it/ambiente/animali/8-cose-c...,8 cose che (forse) non sai sulle vacche sacre ...,"\n Mar 31, 2019 ... Animali. 8 cose c...",3,1,0,2026-05-19 14:50:23.233
22,2,g3t3,q4,Quali sono i animali dall'India,serp4,https://www.focus.it/ambiente/animali/nella-te...,Nella terra della tigre: il ritorno della regi...,"\n Nov 22, 2022 ... Le giungle dell'I...",4,1,0,2026-05-19 14:50:23.234
23,2,g3t3,q4,Quali sono i animali dall'India,serp4,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... Se invece volete ...",5,1,0,2026-05-19 14:50:23.236
24,2,g3t3,q4,Quali sono i animali dall'India,serp4,https://www.goasia.it/geografia-natura-e-clima...,"Geografia, natura e clima dell'India - Go Asia",\n Molteplici varietà di animali sono...,6,1,0,2026-05-19 14:50:23.237
25,2,g3t3,q4,Quali sono i animali dall'India,serp4,https://www.focusjunior.it/news/quali-e-quante...,"Guerre nel mondo, quali e quante sono in corso...","\n Mar 21, 2022 ... Guerra nel Mali (...",7,0,0,2026-05-19 14:50:23.238
26,2,g3t3,q4,Quali sono i animali dall'India,serp4,https://animalia.bio/it/india-animals,India - Animalia,"\n In India sono segnalate 172 (il 2,...",8,1,0,2026-05-19 14:50:23.239
27,2,g3t3,q4,Quali sono i animali dall'India,serp4,https://www.focusjunior.it/animali/entomofagia...,Entomofagia: quali insetti si mangiano nel mon...,\n Tra le varie teorie per un futuro ...,9,0,0,2026-05-19 14:50:23.240
28,2,g3t3,q4,Quali sono i animali dall'India,serp4,https://animalia.bio/it/endemic-lists/country/...,Endemic Animals of India - Animalia,\n Animali endemici dell'India. Home ...,10,1,0,2026-05-19 14:50:23.242

In [17]:
click_df = pd.read_csv("Data/clicked_results_df.csv")
click_df.loc[click_df["uid"]==4]

,uid,topic_number,query,url,rank,timestamp,serp_id
10,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://it.gov-civ-guarda.pt/flag-india,7,2026-05-19 14:55:47.060,serp13
11,4,g3t2,Quale il simbolo dell'India,https://liceoberchet.edu.it/ricerche/geo4d_03/...,1,2026-05-19 15:06:06.889,serp16
12,4,g3t2,Quale il simbolo dell'India,https://www.focus.it/ambiente/animali/8-cose-c...,2,2026-05-19 15:06:28.655,serp16
13,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:36.085,serp16
14,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:49.996,serp16
15,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:11:04.292,serp14
16,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:12:03.487,serp14
17,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:14:14.237,serp17
18,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:17:21.809,serp17
19,4,g3t1,Fiume sacro indiano,https://www.goasia.it/la-religione-gange-fiume...,1,2026-05-19 15:20:26.846,serp18

In [14]:
len(navigation_quality_df.loc[navigation_quality_df["effective_navigation"]==1]), len(navigation_quality_df)

(45, 103)

## information distillation

### automatic scraping

In [ ]:
# import pandas as pd
# import urllib3
# from urllib3 import Retry
# from tqdm.notebook import tqdm
# import time
# from bs4 import BeautifulSoup

# serp_df = pd.read_csv("Data/logs_compiled.csv")
# len(serp_df["url"].unique())

# corpus = []
# for idx, url in tqdm(zip(range(len(serp_df["url"].unique())), serp_df["url"].unique()), total = len(serp_df["url"].unique())):
#     if idx % 50 == 0 and idx!=0:
#         time.sleep(10)
#     if pd.notna(url):
#         try:
#             html = urllib3.request("GET", url, retries=Retry(5), headers={'User-Agent': 'Mozilla/5.0'})
#             # html = urllib3.request("GET", url, retries=False)
#             if html.status == 200:
#                 soup = BeautifulSoup(markup = html.data, features='lxml')
#                 # kill all script and style elements
#                 for script in soup(["script", "style", "nav", "header", "footer", "aside", "img", "link"]):
#                     script.extract() # rip it out
#                     # script.decompose() 
#                 corpus.append(["d"+str(idx), url, str(soup.body), str(soup.body.get_text(separator='\n ', strip=True)), "auto-scraped"])
#             else:
#                 corpus.append(["d"+str(idx), url, None, None, "manual-scraped"])
#         except:
#             corpus.append(["d"+str(idx), url, None, None, "manual-scraped"])

In [ ]:
# corpus_df = pd.DataFrame(corpus, columns = ["doc_id", "url", "html_content", "text_content", "scraping_source"])
# corpus_df.to_excel("Data/corpus.xlsx", index=False)
# # corpus_df.to_csv("Data/corpus.tsv", index=False, encoding="utf8", sep="\t")

In [ ]:
# corpus_df.head()

In [ ]:
# len(corpus_df.loc[pd.isna(corpus_df["text_content"])])

### manual scraping

In [ ]:
# html_text = """
# <body><p class="s1" style="padding-top: 2pt;text-indent: 0pt;text-align: center;">LA BANDIERA DELL’INDIA</p><p style="text-indent: 0pt;text-align: left;"><br/></p><p style="padding-left: 59pt;text-indent: 0pt;text-align: left;"><span><img width="507" height="373" alt="image" src="3_files/Image_001.jpg"/></span></p><p style="padding-top: 5pt;text-indent: 0pt;text-align: left;"><br/></p><p style="padding-left: 5pt;text-indent: 0pt;text-align: justify;">La bandiera dell’India è anche detta TIRANGA cioè tricolore.</p><p style="padding-top: 5pt;padding-left: 5pt;text-indent: 0pt;text-align: justify;">E’  suddivisa  in  tre  strisce  orizzontali  di  uguali dimensioni:</p><ul id="l1"><li data-list-text="•"><p style="padding-top: 1pt;padding-left: 27pt;text-indent: -21pt;text-align: justify;">in alto di colore arancione zafferano che simboleggia coraggio e sacrificio;</p></li><li data-list-text="•"><p style="padding-top: 1pt;padding-left: 27pt;text-indent: -21pt;text-align: justify;">al centro di colore bianco che rappresenta pace e verità;</p></li><li data-list-text="•"><p style="padding-top: 1pt;padding-left: 26pt;text-indent: -21pt;text-align: justify;">in basso di colore verde che esprime fede e cavalleria.</p></li></ul><p style="padding-top: 5pt;padding-left: 5pt;text-indent: 0pt;text-align: justify;">Al  centro  c’è  una  ruota  vuota  chiamata  ASHOKA CHAKRA la quale con i suoi 24 raggi raffigura le 24 ore e il progresso costante.</p><p style="text-indent: 0pt;text-align: left;"><br/></p><table style="border-collapse:collapse;margin-left:84.9347pt" cellspacing="0"><tr style="height:118pt"><td style="width:197pt;border-top-style:solid;border-top-width:3pt;border-left-style:solid;border-left-width:2pt;border-bottom-style:solid;border-bottom-width:3pt"><p style="text-indent: 0pt;text-align: left;"><br/></p></td><td style="width:276pt;border-top-style:solid;border-top-width:3pt;border-bottom-style:solid;border-bottom-width:3pt;border-right-style:solid;border-right-width:2pt" rowspan="3"><p style="text-indent: 0pt;text-align: left;"><br/></p><p style="text-indent: 0pt;text-align: left;"><span><img width="128" height="161" alt="image" src="3_files/Image_002.jpg"/></span></p><p style="text-indent: 0pt;text-align: left;"><br/></p><p class="s2" style="padding-right: 2pt;text-indent: 0pt;line-height: 28pt;text-align: right;">India</p></td></tr><tr style="height:114pt"><td style="width:197pt;border-top-style:solid;border-top-width:3pt;border-left-style:solid;border-left-width:2pt;border-bottom-style:solid;border-bottom-width:3pt"><p style="text-indent: 0pt;text-align: left;"><br/></p></td></tr><tr style="height:110pt"><td style="width:197pt;border-top-style:solid;border-top-width:3pt;border-left-style:solid;border-left-width:2pt;border-bottom-style:solid;border-bottom-width:3pt"><p style="text-indent: 0pt;text-align: left;"><br/></p></td></tr></table><p style="text-indent: 0pt;text-align: left;"><br/></p><p class="s3" style="padding-left: 42pt;text-indent: 0pt;text-align: left;">(c) <a href="http://www.flagspot.net/" class="a" target="_blank">www</a><a href="http://www.flagspot.net/" class="s4" target="_blank">.</a><a href="http://www.flagspot.net/" target="_blank">flagspot.net</a></p></body>
# """

In [ ]:
# corpus_df = pd.read_excel("Data/corpus.xlsx")
# url = "https://old.icsestopascoli.edu.it/wp-content/uploads/2020/05/3.Bandiera-dellIndia.pdf"
# idx = corpus_df.loc[corpus_df["url"]==url].index
# corpus_df.loc[idx, ["html_content"]]

                                         html_content
61  <body><p class="s1" style="padding-top: 2pt;te...

In [ ]:
# from bs4 import BeautifulSoup

# soup = BeautifulSoup(markup = html_text, features='lxml')
# # print(soup.body)
# # kill all script and style elements
# for script in soup(["script", "style", "nav", "header", "footer", "aside", "img", "link"]):
#     # print(soup.body)
#     script.extract() # rip it out
#     # print(soup.body)
#     # script.decompose() 
#     corpus_df.loc[idx, ["html_content"]] = str(soup.body)
#     corpus_df.loc[idx, ["text_content"]] = str(soup.body.get_text(separator='\n ', strip=True))

In [ ]:
# corpus_df.loc[idx, ["html_content"]]

                                         html_content
61  <body><p class="s1" style="padding-top: 2pt;te...

In [ ]:
# corpus_df.to_excel("Data/corpus.xlsx", index=False)

### partial answers

In [158]:
import pandas as pd


part_answer_df = pd.read_csv("Data/part_answers_df.csv")
part_answer_df["timestamp"] = pd.to_datetime(part_answer_df["timestamp"])
serp_df = pd.read_csv("Data/logs_compiled.csv")
serp_df["timestamp"] = pd.to_datetime(serp_df["timestamp"])

## linking clicks to which SERP the click took place in
associated_serp_ids = []

for _, row in part_answer_df.iterrows():
    associated_serp = serp_df.loc[
        (serp_df["uid"]==row["uid"]) 
        & (serp_df["topic_number"]==row["topic_number"]) 
        & (serp_df["timestamp"]<row["timestamp"])
    ]

    if len(associated_serp) == 0:
        print(row)
        associated_serp_ids.append(None)

    elif len(associated_serp) > 1:
        # print(associated_serp)
        time_diff = np.inf
        for _, serp in associated_serp.iterrows():
            # print(serp)
            time_diff_compute = row["timestamp"] - serp["timestamp"]
            if time_diff >= time_diff_compute.total_seconds():
                correct_serp = serp["serp_id"]
                time_diff = time_diff_compute.total_seconds()
        associated_serp_ids.append(correct_serp)
    else:
        associated_serp_ids.append(associated_serp["serp_id"].values[0])

part_answer_df["serp_id"] = associated_serp_ids

# linking the resource they clicked on before editing the answer
click_df = pd.read_csv("Data/clicked_results_df.csv")
click_df["timestamp"] = pd.to_datetime(click_df["timestamp"])
view_df = pd.read_csv("Data/viewed_results_df.csv")
view_df["timestamp"] = pd.to_datetime(view_df["timestamp"])

associated_click_time = []
for serp_id in part_answer_df["serp_id"].unique():
    part_answers = part_answer_df.loc[part_answer_df["serp_id"]==serp_id]
    SERP_clicks = click_df.loc[click_df["serp_id"]==serp_id] # all clicks in the SERP
    SERP_views = view_df.loc[(view_df["serp_id"]==serp_id)&(view_df["viewType"]=="resultExposureEnded")] # all views in the SERP
    # print(f"number of clicks: {len(SERP_clicks)} and number of view: {len(SERP_views)}")
    for _, row in part_answers.iterrows():
        answer_time = row["timestamp"]
        potential_clicks = SERP_clicks.loc[SERP_clicks["timestamp"]<answer_time] # clicks before the answer was entered
        potential_views = SERP_views.loc[SERP_views["timestamp"]<answer_time] # views before the answer was entered
        if len(potential_clicks)==0:
            print("Could not find any clicks before user ", row["uid"], "(", row["topic_number"],") entered an answer at ", answer_time)
            associated_click_time.append(None)
        else:
            last_click_time = potential_clicks["timestamp"].max() # time when the user made their last click 
            # views_after_click = potential_views.loc[potential_views["timestamp"]>last_click_time]
            # if len(views_after_click) > 0: # user viewed SERP snippets after their last click but before opening the answer box
            #     print("User ", row["uid"], "(", row["topic_number"],") looked at a snippet at ", views_after_click["timestamp"].min(), " which was after their last click at ", last_click_time, " but before entering an answer at ", answer_time)
            #     associated_click_time.append(None)
            # else:
            associated_click_time.append(last_click_time)

part_answer_df["associated_click_time"] = associated_click_time
part_answer_df.to_csv("Data/part_answers_df.csv", index=False, encoding="utf8")

Could not find any clicks before user  3 ( g3t1 ) entered an answer at  2026-05-19 14:51:28.300000
Could not find any clicks before user  3 ( g3t2 ) entered an answer at  2026-05-19 15:08:51.862000
Could not find any clicks before user  5 ( g3t1 ) entered an answer at  2026-05-19 14:53:36.619000
Could not find any clicks before user  5 ( g3t1 ) entered an answer at  2026-05-19 14:53:50.789000
Could not find any clicks before user  5 ( g3t1 ) entered an answer at  2026-05-19 14:53:58.694000
Could not find any clicks before user  5 ( g3t1 ) entered an answer at  2026-05-19 14:54:31.160000
Could not find any clicks before user  5 ( g3t1 ) entered an answer at  2026-05-19 14:54:52.469000
Could not find any clicks before user  5 ( g3t1 ) entered an answer at  2026-05-19 14:55:19.927000
Could not find any clicks before user  5 ( g3t1 ) entered an answer at  2026-05-19 14:57:18.033000
Could not find any clicks before user  5 ( g3t1 ) entered an answer at  2026-05-19 14:57:57.095000
Could not find any clicks before user  5 ( g3t1 ) entered an answer at  2026-05-19 14:58:30.927000
Could not find any clicks before user  5 ( g3t3 ) entered an answer at  2026-05-19 15:04:42.113000
Could not find any clicks before user  5 ( g3t2 ) entered an answer at  2026-05-19 15:21:23.766000
Could not find any clicks before user  5 ( g3t2 ) entered an answer at  2026-05-19 15:22:13.649000
Could not find any clicks before user  5 ( g3t2 ) entered an answer at  2026-05-19 15:22:57.080000
Could not find any clicks before user  6 ( g3t1 ) entered an answer at  2026-05-19 14:52:27.066000
Could not find any clicks before user  7 ( g3t2 ) entered an answer at  2026-05-19 14:53:08.193000
Could not find any clicks before user  7 ( g3t2 ) entered an answer at  2026-05-19 14:53:55.227000
Could not find any clicks before user  7 ( g3t3 ) entered an answer at  2026-05-19 14:57:21.552000
Could not find any clicks before user  7 ( g3t3 ) entered an answer at  2026-05-19 14:58:00.349000
Could not find any clicks before user  7 ( g3t3 ) entered an answer at  2026-05-19 14:58:37.823000
Could not find any clicks before user  7 ( g3t3 ) entered an answer at  2026-05-19 14:59:05.264000
Could not find any clicks before user  7 ( g3t3 ) entered an answer at  2026-05-19 14:59:35.237000
Could not find any clicks before user  7 ( g3t3 ) entered an answer at  2026-05-19 14:59:43.831000
Could not find any clicks before user  7 ( g3t1 ) entered an answer at  2026-05-19 15:03:43.531000
Could not find any clicks before user  7 ( g3t1 ) entered an answer at  2026-05-19 15:04:38.351000
Could not find any clicks before user  7 ( g3t1 ) entered an answer at  2026-05-19 15:05:33.869000
Could not find any clicks before user  8 ( g3t2 ) entered an answer at  2026-05-19 15:14:46.357000
Could not find any clicks before user  8 ( g3t2 ) entered an answer at  2026-05-19 15:14:59.115000
Could not find any clicks before user  8 ( g3t1 ) entered an answer at  2026-05-19 15:16:37.247000
Could not find any clicks before user  10 ( g4t1 ) entered an answer at  2026-05-19 11:02:48.094000
Could not find any clicks before user  10 ( g4t1 ) entered an answer at  2026-05-19 11:03:32.282000
Could not find any clicks before user  10 ( g4t1 ) entered an answer at  2026-05-19 11:03:49.442000
Could not find any clicks before user  10 ( g4t1 ) entered an answer at  2026-05-19 11:04:09.171000
Could not find any clicks before user  10 ( g4t1 ) entered an answer at  2026-05-19 11:04:50.866000
Could not find any clicks before user  10 ( g4t1 ) entered an answer at  2026-05-19 11:05:40.698000
Could not find any clicks before user  12 ( g4t3 ) entered an answer at  2026-05-19 11:17:42.945000
Could not find any clicks before user  14 ( g4t1 ) entered an answer at  2026-05-19 10:47:49.328000
Could not find any clicks before user  14 ( g4t1 ) entered an answer at  2026-05-19 10:49:57.203000
Could not find any clicks before user  14 ( g4t2 ) entered an answer at  2026-05-19 11:10:50.156000
Could not find any clicks before user  16 ( g4t1 ) entered an answer at  2026-05-19 10:46:55.760000
Could not find any clicks before user  17 ( g3t2 ) entered an answer at  2026-05-19 15:08:10.562000
Could not find any clicks before user  17 ( g3t2 ) entered an answer at  2026-05-19 15:13:25.390000
Could not find any clicks before user  17 ( g3t2 ) entered an answer at  2026-05-19 15:13:51.100000

In [159]:
len(part_answer_df.loc[pd.isna(part_answer_df["associated_click_time"])]), len(part_answer_df)

(44, 177)

In [160]:
len(part_answer_df["associated_click_time"].unique())

56

In [161]:
click_df = pd.read_csv("Data/clicked_results_df.csv")
click_df["timestamp"] = pd.to_datetime(click_df["timestamp"])

part_answer_df = pd.read_csv("Data/part_answers_df.csv")
part_answer_df["timestamp"] = pd.to_datetime(part_answer_df["timestamp"])
part_answer_df["associated_click_time"] = pd.to_datetime(part_answer_df["associated_click_time"])

relevance_df = pd.read_csv("Data/relevance.csv")

answer_list = []
answer_time_list = []
relevance = []
for _, row in click_df.iterrows():
    click_time = row["timestamp"]
    topic_num = row["topic_number"]
    relevant_urls = relevance_df.loc[relevance_df["topic_number"]==topic_num]["doc"].tolist()
    url = row["url"]
    relevance.append(int(url in relevant_urls))
    part_answers = part_answer_df.loc[part_answer_df["associated_click_time"]==click_time]
    if len(part_answers) == 0: # user did not interact with answer box after this click
        answer = None
        answer_time = None
    else:
        answer_time = part_answers["timestamp"].max() # taking the last instance of opening the answer box to enter an answer after a click
        answer = part_answers.loc[part_answers["timestamp"]==answer_time]["answer"].values[0]
    answer_list.append(answer)
    answer_time_list.append(answer_time)

click_df["relevance_score"] = relevance
click_df["answer"] = answer_list
click_df["answer_time"] = answer_time_list

In [162]:
import spacy

nlp = spacy.load("it_core_news_lg")

ref_ans = []
change_from_prev_answer = []

for uid in click_df["uid"].unique():
    user_sessions = click_df.loc[click_df["uid"]==uid]
    for topic_num in user_sessions["topic_number"].unique():
        prev_ans = None # start with no previous answer for a task
        clicks = user_sessions.loc[user_sessions["topic_number"]==topic_num].reset_index()
        for i, row in clicks.iterrows():
            current_ans = row["answer"] # the answer entered after a click
            if pd.isna(current_ans): # answer box is empty
                current_ans = ""
            current_ans = current_ans.lower()
            current_ans_tokens = [token.text for token in nlp(current_ans)]
            if i == 0: # first time opening the answer box for this task
                ans_diff = current_ans_tokens
            else:
                if pd.isna(prev_ans):
                    prev_ans = ""
                prev_ans = prev_ans.lower()
                prev_ans_tokens = [token.text for token in nlp(prev_ans)]
                ans_diff = list(set(current_ans_tokens).difference(set(prev_ans_tokens)))

            ref_ans.append(prev_ans)
            change_from_prev_answer.append(ans_diff)
            if pd.isna(row["answer_time"])==False: # if the user did open the answer box after current click
                prev_ans = current_ans # answered entered into the answer box after the current click becomes the reference answer for subsequent clicks

click_df["answer_previously"] = ref_ans
click_df["change_from_prev_ans"] = change_from_prev_answer

In [163]:
with open("Data/answer_set.json", 'r') as f:
        answer_set = json.load(f)

match_counts = []
matched_keywords = []
for _, row in click_df.iterrows():
        num_matches = 0
        answers = answer_set[row["topic_number"]]
        matched_answers = []
        if pd.isna(row["answer"]): # empty answer box
                if pd.isna(row["answer_time"]): # but user did not open the answer box
                        if pd.isna(row["answer_previously"]):
                                row_answer = "" # if the ref answer is also empty
                        else:
                                row_answer = row["answer_previously"] # take the answer already in the answer box
                else: # user did open the answer box
                        row_answer = "" # the answer box is empty
        else:
                row_answer = row["answer"]
        for answer_key in answers.keys():
                if answer_key.title() in row_answer.title():
                        matched_answers.append(answer_key)
                        num_matches += 1
                else:
                        for answer in answers[answer_key]:
                                if answer.title() in row_answer.title():
                                # print(row_answer, ";", answer)
                                        matched_answers.append(answer)
                                        num_matches += 1
                                        break
        # print(row["uid"], row["topic_number"], row_answer, num_matches)
        match_counts.append(num_matches)
        matched_keywords.append(matched_answers)

click_df["num_answer_matches"] = match_counts
click_df["matched_keywords"] = matched_keywords

reqd_keywords_map = {
        "g3t1": 1,
        "g3t2": 2,
        "g3t3": 5,
        "g4t1": 4,
        "g4t2": 2,
        "g4t3": 3
}
click_df["answer_match_ratio"] = [round(min(row["num_answer_matches"]/reqd_keywords_map[row["topic_number"]],1.00),2) for _, row in click_df.iterrows()]

In [164]:
effective_distillation = []
problems = {}

for uid in click_df["uid"].unique():
    user_clicks = click_df.loc[click_df["uid"]==uid]
    for topic_num in user_clicks["topic_number"].unique():
        session_clicks = user_clicks.loc[user_clicks["topic_number"]==topic_num].reset_index()
        session_clicks["answer"] = session_clicks["answer"].fillna(value="")
        session_clicks["answer_previously"] = session_clicks["answer_previously"].fillna(value="")
        # print(session_clicks)
        for i, row in session_clicks.iterrows():
            if row["relevance_score"]==0: # clicked on an irrelevant result
                if pd.isna(row["answer_time"]): # did not open the answer box
                    effective_distillation.append(1)
                else: # opened the answer box
                    if row["answer"].lower()==row["answer_previously"].lower(): # answer did not change
                        effective_distillation.append(1)
                    else:
                        effective_distillation.append(0) # changed the answer
            elif row["relevance_score"]==1: # clicked on a relevant result
                if i == 0: # first answering attempt
                    if row["answer_match_ratio"] > 0: # added at least one correct keyword
                        effective_distillation.append(1)
                    else: # did not add any correct keywords
                        effective_distillation.append(0)
                else: # subsequent answering attempts
                    if row["answer"] == row["answer_previously"]: # answer did not change
                        if row["answer_match_ratio"] == 1: # already have full correct answer
                            effective_distillation.append(1)
                        else: # answer is not fully correct yet
                            effective_distillation.append(0)
                    else: # changed answer
                        prev_row = session_clicks.iloc[i-1]
                        if row["answer_match_ratio"] > prev_row["answer_match_ratio"]: # improved their answer
                            effective_distillation.append(1)
                        else: # answer did not improve
                            effective_distillation.append(0)
            else:
                print("Result is neither relevant nor irrelevant??")

# print(effective_distillation)
click_df["effective_distillation"] = effective_distillation

In [165]:
click_df.to_csv("Data/information_distillation_df.csv", index=False, encoding="utf8")

In [166]:
click_df.loc[(click_df["uid"]==9)]

,uid,topic_number,query,url,rank,timestamp,serp_id,relevance_score,answer,answer_time,answer_previously,change_from_prev_ans,num_answer_matches,matched_keywords,answer_match_ratio,effective_distillation
32,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.focusjunior.it/scienza/spazio/laik...,2,2026-05-19 10:43:58.958,serp54,1,None,NaT,None,[],0,[],0.0,0
33,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.nationalgeographic.it/spazio/2021/...,3,2026-05-19 10:44:41.360,serp54,1,None,NaT,,[],0,[],0.0,0
34,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.focusjunior.it/scienza/spazio/stel...,6,2026-05-19 10:45:32.387,serp54,0,None,NaT,,[],0,[],0.0,1
35,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.storicang.it/foto-del-giorno/laika...,1,2026-05-19 10:46:16.185,serp54,1,None,NaT,,[],0,[],0.0,0
36,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.focusjunior.it/scienza/spazio/laik...,2,2026-05-19 10:46:57.627,serp54,1,Il primo animale mandato nello spazio è state ...,2026-05-19 10:51:04.098,,"[nello, primo, una, animale, nome, laika, mand...",1,[Laika],0.5,1
37,9,g4t1,Come si chiamano i satteliti maggiori di Giove,https://www.astronomitaly.com/blog/astronomy-p...,1,2026-05-19 10:52:26.337,serp55,1,None,NaT,None,[],0,[],0.0,0
38,9,g4t1,Come si chiamano i satteliti maggiori di Giove,https://starwalk.space/it/news/jupiter-galilea...,2,2026-05-19 10:53:18.182,serp55,1,None,NaT,,[],0,[],0.0,0
39,9,g4t1,Come si chiamano i satteliti maggiori di Giove,https://edu.inaf.it/astrofoto/giove-satelliti-...,3,2026-05-19 10:53:42.819,serp55,1,None,NaT,,[],0,[],0.0,0
40,9,g4t1,Come si chiamano i satteliti maggiori di Giove,https://www.focusjunior.it/news/news-e-curiosi...,4,2026-05-19 10:54:25.155,serp55,0,None,NaT,,[],0,[],0.0,1
41,9,g4t1,Come si chiamano i satelliti maggiori di Giove,https://www.astronomitaly.com/blog/astronomy-p...,1,2026-05-19 10:56:01.873,serp56,1,NaN,2026-05-19 10:56:38.893,,[],0,[],0.0,0
42,9,g4t1,Come si chiamano i satelliti maggiori di Giove,https://www.astronomitaly.com/blog/astronomy-p...,1,2026-05-19 10:56:39.796,serp56,1,None,NaT,,[],0,[],0.0,0
43,9,g4t1,Come si chiamano i satelliti maggiori di Giove,https://www.focusjunior.it/news/lallineamento-...,5,2026-05-19 10:57:32.698,serp56,0,None,NaT,,[],0,[],0.0,1
44,9,g4t1,Come si chiamano i satelliti maggiori di Giove,https://edu.inaf.it/astrofoto/giove-satelliti-...,3,2026-05-19 10:58:05.587,serp56,1,None,NaT,,[],0,[],0.0,0
45,9,g4t1,Come si chiamano i satelliti maggiori di Giove,https://www.astronomitaly.com/blog/astronomy-p...,1,2026-05-19 10:58:48.575,serp56,1,Ganimede e Callisto,2026-05-19 11:00:04.860,,"[callisto, ganimede, e]",2,"[ganimede, callisto]",0.5,1
46,9,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.focusjunior.it/scienza/spazio/stel...,1,2026-05-19 11:03:22.373,serp57,0,None,NaT,None,[],0,[],0.0,1
47,9,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.castfvg.it/galassie/gruppo_locale/...,3,2026-05-19 11:04:28.011,serp57,1,None,NaT,,[],0,[],0.0,0
48,9,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,https://123stella.astronomiamo.it/Fase.aspx?Ar...,2,2026-05-19 11:04:55.643,serp57,0,None,NaT,,[],0,[],0.0,1
49,9,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,https://123stella.astronomiamo.it/Fase.aspx?Ar...,2,2026-05-19 11:05:22.754,serp57,0,None,NaT,,[],0,[],0.0,1
50,9,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.castfvg.it/galassie/gruppo_locale/...,3,2026-05-19 11:05:36.905,serp57,1,None,NaT,,[],0,[],0.0,0
51,9,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,https://123stella.astronomiamo.it/Fase.aspx?Ar...,2,2026-05-19 11:06:07.472,serp57,0,None,NaT,,[],0,[],0.0,1
52,9,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.focusjunior.it/content/uploads/sit...,4,2026-05-19 11:07:15.094,serp57,0,None,NaT,,[],0,[],0.0,1
53,9,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.focusjunior.it/scienza/spazio/stel...,1,2026-05-19 11:07:20.975,serp57,0,None,NaT,,[],0,[],0.0,1
54,9,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.focusjunior.it/content/uploads/sit...,4,2026-05-19 11:08:14.999,serp57,0,None,NaT,,[],0,[],0.0,1
55,9,g4t3,3 galassie oltre la nostra,https://www.focusjunior.it/scienza/spazio/univ...,6,2026-05-19 11:10:14.279,serp59,0,None,NaT,,[],0,[],0.0,1
56,9,g4t3,3 galassie oltre la nostra,https://www.castfvg.it/galassie/gruppo_locale/...,5,2026-05-19 11:11:43.196,serp59,1,None,NaT,,[],0,[],0.0,0
57,9,g4t3,3 galassie oltre la nostra,https://www.focusjunior.it/scienza/spazio/stel...,9,2026-05-19 11:12:12.633,serp59,0,None,NaT,,[],0,[],0.0,1
58,9,g4t3,3 galassie oltre la nostra,https://spaziotempo.altervista.org/gruppo-locale/,7,2026-05-19 11:14:04.823,serp59,1,NaN,2026-05-19 11:14:52.109,,[],0,[],0.0,0
59,9,g4t3,3 galassie oltre la nostra,https://www.media.inaf.it/2014/03/12/un-consig...,1,2026-05-19 11:15:07.153,serp59,1,None,NaT,,[],0,[],0.0,0
60,9,g4t3,3 galassie oltre la nostra,https://www.focus.it/scienza/spazio/hubble-nel...,4,2026-05-19 11:15:22.861,serp59,1,None,NaT,,[],0,[],0.0,0
61,9,g4t3,3 galassie oltre la nostra,https://www.focus.it/scienza/spazio/la-via-lat...,2,2026-05-19 11:15:39.675,serp59,1,None,NaT,,[],0,[],0.0,0
62,9,g4t3,3 galassie oltre la nostra,https://www.focusjunior.it/scienza/spazio/stel...,9,2026-05-19 11:16:17.601,serp59,0,None,NaT,,[],0,[],0.0,1
63,9,g4t3,3 galassie oltre la nostra,https://www.focusjunior.it/scienza/spazio/stel...,9,2026-05-19 11:16:30.795,serp59,0,Andromeda Triangolo Orsa Minore,2026-05-19 11:20:01.186,,"[andromeda, minore, orsa, triangolo]",3,"[Andromeda, Triangolo, Orsa Minore]",1.0,0

## Final answers

In [7]:
import pandas as pd
import json
# import spacy

# nlp = spacy.load("it_core_news_lg")

final_answer_df = pd.read_csv("Data/final_answer_df.csv")
final_answer_df["timestamp"] = pd.to_datetime(final_answer_df["timestamp"])
final_answer_df = final_answer_df[["uid", "topic_number", "prompt", "answer", "TaskStartOrEnd", "timestamp"]]

final_answers = []

for _, row in final_answer_df[final_answer_df["TaskStartOrEnd"]=="TaskEnd"].iterrows():
    uid = row["uid"]
    topic_num = row["topic_number"]
    start_time = final_answer_df.loc[(final_answer_df["uid"]==uid) & (final_answer_df["topic_number"]==topic_num) & (final_answer_df["TaskStartOrEnd"]=="TaskStart")]["timestamp"].values[0]
    task_duration = (row["timestamp"] - start_time).total_seconds()/60
    final_answers.append([uid, topic_num, row["prompt"], row["answer"], start_time, row["timestamp"], task_duration])

final_answer_df = pd.DataFrame(final_answers, columns=["uid", "topic_number", "prompt", "answer", "TaskStartTime", "TaskEndTime", "TaskDuration"])
# final_answer_df

with open("Data/answer_set.json", 'r') as f:
        answer_set = json.load(f)

reqd_keywords_map = {
        "g3t1": 1,
        "g3t2": 2,
        "g3t3": 5,
        "g4t1": 4,
        "g4t2": 2,
        "g4t3": 3
}

match_counts = []
matched_keywords = []
for _, row in final_answer_df.iterrows():
        num_matches = 0
        answers = answer_set[row["topic_number"]]
        matched_answers = []
        for answer_key in answers.keys():
                if answer_key.title() in row["answer"].title():
                        matched_answers.append(answer_key)
                        num_matches += 1
                else:
                        for answer in answers[answer_key]:
                                if answer.title() in row["answer"].title():
                                # print(row["answer"], ";", answer)
                                        matched_answers.append(answer)
                                        num_matches += 1
                                        break
        # print(row["uid"], row["topic_number"], row["answer"], num_matches)
        match_counts.append(num_matches)
        matched_keywords.append(matched_answers)

final_answer_df["num_answer_matches"] = match_counts
final_answer_df["matched_keywords"] = matched_keywords
final_answer_df["answer_match_ratio"] = [round(min(row["num_answer_matches"]/reqd_keywords_map[row["topic_number"]],1.00),2) for _, row in final_answer_df.iterrows()]

In [8]:
final_answer_df.head()

,uid,topic_number,prompt,answer,TaskStartTime,TaskEndTime,TaskDuration,num_answer_matches,matched_keywords,answer_match_ratio
0,1,g3t3,Quali sono 5 animali tipici dell'India?,Rinoceronte tigre Leone stambecco cervo,2026-05-19 14:48:04.522,2026-05-19 14:56:19.153,8.243850,4,"[tigre, rinoceronte, leone, cervo]",0.8
1,1,g3t2,Qual è il nome del simbolo al centro della ban...,Il simbolo della bandiera rappresenta una ruota,2026-05-19 14:56:45.133,2026-05-19 15:06:18.848,9.561917,1,[ruota],0.5
2,1,g3t1,Come si chiama il fiume sacro agli indiani?,Il fiume gange,2026-05-19 15:06:45.708,2026-05-19 15:10:10.812,3.418400,1,[gange],1.0
3,2,g3t3,Quali sono 5 animali tipici dell'India?,"Tigre,leone,rinoceronte,barasingha,blackbuck.",2026-05-19 14:48:38.961,2026-05-19 14:58:07.578,9.476950,5,"[tigre, rinoceronte, leone, barasingha, blackb...",1.0
4,2,g3t2,Qual è il nome del simbolo al centro della ban...,Ruota,2026-05-19 14:58:35.224,2026-05-19 15:10:30.790,11.926100,1,[ruota],0.5

In [9]:
final_answer_df.to_csv("Data/final_answer_df.csv", index=False, encoding='utf8')