In [1]:
import json
import pandas as pd
import glob
import numpy as np
import driver

In [ ]:
query_df = pd.DataFrame()
query_actions_df = pd.DataFrame() 
serp_df = pd.DataFrame()
clicked_results_df = pd.DataFrame()
viewed_results_df = pd.DataFrame()
final_answer_df = pd.DataFrame()

for file_name in glob.glob("Data/3rd/*_FULL.log"):
    # print(file_name)
    with open(file_name, 'r') as f:
        result = [json.loads(x) for x in f.readlines()]
    
    # query actions
    query_temp_df = driver.get_queries(result)
    query_df = pd.concat([query_df, query_temp_df], ignore_index=True)

    # query actions
    query_actions_temp_df = driver.get_query_actions(result)
    query_actions_df = pd.concat([query_actions_df, query_actions_temp_df], ignore_index=True)

    # SERPs generated
    serp_temp_df = driver.get_generated_serps(result)
    serp_df = pd.concat([serp_df, serp_temp_df], ignore_index=True)

    # Clicked results
    clicked_results_temp_df = driver.get_clicked_results(result)
    clicked_results_df = pd.concat([clicked_results_df, clicked_results_temp_df], ignore_index=True)

    # Viewed results
    viewed_results_temp_df = driver.get_viewed_results(result) 
    viewed_results_df = pd.concat([viewed_results_df, viewed_results_temp_df])

    # final answers
    final_answer_temp_df = driver.get_final_answers(result)
    final_answer_df = pd.concat([final_answer_df, final_answer_temp_df], ignore_index=True)

for file_name in glob.glob("Data/4th/*_FULL.log"):
    # print(file_name)
    with open(file_name, 'r') as f:
        result = [json.loads(x) for x in f.readlines()]
    
    # query actions
    query_temp_df = driver.get_queries(result)
    query_df = pd.concat([query_df, query_temp_df], ignore_index=True)

    # query actions
    query_actions_temp_df = driver.get_query_actions(result)
    query_actions_df = pd.concat([query_actions_df, query_actions_temp_df], ignore_index=True)

    # SERPs generated
    serp_temp_df = driver.get_generated_serps(result)
    serp_df = pd.concat([serp_df, serp_temp_df], ignore_index=True)

    # Clicked results
    clicked_results_temp_df = driver.get_clicked_results(result)
    clicked_results_df = pd.concat([clicked_results_df, clicked_results_temp_df], ignore_index=True)

    # Viewed results
    viewed_results_temp_df = driver.get_viewed_results(result) 
    viewed_results_df = pd.concat([viewed_results_df, viewed_results_temp_df])

    # final answers
    final_answer_temp_df = driver.get_final_answers(result)
    final_answer_df = pd.concat([final_answer_df, final_answer_temp_df], ignore_index=True)


## assigning qid
query_df["qid"] = ["q"+str(i) for i in range(1, len(query_df)+1)]
query_df = query_df[["uid", "topic_number", "qid", "query", "timestamp"]]


## assigning serp id
serp_num = 0
serp_id_list = []

for _, row in serp_df.iterrows():
    if row["rank"]==1 or pd.isna(row["rank"]):
        serp_num += 1
    serp_id_list.append("serp"+str(serp_num))

serp_df["serp_id"] = serp_id_list
serp_df = serp_df[["uid", "topic_number", "query", "serp_id", "url", "title", "snippet", "rank", "timestamp"]]

## removing duplicates
final_answer_df = final_answer_df.drop_duplicates(ignore_index=True)

## query formulation

In [3]:
query_df.head()

,uid,topic_number,qid,query,timestamp
0,17,g3t3,q1,Quali sono i 5 animali tipici del india,2026-05-19 14:50:53.443
1,17,g3t2,q2,Quale il simbolo del la bandiera del india,2026-05-19 15:00:09.059
2,17,g3t2,q3,qual e la bandiera dell india,2026-05-19 15:07:43.639
3,17,g3t2,q4,Quale ilsimbolo al centro della bandiera dell ...,2026-05-19 15:12:24.264
4,17,g3t1,q5,Il nome del fiume sacro,2026-05-19 15:26:21.050

In [4]:
serp_df.head()

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
0,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:50:54.636
1,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,2026-05-19 14:50:54.638
2,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://animalia.bio/it/india-animals,India - Animalia,"\n Flora e fauna ... L'India, ufficia...",3.0,2026-05-19 14:50:54.640
3,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/news/news-e-curiosi...,Quali sono gli sport più seguiti e praticati a...,"\n Il cricket è seguito da circa 2,5 ...",4.0,2026-05-19 14:50:54.644
4,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.goasia.it/geografia-natura-e-clima...,"Geografia, natura e clima dell'India - Go Asia",\n Molteplici varietà di animali sono...,5.0,2026-05-19 14:50:54.645

In [5]:
serp_df.loc[serp_df["rank"].isna()]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
267,5,g3t1,come si chiama il fiume sacro agli indianischen,serp33,None,None,None,NaN,2026-05-19 14:52:35.518
268,5,g3t1,come si chiama il fiume sacro agli indianischen,serp34,None,None,None,NaN,2026-05-19 14:52:46.904
283,5,g3t3,Qali sono 5 animali tipici dell india,serp37,None,None,None,NaN,2026-05-19 15:01:44.186
284,5,g3t3,Qali sono 5 animali tipici dell india,serp38,None,None,None,NaN,2026-05-19 15:01:47.876
285,5,g3t3,Qali sono 5 animali tipici dell india,serp39,None,None,None,NaN,2026-05-19 15:01:58.337
306,5,g3t2,Qal e il,serp42,None,None,None,NaN,2026-05-19 15:15:44.081
327,5,g3t2,Qal e il,serp45,None,None,None,NaN,2026-05-19 15:21:02.658
451,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp61,None,None,None,NaN,2026-05-19 15:04:52.511
452,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp62,None,None,None,NaN,2026-05-19 15:05:05.152
453,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp63,None,None,None,NaN,2026-05-19 15:08:36.757
454,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp64,None,None,None,NaN,2026-05-19 15:09:48.390
642,12,g4t3,3 galassie olt4e la nostra,serp84,None,None,None,NaN,2026-05-19 11:16:50.790
643,12,g4t3,3 galassie olt4e la nostra,serp85,None,None,None,NaN,2026-05-19 11:16:54.735
819,15,g4t3,qualifiche f1,serp103,None,None,None,NaN,2026-05-19 10:55:32.846
841,15,g4t3,Nomi di alre galassie,serp106,None,None,None,NaN,2026-05-19 11:06:11.428
961,9,g4t3,3 galassie oly,serp121,None,None,None,NaN,2026-05-19 11:09:41.822

In [6]:
df = pd.DataFrame(serp_df.loc[(serp_df["rank"]==1)|(serp_df["rank"].isna())].groupby(["uid", "topic_number"])["query"].value_counts()).reset_index()
df.loc[df["count"]>1]

    uid topic_number                                              query  count
13    4         g3t2  Che cosa rappresenta l'imagine del simbolo ban...      3
14    4         g3t2                        Quale il simbolo dell'India      2
16    5         g3t1         come si chiama il fiume sacro agli indiani      2
17    5         g3t1    come si chiama il fiume sacro agli indianischen      2
19    5         g3t2                                           Qal e il      2
20    5         g3t2              Qual eil simbolo della bandiera india      2
22    5         g3t3              Qali sono 5 animali tipici dell india      3
23    5         g3t3             Quali sono 5 animali tipici dell india      2
25    6         g3t2                              Simbolo andiera India      2
31    7         g3t2           il simbolo della baniera dell dell'india      2
33    8         g3t1                                  Fiume sacro India      2
34    8         g3t2  Come si chiama il nome dell disegno nell centr...      2
39    8         g3t3                    Quali sono 5 animali dell India      2
41    9         g4t1     Come si chiamano i satteliti maggiori di Giove      2
47   10         g4t1    Come  si chiamano i satelliti maggiori di Giove      2
59   12         g4t3                         3 galassie olt4e la nostra      2
67   14         g4t1              come si chiamano i satelliti di giove      2
76   15         g4t2  Qual è stato il primo animale nello spazio e c...      3
82   16         g4t1    Come si chiamano i satelliti  maggiori di Giove      2
85   16         g4t3  Quali sono altre nomi di tre galassie in oltre...      2
88   17         g3t2         Quale il simbolo del la bandiera del india      2
91   17         g3t3            Quali sono i 5 animali tipici del india      2

In [7]:
q_df = pd.DataFrame(query_df.groupby(["uid", "topic_number"])["query"].value_counts()).reset_index()
q_df.loc[q_df["count"]>1]

    uid topic_number                                              query  count
13    4         g3t2  Che cosa rappresenta l'imagine del simbolo ban...      2
14    4         g3t2                        Quale il simbolo dell'India      2
16    5         g3t1         come si chiama il fiume sacro agli indiani      2
17    5         g3t1    come si chiama il fiume sacro agli indianischen      2
19    5         g3t2              Qual eil simbolo della bandiera india      2
22    5         g3t3              Qali sono 5 animali tipici dell india      3
23    5         g3t3             Quali sono 5 animali tipici dell india      2
29    7         g3t2           il simbolo della baniera dell dell'india      2
31    8         g3t1                                  Fiume sacro India      2
32    8         g3t2  Come si chiama il nome dell disegno nell centr...      2
45   10         g4t1    Come  si chiamano i satelliti maggiori di Giove      2
49   11         g4t2  Qual è stato il primo animale nello spazio e c...      2
57   12         g4t3                         3 galassie olt4e la nostra      2
74   15         g4t2  Qual è stato il primo animale nello spazio e c...      3
75   15         g4t3  Quali sono i nomi di altre 3 galassie oltre la...      2
79   16         g4t1    Come si chiamano i satelliti  maggiori di Giove      2
82   16         g4t3  Quali sono altre nomi di tre galassie in oltre...      2

In [8]:
q_df.loc[q_df["count"]==3]["query"].tolist()

['Qali sono 5 animali tipici dell india',
 'Qual è stato il primo animale nello spazio e come si chiamava']

In [9]:
query_df.loc[query_df["uid"]==15]

,uid,topic_number,qid,query,timestamp
91,15,g4t2,q92,Qual è stato il primo animale nello spazio e c...,2026-05-19 10:44:45.385
92,15,g4t2,q93,Qual è stato il primo animale nello spazio e c...,2026-05-19 10:46:43.174
93,15,g4t2,q94,Qual è stato il primo animale nello spazio e c...,2026-05-19 10:51:12.928
94,15,g4t3,q95,qualifiche f1,2026-05-19 10:55:31.771
95,15,g4t3,q96,Quali sono i nomi di altre 3 galassie oltre la...,2026-05-19 10:57:32.254
96,15,g4t3,q97,Quali sono i nomi di altre 3 galassie oltre la...,2026-05-19 11:03:56.641
97,15,g4t3,q98,Quali sono i nomi di altre 3 galassie oltre la...,2026-05-19 11:04:18.615
98,15,g4t3,q99,Nomi di alre galassie,2026-05-19 11:06:09.998
99,15,g4t1,q100,Come si chiamano i satelliti maggiori di Giove,2026-05-19 11:15:45.762

In [10]:
serp_df["uid"].unique()

<IntegerArray>
[17, 18, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 9]
Length: 18, dtype: Int64

In [11]:
query_df.loc[query_df["uid"]==4]

,uid,topic_number,qid,query,timestamp
22,4,g3t2,q23,Che cosa rappresenta l'imagine del simbolo ban...,2026-05-19 14:54:57.981
23,4,g3t2,q24,Che cosa rappresenta l'imagine del simbolo ban...,2026-05-19 14:59:35.687
24,4,g3t2,q25,Quale il simbolo dell'India,2026-05-19 15:03:52.949
25,4,g3t2,q26,Quale il simbolo dell'India,2026-05-19 15:05:57.147
26,4,g3t3,q27,5 animali tipici dell'India,2026-05-19 15:14:08.813
27,4,g3t1,q28,Fiume sacro indiano,2026-05-19 15:20:20.872

In [12]:
serp_df.loc[(serp_df["uid"]==4) & (serp_df["query"]=="Che cosa rappresenta l'imagine del simbolo banderia dell'India")]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
178,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 14:54:59.384
179,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... La storia della b...",2.0,2026-05-19 14:54:59.386
180,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focus.it/ambiente/animali/8-cose-c...,8 cose che (forse) non sai sulle vacche sacre ...,"\n Mar 31, 2019 ... Per molti indù, c...",3.0,2026-05-19 14:54:59.387
181,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focusjunior.it/news/holi-festival-...,"Holi festival, la festa dei colori - FocusJuni...","\n Mar 23, 2024 ... Si chiama Holi ed...",4.0,2026-05-19 14:54:59.392
182,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focusjunior.it/scuola/geografia/le...,Quali sono le 10 Nazioni più popolate del mond...,"\n Apr 16, 2017 ... Il Pakistan , che...",5.0,2026-05-19 14:54:59.394
183,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focusjunior.it/scuola/geografia/10...,10 cose che (forse) non sai sull'Europa - Focu...,"\n Dal nome, alla bandiera passando p...",6.0,2026-05-19 14:54:59.396
184,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://it.gov-civ-guarda.pt/flag-india,"Bandiera dell'India | Storia, design e signifi...",\n ... simbolo distintivo che potesse...,7.0,2026-05-19 14:54:59.398
185,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focusjunior.it/news/plogging-corre...,"Plogging, cos'è e perché aiuta il pianeta - Fo...",\n L'amore per l'ambiente ha portato ...,8.0,2026-05-19 14:54:59.399
186,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focusjunior.it/scuola/storia/rivol...,"Rivoluzione: quando il popolo si ribella, la s...","\n May 20, 2019 ... Il 22 settembre 1...",9.0,2026-05-19 14:54:59.401
187,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focusjunior.it/scuola/storia/chi-s...,Chi sono i curdi? - FocusJunior.it,"\n La bandiera curda, che oggi svento...",10.0,2026-05-19 14:54:59.403
188,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 14:59:37.155
189,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... La storia della b...",2.0,2026-05-19 14:59:37.157
190,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://www.focus.it/ambiente/animali/8-cose-c...,8 cose che (forse) non sai sulle vacche sacre ...,"\n Mar 31, 2019 ... Per molti indù, c...",3.0,2026-05-19 14:59:37.160
191,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://www.focusjunior.it/news/holi-festival-...,"Holi festival, la festa dei colori - FocusJuni...","\n Mar 23, 2024 ... Si chiama Holi ed...",4.0,2026-05-19 14:59:37.162
192,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://www.focusjunior.it/scuola/geografia/le...,Quali sono le 10 Nazioni più popolate del mond...,"\n Apr 16, 2017 ... Il Pakistan , che...",5.0,2026-05-19 14:59:37.165
193,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://www.focusjunior.it/scuola/geografia/10...,10 cose che (forse) non sai sull'Europa - Focu...,"\n Dal nome, alla bandiera passando p...",6.0,2026-05-19 14:59:37.173
194,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://it.gov-civ-guarda.pt/flag-india,"Bandiera dell'India | Storia, design e signifi...",\n ... simbolo distintivo che potesse...,7.0,2026-05-19 14:59:37.175
195,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://www.focusjunior.it/news/plogging-corre...,"Plogging, cos'è e perché aiuta il pianeta - Fo...",\n L'amore per l'ambiente ha portato ...,8.0,2026-05-19 14:59:37.178
196,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://www.focusjunior.it/scuola/storia/rivol...,"Rivoluzione: quando il popolo si ribella, la s...","\n May 20, 2019 ... Il 22 settembre 1...",9.0,2026-05-19 14:59:37.180
197,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://www.focusjunior.it/scuola/storia/chi-s...,Chi sono i curdi? - FocusJunior.it,"\n La bandiera curda, che oggi svento...",10.0,2026-05-19 14:59:37.182
218,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 15:10:33.501
219,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... La storia della b...",2.0,2026-05-19 15:10:33.507
220,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://www.focus.it/ambiente/animali/8-cose-c...,8 cose che (forse) non sai sulle vacche sacre ...,"\n Mar 31, 2019 ... Per molti indù, c...",3.0,2026-05-19 15:10:33.519
221,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://www.focusjunior.it/news/holi-festival-...,"Holi festival, la festa dei colori - FocusJuni...","\n Mar 23, 2024 ... Si chiama Holi ed...",4.0,2026-05-19 15:10:33.523
222,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://www.focusjunior.it/scuola/geografia/le...,Quali sono le 10 Nazioni più popolate del mond...,"\n Apr 16, 2017 ... Il Pakistan , che...",5.0,2026-05-19 15:10:33.526
223,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://www.focusjunior.it/scuola/geografia/10...,10 cose che (forse) non sai sull'Europa - Focu...,"\n Dal nome, alla bandiera passando p...",6.0,2026-05-19 15:10:33.530
224,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://it.gov-civ-guarda.pt/flag-india,"Bandiera dell'India | Storia, design e signifi...",\n ... simbolo distintivo che potesse...,7.0,2026-05-19 15:10:33.535
225,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://www.focusjunior.it/news/plogging-corre...,"Plogging, cos'è e perché aiuta il pianeta - Fo...",\n L'amore per l'ambiente ha portato ...,8.0,2026-05-19 15:10:33.540
226,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://www.focusjunior.it/scuola/storia/rivol...,"Rivoluzione: quando il popolo si ribella, la s...","\n May 20, 2019 ... Il 22 settembre 1...",9.0,2026-05-19 15:10:33.545
227,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://www.focusjunior.it/scuola/storia/chi-s...,Chi sono i curdi? - FocusJunior.it,"\n La bandiera curda, che oggi svento...",10.0,2026-05-19 15:10:33.551

In [13]:
serp_df.loc[(serp_df["uid"]==4)]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
178,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 14:54:59.384
179,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... La storia della b...",2.0,2026-05-19 14:54:59.386
180,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focus.it/ambiente/animali/8-cose-c...,8 cose che (forse) non sai sulle vacche sacre ...,"\n Mar 31, 2019 ... Per molti indù, c...",3.0,2026-05-19 14:54:59.387
181,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focusjunior.it/news/holi-festival-...,"Holi festival, la festa dei colori - FocusJuni...","\n Mar 23, 2024 ... Si chiama Holi ed...",4.0,2026-05-19 14:54:59.392
182,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focusjunior.it/scuola/geografia/le...,Quali sono le 10 Nazioni più popolate del mond...,"\n Apr 16, 2017 ... Il Pakistan , che...",5.0,2026-05-19 14:54:59.394
...,...,...,...,...,...,...,...,...,...
252,4,g3t1,Fiume sacro indiano,serp31,https://it.renovables.blog/acqua/il-sacro-fium...,Alla scoperta del Gange: il fiume sacro e inqu...,"\n La sorgente del fiume Gange, noto ...",6.0,2026-05-19 15:20:22.204
253,4,g3t1,Fiume sacro indiano,serp31,https://www.consciousjourneys.com/it/approfond...,"Varanasi, la città sacra per gli induisti sul ...",\n Varanasi è un'importante città ind...,7.0,2026-05-19 15:20:22.204
254,4,g3t1,Fiume sacro indiano,serp31,https://www.cinziamalaguti.it/fiumi-sacri-il-g...,Fiumi sacri: il Gange - Esperienziando Vitae,\n Il Gange scorre nel Nord dell'Indi...,8.0,2026-05-19 15:20:22.205
255,4,g3t1,Fiume sacro indiano,serp31,https://www.skuola.net/geografia-medie/india-d...,"L'India: un viaggio tra cultura, geografia e t...","\n Jun 28, 2014 ... Alla costa indian...",9.0,2026-05-19 15:20:22.206
256,4,g3t1,Fiume sacro indiano,serp31,https://www.focusjunior.it/animali/enciclopedi...,"Il gruccione, poco conosciuto ma davvero bello...","\n Mar 25, 2014 ... ... India e Sri L...",10.0,2026-05-19 15:20:22.207

In [14]:
relevance = pd.read_csv("Data/relevance.csv")
relevance_score = []

for _, row in serp_df.iterrows():
    relevant_docs = relevance.loc[relevance["tid"]==row["topic_number"]]["doc"].tolist()
    if row["url"] in relevant_docs:
        relevance_score.append(1)
    else:
        relevance_score.append(0)

serp_df["relevance_score"] = relevance_score

In [15]:
temp = serp_df.loc[serp_df["rank"]<=10].groupby(["serp_id"])["relevance_score"].sum()/10
df = pd.DataFrame(temp).reset_index()
df.columns = ["serp_id", "precision@10"]
df["query"] = [serp_df.loc[serp_df["serp_id"]==serp_id]["query"].values[0] for serp_id in df["serp_id"]]
df["tid"] = [serp_df.loc[serp_df["serp_id"]==serp_id]["topic_number"].values[0] for serp_id in df["serp_id"]]
df["uid"] = [serp_df.loc[serp_df["serp_id"]==serp_id]["uid"].values[0] for serp_id in df["serp_id"]]
df = df[["uid", "tid", "serp_id", "query", "precision@10"]]
df.to_csv("Data/query_formulation_df.csv", index=False)

In [16]:
df

,uid,tid,serp_id,query,precision@10
0,17,g3t3,serp1,Quali sono i 5 animali tipici del india,0.5
1,18,g3t2,serp10,Quale il nome del simbolo al centro della band...,0.3
2,15,g4t2,serp100,Qual è stato il primo animale nello spazio e c...,0.0
3,15,g4t2,serp101,Qual è stato il primo animale nello spazio e c...,0.0
4,15,g4t2,serp102,Qual è stato il primo animale nello spazio e c...,0.0
...,...,...,...,...,...
101,14,g4t3,serp95,Gli altri nomi delle galassie,0.0
102,14,g4t3,serp96,Galassie oltre la nostra,0.0
103,14,g4t2,serp97,"Come si chia,",0.0
104,14,g4t2,serp98,Come si chiama il primo animale che e,0.0
105,14,g4t2,serp99,Come si chiama il primo animale che e stato ne...,0.0

In [17]:
effective_query = df.loc[df["precision@10"]>=0.8]["serp_id"].tolist() # above 3rd quartile

In [18]:
serp_df["effective_query"] = [int(serp_id in effective_query) for serp_id in serp_df["serp_id"]]

In [19]:
serp_df.loc[(serp_df["effective_query"]==0)&((serp_df["rank"]==1) | (serp_df["rank"].isna()))]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,relevance_score,effective_query
0,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:50:54.636,1,0
10,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:52:45.059,1,0
20,17,g3t2,Quale il simbolo del la bandiera del india,serp3,https://liceoberchet.edu.it/ricerche/geo4d_03/...,India Britannica,\n Bandiera di stato a terra dal 2 ag...,1.0,2026-05-19 15:00:11.086,1,0
27,17,g3t2,Quale il simbolo del la bandiera del india,serp4,https://liceoberchet.edu.it/ricerche/geo4d_03/...,India Britannica,\n Bandiera di stato a terra dal 2 ag...,1.0,2026-05-19 15:01:27.269,1,0
34,17,g3t2,qual e la bandiera dell india,serp5,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... ... le persone e ...",1.0,2026-05-19 15:07:44.856,1,0
...,...,...,...,...,...,...,...,...,...,...,...
939,9,g4t1,Come si chiamano i satteliti maggiori di Giove,serp118,https://www.astronomitaly.com/blog/astronomy-p...,"Io, Europa, Ganimede e Callisto: guida ai 4 sa...","\n Mar 19, 2024 ... ... dei Medici, e...",1.0,2026-05-19 10:53:13.348,0,0
945,9,g4t1,Come si chiamano i satelliti maggiori di Giove,serp119,https://www.astronomitaly.com/blog/astronomy-p...,"Io, Europa, Ganimede e Callisto: guida ai 4 sa...","\n Mar 19, 2024 ... Io, Europa, Ganim...",1.0,2026-05-19 10:55:55.513,0,0
951,9,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,serp120,https://www.focusjunior.it/scienza/spazio/stel...,10 cose (+3) che forse non sai sulle stelle - ...,"\n Informazioni scientifiche, miti e ...",1.0,2026-05-19 11:02:49.295,0,0
961,9,g4t3,3 galassie oly,serp121,None,None,None,NaN,2026-05-19 11:09:41.822,0,0
962,9,g4t3,3 galassie oltre la nostra,serp122,https://www.media.inaf.it/2014/03/12/un-consig...,Un Consiglio dei Giganti per il Gruppo Locale ...,"\n Mar 12, 2014 ... “Tutte le galassi...",1.0,2026-05-19 11:09:51.577,0,0

In [20]:
serp_df.loc[(serp_df["effective_query"]==1)&((serp_df["rank"]==1) | (serp_df["rank"].isna()))]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,relevance_score,effective_query
247,4,g3t1,Fiume sacro indiano,serp31,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Il Gange è un grande fiume del sub...,1.0,2026-05-19 15:20:22.199,1,1
475,8,g3t1,Fiume sacro India,serp67,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Secondo gli indù questo fiume è sa...,1.0,2026-05-19 15:16:03.549,1,1
485,8,g3t1,Fiume sacro India,serp68,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Secondo gli indù questo fiume è sa...,1.0,2026-05-19 15:16:18.583,1,1

## results navigation

In [21]:
serp_df.head(20)

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,relevance_score,effective_query
0,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:50:54.636,1,0
1,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,2026-05-19 14:50:54.638,1,0
2,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://animalia.bio/it/india-animals,India - Animalia,"\n Flora e fauna ... L'India, ufficia...",3.0,2026-05-19 14:50:54.640,1,0
3,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/news/news-e-curiosi...,Quali sono gli sport più seguiti e praticati a...,"\n Il cricket è seguito da circa 2,5 ...",4.0,2026-05-19 14:50:54.644,0,0
4,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.goasia.it/geografia-natura-e-clima...,"Geografia, natura e clima dell'India - Go Asia",\n Molteplici varietà di animali sono...,5.0,2026-05-19 14:50:54.645,1,0
5,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://liceoberchet.edu.it/ricerche/geo4d_03/...,La Fauna,\n L'orso labiato ( Melursus ursinus)...,6.0,2026-05-19 14:50:54.647,1,0
6,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/animali/come-fanno-...,Come fanno i camaleonti a cambiare colore? - F...,\n ... della naturale pigmentazione g...,7.0,2026-05-19 14:50:54.648,0,0
7,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/animali/animali-sel...,I 10 serpenti più velenosi e letali del mondo ...,\n FocusJunior.it Animali Animali sel...,8.0,2026-05-19 14:50:54.650,0,0
8,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... L'abitazione tradi...",9.0,2026-05-19 14:50:54.652,0,0
9,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/tag/animali-in-esti...,animali in estinzione Archives - FocusJunior.it,\n Una rara tartaruga dal guscio moll...,10.0,2026-05-19 14:50:54.664,0,0
10,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:52:45.059,1,0
11,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,2026-05-19 14:52:45.062,1,0
12,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://animalia.bio/it/india-animals,India - Animalia,"\n Flora e fauna ... L'India, ufficia...",3.0,2026-05-19 14:52:45.064,1,0
13,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.focusjunior.it/news/news-e-curiosi...,Quali sono gli sport più seguiti e praticati a...,"\n Il cricket è seguito da circa 2,5 ...",4.0,2026-05-19 14:52:45.067,0,0
14,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.goasia.it/geografia-natura-e-clima...,"Geografia, natura e clima dell'India - Go Asia",\n Molteplici varietà di animali sono...,5.0,2026-05-19 14:52:45.069,1,0
15,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://liceoberchet.edu.it/ricerche/geo4d_03/...,La Fauna,\n L'orso labiato ( Melursus ursinus)...,6.0,2026-05-19 14:52:45.072,1,0
16,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.focusjunior.it/animali/come-fanno-...,Come fanno i camaleonti a cambiare colore? - F...,\n ... della naturale pigmentazione g...,7.0,2026-05-19 14:52:45.075,0,0
17,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.focusjunior.it/animali/animali-sel...,I 10 serpenti più velenosi e letali del mondo ...,\n FocusJunior.it Animali Animali sel...,8.0,2026-05-19 14:52:45.078,0,0
18,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... L'abitazione tradi...",9.0,2026-05-19 14:52:45.081,0,0
19,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.focusjunior.it/tag/animali-in-esti...,animali in estinzione Archives - FocusJunior.it,\n Una rara tartaruga dal guscio moll...,10.0,2026-05-19 14:52:45.083,0,0

In [22]:
clicked_results_df.head(40)

,uid,topic_number,query,url,rank,timestamp
0,17,g3t3,Quali sono i 5 animali tipici del india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:29.948
1,17,g3t3,Quali sono i 5 animali tipici del india,https://www.focusjunior.it/animali/animali-sel...,8,2026-05-19 14:51:59.753
2,17,g3t3,Quali sono i 5 animali tipici del india,https://www.focusjunior.it/news/news-e-curiosi...,4,2026-05-19 14:53:05.134
3,17,g3t2,Quale il simbolo del la bandiera del india,https://liceoberchet.edu.it/ricerche/geo4d_03/...,1,2026-05-19 15:00:39.029
4,17,g3t2,Quale il simbolo del la bandiera del india,https://www.focusjunior.it/scuola/geografia/qu...,5,2026-05-19 15:01:01.003
5,17,g3t2,Quale il simbolo del la bandiera del india,https://www.focusjunior.it/scuola/geografia/le...,4,2026-05-19 15:01:38.336
6,17,g3t2,Quale ilsimbolo al centro della bandiera dell ...,https://sullestradedelmondo.it/bandiera-indiana/,1,2026-05-19 15:17:12.494
7,17,g3t1,Il nome del fiume sacro,https://www.beyondthetrip.net/2019/04/03/fiume...,1,2026-05-19 15:26:27.708
8,18,g3t3,Quali sono i cinque tipici animali dell l india,https://www.terreincognitemagazine.it/natura-s...,2,2026-05-19 14:53:05.881
9,18,g3t3,Quali sono i 5 cinque tipici animali dell l i...,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:55:22.455
10,18,g3t2,Simbolo della bandiera dell'india,https://it.gov-civ-guarda.pt/flag-india,6,2026-05-19 15:14:24.499
11,18,g3t1,Come si chiama il fiume sacro degli indiani,https://www.goasia.it/la-religione-gange-fiume...,1,2026-05-19 15:16:17.329
12,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:43.444
13,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:53:19.408
14,1,g3t2,Quale è il nome del simbolo al centro della ba...,https://it.gov-civ-guarda.pt/flag-india,1,2026-05-19 15:02:48.776
15,1,g3t1,Fiume sacro degli indiani,https://www.consciousjourneys.com/it/approfond...,2,2026-05-19 15:08:58.405
16,2,g3t3,Quali sono i 5 animali tipici dall'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:52:53.759
17,2,g3t2,Qual è il nome del simbolo al centro della b...,https://sullestradedelmondo.it/bandiera-indiana/,3,2026-05-19 15:09:25.575
18,2,g3t1,Come si chiama il fiume sacro agli indiani,https://www.consciousjourneys.com/it/approfond...,1,2026-05-19 15:14:18.095
19,3,g3t3,Quali sono 5 animali tipici dell'india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:56:28.100
20,3,g3t2,Quale il nome del simbolo al centro della band...,https://mastroviaggiatore.it/saree/blog/lindia...,1,2026-05-19 15:05:39.212
21,3,g3t2,Quale il nome del simbolo al centro della band...,https://it.gov-civ-guarda.pt/flag-india,3,2026-05-19 15:06:00.133
22,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://it.gov-civ-guarda.pt/flag-india,7,2026-05-19 14:55:47.060
23,4,g3t2,Quale il simbolo dell'India,https://liceoberchet.edu.it/ricerche/geo4d_03/...,1,2026-05-19 15:06:06.889
24,4,g3t2,Quale il simbolo dell'India,https://www.focus.it/ambiente/animali/8-cose-c...,2,2026-05-19 15:06:28.655
25,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:36.085
26,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:49.996
27,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:11:04.292
28,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:12:03.487
29,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:14:14.237
30,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:17:21.809
31,4,g3t1,Fiume sacro indiano,https://www.goasia.it/la-religione-gange-fiume...,1,2026-05-19 15:20:26.846
32,5,g3t3,Quali sono 5 animali tipici dell india,https://www.terreincognitemagazine.it/natura-s...,2,2026-05-19 15:08:18.588
33,5,g3t2,Qual eil simbolo della bandiera india,https://sullestradedelmondo.it/bandiera-indiana/,1,2026-05-19 15:19:29.861
34,6,g3t3,Quali sono 5 animali tipici dell'india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:56:05.417
35,6,g3t2,Quale il simbolo al centro della bandiera dell...,https://www.skuola.net/geografia-medie/india-d...,1,2026-05-19 15:08:05.059
36,6,g3t2,Simbolo andiera India,https://www.bandiere-nazionali.com/bandiera-in...,3,2026-05-19 15:11:31.642
37,6,g3t2,Simbolo andiera India,https://sullestradedelmondo.it/bandiera-indiana/,4,2026-05-19 15:13:24.460
38,8,g3t3,Quali sono 5 animali dell India,https://www.focusjunior.it/scuola/geografia/le...,5,2026-05-19 14:51:21.199
39,8,g3t3,Quali sono 5 animali dell India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:42.534

In [23]:
clicked_results_df.dtypes

uid                      Int64
topic_number            object
query                   object
url                     object
rank                     Int64
timestamp       datetime64[ns]
dtype: object

In [24]:
associated_serp_ids = []

for _, row in clicked_results_df.iterrows():
    associated_serp = serp_df.loc[
        (serp_df["uid"]==row["uid"]) 
        & (serp_df["topic_number"]==row["topic_number"]) 
        & (serp_df["query"]==row["query"]) 
        & (serp_df["url"]==row["url"]) 
        & (serp_df["rank"]==row["rank"]) 
        & (serp_df["timestamp"]<row["timestamp"])
    ]

    if len(associated_serp) == 0:
        print(row)
        associated_serp_ids.append(None)

    elif len(associated_serp) > 1:
        # print(associated_serp)
        time_diff = np.inf
        for _, serp in associated_serp.iterrows():
            # print(serp)
            time_diff_compute = row["timestamp"] - serp["timestamp"]
            if time_diff >= time_diff_compute.total_seconds():
                correct_serp = serp["serp_id"]
                time_diff = time_diff_compute.total_seconds()
        associated_serp_ids.append(correct_serp)
    else:
        associated_serp_ids.append(associated_serp["serp_id"].values[0])

clicked_results_df["serp_id"] = associated_serp_ids

In [25]:
clicked_results_df.loc[pd.isna(clicked_results_df["serp_id"])]

Empty DataFrame
Columns: [uid, topic_number, query, url, rank, timestamp, serp_id]
Index: []

In [26]:
clicked_results_df.loc[clicked_results_df["timestamp"]=="2026-05-19 10:46:51.654"]

,uid,topic_number,query,url,rank,timestamp,serp_id
103,15,g4t2,Qual è stato il primo animale nello spazio e c...,https://www.storicang.it/foto-del-giorno/laika...,1,2026-05-19 10:46:51.654,serp101

In [27]:
clicked_results_df.loc[clicked_results_df["timestamp"]=="2026-05-19 10:51:16.099"]

,uid,topic_number,query,url,rank,timestamp,serp_id
104,15,g4t2,Qual è stato il primo animale nello spazio e c...,https://www.storicang.it/foto-del-giorno/laika...,1,2026-05-19 10:51:16.099,serp102

In [28]:
clicked_results_df.head(20)

,uid,topic_number,query,url,rank,timestamp,serp_id
0,17,g3t3,Quali sono i 5 animali tipici del india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:29.948,serp1
1,17,g3t3,Quali sono i 5 animali tipici del india,https://www.focusjunior.it/animali/animali-sel...,8,2026-05-19 14:51:59.753,serp1
2,17,g3t3,Quali sono i 5 animali tipici del india,https://www.focusjunior.it/news/news-e-curiosi...,4,2026-05-19 14:53:05.134,serp2
3,17,g3t2,Quale il simbolo del la bandiera del india,https://liceoberchet.edu.it/ricerche/geo4d_03/...,1,2026-05-19 15:00:39.029,serp3
4,17,g3t2,Quale il simbolo del la bandiera del india,https://www.focusjunior.it/scuola/geografia/qu...,5,2026-05-19 15:01:01.003,serp3
5,17,g3t2,Quale il simbolo del la bandiera del india,https://www.focusjunior.it/scuola/geografia/le...,4,2026-05-19 15:01:38.336,serp4
6,17,g3t2,Quale ilsimbolo al centro della bandiera dell ...,https://sullestradedelmondo.it/bandiera-indiana/,1,2026-05-19 15:17:12.494,serp6
7,17,g3t1,Il nome del fiume sacro,https://www.beyondthetrip.net/2019/04/03/fiume...,1,2026-05-19 15:26:27.708,serp7
8,18,g3t3,Quali sono i cinque tipici animali dell l india,https://www.terreincognitemagazine.it/natura-s...,2,2026-05-19 14:53:05.881,serp8
9,18,g3t3,Quali sono i 5 cinque tipici animali dell l i...,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:55:22.455,serp9
10,18,g3t2,Simbolo della bandiera dell'india,https://it.gov-civ-guarda.pt/flag-india,6,2026-05-19 15:14:24.499,serp11
11,18,g3t1,Come si chiama il fiume sacro degli indiani,https://www.goasia.it/la-religione-gange-fiume...,1,2026-05-19 15:16:17.329,serp12
12,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:43.444,serp13
13,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:53:19.408,serp13
14,1,g3t2,Quale è il nome del simbolo al centro della ba...,https://it.gov-civ-guarda.pt/flag-india,1,2026-05-19 15:02:48.776,serp14
15,1,g3t1,Fiume sacro degli indiani,https://www.consciousjourneys.com/it/approfond...,2,2026-05-19 15:08:58.405,serp15
16,2,g3t3,Quali sono i 5 animali tipici dall'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:52:53.759,serp17
17,2,g3t2,Qual è il nome del simbolo al centro della b...,https://sullestradedelmondo.it/bandiera-indiana/,3,2026-05-19 15:09:25.575,serp19
18,2,g3t1,Come si chiama il fiume sacro agli indiani,https://www.consciousjourneys.com/it/approfond...,1,2026-05-19 15:14:18.095,serp20
19,3,g3t3,Quali sono 5 animali tipici dell'india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:56:28.100,serp22

In [29]:
df = pd.DataFrame(clicked_results_df.groupby(["uid", "topic_number", "serp_id"])["url"].value_counts()).reset_index()

click_count = []

for _, row in serp_df.iterrows():
    serp_row = df.loc[(df["uid"]==row["uid"])&(df["topic_number"]==row["topic_number"])&(df["serp_id"]==row["serp_id"])&(df["url"]==row["url"])]
    if len(serp_row) > 1:
        print(row, serp_row)
    elif len(serp_row) == 0:
        click_count.append(0)
    else:
        click_count.append(serp_row["count"].values[0])

serp_df["click_count"] = click_count

In [30]:
serp_df.head(20)

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,relevance_score,effective_query,click_count
0,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:50:54.636,1,0,1
1,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,2026-05-19 14:50:54.638,1,0,0
2,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://animalia.bio/it/india-animals,India - Animalia,"\n Flora e fauna ... L'India, ufficia...",3.0,2026-05-19 14:50:54.640,1,0,0
3,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/news/news-e-curiosi...,Quali sono gli sport più seguiti e praticati a...,"\n Il cricket è seguito da circa 2,5 ...",4.0,2026-05-19 14:50:54.644,0,0,0
4,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.goasia.it/geografia-natura-e-clima...,"Geografia, natura e clima dell'India - Go Asia",\n Molteplici varietà di animali sono...,5.0,2026-05-19 14:50:54.645,1,0,0
5,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://liceoberchet.edu.it/ricerche/geo4d_03/...,La Fauna,\n L'orso labiato ( Melursus ursinus)...,6.0,2026-05-19 14:50:54.647,1,0,0
6,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/animali/come-fanno-...,Come fanno i camaleonti a cambiare colore? - F...,\n ... della naturale pigmentazione g...,7.0,2026-05-19 14:50:54.648,0,0,0
7,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/animali/animali-sel...,I 10 serpenti più velenosi e letali del mondo ...,\n FocusJunior.it Animali Animali sel...,8.0,2026-05-19 14:50:54.650,0,0,1
8,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... L'abitazione tradi...",9.0,2026-05-19 14:50:54.652,0,0,0
9,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/tag/animali-in-esti...,animali in estinzione Archives - FocusJunior.it,\n Una rara tartaruga dal guscio moll...,10.0,2026-05-19 14:50:54.664,0,0,0
10,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:52:45.059,1,0,0
11,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,2026-05-19 14:52:45.062,1,0,0
12,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://animalia.bio/it/india-animals,India - Animalia,"\n Flora e fauna ... L'India, ufficia...",3.0,2026-05-19 14:52:45.064,1,0,0
13,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.focusjunior.it/news/news-e-curiosi...,Quali sono gli sport più seguiti e praticati a...,"\n Il cricket è seguito da circa 2,5 ...",4.0,2026-05-19 14:52:45.067,0,0,1
14,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.goasia.it/geografia-natura-e-clima...,"Geografia, natura e clima dell'India - Go Asia",\n Molteplici varietà di animali sono...,5.0,2026-05-19 14:52:45.069,1,0,0
15,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://liceoberchet.edu.it/ricerche/geo4d_03/...,La Fauna,\n L'orso labiato ( Melursus ursinus)...,6.0,2026-05-19 14:52:45.072,1,0,0
16,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.focusjunior.it/animali/come-fanno-...,Come fanno i camaleonti a cambiare colore? - F...,\n ... della naturale pigmentazione g...,7.0,2026-05-19 14:52:45.075,0,0,0
17,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.focusjunior.it/animali/animali-sel...,I 10 serpenti più velenosi e letali del mondo ...,\n FocusJunior.it Animali Animali sel...,8.0,2026-05-19 14:52:45.078,0,0,0
18,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... L'abitazione tradi...",9.0,2026-05-19 14:52:45.081,0,0,0
19,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://www.focusjunior.it/tag/animali-in-esti...,animali in estinzione Archives - FocusJunior.it,\n Una rara tartaruga dal guscio moll...,10.0,2026-05-19 14:52:45.083,0,0,0

In [31]:
len(serp_df.loc[pd.isna(serp_df["rank"])])

16

In [32]:
cleaned_serp_df = serp_df.dropna(subset=["rank"])
cleaned_serp_df["rank"] = cleaned_serp_df["rank"].astype(int)

C:\Users\hrishitachakra\AppData\Local\Temp\ipykernel_16024\193022930.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_serp_df["rank"] = cleaned_serp_df["rank"].astype(int)

In [33]:
len(serp_df), len(cleaned_serp_df)

(972, 956)

In [34]:
serp_df.to_csv("Data/logs_compiled.csv", index=False)
cleaned_serp_df.to_csv("Data/results_navigation.csv", index=False)

In [35]:
serp_df.loc[serp_df["serp_id"]=="serp119"]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,relevance_score,effective_query,click_count
945,9,g4t1,Come si chiamano i satelliti maggiori di Giove,serp119,https://www.astronomitaly.com/blog/astronomy-p...,"Io, Europa, Ganimede e Callisto: guida ai 4 sa...","\n Mar 19, 2024 ... Io, Europa, Ganim...",1.0,2026-05-19 10:55:55.513,0,0,3
946,9,g4t1,Come si chiamano i satelliti maggiori di Giove,serp119,https://starwalk.space/it/news/jupiter-galilea...,"Lune di Giove: quante sono, nomi e ordine | Lu...",\n Quante lune ha Giove nel 2026? Qua...,2.0,2026-05-19 10:55:55.519,1,0,0
947,9,g4t1,Come si chiamano i satelliti maggiori di Giove,serp119,https://edu.inaf.it/astrofoto/giove-satelliti-...,Giove e i suoi satelliti - EduINAF,"\n Dec 3, 2021 ... Il pianeta è compo...",3.0,2026-05-19 10:55:55.524,1,0,1
948,9,g4t1,Come si chiamano i satelliti maggiori di Giove,serp119,https://www.focusjunior.it/news/news-e-curiosi...,Perché alcuni pianeti hanno gli anelli? - Focu...,"\n Mar 18, 2024 ... Gli anelli planet...",4.0,2026-05-19 10:55:55.531,0,0,0
949,9,g4t1,Come si chiamano i satelliti maggiori di Giove,serp119,https://www.focusjunior.it/news/lallineamento-...,"Oggi, 28 febbraio 2025, si verificherà l'allin...","\n Feb 28, 2025 ... ... di Venere, Ma...",5.0,2026-05-19 10:55:55.543,0,0,1
950,9,g4t1,Come si chiamano i satelliti maggiori di Giove,serp119,https://www.focusjunior.it/scienza/spazio/pian...,Quanto dura un giorno sugli altri pianeti? - F...,\n Quanto può durare un giorno su alt...,6.0,2026-05-19 10:55:55.546,0,0,0

## information distillation

In [36]:
with open("Data/answer_set.json", 'r') as f:
        answer_set = json.load(f)

match_counts = []
for _, row in final_answer_df.iterrows():
        num_matches = 0
        answers = answer_set[row["topic_number"]]
        for answer_key in answers.keys():
                for answer in answers[answer_key]:
                        if answer.lower() in row["answer"].lower():
                        # print(row["answer"], ";", answer)
                                num_matches += 1
                                break
        print(row["uid"], row["topic_number"], row["answer"], num_matches)
        match_counts.append(num_matches)

final_answer_df["num_answer_matches"] = match_counts

17 g3t3 Pavone tigre 🐅 scimmia 🐵 leone cobra 5
17 g3t2 Rapreseta la ruota dellavitabhuddista, si chiama ashoka  2
17 g3t1 Il fiume si chiama  gange 1
18 g3t3 Tigre del bengala ,Leone asiatico ,rinoceronte Indiano ,barasingha ,Blackbuck 5
18 g3t2 Sole 0
18 g3t1 Il gange u 1
1 g3t3 Rinoceronte tigre Leone stambecco cervo 3
1 g3t2 Il simbolo della bandiera rappresenta una ruota 1
1 g3t1 Il fiume gange 1
2 g3t3 Tigre,leone,rinoceronte,barasingha,blackbuck. 5
2 g3t2 Ruota  1
2 g3t1 Fiume gange  1
3 g3t1 Gange 1
3 g3t3 Tigre ,Leone, rinoceronte ,Blackbuck barasingha  5
3 g3t2 Un sole 0
4 g3t2 Ashoka. La ruota della vita buddista 2
4 g3t3 Tigre del bengaline
Leone asiatico
Rinoceronte Indiano
Blackbuck
Barasingha  5
4 g3t1 Gange 1
5 g3t1 Gange, il fiume sacro agli indu e la popolazione indiana 1
5 g3t3 Natura selvaggia tra tigri e leoni terrelncognite magazine 0
5 g3t2 Bandiera indiana significato ashoka chakra simbolo della vita  1
6 g3t1 Gange 1
6 g3t3 Tigress del bengala Leone asiatico rinoceronte INDIANO barasingha blackbuck 5
6 g3t2 La ruota ashoka chakra 2
7 g3t2 E un. Sole blu 0
7 g3t3 Bengala Leone asiatico  rinoceronte indiano barasighna 2
7 g3t1 Gange il fiume sacro again indu e alla popolazione indiana 1
8 g3t3 Tigre elefante pavone rinoceronte scimmie 4
8 g3t2 Ruota con 24 raggi,blu nevy 1
8 g3t1 Gange 1
10 g4t3 Galassia del triangolo galassia del pegaso galassia della fenice 1
10 g4t2 Il primo animale che è andato nello spazio  era il cane Laika 2
10 g4t1 Io Europa ganimede e calisto 3
11 g4t3 Andromeda galassia del triangolo piccola nube di magellano
 3
11 g4t1 Callisto Europa Ganimede  Io 4
11 g4t2 Laika 1
12 g4t1 Io, Ganimede, Europa, Callisto  4
12 g4t2 È stato un cane di nome Laika 2
12 g4t3 Andromeda, galassia del triangolo M31, galassia sombrero M104 3
13 g4t1 Io, Europa, Ganimede e Callisto sono i 4 satelliti di Giove 4
13 g4t3 Le 3 galassie sono NGC3109,galassia di Andromeda galassia del triangolo  3
13 g4t2 Laika è stata il primo animale ed  è un cane  2
14 g4t1 Ganimede Callisto io Europa  4
14 g4t3 Andromeda del triangolo gruppo locale 2
14 g4t2 Un cane di nome Laika 2
15 g4t2 Il primo animale nello spazio è un cane e si chiamava Laika. 2
15 g4t3 Galassia di Andromeda Galassie di Fireworks Galassia del Triangolo 3
15 g4t1 Io Europa Ganimede e Callisto 4
16 g4t1 I satelliti maggiori di Giove si chiamano lune galileiane 1
16 g4t3 Andromeda, Galassia Sombrero ,Galassia del Triangolo
 3
16 g4t2 Il primo animali è stato un cane che si chiamava Laika 2
9 g4t2 Il primo animale  mandato nello spazio è state una cagnietta Di nome Laika  1
9 g4t1 Ganimede e Callisto  2
9 g4t3 Andromeda Triangolo Orsa Minore 3

In [37]:
final_answer_df.to_csv("Data/final_answer_df.csv", index=False)

In [38]:
final_answer_df.loc[final_answer_df["topic_number"]=="g3t1"]

,uid,topic_number,prompt,answer,timestamp,num_answer_matches
2,17,g3t1,Come si chiama il fiume sacro agli indiani?,Il fiume si chiama gange,2026-05-19 15:27:44.380,1
5,18,g3t1,Come si chiama il fiume sacro agli indiani?,Il gange u,2026-05-19 15:17:10.220,1
8,1,g3t1,Come si chiama il fiume sacro agli indiani?,Il fiume gange,2026-05-19 15:10:10.812,1
11,2,g3t1,Come si chiama il fiume sacro agli indiani?,Fiume gange,2026-05-19 15:15:05.518,1
12,3,g3t1,Come si chiama il fiume sacro agli indiani?,Gange,2026-05-19 14:51:32.588,1
17,4,g3t1,Come si chiama il fiume sacro agli indiani?,Gange,2026-05-19 15:21:00.731,1
18,5,g3t1,Come si chiama il fiume sacro agli indiani?,"Gange, il fiume sacro agli indu e la popolazio...",2026-05-19 14:58:33.130,1
21,6,g3t1,Come si chiama il fiume sacro agli indiani?,Gange,2026-05-19 14:52:28.940,1
26,7,g3t1,Come si chiama il fiume sacro agli indiani?,Gange il fiume sacro again indu e alla popolaz...,2026-05-19 15:05:34.776,1
29,8,g3t1,Come si chiama il fiume sacro agli indiani?,Gange,2026-05-19 15:16:38.128,1