In [1]:
import json
import pandas as pd
import glob
import numpy as np
import driver

In [2]:
query_df = pd.DataFrame()
query_actions_df = pd.DataFrame() 
serp_df = pd.DataFrame()
clicked_results_df = pd.DataFrame()
viewed_results_df = pd.DataFrame()
final_answer_df = pd.DataFrame()

for file_name in glob.glob("Data/3rd/*_FULL.log"):
    # print(file_name)
    with open(file_name, 'r') as f:
        result = [json.loads(x) for x in f.readlines()]
    
    # query actions
    query_temp_df = driver.get_queries(result)
    query_df = pd.concat([query_df, query_temp_df], ignore_index=True)

    # query actions
    query_actions_temp_df = driver.get_query_actions(result)
    query_actions_df = pd.concat([query_actions_df, query_actions_temp_df], ignore_index=True)

    # SERPs generated
    serp_temp_df = driver.get_generated_serps(result)
    serp_df = pd.concat([serp_df, serp_temp_df], ignore_index=True)

    # Clicked results
    clicked_results_temp_df = driver.get_clicked_results(result)
    clicked_results_df = pd.concat([clicked_results_df, clicked_results_temp_df], ignore_index=True)

    # Viewed results
    viewed_results_temp_df = driver.get_viewed_results(result) 
    viewed_results_df = pd.concat([viewed_results_df, viewed_results_temp_df])

    # final answers
    final_answer_temp_df = driver.get_final_answers(result)
    final_answer_df = pd.concat([final_answer_df, final_answer_temp_df], ignore_index=True)

for file_name in glob.glob("Data/4th/*_FULL.log"):
    # print(file_name)
    with open(file_name, 'r') as f:
        result = [json.loads(x) for x in f.readlines()]
    
    # query actions
    query_temp_df = driver.get_queries(result)
    query_df = pd.concat([query_df, query_temp_df], ignore_index=True)

    # query actions
    query_actions_temp_df = driver.get_query_actions(result)
    query_actions_df = pd.concat([query_actions_df, query_actions_temp_df], ignore_index=True)

    # SERPs generated
    serp_temp_df = driver.get_generated_serps(result)
    serp_df = pd.concat([serp_df, serp_temp_df], ignore_index=True)

    # Clicked results
    clicked_results_temp_df = driver.get_clicked_results(result)
    clicked_results_df = pd.concat([clicked_results_df, clicked_results_temp_df], ignore_index=True)

    # Viewed results
    viewed_results_temp_df = driver.get_viewed_results(result) 
    viewed_results_df = pd.concat([viewed_results_df, viewed_results_temp_df])

    # final answers
    final_answer_temp_df = driver.get_final_answers(result)
    final_answer_df = pd.concat([final_answer_df, final_answer_temp_df], ignore_index=True)

## reordering all dataframes uid, topic_number, and timestamp
query_df = query_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
query_actions_df = query_actions_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
serp_df = serp_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
clicked_results_df = clicked_results_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
viewed_results_df = viewed_results_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
final_answer_df = final_answer_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)


## assigning qid
query_df["qid"] = ["q"+str(i) for i in range(1, len(query_df)+1)]
query_df = query_df[["uid", "topic_number", "qid", "query", "source", "timestamp"]]


## assigning serp id
serp_num = 0
serp_id_list = []

for _, row in serp_df.iterrows():
    if row["rank"]==1 or pd.isna(row["rank"]):
        serp_num += 1
    serp_id_list.append("serp"+str(serp_num))

serp_df["serp_id"] = serp_id_list
serp_df = serp_df[["uid", "topic_number", "query", "serp_id", "url", "title", "snippet", "rank", "timestamp"]]

## removing duplicates
final_answer_df = final_answer_df.drop_duplicates(ignore_index=True)

In [3]:
query_df.sort_values(["uid", "timestamp"])

,uid,topic_number,qid,query,source,timestamp
0,1,g3t3,q1,Quali sono i cinque animali tipici dell india,UserFormulated,2026-05-19 14:51:26.583
1,1,g3t2,q2,Quale è il nome del simbolo al centro della ba...,UserFormulated,2026-05-19 15:02:41.120
2,1,g3t1,q3,Fiume sacro degli indiani,UserFormulated,2026-05-19 15:08:39.525
3,2,g3t3,q4,Quali sono i animali dall'India,UserFormulated,2026-05-19 14:50:22.081
4,2,g3t3,q5,Quali sono i 5 animali tipici dall'India,UserFormulated,2026-05-19 14:51:20.189
...,...,...,...,...,...,...
113,18,g3t3,q114,Quali sono i cinque tipici animali dell l india,UserFormulated,2026-05-19 14:52:34.782
114,18,g3t3,q115,Quali sono i 5 cinque tipici animali dell l i...,UserFormulated,2026-05-19 14:54:58.878
115,18,g3t2,q116,Quale il nome del simbolo al centro della band...,UserFormulated,2026-05-19 15:09:14.538
116,18,g3t2,q117,Simbolo della bandiera dell'india,UserFormulated,2026-05-19 15:13:42.292
117,18,g3t1,q118,Come si chiama il fiume sacro degli indiani,UserFormulated,2026-05-19 15:16:04.199

## query formulation

In [4]:
query_df.head()

,uid,topic_number,qid,query,source,timestamp
0,1,g3t3,q1,Quali sono i cinque animali tipici dell india,UserFormulated,2026-05-19 14:51:26.583
1,1,g3t2,q2,Quale è il nome del simbolo al centro della ba...,UserFormulated,2026-05-19 15:02:41.120
2,1,g3t1,q3,Fiume sacro degli indiani,UserFormulated,2026-05-19 15:08:39.525
3,2,g3t3,q4,Quali sono i animali dall'India,UserFormulated,2026-05-19 14:50:22.081
4,2,g3t3,q5,Quali sono i 5 animali tipici dall'India,UserFormulated,2026-05-19 14:51:20.189

In [5]:
len(query_df)

118

In [6]:
serp_df.head()

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
0,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:51:27.687
1,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,2026-05-19 14:51:27.688
2,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.storicang.it/a/civilta-dellindo-i-...,"La civiltà dell'Indo, i misteri di un popolo d...","\n Jun 5, 2023 ... Sono note cinque m...",3.0,2026-05-19 14:51:27.689
3,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... Chi sono, da dove ...",4.0,2026-05-19 14:51:27.690
4,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/comportamento/feste...,Festa della mamma: come si festeggia nel resto...,\n Il dolce tipico per celebrare ques...,5.0,2026-05-19 14:51:27.691

In [7]:
len(serp_df["serp_id"].unique())

118

In [8]:
temp_df = serp_df.loc[(serp_df["rank"]==1) | (pd.isna(serp_df["rank"]))]
len(temp_df)

118

In [9]:
query_df.loc[query_df["uid"]==2]

,uid,topic_number,qid,query,source,timestamp
3,2,g3t3,q4,Quali sono i animali dall'India,UserFormulated,2026-05-19 14:50:22.081
4,2,g3t3,q5,Quali sono i 5 animali tipici dall'India,UserFormulated,2026-05-19 14:51:20.189
5,2,g3t2,q6,Qual è il nome del simbolo al centro della ban...,UserFormulated,2026-05-19 15:05:41.521
6,2,g3t2,q7,Qual è il nome del simbolo al centro della b...,UserFormulated,2026-05-19 15:09:06.317
7,2,g3t1,q8,Come si chiama il fiume sacro agli indiani,UserFormulated,2026-05-19 15:14:10.201

In [10]:
associated_query_ids = []

for _, row in temp_df.iterrows():
    associated_query = query_df.loc[
        (query_df["uid"]==row["uid"]) 
        & (query_df["topic_number"]==row["topic_number"]) 
        & (query_df["query"]==row["query"]) 
        & (query_df["timestamp"]<row["timestamp"])
    ]

    if len(associated_query) == 0:
        print("No query found for serp id: ", row["serp_id"], "; uid: ", row["uid"], "; query: ", row["query"], "; time: ", row["timestamp"])
        # associated_query = query_df.loc[
        #     (query_df["uid"]==row["uid"]) 
        #     & (query_df["topic_number"]==row["topic_number"]) 
        #     # & (query_df["query"]==row["query"]) 
        #     & (query_df["timestamp"]<row["timestamp"])
        # ]
        # print("Matching based on uid and topic number (w/o query match) led to ", len(associated_query), " matches.\n")
        associated_query_ids.append(None)

    elif len(associated_query) > 1:
        # print("multiple queries found: ", row["serp_id"], row["uid"], row["timestamp"])
        time_diff = np.inf
        for _, query in associated_query.iterrows():
            # print(query)
            time_diff_compute = row["timestamp"] - query["timestamp"]
            if time_diff >= time_diff_compute.total_seconds():
                correct_query = query
                time_diff = time_diff_compute.total_seconds()
        # print("query chosen for ", row["serp_id"], "query: ", query["query"], "; timestamp: ", query["timestamp"])
        associated_query_ids.append(correct_query["qid"])
    else:
        associated_query_ids.append(associated_query["qid"].values[0])

temp_df["qid"] = associated_query_ids

C:\Users\Hrishita Chakrabarti\AppData\Local\Temp\ipykernel_33720\1166631844.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df["qid"] = associated_query_ids

In [11]:
temp_df.loc[temp_df["uid"]==4]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,qid
86,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 14:54:59.384,q13
96,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 14:59:37.155,q14
106,4,g3t2,Quale il simbolo dell'India,serp15,https://liceoberchet.edu.it/ricerche/geo4d_03/...,India Britannica,\n Allora l'Union Jack era pulito ma ...,1.0,2026-05-19 15:03:54.002,q15
116,4,g3t2,Quale il simbolo dell'India,serp16,https://liceoberchet.edu.it/ricerche/geo4d_03/...,India Britannica,\n Allora l'Union Jack era pulito ma ...,1.0,2026-05-19 15:05:58.689,q16
126,4,g3t3,5 animali tipici dell'India,serp17,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 15:14:09.972,q17
145,4,g3t1,Fiume sacro indiano,serp18,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Il Gange è un grande fiume del sub...,1.0,2026-05-19 15:20:22.199,q18

In [12]:
set(query_df["qid"]) - set(temp_df["qid"])

set()

In [13]:
len(set(query_df["qid"]) - set(temp_df["qid"])), len(temp_df.loc[pd.isna(temp_df["qid"])])

(0, 0)

In [14]:
len(temp_df["qid"].unique()), len(temp_df)

(118, 118)

In [15]:
df = pd.DataFrame(temp_df.groupby(["qid"])["uid"].value_counts()).reset_index()
df.loc[df["count"]>1].sort_values(by=["uid"])

Empty DataFrame
Columns: [qid, uid, count]
Index: []

In [16]:
temp_df.loc[temp_df["uid"]==8]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,qid
308,8,g3t3,Quali sono i,serp43,https://www.focusjunior.it/scienza/ambiente/vu...,"Quali sono i vulcani attivi in Italia? I ""magn...",\n In Italia esistono almeno 10 vulca...,1.0,2026-05-19 14:49:49.307,q43
318,8,g3t3,Quali sono 5 animali dell India,serp44,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:51:12.191,q44
328,8,g3t3,Quali sono 5 animali dell India,serp45,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:53:54.964,q45
338,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp46,None,None,None,NaN,2026-05-19 15:04:52.511,q46
339,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp47,None,None,None,NaN,2026-05-19 15:05:05.152,q47
340,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp48,None,None,None,NaN,2026-05-19 15:08:36.757,q48
341,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp49,None,None,None,NaN,2026-05-19 15:09:48.390,q49
342,8,g3t2,centro bandiera india simbolo,serp50,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 15:11:41.365,q50
352,8,g3t2,Bandira india simbolo,serp51,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 15:14:07.992,q51
362,8,g3t1,Fiume sacro India,serp52,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Secondo gli indù questo fiume è sa...,1.0,2026-05-19 15:16:03.549,q52
372,8,g3t1,Fiume sacro India,serp53,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Secondo gli indù questo fiume è sa...,1.0,2026-05-19 15:16:18.583,q53

In [17]:
temp_df.loc[temp_df["qid"].isin(df.loc[df["count"]>1]["qid"].unique().tolist())]

Empty DataFrame
Columns: [uid, topic_number, query, serp_id, url, title, snippet, rank, timestamp, qid]
Index: []

In [18]:
temp_df.loc[temp_df["uid"]==5]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,qid
155,5,g3t1,Come si chiama il fiume,serp19,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n ... si dice possa curare anche i m...,1.0,2026-05-19 14:50:32.173,q19
165,5,g3t1,come si chiama il fiume sacro agli indianischen,serp20,None,None,None,NaN,2026-05-19 14:52:35.518,q20
166,5,g3t1,come si chiama il fiume sacro agli indianischen,serp21,None,None,None,NaN,2026-05-19 14:52:46.904,q21
167,5,g3t1,come si chiama il fiume sacro agli indiani,serp22,https://www.consciousjourneys.com/it/approfond...,"Gange, il fiume sacro agli indù e alla popolaz...","\n È altresì importante per la pesca,...",1.0,2026-05-19 14:53:00.313,q22
174,5,g3t1,come si chiama il fiume sacro agli indiani,serp23,https://www.consciousjourneys.com/it/approfond...,"Gange, il fiume sacro agli indù e alla popolaz...","\n È altresì importante per la pesca,...",1.0,2026-05-19 14:54:36.969,q23
181,5,g3t3,Qali sono 5 animali tipici dell india,serp24,None,None,None,NaN,2026-05-19 15:01:44.186,q24
182,5,g3t3,Qali sono 5 animali tipici dell india,serp25,None,None,None,NaN,2026-05-19 15:01:47.876,q25
183,5,g3t3,Qali sono 5 animali tipici dell india,serp26,None,None,None,NaN,2026-05-19 15:01:58.337,q26
184,5,g3t3,Quali sono 5 animali tipici dell india,serp27,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 15:02:31.643,q27
194,5,g3t3,Quali sono 5 animali tipici dell india,serp28,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 15:08:16.643,q28
204,5,g3t2,Qal e il,serp29,None,None,None,NaN,2026-05-19 15:15:44.081,q29
205,5,g3t2,Qual eil simbolo della bandiera india,serp30,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... I 24 raggi della ...",1.0,2026-05-19 15:19:13.407,q30
215,5,g3t2,Qual eil simbolo della bandiera india,serp31,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... I 24 raggi della ...",1.0,2026-05-19 15:21:01.262,q31
225,5,g3t2,Bandiera,serp32,https://www.focusjunior.it/scienza/ambiente/ch...,Che cos'è la Bandiera Blu? - FocusJunior.it,\n In altre parole la Bandiera Blu in...,1.0,2026-05-19 15:21:18.057,q32

In [19]:
query_df.loc[query_df["uid"]==5]

,uid,topic_number,qid,query,source,timestamp
18,5,g3t1,q19,Come si chiama il fiume,UserFormulated,2026-05-19 14:50:30.668
19,5,g3t1,q20,come si chiama il fiume sacro agli indianischen,UserFormulated,2026-05-19 14:52:33.886
20,5,g3t1,q21,come si chiama il fiume sacro agli indianischen,UserFormulated,2026-05-19 14:52:45.184
21,5,g3t1,q22,come si chiama il fiume sacro agli indiani,UserFormulated,2026-05-19 14:52:58.725
22,5,g3t1,q23,come si chiama il fiume sacro agli indiani,UserFormulated,2026-05-19 14:54:34.881
23,5,g3t3,q24,Qali sono 5 animali tipici dell india,UserFormulated,2026-05-19 15:01:42.366
24,5,g3t3,q25,Qali sono 5 animali tipici dell india,UserFormulated,2026-05-19 15:01:46.525
25,5,g3t3,q26,Qali sono 5 animali tipici dell india,UserFormulated,2026-05-19 15:01:56.495
26,5,g3t3,q27,Quali sono 5 animali tipici dell india,UserFormulated,2026-05-19 15:02:30.582
27,5,g3t3,q28,Quali sono 5 animali tipici dell india,UserFormulated,2026-05-19 15:08:15.219
28,5,g3t2,q29,Qal e il,UserFormulated,2026-05-19 15:15:42.116
29,5,g3t2,q30,Qual eil simbolo della bandiera india,UserFormulated,2026-05-19 15:19:12.025
30,5,g3t2,q31,Qual eil simbolo della bandiera india,UserFormulated,2026-05-19 15:20:59.385
31,5,g3t2,q32,Bandiera,UserFormulated,2026-05-19 15:21:16.565

In [20]:
temp_df.loc[pd.isna(temp_df["rank"])]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,qid
165,5,g3t1,come si chiama il fiume sacro agli indianischen,serp20,None,None,None,NaN,2026-05-19 14:52:35.518,q20
166,5,g3t1,come si chiama il fiume sacro agli indianischen,serp21,None,None,None,NaN,2026-05-19 14:52:46.904,q21
181,5,g3t3,Qali sono 5 animali tipici dell india,serp24,None,None,None,NaN,2026-05-19 15:01:44.186,q24
182,5,g3t3,Qali sono 5 animali tipici dell india,serp25,None,None,None,NaN,2026-05-19 15:01:47.876,q25
183,5,g3t3,Qali sono 5 animali tipici dell india,serp26,None,None,None,NaN,2026-05-19 15:01:58.337,q26
204,5,g3t2,Qal e il,serp29,None,None,None,NaN,2026-05-19 15:15:44.081,q29
338,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp46,None,None,None,NaN,2026-05-19 15:04:52.511,q46
339,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp47,None,None,None,NaN,2026-05-19 15:05:05.152,q47
340,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp48,None,None,None,NaN,2026-05-19 15:08:36.757,q48
341,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp49,None,None,None,NaN,2026-05-19 15:09:48.390,q49
414,9,g4t3,3 galassie oly,serp58,None,None,None,NaN,2026-05-19 11:09:41.822,q58
582,12,g4t3,3 galassie olt4e la nostra,serp76,None,None,None,NaN,2026-05-19 11:16:50.790,q76
583,12,g4t3,3 galassie olt4e la nostra,serp77,None,None,None,NaN,2026-05-19 11:16:54.735,q77
749,15,g4t3,qualifiche f1,serp94,None,None,None,NaN,2026-05-19 10:55:32.846,q94
781,15,g4t3,Nomi di alre galassie,serp98,None,None,None,NaN,2026-05-19 11:06:11.428,q98

In [21]:
query_df["serp_id"] = [temp_df.loc[temp_df["qid"]==qid]["serp_id"].values[0] for qid in query_df["qid"]]
query_df = query_df[["uid", "topic_number", "qid", "query", "source", "serp_id", "timestamp"]]
query_df.to_csv("Data/query_df.csv", index=False, encoding='utf8')

In [22]:
query_df.head()

,uid,topic_number,qid,query,source,serp_id,timestamp
0,1,g3t3,q1,Quali sono i cinque animali tipici dell india,UserFormulated,serp1,2026-05-19 14:51:26.583
1,1,g3t2,q2,Quale è il nome del simbolo al centro della ba...,UserFormulated,serp2,2026-05-19 15:02:41.120
2,1,g3t1,q3,Fiume sacro degli indiani,UserFormulated,serp3,2026-05-19 15:08:39.525
3,2,g3t3,q4,Quali sono i animali dall'India,UserFormulated,serp4,2026-05-19 14:50:22.081
4,2,g3t3,q5,Quali sono i 5 animali tipici dall'India,UserFormulated,serp5,2026-05-19 14:51:20.189

In [23]:
serp_df.loc[serp_df["rank"].isna()]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
165,5,g3t1,come si chiama il fiume sacro agli indianischen,serp20,None,None,None,NaN,2026-05-19 14:52:35.518
166,5,g3t1,come si chiama il fiume sacro agli indianischen,serp21,None,None,None,NaN,2026-05-19 14:52:46.904
181,5,g3t3,Qali sono 5 animali tipici dell india,serp24,None,None,None,NaN,2026-05-19 15:01:44.186
182,5,g3t3,Qali sono 5 animali tipici dell india,serp25,None,None,None,NaN,2026-05-19 15:01:47.876
183,5,g3t3,Qali sono 5 animali tipici dell india,serp26,None,None,None,NaN,2026-05-19 15:01:58.337
204,5,g3t2,Qal e il,serp29,None,None,None,NaN,2026-05-19 15:15:44.081
338,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp46,None,None,None,NaN,2026-05-19 15:04:52.511
339,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp47,None,None,None,NaN,2026-05-19 15:05:05.152
340,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp48,None,None,None,NaN,2026-05-19 15:08:36.757
341,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp49,None,None,None,NaN,2026-05-19 15:09:48.390
414,9,g4t3,3 galassie oly,serp58,None,None,None,NaN,2026-05-19 11:09:41.822
582,12,g4t3,3 galassie olt4e la nostra,serp76,None,None,None,NaN,2026-05-19 11:16:50.790
583,12,g4t3,3 galassie olt4e la nostra,serp77,None,None,None,NaN,2026-05-19 11:16:54.735
749,15,g4t3,qualifiche f1,serp94,None,None,None,NaN,2026-05-19 10:55:32.846
781,15,g4t3,Nomi di alre galassie,serp98,None,None,None,NaN,2026-05-19 11:06:11.428

In [24]:
df = pd.DataFrame(serp_df.loc[(serp_df["rank"]==1)|(serp_df["rank"].isna())].groupby(["uid", "topic_number"])["query"].value_counts()).reset_index()
df.loc[df["count"]>1]

    uid topic_number                                              query  count
13    4         g3t2  Che cosa rappresenta l'imagine del simbolo ban...      2
14    4         g3t2                        Quale il simbolo dell'India      2
16    5         g3t1         come si chiama il fiume sacro agli indiani      2
17    5         g3t1    come si chiama il fiume sacro agli indianischen      2
19    5         g3t2              Qual eil simbolo della bandiera india      2
22    5         g3t3              Qali sono 5 animali tipici dell india      3
23    5         g3t3             Quali sono 5 animali tipici dell india      2
31    7         g3t2           il simbolo della baniera dell dell'india      2
33    8         g3t1                                  Fiume sacro India      2
34    8         g3t2  Come si chiama il nome dell disegno nell centr...      2
39    8         g3t3                    Quali sono 5 animali dell India      2
47   10         g4t1    Come  si chiamano i satelliti maggiori di Giove      2
51   11         g4t2  Qual è stato il primo animale nello spazio e c...      2
59   12         g4t3                         3 galassie olt4e la nostra      2
76   15         g4t2  Qual è stato il primo animale nello spazio e c...      3
77   15         g4t3  Quali sono i nomi di altre 3 galassie oltre la...      2
82   16         g4t1    Come si chiamano i satelliti  maggiori di Giove      2
85   16         g4t3  Quali sono altre nomi di tre galassie in oltre...      3

In [25]:
q_df = pd.DataFrame(query_df.groupby(["uid", "topic_number"])["query"].value_counts()).reset_index()
q_df.loc[q_df["count"]>1]

    uid topic_number                                              query  count
13    4         g3t2  Che cosa rappresenta l'imagine del simbolo ban...      2
14    4         g3t2                        Quale il simbolo dell'India      2
16    5         g3t1         come si chiama il fiume sacro agli indiani      2
17    5         g3t1    come si chiama il fiume sacro agli indianischen      2
19    5         g3t2              Qual eil simbolo della bandiera india      2
22    5         g3t3              Qali sono 5 animali tipici dell india      3
23    5         g3t3             Quali sono 5 animali tipici dell india      2
31    7         g3t2           il simbolo della baniera dell dell'india      2
33    8         g3t1                                  Fiume sacro India      2
34    8         g3t2  Come si chiama il nome dell disegno nell centr...      2
39    8         g3t3                    Quali sono 5 animali dell India      2
47   10         g4t1    Come  si chiamano i satelliti maggiori di Giove      2
51   11         g4t2  Qual è stato il primo animale nello spazio e c...      2
59   12         g4t3                         3 galassie olt4e la nostra      2
76   15         g4t2  Qual è stato il primo animale nello spazio e c...      3
77   15         g4t3  Quali sono i nomi di altre 3 galassie oltre la...      2
82   16         g4t1    Come si chiamano i satelliti  maggiori di Giove      2
85   16         g4t3  Quali sono altre nomi di tre galassie in oltre...      3

In [26]:
q_df.loc[q_df["count"]==3]["query"].tolist()

['Qali sono 5 animali tipici dell india',
 'Qual è stato il primo animale nello spazio e come si chiamava',
 'Quali sono altre nomi di tre galassie in oltre la nostra']

In [27]:
query_df.loc[query_df["uid"]==15]

,uid,topic_number,qid,query,source,serp_id,timestamp
90,15,g4t2,q91,Qual è stato il primo animale nello spazio e c...,UserFormulated,serp91,2026-05-19 10:44:45.385
91,15,g4t2,q92,Qual è stato il primo animale nello spazio e c...,UserFormulated,serp92,2026-05-19 10:46:43.174
92,15,g4t2,q93,Qual è stato il primo animale nello spazio e c...,UserFormulated,serp93,2026-05-19 10:51:12.928
93,15,g4t3,q94,qualifiche f1,UserFormulated,serp94,2026-05-19 10:55:31.771
94,15,g4t3,q95,Quali sono i nomi di altre 3 galassie oltre la...,UserFormulated,serp95,2026-05-19 10:57:32.254
95,15,g4t3,q96,Quali sono i nomi di altre 3 galassie oltre la...,UserFormulated,serp96,2026-05-19 11:03:56.641
96,15,g4t3,q97,Quali sono i nomi di altre 3 galassie oltre la...,UserFormulated,serp97,2026-05-19 11:04:18.615
97,15,g4t3,q98,Nomi di alre galassie,UserFormulated,serp98,2026-05-19 11:06:09.998
98,15,g4t3,q99,Nomi di altre galassie,DidYouMean,serp99,2026-05-19 11:06:17.339
99,15,g4t1,q100,Come si chiamano i satelliti maggiori di Giove,UserFormulated,serp100,2026-05-19 11:15:45.762

In [28]:
serp_df["uid"].unique()

<IntegerArray>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
Length: 18, dtype: Int64

In [29]:
query_df.loc[query_df["uid"]==4]

,uid,topic_number,qid,query,source,serp_id,timestamp
12,4,g3t2,q13,Che cosa rappresenta l'imagine del simbolo ban...,UserFormulated,serp13,2026-05-19 14:54:57.981
13,4,g3t2,q14,Che cosa rappresenta l'imagine del simbolo ban...,UserFormulated,serp14,2026-05-19 14:59:35.687
14,4,g3t2,q15,Quale il simbolo dell'India,UserFormulated,serp15,2026-05-19 15:03:52.949
15,4,g3t2,q16,Quale il simbolo dell'India,UserFormulated,serp16,2026-05-19 15:05:57.147
16,4,g3t3,q17,5 animali tipici dell'India,UserFormulated,serp17,2026-05-19 15:14:08.813
17,4,g3t1,q18,Fiume sacro indiano,UserFormulated,serp18,2026-05-19 15:20:20.872

In [30]:
serp_df.loc[(serp_df["uid"]==4) & (serp_df["query"]=="Che cosa rappresenta l'imagine del simbolo banderia dell'India")]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
86,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 14:54:59.384
87,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... La storia della b...",2.0,2026-05-19 14:54:59.386
88,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focus.it/ambiente/animali/8-cose-c...,8 cose che (forse) non sai sulle vacche sacre ...,"\n Mar 31, 2019 ... Per molti indù, c...",3.0,2026-05-19 14:54:59.387
89,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focusjunior.it/news/holi-festival-...,"Holi festival, la festa dei colori - FocusJuni...","\n Mar 23, 2024 ... Si chiama Holi ed...",4.0,2026-05-19 14:54:59.392
90,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focusjunior.it/scuola/geografia/le...,Quali sono le 10 Nazioni più popolate del mond...,"\n Apr 16, 2017 ... Il Pakistan , che...",5.0,2026-05-19 14:54:59.394
91,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focusjunior.it/scuola/geografia/10...,10 cose che (forse) non sai sull'Europa - Focu...,"\n Dal nome, alla bandiera passando p...",6.0,2026-05-19 14:54:59.396
92,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://it.gov-civ-guarda.pt/flag-india,"Bandiera dell'India | Storia, design e signifi...",\n ... simbolo distintivo che potesse...,7.0,2026-05-19 14:54:59.398
93,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focusjunior.it/news/plogging-corre...,"Plogging, cos'è e perché aiuta il pianeta - Fo...",\n L'amore per l'ambiente ha portato ...,8.0,2026-05-19 14:54:59.399
94,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focusjunior.it/scuola/storia/rivol...,"Rivoluzione: quando il popolo si ribella, la s...","\n May 20, 2019 ... Il 22 settembre 1...",9.0,2026-05-19 14:54:59.401
95,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focusjunior.it/scuola/storia/chi-s...,Chi sono i curdi? - FocusJunior.it,"\n La bandiera curda, che oggi svento...",10.0,2026-05-19 14:54:59.403
96,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 14:59:37.155
97,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... La storia della b...",2.0,2026-05-19 14:59:37.157
98,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://www.focus.it/ambiente/animali/8-cose-c...,8 cose che (forse) non sai sulle vacche sacre ...,"\n Mar 31, 2019 ... Per molti indù, c...",3.0,2026-05-19 14:59:37.160
99,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://www.focusjunior.it/news/holi-festival-...,"Holi festival, la festa dei colori - FocusJuni...","\n Mar 23, 2024 ... Si chiama Holi ed...",4.0,2026-05-19 14:59:37.162
100,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://www.focusjunior.it/scuola/geografia/le...,Quali sono le 10 Nazioni più popolate del mond...,"\n Apr 16, 2017 ... Il Pakistan , che...",5.0,2026-05-19 14:59:37.165
101,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://www.focusjunior.it/scuola/geografia/10...,10 cose che (forse) non sai sull'Europa - Focu...,"\n Dal nome, alla bandiera passando p...",6.0,2026-05-19 14:59:37.173
102,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://it.gov-civ-guarda.pt/flag-india,"Bandiera dell'India | Storia, design e signifi...",\n ... simbolo distintivo che potesse...,7.0,2026-05-19 14:59:37.175
103,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://www.focusjunior.it/news/plogging-corre...,"Plogging, cos'è e perché aiuta il pianeta - Fo...",\n L'amore per l'ambiente ha portato ...,8.0,2026-05-19 14:59:37.178
104,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://www.focusjunior.it/scuola/storia/rivol...,"Rivoluzione: quando il popolo si ribella, la s...","\n May 20, 2019 ... Il 22 settembre 1...",9.0,2026-05-19 14:59:37.180
105,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://www.focusjunior.it/scuola/storia/chi-s...,Chi sono i curdi? - FocusJunior.it,"\n La bandiera curda, che oggi svento...",10.0,2026-05-19 14:59:37.182

In [31]:
serp_df.loc[(serp_df["uid"]==4)]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
86,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 14:54:59.384
87,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... La storia della b...",2.0,2026-05-19 14:54:59.386
88,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focus.it/ambiente/animali/8-cose-c...,8 cose che (forse) non sai sulle vacche sacre ...,"\n Mar 31, 2019 ... Per molti indù, c...",3.0,2026-05-19 14:54:59.387
89,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focusjunior.it/news/holi-festival-...,"Holi festival, la festa dei colori - FocusJuni...","\n Mar 23, 2024 ... Si chiama Holi ed...",4.0,2026-05-19 14:54:59.392
90,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focusjunior.it/scuola/geografia/le...,Quali sono le 10 Nazioni più popolate del mond...,"\n Apr 16, 2017 ... Il Pakistan , che...",5.0,2026-05-19 14:54:59.394
...,...,...,...,...,...,...,...,...,...
150,4,g3t1,Fiume sacro indiano,serp18,https://it.renovables.blog/acqua/il-sacro-fium...,Alla scoperta del Gange: il fiume sacro e inqu...,"\n La sorgente del fiume Gange, noto ...",6.0,2026-05-19 15:20:22.204
151,4,g3t1,Fiume sacro indiano,serp18,https://www.consciousjourneys.com/it/approfond...,"Varanasi, la città sacra per gli induisti sul ...",\n Varanasi è un'importante città ind...,7.0,2026-05-19 15:20:22.204
152,4,g3t1,Fiume sacro indiano,serp18,https://www.cinziamalaguti.it/fiumi-sacri-il-g...,Fiumi sacri: il Gange - Esperienziando Vitae,\n Il Gange scorre nel Nord dell'Indi...,8.0,2026-05-19 15:20:22.205
153,4,g3t1,Fiume sacro indiano,serp18,https://www.skuola.net/geografia-medie/india-d...,"L'India: un viaggio tra cultura, geografia e t...","\n Jun 28, 2014 ... Alla costa indian...",9.0,2026-05-19 15:20:22.206
154,4,g3t1,Fiume sacro indiano,serp18,https://www.focusjunior.it/animali/enciclopedi...,"Il gruccione, poco conosciuto ma davvero bello...","\n Mar 25, 2014 ... ... India e Sri L...",10.0,2026-05-19 15:20:22.207

In [32]:
relevance = pd.read_csv("Data/relevance.csv")
relevance.loc[relevance["topic_number"]=="g3t2"]

,topic_number,topic,doc,relevance
14,g3t2,Bandiera India simbolo,https://liceoberchet.edu.it/ricerche/geo4d_03/...,1
15,g3t2,Bandiera India simbolo,https://www.wisdomlib.org/it/concept/dharmacakra,1
16,g3t2,Bandiera India simbolo,https://www.bandiere-nazionali.com/bandiera-in...,1
17,g3t2,Bandiera India simbolo,https://www.wisdomlib.org/it/concept/ashoka,1
18,g3t2,Bandiera India simbolo,https://www.fuorimag.it/la-bandiera-dellindia/,1
19,g3t2,Bandiera India simbolo,https://flags-world.com/it/bandiera-india-colo...,1
20,g3t2,Bandiera India simbolo,https://sullestradedelmondo.it/bandiera-indiana/,1
21,g3t2,Bandiera India simbolo,https://mastroviaggiatore.it/saree/blog/lindia...,1
22,g3t2,Bandiera India simbolo,https://isha.sadhguru.org/mahashivratri/it/shi...,1
23,g3t2,Bandiera India simbolo,https://www.bandiere-mondo.it/india,1
24,g3t2,Bandiera India simbolo,https://it.gov-civ-guarda.pt/flag-india,1
25,g3t2,Bandiera India simbolo,https://it.indiamap360.com/mappa-della-bandier...,1
26,g3t2,Bandiera India simbolo,https://www.ilsaperestorico.it/ashoka-asoka-il...,1
27,g3t2,Bandiera India simbolo,https://old.icsestopascoli.edu.it/wp-content/u...,1
28,g3t2,Bandiera India simbolo,https://www.media.inaf.it/2013/04/04/smc-wing-...,1
29,g3t2,Bandiera India simbolo,https://www.skuola.net/geografia-medie/india-d...,1
30,g3t2,Bandiera India simbolo,https://dinolingo.com/it/hindi-culture-hindi-c...,1

In [33]:
relevance = pd.read_csv("Data/relevance.csv")
relevance_score = []

for _, row in serp_df.iterrows():
    relevant_docs = relevance.loc[relevance["topic_number"]==row["topic_number"]]["doc"].tolist()
    if row["url"] in relevant_docs:
        relevance_score.append(1)
    else:
        relevance_score.append(0)

serp_df["relevance_score"] = relevance_score

In [34]:
temp = serp_df.loc[serp_df["rank"]<=10].groupby(["serp_id"])["relevance_score"].sum()/10
df = pd.DataFrame(temp).reset_index()
df.columns = ["serp_id", "precision@10"]
df["query"] = [serp_df.loc[serp_df["serp_id"]==serp_id]["query"].values[0] for serp_id in df["serp_id"]]
df["topic_number"] = [serp_df.loc[serp_df["serp_id"]==serp_id]["topic_number"].values[0] for serp_id in df["serp_id"]]
df["uid"] = [serp_df.loc[serp_df["serp_id"]==serp_id]["uid"].values[0] for serp_id in df["serp_id"]]
df = df[["uid", "topic_number", "serp_id", "query", "precision@10"]]
df = df.sort_values(by=["uid"]).reset_index(drop=True)
df = df[["uid","topic_number","query","serp_id", "precision@10"]]
df.to_csv("Data/query_formulation_df.csv", index=False, encoding='utf8')

In [35]:
df

,uid,topic_number,query,serp_id,precision@10
0,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,0.2
1,1,g3t1,Fiume sacro degli indiani,serp3,0.4
2,1,g3t2,Quale è il nome del simbolo al centro della ba...,serp2,0.1
3,2,g3t1,Come si chiama il fiume sacro agli indiani,serp8,0.4
4,2,g3t2,Qual è il nome del simbolo al centro della b...,serp7,0.4
...,...,...,...,...,...
98,18,g3t1,Come si chiama il fiume sacro degli indiani,serp118,0.4
99,18,g3t3,Quali sono i cinque tipici animali dell l india,serp114,0.2
100,18,g3t3,Quali sono i 5 cinque tipici animali dell l i...,serp115,0.1
101,18,g3t2,Quale il nome del simbolo al centro della band...,serp116,0.4
102,18,g3t2,Simbolo della bandiera dell'india,serp117,0.9

## results navigation

In [36]:
serp_df.head(20)

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,relevance_score
0,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:51:27.687,1
1,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,2026-05-19 14:51:27.688,1
2,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.storicang.it/a/civilta-dellindo-i-...,"La civiltà dell'Indo, i misteri di un popolo d...","\n Jun 5, 2023 ... Sono note cinque m...",3.0,2026-05-19 14:51:27.689,0
3,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... Chi sono, da dove ...",4.0,2026-05-19 14:51:27.690,0
4,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/comportamento/feste...,Festa della mamma: come si festeggia nel resto...,\n Il dolce tipico per celebrare ques...,5.0,2026-05-19 14:51:27.691,0
5,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/giochi/i-20-parchi-...,I 20 parchi divertimento più belli d'Italia - ...,\n Parco faunistico immerso in un bos...,6.0,2026-05-19 14:51:27.693,0
6,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scuola/geografia/10...,10 cose che (forse) non sai sull'Europa - Focu...,\n Come popolazione conta 508 milioni...,7.0,2026-05-19 14:51:27.694,0
7,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scienza/ambiente/ec...,9 interessantissime curiosità sulle piante gra...,\n 2 - QUALI SONO LE TIPOLOGIE? Esist...,8.0,2026-05-19 14:51:27.696,0
8,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scienza/natura/le-s...,Le spiagge più strane e colorate del mondo - F...,\n ... è di origine vulcanica: in pra...,9.0,2026-05-19 14:51:27.697,0
9,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/animali/curiosita-a...,Idee per nomi di gatto - FocusJunior.it,"\n Mar 19, 2025 ... Il gatto è l'anim...",10.0,2026-05-19 14:51:27.699,0
10,1,g3t2,Quale è il nome del simbolo al centro della ba...,serp2,https://it.gov-civ-guarda.pt/flag-india,"Bandiera dell'India | Storia, design e signifi...",\n Nel 1921 uno studente di nome Ping...,1.0,2026-05-19 15:02:42.576,1
11,1,g3t1,Fiume sacro degli indiani,serp3,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Qui le persone rendono omaggio ai ...,1.0,2026-05-19 15:08:41.314,1
12,1,g3t1,Fiume sacro degli indiani,serp3,https://www.consciousjourneys.com/it/approfond...,"Gange, il fiume sacro agli indù e alla popolaz...","\n Come abbiamo detto, il Gange è il ...",2.0,2026-05-19 15:08:41.315,1
13,1,g3t1,Fiume sacro degli indiani,serp3,https://italiano.memphistours.com/india/fiume-...,Alla Scoperta del Sacro Fiume Gange - India - ...,\n Le Sundarbans sono un ecosistema u...,3.0,2026-05-19 15:08:41.316,1
14,1,g3t1,Fiume sacro degli indiani,serp3,https://it.renovables.blog/acqua/il-sacro-fium...,Alla scoperta del Gange: il fiume sacro e inqu...,\n Oltre a essere il fiume più lungo ...,4.0,2026-05-19 15:08:41.317,1
15,1,g3t1,Fiume sacro degli indiani,serp3,https://www.skuola.net/geografia-medie/india-d...,"L'India: un viaggio tra cultura, geografia e t...","\n Jun 28, 2014 ... Alla costa indian...",5.0,2026-05-19 15:08:41.319,0
16,1,g3t1,Fiume sacro degli indiani,serp3,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... Lungo quella terra...",6.0,2026-05-19 15:08:41.320,0
17,1,g3t1,Fiume sacro degli indiani,serp3,https://www.focusjunior.it/scuola/storia/le-re...,Quali sono le grandi religioni nel mondo? - Fo...,"\n Da allora, gli ebrei sanno di dove...",7.0,2026-05-19 15:08:41.321,0
18,1,g3t1,Fiume sacro degli indiani,serp3,https://www.focusjunior.it/scuola/ricerche-per...,Ricerche per la scuola | L'Arabia Saudita - Fo...,\n ... della Ka-ba . L'importanza spi...,8.0,2026-05-19 15:08:41.322,0
19,2,g3t3,Quali sono i animali dall'India,serp4,https://www.focusjunior.it/scuola/storia/il-pi...,Chi ha inventato il pigiama? - FocusJunior.it,\n Ma quali sono le sue origini? DAL ...,1.0,2026-05-19 14:50:23.230,0

In [37]:
clicked_results_df.head(40)

,uid,topic_number,query,url,rank,timestamp
0,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:43.444
1,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:53:19.408
2,1,g3t2,Quale è il nome del simbolo al centro della ba...,https://it.gov-civ-guarda.pt/flag-india,1,2026-05-19 15:02:48.776
3,1,g3t1,Fiume sacro degli indiani,https://www.consciousjourneys.com/it/approfond...,2,2026-05-19 15:08:58.405
4,2,g3t3,Quali sono i 5 animali tipici dall'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:52:53.759
5,2,g3t2,Qual è il nome del simbolo al centro della b...,https://sullestradedelmondo.it/bandiera-indiana/,3,2026-05-19 15:09:25.575
6,2,g3t1,Come si chiama il fiume sacro agli indiani,https://www.consciousjourneys.com/it/approfond...,1,2026-05-19 15:14:18.095
7,3,g3t3,Quali sono 5 animali tipici dell'india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:56:28.100
8,3,g3t2,Quale il nome del simbolo al centro della band...,https://mastroviaggiatore.it/saree/blog/lindia...,1,2026-05-19 15:05:39.212
9,3,g3t2,Quale il nome del simbolo al centro della band...,https://it.gov-civ-guarda.pt/flag-india,3,2026-05-19 15:06:00.133
10,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://it.gov-civ-guarda.pt/flag-india,7,2026-05-19 14:55:47.060
11,4,g3t2,Quale il simbolo dell'India,https://liceoberchet.edu.it/ricerche/geo4d_03/...,1,2026-05-19 15:06:06.889
12,4,g3t2,Quale il simbolo dell'India,https://www.focus.it/ambiente/animali/8-cose-c...,2,2026-05-19 15:06:28.655
13,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:36.085
14,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:49.996
15,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:11:04.292
16,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:12:03.487
17,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:14:14.237
18,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:17:21.809
19,4,g3t1,Fiume sacro indiano,https://www.goasia.it/la-religione-gange-fiume...,1,2026-05-19 15:20:26.846
20,5,g3t3,Quali sono 5 animali tipici dell india,https://www.terreincognitemagazine.it/natura-s...,2,2026-05-19 15:08:18.588
21,5,g3t2,Qual eil simbolo della bandiera india,https://sullestradedelmondo.it/bandiera-indiana/,1,2026-05-19 15:19:29.861
22,6,g3t3,Quali sono 5 animali tipici dell'india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:56:05.417
23,6,g3t2,Quale il simbolo al centro della bandiera dell...,https://www.skuola.net/geografia-medie/india-d...,1,2026-05-19 15:08:05.059
24,6,g3t2,Simbolo andiera India,https://www.bandiere-nazionali.com/bandiera-in...,3,2026-05-19 15:11:31.642
25,6,g3t2,Simbolo andiera India,https://sullestradedelmondo.it/bandiera-indiana/,4,2026-05-19 15:13:24.460
26,8,g3t3,Quali sono 5 animali dell India,https://www.focusjunior.it/scuola/geografia/le...,5,2026-05-19 14:51:21.199
27,8,g3t3,Quali sono 5 animali dell India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:42.534
28,8,g3t3,Quali sono 5 animali dell India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:52:02.269
29,8,g3t3,Quali sono 5 animali dell India,https://animalia.bio/it/india-animals,4,2026-05-19 14:54:13.476
30,8,g3t3,Quali sono 5 animali dell India,https://animalia.bio/it/india-animals,4,2026-05-19 14:55:56.413
31,8,g3t2,centro bandiera india simbolo,https://www.bandiere-nazionali.com/bandiera-in...,2,2026-05-19 15:11:51.878
32,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.focusjunior.it/scienza/spazio/laik...,2,2026-05-19 10:43:58.958
33,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.nationalgeographic.it/spazio/2021/...,3,2026-05-19 10:44:41.360
34,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.focusjunior.it/scienza/spazio/stel...,6,2026-05-19 10:45:32.387
35,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.storicang.it/foto-del-giorno/laika...,1,2026-05-19 10:46:16.185
36,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.focusjunior.it/scienza/spazio/laik...,2,2026-05-19 10:46:57.627
37,9,g4t1,Come si chiamano i satteliti maggiori di Giove,https://www.astronomitaly.com/blog/astronomy-p...,1,2026-05-19 10:52:26.337
38,9,g4t1,Come si chiamano i satteliti maggiori di Giove,https://starwalk.space/it/news/jupiter-galilea...,2,2026-05-19 10:53:18.182
39,9,g4t1,Come si chiamano i satteliti maggiori di Giove,https://edu.inaf.it/astrofoto/giove-satelliti-...,3,2026-05-19 10:53:42.819

In [38]:
clicked_results_df.dtypes

uid                      Int64
topic_number            object
query                   object
url                     object
rank                     Int64
timestamp       datetime64[ns]
dtype: object

In [39]:
associated_serp_ids = []

for _, row in clicked_results_df.iterrows():
    associated_serp = serp_df.loc[
        (serp_df["uid"]==row["uid"]) 
        & (serp_df["topic_number"]==row["topic_number"]) 
        & (serp_df["query"]==row["query"]) 
        & (serp_df["url"]==row["url"]) 
        & (serp_df["rank"]==row["rank"]) 
        & (serp_df["timestamp"]<row["timestamp"])
    ]

    if len(associated_serp) == 0:
        print(row)
        associated_serp_ids.append(None)

    elif len(associated_serp) > 1:
        # print(associated_serp)
        time_diff = np.inf
        for _, serp in associated_serp.iterrows():
            # print(serp)
            time_diff_compute = row["timestamp"] - serp["timestamp"]
            if time_diff >= time_diff_compute.total_seconds():
                correct_serp = serp["serp_id"]
                time_diff = time_diff_compute.total_seconds()
        associated_serp_ids.append(correct_serp)
    else:
        associated_serp_ids.append(associated_serp["serp_id"].values[0])

clicked_results_df["serp_id"] = associated_serp_ids

In [40]:
associated_serp_ids = []

for _, row in viewed_results_df.iterrows():
    associated_serp = serp_df.loc[
        (serp_df["uid"]==row["uid"]) 
        & (serp_df["topic_number"]==row["topic_number"]) 
        & (serp_df["query"]==row["query"]) 
        & (serp_df["url"]==row["url"]) 
        & (serp_df["rank"]==row["rank"]) 
        & (serp_df["timestamp"]<row["timestamp"])
    ]

    if len(associated_serp) == 0:
        print(row)
        associated_serp_ids.append(None)

    elif len(associated_serp) > 1:
        # print(associated_serp)
        time_diff = np.inf
        for _, serp in associated_serp.iterrows():
            # print(serp)
            time_diff_compute = row["timestamp"] - serp["timestamp"]
            if time_diff >= time_diff_compute.total_seconds():
                correct_serp = serp["serp_id"]
                time_diff = time_diff_compute.total_seconds()
        associated_serp_ids.append(correct_serp)
    else:
        associated_serp_ids.append(associated_serp["serp_id"].values[0])

viewed_results_df["serp_id"] = associated_serp_ids

In [41]:
clicked_results_df.loc[(clicked_results_df["uid"]==4)&(clicked_results_df["topic_number"]=="g3t2")&(clicked_results_df["query"]=="Che cosa rappresenta l'imagine del simbolo banderia dell'India")&(clicked_results_df["rank"]==2)]

,uid,topic_number,query,url,rank,timestamp,serp_id
15,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:11:04.292,serp14
16,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:12:03.487,serp14

In [42]:
viewed_results_df.loc[(viewed_results_df["uid"]==4)&(viewed_results_df["topic_number"]=="g3t2")&(viewed_results_df["query"]=="Che cosa rappresenta l'imagine del simbolo banderia dell'India")&(viewed_results_df["rank"]==2)]

,uid,topic_number,query,url,rank,viewType,timestamp,serp_id
149,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,2026-05-19 14:54:59.696,serp13
154,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,2026-05-19 14:55:37.301,serp13
165,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,2026-05-19 14:58:09.379,serp13
169,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,2026-05-19 14:58:14.141,serp13
197,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,2026-05-19 14:58:46.706,serp13
213,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,2026-05-19 14:59:35.679,serp13
217,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,2026-05-19 14:59:37.452,serp14
219,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,2026-05-19 14:59:42.185,serp14
327,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,2026-05-19 15:10:33.828,serp14
328,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,2026-05-19 15:11:04.278,serp14
331,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,2026-05-19 15:11:53.293,serp14
332,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,2026-05-19 15:12:03.475,serp14

In [43]:
clicked_results_df.loc[pd.isna(clicked_results_df["serp_id"])]

Empty DataFrame
Columns: [uid, topic_number, query, url, rank, timestamp, serp_id]
Index: []

In [44]:
viewed_results_df.loc[pd.isna(viewed_results_df["serp_id"])]

Empty DataFrame
Columns: [uid, topic_number, query, url, rank, viewType, timestamp, serp_id]
Index: []

In [45]:
clicked_results_df.loc[clicked_results_df["timestamp"]=="2026-05-19 10:46:51.654"]

,uid,topic_number,query,url,rank,timestamp,serp_id
123,15,g4t2,Qual è stato il primo animale nello spazio e c...,https://www.storicang.it/foto-del-giorno/laika...,1,2026-05-19 10:46:51.654,serp92

In [46]:
clicked_results_df.loc[clicked_results_df["timestamp"]=="2026-05-19 10:51:16.099"]

,uid,topic_number,query,url,rank,timestamp,serp_id
124,15,g4t2,Qual è stato il primo animale nello spazio e c...,https://www.storicang.it/foto-del-giorno/laika...,1,2026-05-19 10:51:16.099,serp93

In [47]:
clicked_results_df.head(20)

,uid,topic_number,query,url,rank,timestamp,serp_id
0,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:43.444,serp1
1,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:53:19.408,serp1
2,1,g3t2,Quale è il nome del simbolo al centro della ba...,https://it.gov-civ-guarda.pt/flag-india,1,2026-05-19 15:02:48.776,serp2
3,1,g3t1,Fiume sacro degli indiani,https://www.consciousjourneys.com/it/approfond...,2,2026-05-19 15:08:58.405,serp3
4,2,g3t3,Quali sono i 5 animali tipici dall'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:52:53.759,serp5
5,2,g3t2,Qual è il nome del simbolo al centro della b...,https://sullestradedelmondo.it/bandiera-indiana/,3,2026-05-19 15:09:25.575,serp7
6,2,g3t1,Come si chiama il fiume sacro agli indiani,https://www.consciousjourneys.com/it/approfond...,1,2026-05-19 15:14:18.095,serp8
7,3,g3t3,Quali sono 5 animali tipici dell'india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:56:28.100,serp10
8,3,g3t2,Quale il nome del simbolo al centro della band...,https://mastroviaggiatore.it/saree/blog/lindia...,1,2026-05-19 15:05:39.212,serp11
9,3,g3t2,Quale il nome del simbolo al centro della band...,https://it.gov-civ-guarda.pt/flag-india,3,2026-05-19 15:06:00.133,serp11
10,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://it.gov-civ-guarda.pt/flag-india,7,2026-05-19 14:55:47.060,serp13
11,4,g3t2,Quale il simbolo dell'India,https://liceoberchet.edu.it/ricerche/geo4d_03/...,1,2026-05-19 15:06:06.889,serp16
12,4,g3t2,Quale il simbolo dell'India,https://www.focus.it/ambiente/animali/8-cose-c...,2,2026-05-19 15:06:28.655,serp16
13,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:36.085,serp16
14,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:49.996,serp16
15,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:11:04.292,serp14
16,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:12:03.487,serp14
17,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:14:14.237,serp17
18,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:17:21.809,serp17
19,4,g3t1,Fiume sacro indiano,https://www.goasia.it/la-religione-gange-fiume...,1,2026-05-19 15:20:26.846,serp18

In [48]:
clicked_results_df.to_csv("Data/clicked_results_df.csv", index=False, encoding='utf8')
viewed_results_df.to_csv("Data/viewed_results_df.csv", index=False, encoding='utf8')

In [49]:
df = pd.DataFrame(clicked_results_df.groupby(["uid", "topic_number", "serp_id"])["url"].value_counts()).reset_index()

click_count = []

for _, row in serp_df.iterrows():
    serp_row = df.loc[(df["uid"]==row["uid"])&(df["topic_number"]==row["topic_number"])&(df["serp_id"]==row["serp_id"])&(df["url"]==row["url"])]
    if len(serp_row) > 1:
        print(row, serp_row)
    elif len(serp_row) == 0:
        click_count.append(0)
    else:
        click_count.append(serp_row["count"].values[0])

serp_df["click_count"] = click_count

In [50]:
serp_df.head(20)

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,relevance_score,click_count
0,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:51:27.687,1,2
1,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,2026-05-19 14:51:27.688,1,0
2,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.storicang.it/a/civilta-dellindo-i-...,"La civiltà dell'Indo, i misteri di un popolo d...","\n Jun 5, 2023 ... Sono note cinque m...",3.0,2026-05-19 14:51:27.689,0,0
3,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... Chi sono, da dove ...",4.0,2026-05-19 14:51:27.690,0,0
4,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/comportamento/feste...,Festa della mamma: come si festeggia nel resto...,\n Il dolce tipico per celebrare ques...,5.0,2026-05-19 14:51:27.691,0,0
5,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/giochi/i-20-parchi-...,I 20 parchi divertimento più belli d'Italia - ...,\n Parco faunistico immerso in un bos...,6.0,2026-05-19 14:51:27.693,0,0
6,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scuola/geografia/10...,10 cose che (forse) non sai sull'Europa - Focu...,\n Come popolazione conta 508 milioni...,7.0,2026-05-19 14:51:27.694,0,0
7,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scienza/ambiente/ec...,9 interessantissime curiosità sulle piante gra...,\n 2 - QUALI SONO LE TIPOLOGIE? Esist...,8.0,2026-05-19 14:51:27.696,0,0
8,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scienza/natura/le-s...,Le spiagge più strane e colorate del mondo - F...,\n ... è di origine vulcanica: in pra...,9.0,2026-05-19 14:51:27.697,0,0
9,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/animali/curiosita-a...,Idee per nomi di gatto - FocusJunior.it,"\n Mar 19, 2025 ... Il gatto è l'anim...",10.0,2026-05-19 14:51:27.699,0,0
10,1,g3t2,Quale è il nome del simbolo al centro della ba...,serp2,https://it.gov-civ-guarda.pt/flag-india,"Bandiera dell'India | Storia, design e signifi...",\n Nel 1921 uno studente di nome Ping...,1.0,2026-05-19 15:02:42.576,1,1
11,1,g3t1,Fiume sacro degli indiani,serp3,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Qui le persone rendono omaggio ai ...,1.0,2026-05-19 15:08:41.314,1,0
12,1,g3t1,Fiume sacro degli indiani,serp3,https://www.consciousjourneys.com/it/approfond...,"Gange, il fiume sacro agli indù e alla popolaz...","\n Come abbiamo detto, il Gange è il ...",2.0,2026-05-19 15:08:41.315,1,1
13,1,g3t1,Fiume sacro degli indiani,serp3,https://italiano.memphistours.com/india/fiume-...,Alla Scoperta del Sacro Fiume Gange - India - ...,\n Le Sundarbans sono un ecosistema u...,3.0,2026-05-19 15:08:41.316,1,0
14,1,g3t1,Fiume sacro degli indiani,serp3,https://it.renovables.blog/acqua/il-sacro-fium...,Alla scoperta del Gange: il fiume sacro e inqu...,\n Oltre a essere il fiume più lungo ...,4.0,2026-05-19 15:08:41.317,1,0
15,1,g3t1,Fiume sacro degli indiani,serp3,https://www.skuola.net/geografia-medie/india-d...,"L'India: un viaggio tra cultura, geografia e t...","\n Jun 28, 2014 ... Alla costa indian...",5.0,2026-05-19 15:08:41.319,0,0
16,1,g3t1,Fiume sacro degli indiani,serp3,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... Lungo quella terra...",6.0,2026-05-19 15:08:41.320,0,0
17,1,g3t1,Fiume sacro degli indiani,serp3,https://www.focusjunior.it/scuola/storia/le-re...,Quali sono le grandi religioni nel mondo? - Fo...,"\n Da allora, gli ebrei sanno di dove...",7.0,2026-05-19 15:08:41.321,0,0
18,1,g3t1,Fiume sacro degli indiani,serp3,https://www.focusjunior.it/scuola/ricerche-per...,Ricerche per la scuola | L'Arabia Saudita - Fo...,\n ... della Ka-ba . L'importanza spi...,8.0,2026-05-19 15:08:41.322,0,0
19,2,g3t3,Quali sono i animali dall'India,serp4,https://www.focusjunior.it/scuola/storia/il-pi...,Chi ha inventato il pigiama? - FocusJunior.it,\n Ma quali sono le sue origini? DAL ...,1.0,2026-05-19 14:50:23.230,0,0

In [51]:
len(serp_df.loc[pd.isna(serp_df["rank"])])

15

In [52]:
query_df = pd.read_csv("Data/query_df.csv")
serp_df["qid"] = [query_df.loc[query_df["serp_id"]==serp_id]["qid"].values[0] for serp_id in serp_df["serp_id"]]
serp_df = serp_df[["uid", "topic_number", "qid", "query", "serp_id", "url", "title", "snippet", "rank", "relevance_score", "click_count", "timestamp"]]

In [53]:
serp_df.head(1)

,uid,topic_number,qid,query,serp_id,url,title,snippet,rank,relevance_score,click_count,timestamp
0,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,1,2,2026-05-19 14:51:27.687

In [54]:
cleaned_serp_df = serp_df.dropna(subset=["rank"])
cleaned_serp_df["rank"] = cleaned_serp_df["rank"].astype(int)

C:\Users\Hrishita Chakrabarti\AppData\Local\Temp\ipykernel_33720\193022930.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_serp_df["rank"] = cleaned_serp_df["rank"].astype(int)

In [55]:
len(serp_df), len(cleaned_serp_df)

(945, 930)

In [56]:
serp_df.to_csv("Data/logs_compiled.csv", index=False, encoding='utf8')
cleaned_serp_df.to_csv("Data/results_navigation.csv", index=False, encoding='utf8')

In [57]:
serp_df.loc[serp_df["serp_id"]=="serp119"]

Empty DataFrame
Columns: [uid, topic_number, qid, query, serp_id, url, title, snippet, rank, relevance_score, click_count, timestamp]
Index: []

## information distillation

### automatic scraping

In [58]:
# import pandas as pd
# import urllib3
# from urllib3 import Retry
# from tqdm.notebook import tqdm
# import time
# from bs4 import BeautifulSoup

# serp_df = pd.read_csv("Data/logs_compiled.csv")
# len(serp_df["url"].unique())

# corpus = []
# for idx, url in tqdm(zip(range(len(serp_df["url"].unique())), serp_df["url"].unique()), total = len(serp_df["url"].unique())):
#     if idx % 50 == 0 and idx!=0:
#         time.sleep(10)
#     if pd.notna(url):
#         try:
#             html = urllib3.request("GET", url, retries=Retry(5), headers={'User-Agent': 'Mozilla/5.0'})
#             # html = urllib3.request("GET", url, retries=False)
#             if html.status == 200:
#                 soup = BeautifulSoup(markup = html.data, features='lxml')
#                 # kill all script and style elements
#                 for script in soup(["script", "style", "nav", "header", "footer", "aside", "img", "link"]):
#                     script.extract() # rip it out
#                     # script.decompose() 
#                 corpus.append(["d"+str(idx), url, str(soup.body), str(soup.body.get_text(separator='\n ', strip=True)), "auto-scraped"])
#             else:
#                 corpus.append(["d"+str(idx), url, None, None, "manual-scraped"])
#         except:
#             corpus.append(["d"+str(idx), url, None, None, "manual-scraped"])

In [59]:
# corpus_df = pd.DataFrame(corpus, columns = ["doc_id", "url", "html_content", "text_content", "scraping_source"])
# corpus_df.to_excel("Data/corpus.xlsx", index=False)
# # corpus_df.to_csv("Data/corpus.tsv", index=False, encoding="utf8", sep="\t")

In [60]:
# corpus_df.head()

In [61]:
# len(corpus_df.loc[pd.isna(corpus_df["text_content"])])

### manual scraping

In [62]:
# html_text = """
# <body><p class="s1" style="padding-top: 2pt;text-indent: 0pt;text-align: center;">LA BANDIERA DELL’INDIA</p><p style="text-indent: 0pt;text-align: left;"><br/></p><p style="padding-left: 59pt;text-indent: 0pt;text-align: left;"><span><img width="507" height="373" alt="image" src="3_files/Image_001.jpg"/></span></p><p style="padding-top: 5pt;text-indent: 0pt;text-align: left;"><br/></p><p style="padding-left: 5pt;text-indent: 0pt;text-align: justify;">La bandiera dell’India è anche detta TIRANGA cioè tricolore.</p><p style="padding-top: 5pt;padding-left: 5pt;text-indent: 0pt;text-align: justify;">E’  suddivisa  in  tre  strisce  orizzontali  di  uguali dimensioni:</p><ul id="l1"><li data-list-text="•"><p style="padding-top: 1pt;padding-left: 27pt;text-indent: -21pt;text-align: justify;">in alto di colore arancione zafferano che simboleggia coraggio e sacrificio;</p></li><li data-list-text="•"><p style="padding-top: 1pt;padding-left: 27pt;text-indent: -21pt;text-align: justify;">al centro di colore bianco che rappresenta pace e verità;</p></li><li data-list-text="•"><p style="padding-top: 1pt;padding-left: 26pt;text-indent: -21pt;text-align: justify;">in basso di colore verde che esprime fede e cavalleria.</p></li></ul><p style="padding-top: 5pt;padding-left: 5pt;text-indent: 0pt;text-align: justify;">Al  centro  c’è  una  ruota  vuota  chiamata  ASHOKA CHAKRA la quale con i suoi 24 raggi raffigura le 24 ore e il progresso costante.</p><p style="text-indent: 0pt;text-align: left;"><br/></p><table style="border-collapse:collapse;margin-left:84.9347pt" cellspacing="0"><tr style="height:118pt"><td style="width:197pt;border-top-style:solid;border-top-width:3pt;border-left-style:solid;border-left-width:2pt;border-bottom-style:solid;border-bottom-width:3pt"><p style="text-indent: 0pt;text-align: left;"><br/></p></td><td style="width:276pt;border-top-style:solid;border-top-width:3pt;border-bottom-style:solid;border-bottom-width:3pt;border-right-style:solid;border-right-width:2pt" rowspan="3"><p style="text-indent: 0pt;text-align: left;"><br/></p><p style="text-indent: 0pt;text-align: left;"><span><img width="128" height="161" alt="image" src="3_files/Image_002.jpg"/></span></p><p style="text-indent: 0pt;text-align: left;"><br/></p><p class="s2" style="padding-right: 2pt;text-indent: 0pt;line-height: 28pt;text-align: right;">India</p></td></tr><tr style="height:114pt"><td style="width:197pt;border-top-style:solid;border-top-width:3pt;border-left-style:solid;border-left-width:2pt;border-bottom-style:solid;border-bottom-width:3pt"><p style="text-indent: 0pt;text-align: left;"><br/></p></td></tr><tr style="height:110pt"><td style="width:197pt;border-top-style:solid;border-top-width:3pt;border-left-style:solid;border-left-width:2pt;border-bottom-style:solid;border-bottom-width:3pt"><p style="text-indent: 0pt;text-align: left;"><br/></p></td></tr></table><p style="text-indent: 0pt;text-align: left;"><br/></p><p class="s3" style="padding-left: 42pt;text-indent: 0pt;text-align: left;">(c) <a href="http://www.flagspot.net/" class="a" target="_blank">www</a><a href="http://www.flagspot.net/" class="s4" target="_blank">.</a><a href="http://www.flagspot.net/" target="_blank">flagspot.net</a></p></body>
# """

In [63]:
# corpus_df = pd.read_excel("Data/corpus.xlsx")
# url = "https://old.icsestopascoli.edu.it/wp-content/uploads/2020/05/3.Bandiera-dellIndia.pdf"
# idx = corpus_df.loc[corpus_df["url"]==url].index
# corpus_df.loc[idx, ["html_content"]]

In [64]:
# from bs4 import BeautifulSoup

# soup = BeautifulSoup(markup = html_text, features='lxml')
# # print(soup.body)
# # kill all script and style elements
# for script in soup(["script", "style", "nav", "header", "footer", "aside", "img", "link"]):
#     # print(soup.body)
#     script.extract() # rip it out
#     # print(soup.body)
#     # script.decompose() 
#     corpus_df.loc[idx, ["html_content"]] = str(soup.body)
#     corpus_df.loc[idx, ["text_content"]] = str(soup.body.get_text(separator='\n ', strip=True))

In [65]:
# corpus_df.loc[idx, ["html_content"]]

In [66]:
# corpus_df.to_excel("Data/corpus.xlsx", index=False)

### answer matching

In [67]:
import pandas as pd
import json
# import spacy

# nlp = spacy.load("it_core_news_sm")

final_answer_df = pd.read_csv("Data/final_answer_df.csv")

with open("Data/answer_set.json", 'r') as f:
        answer_set = json.load(f)

match_counts = []
matched_keywords = []
for _, row in final_answer_df.iterrows():
        num_matches = 0
        answers = answer_set[row["topic_number"]]
        matched_answers = []
        for answer_key in answers.keys():
                for answer in answers[answer_key]:
                        if answer.title() in row["answer"].title():
                        # print(row["answer"], ";", answer)
                                matched_answers.append(answer)
                                num_matches += 1
                                break
        print(row["uid"], row["topic_number"], row["answer"], num_matches)
        match_counts.append(num_matches)
        matched_keywords.append(matched_answers)

final_answer_df["num_answer_matches"] = match_counts
final_answer_df["matched_keywords"] = matched_keywords

1 g3t3 Rinoceronte tigre Leone stambecco cervo 3
1 g3t2 Il simbolo della bandiera rappresenta una ruota 1
1 g3t1 Il fiume gange 1
2 g3t3 Tigre,leone,rinoceronte,barasingha,blackbuck. 5
2 g3t2 Ruota  1
2 g3t1 Fiume gange  1
3 g3t1 Gange 1
3 g3t3 Tigre ,Leone, rinoceronte ,Blackbuck barasingha  5
3 g3t2 Un sole 0
4 g3t2 Ashoka. La ruota della vita buddista 2
4 g3t3 Tigre del bengaline
Leone asiatico
Rinoceronte Indiano
Blackbuck
Barasingha  5
4 g3t1 Gange 1
5 g3t1 Gange, il fiume sacro agli indu e la popolazione indiana 1
5 g3t3 Natura selvaggia tra tigri e leoni terrelncognite magazine 0
5 g3t2 Bandiera indiana significato ashoka chakra simbolo della vita  1
6 g3t1 Gange 1
6 g3t3 Tigress del bengala Leone asiatico rinoceronte INDIANO barasingha blackbuck 5
6 g3t2 La ruota ashoka chakra 2
7 g3t2 E un. Sole blu 0
7 g3t3 Bengala Leone asiatico  rinoceronte indiano barasighna 2
7 g3t1 Gange il fiume sacro again indu e alla popolazione indiana 1
8 g3t3 Tigre elefante pavone rinoceronte scimmie 4
8 g3t2 Ruota con 24 raggi,blu nevy 1
8 g3t1 Gange 1
9 g4t2 Il primo animale  mandato nello spazio è state una cagnietta Di nome Laika  1
9 g4t1 Ganimede e Callisto  2
9 g4t3 Andromeda Triangolo Orsa Minore 2
10 g4t3 Galassia del triangolo galassia del pegaso galassia della fenice 3
10 g4t2 Il primo animale che è andato nello spazio  era il cane Laika 2
10 g4t1 Io Europa ganimede e calisto 3
11 g4t3 Andromeda galassia del triangolo piccola nube di magellano
 3
11 g4t1 Callisto Europa Ganimede  Io 4
11 g4t2 Laika 1
12 g4t1 Io, Ganimede, Europa, Callisto  4
12 g4t2 È stato un cane di nome Laika 2
12 g4t3 Andromeda, galassia del triangolo M31, galassia sombrero M104 3
13 g4t1 Io, Europa, Ganimede e Callisto sono i 4 satelliti di Giove 4
13 g4t3 Le 3 galassie sono NGC3109,galassia di Andromeda galassia del triangolo  3
13 g4t2 Laika è stata il primo animale ed  è un cane  2
14 g4t1 Ganimede Callisto io Europa  4
14 g4t3 Andromeda del triangolo gruppo locale 2
14 g4t2 Un cane di nome Laika 2
15 g4t2 Il primo animale nello spazio è un cane e si chiamava Laika. 2
15 g4t3 Galassia di Andromeda Galassie di Fireworks Galassia del Triangolo 2
15 g4t1 Io Europa Ganimede e Callisto 4
16 g4t1 I satelliti maggiori di Giove si chiamano lune galileiane 0
16 g4t3 Andromeda, Galassia Sombrero ,Galassia del Triangolo
 3
16 g4t2 Il primo animali è stato un cane che si chiamava Laika 2
17 g3t3 Pavone tigre 🐅 scimmia 🐵 leone cobra 5
17 g3t2 Rapreseta la ruota dellavitabhuddista, si chiama ashoka  2
17 g3t1 Il fiume si chiama  gange 1
18 g3t3 Tigre del bengala ,Leone asiatico ,rinoceronte Indiano ,barasingha ,Blackbuck 5
18 g3t2 Sole 0
18 g3t1 Il gange u 1

In [68]:
final_answer_df.to_csv("Data/final_answer_df.csv", index=False, encoding='utf8')

In [69]:
final_answer_df.head()

,uid,topic_number,prompt,answer,timestamp,num_answer_matches,matched_keywords
0,1,g3t3,Quali sono 5 animali tipici dell'India?,Rinoceronte tigre Leone stambecco cervo,2026-05-19 14:56:19.153,3,"[tigre, rinoceronte, leone]"
1,1,g3t2,Qual è il nome del simbolo al centro della ban...,Il simbolo della bandiera rappresenta una ruota,2026-05-19 15:06:18.848,1,[ruota]
2,1,g3t1,Come si chiama il fiume sacro agli indiani?,Il fiume gange,2026-05-19 15:10:10.812,1,[gange]
3,2,g3t3,Quali sono 5 animali tipici dell'India?,"Tigre,leone,rinoceronte,barasingha,blackbuck.",2026-05-19 14:58:07.578,5,"[tigre, rinoceronte, leone, barasingha, blackb..."
4,2,g3t2,Qual è il nome del simbolo al centro della ban...,Ruota,2026-05-19 15:10:30.790,1,[ruota]