In [1]:
import json
import pandas as pd
import glob
import numpy as np
import driver

In [2]:
query_df = pd.DataFrame()
query_actions_df = pd.DataFrame() 
serp_df = pd.DataFrame()
clicked_results_df = pd.DataFrame()
viewed_results_df = pd.DataFrame()
final_answer_df = pd.DataFrame()

for file_name in glob.glob("Data/3rd/*_FULL.log"):
    # print(file_name)
    with open(file_name, 'r') as f:
        result = [json.loads(x) for x in f.readlines()]
    
    # query actions
    query_temp_df = driver.get_queries(result)
    query_df = pd.concat([query_df, query_temp_df], ignore_index=True)

    # query actions
    query_actions_temp_df = driver.get_query_actions(result)
    query_actions_df = pd.concat([query_actions_df, query_actions_temp_df], ignore_index=True)

    # SERPs generated
    serp_temp_df = driver.get_generated_serps(result)
    serp_df = pd.concat([serp_df, serp_temp_df], ignore_index=True)

    # Clicked results
    clicked_results_temp_df = driver.get_clicked_results(result)
    clicked_results_df = pd.concat([clicked_results_df, clicked_results_temp_df], ignore_index=True)

    # Viewed results
    viewed_results_temp_df = driver.get_viewed_results(result) 
    viewed_results_df = pd.concat([viewed_results_df, viewed_results_temp_df])

    # final answers
    final_answer_temp_df = driver.get_final_answers(result)
    final_answer_df = pd.concat([final_answer_df, final_answer_temp_df], ignore_index=True)

for file_name in glob.glob("Data/4th/*_FULL.log"):
    # print(file_name)
    with open(file_name, 'r') as f:
        result = [json.loads(x) for x in f.readlines()]
    
    # query actions
    query_temp_df = driver.get_queries(result)
    query_df = pd.concat([query_df, query_temp_df], ignore_index=True)

    # query actions
    query_actions_temp_df = driver.get_query_actions(result)
    query_actions_df = pd.concat([query_actions_df, query_actions_temp_df], ignore_index=True)

    # SERPs generated
    serp_temp_df = driver.get_generated_serps(result)
    serp_df = pd.concat([serp_df, serp_temp_df], ignore_index=True)

    # Clicked results
    clicked_results_temp_df = driver.get_clicked_results(result)
    clicked_results_df = pd.concat([clicked_results_df, clicked_results_temp_df], ignore_index=True)

    # Viewed results
    viewed_results_temp_df = driver.get_viewed_results(result) 
    viewed_results_df = pd.concat([viewed_results_df, viewed_results_temp_df])

    # final answers
    final_answer_temp_df = driver.get_final_answers(result)
    final_answer_df = pd.concat([final_answer_df, final_answer_temp_df], ignore_index=True)

## reordering all dataframes uid, topic_number, and timestamp
query_df = query_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
query_actions_df = query_actions_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
serp_df = serp_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
clicked_results_df = clicked_results_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
viewed_results_df = viewed_results_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)
final_answer_df = final_answer_df.sort_values(["uid", "timestamp"]).reset_index(drop=True)


## assigning qid
query_df["qid"] = ["q"+str(i) for i in range(1, len(query_df)+1)]
query_df = query_df[["uid", "topic_number", "qid", "query", "source", "timestamp"]]


## assigning serp id
serp_num = 0
serp_id_list = []

for _, row in serp_df.iterrows():
    if row["rank"]==1 or pd.isna(row["rank"]):
        serp_num += 1
    serp_id_list.append("serp"+str(serp_num))

serp_df["serp_id"] = serp_id_list
serp_df = serp_df[["uid", "topic_number", "query", "serp_id", "url", "title", "snippet", "rank", "timestamp"]]

## removing duplicates
final_answer_df = final_answer_df.drop_duplicates(ignore_index=True)

In [3]:
query_df.sort_values(["uid", "timestamp"])

,uid,topic_number,qid,query,source,timestamp
0,1,g3t3,q1,Quali sono i cinque animali tipici dell india,UserFormulated,2026-05-19 14:51:26.583
1,1,g3t2,q2,Quale è il nome del simbolo al centro della ba...,UserFormulated,2026-05-19 15:02:41.120
2,1,g3t1,q3,Fiume sacro degli indiani,UserFormulated,2026-05-19 15:08:39.525
3,2,g3t3,q4,Quali sono i animali dall'India,UserFormulated,2026-05-19 14:50:22.081
4,2,g3t3,q5,Quali sono i 5 animali tipici dall'India,UserFormulated,2026-05-19 14:51:20.189
...,...,...,...,...,...,...
113,18,g3t3,q114,Quali sono i cinque tipici animali dell l india,UserFormulated,2026-05-19 14:52:34.782
114,18,g3t3,q115,Quali sono i 5 cinque tipici animali dell l i...,UserFormulated,2026-05-19 14:54:58.878
115,18,g3t2,q116,Quale il nome del simbolo al centro della band...,UserFormulated,2026-05-19 15:09:14.538
116,18,g3t2,q117,Simbolo della bandiera dell'india,UserFormulated,2026-05-19 15:13:42.292
117,18,g3t1,q118,Come si chiama il fiume sacro degli indiani,UserFormulated,2026-05-19 15:16:04.199

## query formulation

In [4]:
query_df.head()

,uid,topic_number,qid,query,source,timestamp
0,1,g3t3,q1,Quali sono i cinque animali tipici dell india,UserFormulated,2026-05-19 14:51:26.583
1,1,g3t2,q2,Quale è il nome del simbolo al centro della ba...,UserFormulated,2026-05-19 15:02:41.120
2,1,g3t1,q3,Fiume sacro degli indiani,UserFormulated,2026-05-19 15:08:39.525
3,2,g3t3,q4,Quali sono i animali dall'India,UserFormulated,2026-05-19 14:50:22.081
4,2,g3t3,q5,Quali sono i 5 animali tipici dall'India,UserFormulated,2026-05-19 14:51:20.189

In [5]:
len(query_df)

118

In [6]:
serp_df.head()

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
0,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:51:27.687
1,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,2026-05-19 14:51:27.688
2,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.storicang.it/a/civilta-dellindo-i-...,"La civiltà dell'Indo, i misteri di un popolo d...","\n Jun 5, 2023 ... Sono note cinque m...",3.0,2026-05-19 14:51:27.689
3,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... Chi sono, da dove ...",4.0,2026-05-19 14:51:27.690
4,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/comportamento/feste...,Festa della mamma: come si festeggia nel resto...,\n Il dolce tipico per celebrare ques...,5.0,2026-05-19 14:51:27.691

In [7]:
len(serp_df["serp_id"].unique())

118

In [8]:
temp_df = serp_df.loc[(serp_df["rank"]==1) | (pd.isna(serp_df["rank"]))]
len(temp_df)

118

In [9]:
query_df.loc[query_df["uid"]==2]

,uid,topic_number,qid,query,source,timestamp
3,2,g3t3,q4,Quali sono i animali dall'India,UserFormulated,2026-05-19 14:50:22.081
4,2,g3t3,q5,Quali sono i 5 animali tipici dall'India,UserFormulated,2026-05-19 14:51:20.189
5,2,g3t2,q6,Qual è il nome del simbolo al centro della ban...,UserFormulated,2026-05-19 15:05:41.521
6,2,g3t2,q7,Qual è il nome del simbolo al centro della b...,UserFormulated,2026-05-19 15:09:06.317
7,2,g3t1,q8,Come si chiama il fiume sacro agli indiani,UserFormulated,2026-05-19 15:14:10.201

In [10]:
associated_query_ids = []

for _, row in temp_df.iterrows():
    associated_query = query_df.loc[
        (query_df["uid"]==row["uid"]) 
        & (query_df["topic_number"]==row["topic_number"]) 
        & (query_df["query"]==row["query"]) 
        & (query_df["timestamp"]<row["timestamp"])
    ]

    if len(associated_query) == 0:
        print("No query found for serp id: ", row["serp_id"], "; uid: ", row["uid"], "; query: ", row["query"], "; time: ", row["timestamp"])
        # associated_query = query_df.loc[
        #     (query_df["uid"]==row["uid"]) 
        #     & (query_df["topic_number"]==row["topic_number"]) 
        #     # & (query_df["query"]==row["query"]) 
        #     & (query_df["timestamp"]<row["timestamp"])
        # ]
        # print("Matching based on uid and topic number (w/o query match) led to ", len(associated_query), " matches.\n")
        associated_query_ids.append(None)

    elif len(associated_query) > 1:
        # print("multiple queries found: ", row["serp_id"], row["uid"], row["timestamp"])
        time_diff = np.inf
        for _, query in associated_query.iterrows():
            # print(query)
            time_diff_compute = row["timestamp"] - query["timestamp"]
            if time_diff >= time_diff_compute.total_seconds():
                correct_query = query
                time_diff = time_diff_compute.total_seconds()
        # print("query chosen for ", row["serp_id"], "query: ", query["query"], "; timestamp: ", query["timestamp"])
        associated_query_ids.append(correct_query["qid"])
    else:
        associated_query_ids.append(associated_query["qid"].values[0])

temp_df["qid"] = associated_query_ids

C:\Users\hrishitachakra\AppData\Local\Temp\ipykernel_29744\1166631844.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df["qid"] = associated_query_ids

In [11]:
temp_df.loc[temp_df["uid"]==4]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,qid
86,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 14:54:59.384,q13
96,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 14:59:37.155,q14
106,4,g3t2,Quale il simbolo dell'India,serp15,https://liceoberchet.edu.it/ricerche/geo4d_03/...,India Britannica,\n Allora l'Union Jack era pulito ma ...,1.0,2026-05-19 15:03:54.002,q15
116,4,g3t2,Quale il simbolo dell'India,serp16,https://liceoberchet.edu.it/ricerche/geo4d_03/...,India Britannica,\n Allora l'Union Jack era pulito ma ...,1.0,2026-05-19 15:05:58.689,q16
126,4,g3t3,5 animali tipici dell'India,serp17,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 15:14:09.972,q17
145,4,g3t1,Fiume sacro indiano,serp18,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Il Gange è un grande fiume del sub...,1.0,2026-05-19 15:20:22.199,q18

In [12]:
set(query_df["qid"]) - set(temp_df["qid"])

set()

In [13]:
len(set(query_df["qid"]) - set(temp_df["qid"])), len(temp_df.loc[pd.isna(temp_df["qid"])])

(0, 0)

In [14]:
len(temp_df["qid"].unique()), len(temp_df)

(118, 118)

In [15]:
df = pd.DataFrame(temp_df.groupby(["qid"])["uid"].value_counts()).reset_index()
df.loc[df["count"]>1].sort_values(by=["uid"])

Empty DataFrame
Columns: [qid, uid, count]
Index: []

In [16]:
temp_df.loc[temp_df["uid"]==8]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,qid
308,8,g3t3,Quali sono i,serp43,https://www.focusjunior.it/scienza/ambiente/vu...,"Quali sono i vulcani attivi in Italia? I ""magn...",\n In Italia esistono almeno 10 vulca...,1.0,2026-05-19 14:49:49.307,q43
318,8,g3t3,Quali sono 5 animali dell India,serp44,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:51:12.191,q44
328,8,g3t3,Quali sono 5 animali dell India,serp45,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:53:54.964,q45
338,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp46,None,None,None,NaN,2026-05-19 15:04:52.511,q46
339,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp47,None,None,None,NaN,2026-05-19 15:05:05.152,q47
340,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp48,None,None,None,NaN,2026-05-19 15:08:36.757,q48
341,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp49,None,None,None,NaN,2026-05-19 15:09:48.390,q49
342,8,g3t2,centro bandiera india simbolo,serp50,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 15:11:41.365,q50
352,8,g3t2,Bandira india simbolo,serp51,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 15:14:07.992,q51
362,8,g3t1,Fiume sacro India,serp52,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Secondo gli indù questo fiume è sa...,1.0,2026-05-19 15:16:03.549,q52
372,8,g3t1,Fiume sacro India,serp53,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Secondo gli indù questo fiume è sa...,1.0,2026-05-19 15:16:18.583,q53

In [17]:
temp_df.loc[temp_df["qid"].isin(df.loc[df["count"]>1]["qid"].unique().tolist())]

Empty DataFrame
Columns: [uid, topic_number, query, serp_id, url, title, snippet, rank, timestamp, qid]
Index: []

In [18]:
temp_df.loc[temp_df["uid"]==5]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,qid
155,5,g3t1,Come si chiama il fiume,serp19,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n ... si dice possa curare anche i m...,1.0,2026-05-19 14:50:32.173,q19
165,5,g3t1,come si chiama il fiume sacro agli indianischen,serp20,None,None,None,NaN,2026-05-19 14:52:35.518,q20
166,5,g3t1,come si chiama il fiume sacro agli indianischen,serp21,None,None,None,NaN,2026-05-19 14:52:46.904,q21
167,5,g3t1,come si chiama il fiume sacro agli indiani,serp22,https://www.consciousjourneys.com/it/approfond...,"Gange, il fiume sacro agli indù e alla popolaz...","\n È altresì importante per la pesca,...",1.0,2026-05-19 14:53:00.313,q22
174,5,g3t1,come si chiama il fiume sacro agli indiani,serp23,https://www.consciousjourneys.com/it/approfond...,"Gange, il fiume sacro agli indù e alla popolaz...","\n È altresì importante per la pesca,...",1.0,2026-05-19 14:54:36.969,q23
181,5,g3t3,Qali sono 5 animali tipici dell india,serp24,None,None,None,NaN,2026-05-19 15:01:44.186,q24
182,5,g3t3,Qali sono 5 animali tipici dell india,serp25,None,None,None,NaN,2026-05-19 15:01:47.876,q25
183,5,g3t3,Qali sono 5 animali tipici dell india,serp26,None,None,None,NaN,2026-05-19 15:01:58.337,q26
184,5,g3t3,Quali sono 5 animali tipici dell india,serp27,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 15:02:31.643,q27
194,5,g3t3,Quali sono 5 animali tipici dell india,serp28,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 15:08:16.643,q28
204,5,g3t2,Qal e il,serp29,None,None,None,NaN,2026-05-19 15:15:44.081,q29
205,5,g3t2,Qual eil simbolo della bandiera india,serp30,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... I 24 raggi della ...",1.0,2026-05-19 15:19:13.407,q30
215,5,g3t2,Qual eil simbolo della bandiera india,serp31,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... I 24 raggi della ...",1.0,2026-05-19 15:21:01.262,q31
225,5,g3t2,Bandiera,serp32,https://www.focusjunior.it/scienza/ambiente/ch...,Che cos'è la Bandiera Blu? - FocusJunior.it,\n In altre parole la Bandiera Blu in...,1.0,2026-05-19 15:21:18.057,q32

In [19]:
query_df.loc[query_df["uid"]==5]

,uid,topic_number,qid,query,source,timestamp
18,5,g3t1,q19,Come si chiama il fiume,UserFormulated,2026-05-19 14:50:30.668
19,5,g3t1,q20,come si chiama il fiume sacro agli indianischen,UserFormulated,2026-05-19 14:52:33.886
20,5,g3t1,q21,come si chiama il fiume sacro agli indianischen,UserFormulated,2026-05-19 14:52:45.184
21,5,g3t1,q22,come si chiama il fiume sacro agli indiani,UserFormulated,2026-05-19 14:52:58.725
22,5,g3t1,q23,come si chiama il fiume sacro agli indiani,UserFormulated,2026-05-19 14:54:34.881
23,5,g3t3,q24,Qali sono 5 animali tipici dell india,UserFormulated,2026-05-19 15:01:42.366
24,5,g3t3,q25,Qali sono 5 animali tipici dell india,UserFormulated,2026-05-19 15:01:46.525
25,5,g3t3,q26,Qali sono 5 animali tipici dell india,UserFormulated,2026-05-19 15:01:56.495
26,5,g3t3,q27,Quali sono 5 animali tipici dell india,UserFormulated,2026-05-19 15:02:30.582
27,5,g3t3,q28,Quali sono 5 animali tipici dell india,UserFormulated,2026-05-19 15:08:15.219
28,5,g3t2,q29,Qal e il,UserFormulated,2026-05-19 15:15:42.116
29,5,g3t2,q30,Qual eil simbolo della bandiera india,UserFormulated,2026-05-19 15:19:12.025
30,5,g3t2,q31,Qual eil simbolo della bandiera india,UserFormulated,2026-05-19 15:20:59.385
31,5,g3t2,q32,Bandiera,UserFormulated,2026-05-19 15:21:16.565

In [20]:
temp_df.loc[pd.isna(temp_df["rank"])]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,qid
165,5,g3t1,come si chiama il fiume sacro agli indianischen,serp20,None,None,None,NaN,2026-05-19 14:52:35.518,q20
166,5,g3t1,come si chiama il fiume sacro agli indianischen,serp21,None,None,None,NaN,2026-05-19 14:52:46.904,q21
181,5,g3t3,Qali sono 5 animali tipici dell india,serp24,None,None,None,NaN,2026-05-19 15:01:44.186,q24
182,5,g3t3,Qali sono 5 animali tipici dell india,serp25,None,None,None,NaN,2026-05-19 15:01:47.876,q25
183,5,g3t3,Qali sono 5 animali tipici dell india,serp26,None,None,None,NaN,2026-05-19 15:01:58.337,q26
204,5,g3t2,Qal e il,serp29,None,None,None,NaN,2026-05-19 15:15:44.081,q29
338,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp46,None,None,None,NaN,2026-05-19 15:04:52.511,q46
339,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp47,None,None,None,NaN,2026-05-19 15:05:05.152,q47
340,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp48,None,None,None,NaN,2026-05-19 15:08:36.757,q48
341,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp49,None,None,None,NaN,2026-05-19 15:09:48.390,q49
414,9,g4t3,3 galassie oly,serp58,None,None,None,NaN,2026-05-19 11:09:41.822,q58
582,12,g4t3,3 galassie olt4e la nostra,serp76,None,None,None,NaN,2026-05-19 11:16:50.790,q76
583,12,g4t3,3 galassie olt4e la nostra,serp77,None,None,None,NaN,2026-05-19 11:16:54.735,q77
749,15,g4t3,qualifiche f1,serp94,None,None,None,NaN,2026-05-19 10:55:32.846,q94
781,15,g4t3,Nomi di alre galassie,serp98,None,None,None,NaN,2026-05-19 11:06:11.428,q98

In [21]:
query_df["serp_id"] = [temp_df.loc[temp_df["qid"]==qid]["serp_id"].values[0] for qid in query_df["qid"]]
query_df = query_df[["uid", "topic_number", "qid", "query", "source", "serp_id", "timestamp"]]
query_df.to_csv("Data/query_df.csv", index=False, encoding='utf8')

In [22]:
query_df.head()

,uid,topic_number,qid,query,source,serp_id,timestamp
0,1,g3t3,q1,Quali sono i cinque animali tipici dell india,UserFormulated,serp1,2026-05-19 14:51:26.583
1,1,g3t2,q2,Quale è il nome del simbolo al centro della ba...,UserFormulated,serp2,2026-05-19 15:02:41.120
2,1,g3t1,q3,Fiume sacro degli indiani,UserFormulated,serp3,2026-05-19 15:08:39.525
3,2,g3t3,q4,Quali sono i animali dall'India,UserFormulated,serp4,2026-05-19 14:50:22.081
4,2,g3t3,q5,Quali sono i 5 animali tipici dall'India,UserFormulated,serp5,2026-05-19 14:51:20.189

In [23]:
serp_df.loc[serp_df["rank"].isna()]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
165,5,g3t1,come si chiama il fiume sacro agli indianischen,serp20,None,None,None,NaN,2026-05-19 14:52:35.518
166,5,g3t1,come si chiama il fiume sacro agli indianischen,serp21,None,None,None,NaN,2026-05-19 14:52:46.904
181,5,g3t3,Qali sono 5 animali tipici dell india,serp24,None,None,None,NaN,2026-05-19 15:01:44.186
182,5,g3t3,Qali sono 5 animali tipici dell india,serp25,None,None,None,NaN,2026-05-19 15:01:47.876
183,5,g3t3,Qali sono 5 animali tipici dell india,serp26,None,None,None,NaN,2026-05-19 15:01:58.337
204,5,g3t2,Qal e il,serp29,None,None,None,NaN,2026-05-19 15:15:44.081
338,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp46,None,None,None,NaN,2026-05-19 15:04:52.511
339,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp47,None,None,None,NaN,2026-05-19 15:05:05.152
340,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp48,None,None,None,NaN,2026-05-19 15:08:36.757
341,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp49,None,None,None,NaN,2026-05-19 15:09:48.390
414,9,g4t3,3 galassie oly,serp58,None,None,None,NaN,2026-05-19 11:09:41.822
582,12,g4t3,3 galassie olt4e la nostra,serp76,None,None,None,NaN,2026-05-19 11:16:50.790
583,12,g4t3,3 galassie olt4e la nostra,serp77,None,None,None,NaN,2026-05-19 11:16:54.735
749,15,g4t3,qualifiche f1,serp94,None,None,None,NaN,2026-05-19 10:55:32.846
781,15,g4t3,Nomi di alre galassie,serp98,None,None,None,NaN,2026-05-19 11:06:11.428

In [24]:
df = pd.DataFrame(serp_df.loc[(serp_df["rank"]==1)|(serp_df["rank"].isna())].groupby(["uid", "topic_number"])["query"].value_counts()).reset_index()
df.loc[df["count"]>1]

    uid topic_number                                              query  count
13    4         g3t2  Che cosa rappresenta l'imagine del simbolo ban...      2
14    4         g3t2                        Quale il simbolo dell'India      2
16    5         g3t1         come si chiama il fiume sacro agli indiani      2
17    5         g3t1    come si chiama il fiume sacro agli indianischen      2
19    5         g3t2              Qual eil simbolo della bandiera india      2
22    5         g3t3              Qali sono 5 animali tipici dell india      3
23    5         g3t3             Quali sono 5 animali tipici dell india      2
31    7         g3t2           il simbolo della baniera dell dell'india      2
33    8         g3t1                                  Fiume sacro India      2
34    8         g3t2  Come si chiama il nome dell disegno nell centr...      2
39    8         g3t3                    Quali sono 5 animali dell India      2
47   10         g4t1    Come  si chiamano i satelliti maggiori di Giove      2
51   11         g4t2  Qual è stato il primo animale nello spazio e c...      2
59   12         g4t3                         3 galassie olt4e la nostra      2
76   15         g4t2  Qual è stato il primo animale nello spazio e c...      3
77   15         g4t3  Quali sono i nomi di altre 3 galassie oltre la...      2
82   16         g4t1    Come si chiamano i satelliti  maggiori di Giove      2
85   16         g4t3  Quali sono altre nomi di tre galassie in oltre...      3

In [25]:
q_df = pd.DataFrame(query_df.groupby(["uid", "topic_number"])["query"].value_counts()).reset_index()
q_df.loc[q_df["count"]>1]

    uid topic_number                                              query  count
13    4         g3t2  Che cosa rappresenta l'imagine del simbolo ban...      2
14    4         g3t2                        Quale il simbolo dell'India      2
16    5         g3t1         come si chiama il fiume sacro agli indiani      2
17    5         g3t1    come si chiama il fiume sacro agli indianischen      2
19    5         g3t2              Qual eil simbolo della bandiera india      2
22    5         g3t3              Qali sono 5 animali tipici dell india      3
23    5         g3t3             Quali sono 5 animali tipici dell india      2
31    7         g3t2           il simbolo della baniera dell dell'india      2
33    8         g3t1                                  Fiume sacro India      2
34    8         g3t2  Come si chiama il nome dell disegno nell centr...      2
39    8         g3t3                    Quali sono 5 animali dell India      2
47   10         g4t1    Come  si chiamano i satelliti maggiori di Giove      2
51   11         g4t2  Qual è stato il primo animale nello spazio e c...      2
59   12         g4t3                         3 galassie olt4e la nostra      2
76   15         g4t2  Qual è stato il primo animale nello spazio e c...      3
77   15         g4t3  Quali sono i nomi di altre 3 galassie oltre la...      2
82   16         g4t1    Come si chiamano i satelliti  maggiori di Giove      2
85   16         g4t3  Quali sono altre nomi di tre galassie in oltre...      3

In [26]:
q_df.loc[q_df["count"]==3]["query"].tolist()

['Qali sono 5 animali tipici dell india',
 'Qual è stato il primo animale nello spazio e come si chiamava',
 'Quali sono altre nomi di tre galassie in oltre la nostra']

In [27]:
query_df.loc[query_df["uid"]==15]

,uid,topic_number,qid,query,source,serp_id,timestamp
90,15,g4t2,q91,Qual è stato il primo animale nello spazio e c...,UserFormulated,serp91,2026-05-19 10:44:45.385
91,15,g4t2,q92,Qual è stato il primo animale nello spazio e c...,UserFormulated,serp92,2026-05-19 10:46:43.174
92,15,g4t2,q93,Qual è stato il primo animale nello spazio e c...,UserFormulated,serp93,2026-05-19 10:51:12.928
93,15,g4t3,q94,qualifiche f1,UserFormulated,serp94,2026-05-19 10:55:31.771
94,15,g4t3,q95,Quali sono i nomi di altre 3 galassie oltre la...,UserFormulated,serp95,2026-05-19 10:57:32.254
95,15,g4t3,q96,Quali sono i nomi di altre 3 galassie oltre la...,UserFormulated,serp96,2026-05-19 11:03:56.641
96,15,g4t3,q97,Quali sono i nomi di altre 3 galassie oltre la...,UserFormulated,serp97,2026-05-19 11:04:18.615
97,15,g4t3,q98,Nomi di alre galassie,UserFormulated,serp98,2026-05-19 11:06:09.998
98,15,g4t3,q99,Nomi di altre galassie,DidYouMean,serp99,2026-05-19 11:06:17.339
99,15,g4t1,q100,Come si chiamano i satelliti maggiori di Giove,UserFormulated,serp100,2026-05-19 11:15:45.762

In [28]:
serp_df["uid"].unique()

<IntegerArray>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
Length: 18, dtype: Int64

In [29]:
query_df.loc[query_df["uid"]==4]

,uid,topic_number,qid,query,source,serp_id,timestamp
12,4,g3t2,q13,Che cosa rappresenta l'imagine del simbolo ban...,UserFormulated,serp13,2026-05-19 14:54:57.981
13,4,g3t2,q14,Che cosa rappresenta l'imagine del simbolo ban...,UserFormulated,serp14,2026-05-19 14:59:35.687
14,4,g3t2,q15,Quale il simbolo dell'India,UserFormulated,serp15,2026-05-19 15:03:52.949
15,4,g3t2,q16,Quale il simbolo dell'India,UserFormulated,serp16,2026-05-19 15:05:57.147
16,4,g3t3,q17,5 animali tipici dell'India,UserFormulated,serp17,2026-05-19 15:14:08.813
17,4,g3t1,q18,Fiume sacro indiano,UserFormulated,serp18,2026-05-19 15:20:20.872

In [30]:
serp_df.loc[(serp_df["uid"]==4) & (serp_df["query"]=="Che cosa rappresenta l'imagine del simbolo banderia dell'India")]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
86,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 14:54:59.384
87,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... La storia della b...",2.0,2026-05-19 14:54:59.386
88,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focus.it/ambiente/animali/8-cose-c...,8 cose che (forse) non sai sulle vacche sacre ...,"\n Mar 31, 2019 ... Per molti indù, c...",3.0,2026-05-19 14:54:59.387
89,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focusjunior.it/news/holi-festival-...,"Holi festival, la festa dei colori - FocusJuni...","\n Mar 23, 2024 ... Si chiama Holi ed...",4.0,2026-05-19 14:54:59.392
90,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focusjunior.it/scuola/geografia/le...,Quali sono le 10 Nazioni più popolate del mond...,"\n Apr 16, 2017 ... Il Pakistan , che...",5.0,2026-05-19 14:54:59.394
91,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focusjunior.it/scuola/geografia/10...,10 cose che (forse) non sai sull'Europa - Focu...,"\n Dal nome, alla bandiera passando p...",6.0,2026-05-19 14:54:59.396
92,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://it.gov-civ-guarda.pt/flag-india,"Bandiera dell'India | Storia, design e signifi...",\n ... simbolo distintivo che potesse...,7.0,2026-05-19 14:54:59.398
93,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focusjunior.it/news/plogging-corre...,"Plogging, cos'è e perché aiuta il pianeta - Fo...",\n L'amore per l'ambiente ha portato ...,8.0,2026-05-19 14:54:59.399
94,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focusjunior.it/scuola/storia/rivol...,"Rivoluzione: quando il popolo si ribella, la s...","\n May 20, 2019 ... Il 22 settembre 1...",9.0,2026-05-19 14:54:59.401
95,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focusjunior.it/scuola/storia/chi-s...,Chi sono i curdi? - FocusJunior.it,"\n La bandiera curda, che oggi svento...",10.0,2026-05-19 14:54:59.403
96,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 14:59:37.155
97,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... La storia della b...",2.0,2026-05-19 14:59:37.157
98,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://www.focus.it/ambiente/animali/8-cose-c...,8 cose che (forse) non sai sulle vacche sacre ...,"\n Mar 31, 2019 ... Per molti indù, c...",3.0,2026-05-19 14:59:37.160
99,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://www.focusjunior.it/news/holi-festival-...,"Holi festival, la festa dei colori - FocusJuni...","\n Mar 23, 2024 ... Si chiama Holi ed...",4.0,2026-05-19 14:59:37.162
100,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://www.focusjunior.it/scuola/geografia/le...,Quali sono le 10 Nazioni più popolate del mond...,"\n Apr 16, 2017 ... Il Pakistan , che...",5.0,2026-05-19 14:59:37.165
101,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://www.focusjunior.it/scuola/geografia/10...,10 cose che (forse) non sai sull'Europa - Focu...,"\n Dal nome, alla bandiera passando p...",6.0,2026-05-19 14:59:37.173
102,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://it.gov-civ-guarda.pt/flag-india,"Bandiera dell'India | Storia, design e signifi...",\n ... simbolo distintivo che potesse...,7.0,2026-05-19 14:59:37.175
103,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://www.focusjunior.it/news/plogging-corre...,"Plogging, cos'è e perché aiuta il pianeta - Fo...",\n L'amore per l'ambiente ha portato ...,8.0,2026-05-19 14:59:37.178
104,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://www.focusjunior.it/scuola/storia/rivol...,"Rivoluzione: quando il popolo si ribella, la s...","\n May 20, 2019 ... Il 22 settembre 1...",9.0,2026-05-19 14:59:37.180
105,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp14,https://www.focusjunior.it/scuola/storia/chi-s...,Chi sono i curdi? - FocusJunior.it,"\n La bandiera curda, che oggi svento...",10.0,2026-05-19 14:59:37.182

In [31]:
serp_df.loc[(serp_df["uid"]==4)]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
86,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19 14:54:59.384
87,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... La storia della b...",2.0,2026-05-19 14:54:59.386
88,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focus.it/ambiente/animali/8-cose-c...,8 cose che (forse) non sai sulle vacche sacre ...,"\n Mar 31, 2019 ... Per molti indù, c...",3.0,2026-05-19 14:54:59.387
89,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focusjunior.it/news/holi-festival-...,"Holi festival, la festa dei colori - FocusJuni...","\n Mar 23, 2024 ... Si chiama Holi ed...",4.0,2026-05-19 14:54:59.392
90,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp13,https://www.focusjunior.it/scuola/geografia/le...,Quali sono le 10 Nazioni più popolate del mond...,"\n Apr 16, 2017 ... Il Pakistan , che...",5.0,2026-05-19 14:54:59.394
...,...,...,...,...,...,...,...,...,...
150,4,g3t1,Fiume sacro indiano,serp18,https://it.renovables.blog/acqua/il-sacro-fium...,Alla scoperta del Gange: il fiume sacro e inqu...,"\n La sorgente del fiume Gange, noto ...",6.0,2026-05-19 15:20:22.204
151,4,g3t1,Fiume sacro indiano,serp18,https://www.consciousjourneys.com/it/approfond...,"Varanasi, la città sacra per gli induisti sul ...",\n Varanasi è un'importante città ind...,7.0,2026-05-19 15:20:22.204
152,4,g3t1,Fiume sacro indiano,serp18,https://www.cinziamalaguti.it/fiumi-sacri-il-g...,Fiumi sacri: il Gange - Esperienziando Vitae,\n Il Gange scorre nel Nord dell'Indi...,8.0,2026-05-19 15:20:22.205
153,4,g3t1,Fiume sacro indiano,serp18,https://www.skuola.net/geografia-medie/india-d...,"L'India: un viaggio tra cultura, geografia e t...","\n Jun 28, 2014 ... Alla costa indian...",9.0,2026-05-19 15:20:22.206
154,4,g3t1,Fiume sacro indiano,serp18,https://www.focusjunior.it/animali/enciclopedi...,"Il gruccione, poco conosciuto ma davvero bello...","\n Mar 25, 2014 ... ... India e Sri L...",10.0,2026-05-19 15:20:22.207

In [32]:
relevance = pd.read_csv("Data/relevance.csv")
relevance_score = []

for _, row in serp_df.iterrows():
    relevant_docs = relevance.loc[relevance["topic_number"]==row["topic_number"]]["doc"].tolist()
    if row["url"] in relevant_docs:
        relevance_score.append(1)
    else:
        relevance_score.append(0)

serp_df["relevance_score"] = relevance_score

In [33]:
temp = serp_df.loc[serp_df["rank"]<=10].groupby(["serp_id"])["relevance_score"].sum()/10
df = pd.DataFrame(temp).reset_index()
df.columns = ["serp_id", "precision@10"]
df["query"] = [serp_df.loc[serp_df["serp_id"]==serp_id]["query"].values[0] for serp_id in df["serp_id"]]
df["topic_number"] = [serp_df.loc[serp_df["serp_id"]==serp_id]["topic_number"].values[0] for serp_id in df["serp_id"]]
df["uid"] = [serp_df.loc[serp_df["serp_id"]==serp_id]["uid"].values[0] for serp_id in df["serp_id"]]
df = df[["uid", "topic_number", "serp_id", "query", "precision@10"]]
df = df.sort_values(by=["uid"]).reset_index(drop=True)
df.to_csv("Data/query_formulation_df.csv", index=False, encoding='utf8')

In [34]:
df

,uid,topic_number,serp_id,query,precision@10
0,1,g3t3,serp1,Quali sono i cinque animali tipici dell india,0.2
1,1,g3t2,serp2,Quale è il nome del simbolo al centro della ba...,0.1
2,1,g3t1,serp3,Fiume sacro degli indiani,0.4
3,2,g3t3,serp4,Quali sono i animali dall'India,0.7
4,2,g3t3,serp5,Quali sono i 5 animali tipici dall'India,0.2
...,...,...,...,...,...
98,18,g3t3,serp114,Quali sono i cinque tipici animali dell l india,0.2
99,18,g3t2,serp117,Simbolo della bandiera dell'india,0.7
100,18,g3t2,serp116,Quale il nome del simbolo al centro della band...,0.3
101,18,g3t1,serp118,Come si chiama il fiume sacro degli indiani,0.4
102,18,g3t3,serp115,Quali sono i 5 cinque tipici animali dell l i...,0.1

## results navigation

In [35]:
serp_df.head(20)

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,relevance_score
0,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:51:27.687,1
1,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,2026-05-19 14:51:27.688,1
2,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.storicang.it/a/civilta-dellindo-i-...,"La civiltà dell'Indo, i misteri di un popolo d...","\n Jun 5, 2023 ... Sono note cinque m...",3.0,2026-05-19 14:51:27.689,0
3,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... Chi sono, da dove ...",4.0,2026-05-19 14:51:27.690,0
4,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/comportamento/feste...,Festa della mamma: come si festeggia nel resto...,\n Il dolce tipico per celebrare ques...,5.0,2026-05-19 14:51:27.691,0
5,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/giochi/i-20-parchi-...,I 20 parchi divertimento più belli d'Italia - ...,\n Parco faunistico immerso in un bos...,6.0,2026-05-19 14:51:27.693,0
6,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scuola/geografia/10...,10 cose che (forse) non sai sull'Europa - Focu...,\n Come popolazione conta 508 milioni...,7.0,2026-05-19 14:51:27.694,0
7,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scienza/ambiente/ec...,9 interessantissime curiosità sulle piante gra...,\n 2 - QUALI SONO LE TIPOLOGIE? Esist...,8.0,2026-05-19 14:51:27.696,0
8,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scienza/natura/le-s...,Le spiagge più strane e colorate del mondo - F...,\n ... è di origine vulcanica: in pra...,9.0,2026-05-19 14:51:27.697,0
9,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/animali/curiosita-a...,Idee per nomi di gatto - FocusJunior.it,"\n Mar 19, 2025 ... Il gatto è l'anim...",10.0,2026-05-19 14:51:27.699,0
10,1,g3t2,Quale è il nome del simbolo al centro della ba...,serp2,https://it.gov-civ-guarda.pt/flag-india,"Bandiera dell'India | Storia, design e signifi...",\n Nel 1921 uno studente di nome Ping...,1.0,2026-05-19 15:02:42.576,1
11,1,g3t1,Fiume sacro degli indiani,serp3,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Qui le persone rendono omaggio ai ...,1.0,2026-05-19 15:08:41.314,1
12,1,g3t1,Fiume sacro degli indiani,serp3,https://www.consciousjourneys.com/it/approfond...,"Gange, il fiume sacro agli indù e alla popolaz...","\n Come abbiamo detto, il Gange è il ...",2.0,2026-05-19 15:08:41.315,1
13,1,g3t1,Fiume sacro degli indiani,serp3,https://italiano.memphistours.com/india/fiume-...,Alla Scoperta del Sacro Fiume Gange - India - ...,\n Le Sundarbans sono un ecosistema u...,3.0,2026-05-19 15:08:41.316,1
14,1,g3t1,Fiume sacro degli indiani,serp3,https://it.renovables.blog/acqua/il-sacro-fium...,Alla scoperta del Gange: il fiume sacro e inqu...,\n Oltre a essere il fiume più lungo ...,4.0,2026-05-19 15:08:41.317,1
15,1,g3t1,Fiume sacro degli indiani,serp3,https://www.skuola.net/geografia-medie/india-d...,"L'India: un viaggio tra cultura, geografia e t...","\n Jun 28, 2014 ... Alla costa indian...",5.0,2026-05-19 15:08:41.319,0
16,1,g3t1,Fiume sacro degli indiani,serp3,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... Lungo quella terra...",6.0,2026-05-19 15:08:41.320,0
17,1,g3t1,Fiume sacro degli indiani,serp3,https://www.focusjunior.it/scuola/storia/le-re...,Quali sono le grandi religioni nel mondo? - Fo...,"\n Da allora, gli ebrei sanno di dove...",7.0,2026-05-19 15:08:41.321,0
18,1,g3t1,Fiume sacro degli indiani,serp3,https://www.focusjunior.it/scuola/ricerche-per...,Ricerche per la scuola | L'Arabia Saudita - Fo...,\n ... della Ka-ba . L'importanza spi...,8.0,2026-05-19 15:08:41.322,0
19,2,g3t3,Quali sono i animali dall'India,serp4,https://www.focusjunior.it/scuola/storia/il-pi...,Chi ha inventato il pigiama? - FocusJunior.it,\n Ma quali sono le sue origini? DAL ...,1.0,2026-05-19 14:50:23.230,0

In [36]:
clicked_results_df.head(40)

,uid,topic_number,query,url,rank,timestamp
0,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:43.444
1,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:53:19.408
2,1,g3t2,Quale è il nome del simbolo al centro della ba...,https://it.gov-civ-guarda.pt/flag-india,1,2026-05-19 15:02:48.776
3,1,g3t1,Fiume sacro degli indiani,https://www.consciousjourneys.com/it/approfond...,2,2026-05-19 15:08:58.405
4,2,g3t3,Quali sono i 5 animali tipici dall'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:52:53.759
5,2,g3t2,Qual è il nome del simbolo al centro della b...,https://sullestradedelmondo.it/bandiera-indiana/,3,2026-05-19 15:09:25.575
6,2,g3t1,Come si chiama il fiume sacro agli indiani,https://www.consciousjourneys.com/it/approfond...,1,2026-05-19 15:14:18.095
7,3,g3t3,Quali sono 5 animali tipici dell'india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:56:28.100
8,3,g3t2,Quale il nome del simbolo al centro della band...,https://mastroviaggiatore.it/saree/blog/lindia...,1,2026-05-19 15:05:39.212
9,3,g3t2,Quale il nome del simbolo al centro della band...,https://it.gov-civ-guarda.pt/flag-india,3,2026-05-19 15:06:00.133
10,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://it.gov-civ-guarda.pt/flag-india,7,2026-05-19 14:55:47.060
11,4,g3t2,Quale il simbolo dell'India,https://liceoberchet.edu.it/ricerche/geo4d_03/...,1,2026-05-19 15:06:06.889
12,4,g3t2,Quale il simbolo dell'India,https://www.focus.it/ambiente/animali/8-cose-c...,2,2026-05-19 15:06:28.655
13,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:36.085
14,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:49.996
15,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:11:04.292
16,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:12:03.487
17,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:14:14.237
18,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:17:21.809
19,4,g3t1,Fiume sacro indiano,https://www.goasia.it/la-religione-gange-fiume...,1,2026-05-19 15:20:26.846
20,5,g3t3,Quali sono 5 animali tipici dell india,https://www.terreincognitemagazine.it/natura-s...,2,2026-05-19 15:08:18.588
21,5,g3t2,Qual eil simbolo della bandiera india,https://sullestradedelmondo.it/bandiera-indiana/,1,2026-05-19 15:19:29.861
22,6,g3t3,Quali sono 5 animali tipici dell'india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:56:05.417
23,6,g3t2,Quale il simbolo al centro della bandiera dell...,https://www.skuola.net/geografia-medie/india-d...,1,2026-05-19 15:08:05.059
24,6,g3t2,Simbolo andiera India,https://www.bandiere-nazionali.com/bandiera-in...,3,2026-05-19 15:11:31.642
25,6,g3t2,Simbolo andiera India,https://sullestradedelmondo.it/bandiera-indiana/,4,2026-05-19 15:13:24.460
26,8,g3t3,Quali sono 5 animali dell India,https://www.focusjunior.it/scuola/geografia/le...,5,2026-05-19 14:51:21.199
27,8,g3t3,Quali sono 5 animali dell India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:42.534
28,8,g3t3,Quali sono 5 animali dell India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:52:02.269
29,8,g3t3,Quali sono 5 animali dell India,https://animalia.bio/it/india-animals,4,2026-05-19 14:54:13.476
30,8,g3t3,Quali sono 5 animali dell India,https://animalia.bio/it/india-animals,4,2026-05-19 14:55:56.413
31,8,g3t2,centro bandiera india simbolo,https://www.bandiere-nazionali.com/bandiera-in...,2,2026-05-19 15:11:51.878
32,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.focusjunior.it/scienza/spazio/laik...,2,2026-05-19 10:43:58.958
33,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.nationalgeographic.it/spazio/2021/...,3,2026-05-19 10:44:41.360
34,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.focusjunior.it/scienza/spazio/stel...,6,2026-05-19 10:45:32.387
35,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.storicang.it/foto-del-giorno/laika...,1,2026-05-19 10:46:16.185
36,9,g4t2,Quale è il primo animale nello spazio e come s...,https://www.focusjunior.it/scienza/spazio/laik...,2,2026-05-19 10:46:57.627
37,9,g4t1,Come si chiamano i satteliti maggiori di Giove,https://www.astronomitaly.com/blog/astronomy-p...,1,2026-05-19 10:52:26.337
38,9,g4t1,Come si chiamano i satteliti maggiori di Giove,https://starwalk.space/it/news/jupiter-galilea...,2,2026-05-19 10:53:18.182
39,9,g4t1,Come si chiamano i satteliti maggiori di Giove,https://edu.inaf.it/astrofoto/giove-satelliti-...,3,2026-05-19 10:53:42.819

In [37]:
clicked_results_df.dtypes

uid                      Int64
topic_number            object
query                   object
url                     object
rank                     Int64
timestamp       datetime64[ns]
dtype: object

In [38]:
associated_serp_ids = []

for _, row in clicked_results_df.iterrows():
    associated_serp = serp_df.loc[
        (serp_df["uid"]==row["uid"]) 
        & (serp_df["topic_number"]==row["topic_number"]) 
        & (serp_df["query"]==row["query"]) 
        & (serp_df["url"]==row["url"]) 
        & (serp_df["rank"]==row["rank"]) 
        & (serp_df["timestamp"]<row["timestamp"])
    ]

    if len(associated_serp) == 0:
        print(row)
        associated_serp_ids.append(None)

    elif len(associated_serp) > 1:
        # print(associated_serp)
        time_diff = np.inf
        for _, serp in associated_serp.iterrows():
            # print(serp)
            time_diff_compute = row["timestamp"] - serp["timestamp"]
            if time_diff >= time_diff_compute.total_seconds():
                correct_serp = serp["serp_id"]
                time_diff = time_diff_compute.total_seconds()
        associated_serp_ids.append(correct_serp)
    else:
        associated_serp_ids.append(associated_serp["serp_id"].values[0])

clicked_results_df["serp_id"] = associated_serp_ids

In [39]:
associated_serp_ids = []

for _, row in viewed_results_df.iterrows():
    associated_serp = serp_df.loc[
        (serp_df["uid"]==row["uid"]) 
        & (serp_df["topic_number"]==row["topic_number"]) 
        & (serp_df["query"]==row["query"]) 
        & (serp_df["url"]==row["url"]) 
        & (serp_df["rank"]==row["rank"]) 
        & (serp_df["timestamp"]<row["timestamp"])
    ]

    if len(associated_serp) == 0:
        print(row)
        associated_serp_ids.append(None)

    elif len(associated_serp) > 1:
        # print(associated_serp)
        time_diff = np.inf
        for _, serp in associated_serp.iterrows():
            # print(serp)
            time_diff_compute = row["timestamp"] - serp["timestamp"]
            if time_diff >= time_diff_compute.total_seconds():
                correct_serp = serp["serp_id"]
                time_diff = time_diff_compute.total_seconds()
        associated_serp_ids.append(correct_serp)
    else:
        associated_serp_ids.append(associated_serp["serp_id"].values[0])

viewed_results_df["serp_id"] = associated_serp_ids

In [40]:
clicked_results_df.loc[(clicked_results_df["uid"]==4)&(clicked_results_df["topic_number"]=="g3t2")&(clicked_results_df["query"]=="Che cosa rappresenta l'imagine del simbolo banderia dell'India")&(clicked_results_df["rank"]==2)]

,uid,topic_number,query,url,rank,timestamp,serp_id
15,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:11:04.292,serp14
16,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:12:03.487,serp14

In [41]:
viewed_results_df.loc[(viewed_results_df["uid"]==4)&(viewed_results_df["topic_number"]=="g3t2")&(viewed_results_df["query"]=="Che cosa rappresenta l'imagine del simbolo banderia dell'India")&(viewed_results_df["rank"]==2)]

,uid,topic_number,query,url,rank,viewType,timestamp,serp_id
149,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,2026-05-19 14:54:59.696,serp13
154,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,2026-05-19 14:55:37.301,serp13
165,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,2026-05-19 14:58:09.379,serp13
169,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,2026-05-19 14:58:14.141,serp13
197,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,2026-05-19 14:58:46.706,serp13
213,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,2026-05-19 14:59:35.679,serp13
217,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,2026-05-19 14:59:37.452,serp14
219,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,2026-05-19 14:59:42.185,serp14
327,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,2026-05-19 15:10:33.828,serp14
328,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,2026-05-19 15:11:04.278,serp14
331,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureStarted,2026-05-19 15:11:53.293,serp14
332,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,resultExposureEnded,2026-05-19 15:12:03.475,serp14

In [42]:
clicked_results_df.loc[pd.isna(clicked_results_df["serp_id"])]

Empty DataFrame
Columns: [uid, topic_number, query, url, rank, timestamp, serp_id]
Index: []

In [43]:
viewed_results_df.loc[pd.isna(viewed_results_df["serp_id"])]

Empty DataFrame
Columns: [uid, topic_number, query, url, rank, viewType, timestamp, serp_id]
Index: []

In [44]:
clicked_results_df.loc[clicked_results_df["timestamp"]=="2026-05-19 10:46:51.654"]

,uid,topic_number,query,url,rank,timestamp,serp_id
123,15,g4t2,Qual è stato il primo animale nello spazio e c...,https://www.storicang.it/foto-del-giorno/laika...,1,2026-05-19 10:46:51.654,serp92

In [45]:
clicked_results_df.loc[clicked_results_df["timestamp"]=="2026-05-19 10:51:16.099"]

,uid,topic_number,query,url,rank,timestamp,serp_id
124,15,g4t2,Qual è stato il primo animale nello spazio e c...,https://www.storicang.it/foto-del-giorno/laika...,1,2026-05-19 10:51:16.099,serp93

In [46]:
clicked_results_df.head(20)

,uid,topic_number,query,url,rank,timestamp,serp_id
0,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:51:43.444,serp1
1,1,g3t3,Quali sono i cinque animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:53:19.408,serp1
2,1,g3t2,Quale è il nome del simbolo al centro della ba...,https://it.gov-civ-guarda.pt/flag-india,1,2026-05-19 15:02:48.776,serp2
3,1,g3t1,Fiume sacro degli indiani,https://www.consciousjourneys.com/it/approfond...,2,2026-05-19 15:08:58.405,serp3
4,2,g3t3,Quali sono i 5 animali tipici dall'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:52:53.759,serp5
5,2,g3t2,Qual è il nome del simbolo al centro della b...,https://sullestradedelmondo.it/bandiera-indiana/,3,2026-05-19 15:09:25.575,serp7
6,2,g3t1,Come si chiama il fiume sacro agli indiani,https://www.consciousjourneys.com/it/approfond...,1,2026-05-19 15:14:18.095,serp8
7,3,g3t3,Quali sono 5 animali tipici dell'india,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 14:56:28.100,serp10
8,3,g3t2,Quale il nome del simbolo al centro della band...,https://mastroviaggiatore.it/saree/blog/lindia...,1,2026-05-19 15:05:39.212,serp11
9,3,g3t2,Quale il nome del simbolo al centro della band...,https://it.gov-civ-guarda.pt/flag-india,3,2026-05-19 15:06:00.133,serp11
10,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://it.gov-civ-guarda.pt/flag-india,7,2026-05-19 14:55:47.060,serp13
11,4,g3t2,Quale il simbolo dell'India,https://liceoberchet.edu.it/ricerche/geo4d_03/...,1,2026-05-19 15:06:06.889,serp16
12,4,g3t2,Quale il simbolo dell'India,https://www.focus.it/ambiente/animali/8-cose-c...,2,2026-05-19 15:06:28.655,serp16
13,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:36.085,serp16
14,4,g3t2,Quale il simbolo dell'India,https://www.skuola.net/geografia-medie/india-d...,3,2026-05-19 15:07:49.996,serp16
15,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:11:04.292,serp14
16,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,https://sullestradedelmondo.it/bandiera-indiana/,2,2026-05-19 15:12:03.487,serp14
17,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:14:14.237,serp17
18,4,g3t3,5 animali tipici dell'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,2026-05-19 15:17:21.809,serp17
19,4,g3t1,Fiume sacro indiano,https://www.goasia.it/la-religione-gange-fiume...,1,2026-05-19 15:20:26.846,serp18

In [47]:
clicked_results_df.to_csv("Data/clicked_results_df.csv", index=False, encoding='utf8')
viewed_results_df.to_csv("Data/viewed_results_df.csv", index=False, encoding='utf8')

In [48]:
df = pd.DataFrame(clicked_results_df.groupby(["uid", "topic_number", "serp_id"])["url"].value_counts()).reset_index()

click_count = []

for _, row in serp_df.iterrows():
    serp_row = df.loc[(df["uid"]==row["uid"])&(df["topic_number"]==row["topic_number"])&(df["serp_id"]==row["serp_id"])&(df["url"]==row["url"])]
    if len(serp_row) > 1:
        print(row, serp_row)
    elif len(serp_row) == 0:
        click_count.append(0)
    else:
        click_count.append(serp_row["count"].values[0])

serp_df["click_count"] = click_count

In [49]:
serp_df.head(20)

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,relevance_score,click_count
0,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19 14:51:27.687,1,2
1,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,2026-05-19 14:51:27.688,1,0
2,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.storicang.it/a/civilta-dellindo-i-...,"La civiltà dell'Indo, i misteri di un popolo d...","\n Jun 5, 2023 ... Sono note cinque m...",3.0,2026-05-19 14:51:27.689,0,0
3,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... Chi sono, da dove ...",4.0,2026-05-19 14:51:27.690,0,0
4,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/comportamento/feste...,Festa della mamma: come si festeggia nel resto...,\n Il dolce tipico per celebrare ques...,5.0,2026-05-19 14:51:27.691,0,0
5,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/giochi/i-20-parchi-...,I 20 parchi divertimento più belli d'Italia - ...,\n Parco faunistico immerso in un bos...,6.0,2026-05-19 14:51:27.693,0,0
6,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scuola/geografia/10...,10 cose che (forse) non sai sull'Europa - Focu...,\n Come popolazione conta 508 milioni...,7.0,2026-05-19 14:51:27.694,0,0
7,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scienza/ambiente/ec...,9 interessantissime curiosità sulle piante gra...,\n 2 - QUALI SONO LE TIPOLOGIE? Esist...,8.0,2026-05-19 14:51:27.696,0,0
8,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/scienza/natura/le-s...,Le spiagge più strane e colorate del mondo - F...,\n ... è di origine vulcanica: in pra...,9.0,2026-05-19 14:51:27.697,0,0
9,1,g3t3,Quali sono i cinque animali tipici dell india,serp1,https://www.focusjunior.it/animali/curiosita-a...,Idee per nomi di gatto - FocusJunior.it,"\n Mar 19, 2025 ... Il gatto è l'anim...",10.0,2026-05-19 14:51:27.699,0,0
10,1,g3t2,Quale è il nome del simbolo al centro della ba...,serp2,https://it.gov-civ-guarda.pt/flag-india,"Bandiera dell'India | Storia, design e signifi...",\n Nel 1921 uno studente di nome Ping...,1.0,2026-05-19 15:02:42.576,1,1
11,1,g3t1,Fiume sacro degli indiani,serp3,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Qui le persone rendono omaggio ai ...,1.0,2026-05-19 15:08:41.314,1,0
12,1,g3t1,Fiume sacro degli indiani,serp3,https://www.consciousjourneys.com/it/approfond...,"Gange, il fiume sacro agli indù e alla popolaz...","\n Come abbiamo detto, il Gange è il ...",2.0,2026-05-19 15:08:41.315,1,1
13,1,g3t1,Fiume sacro degli indiani,serp3,https://italiano.memphistours.com/india/fiume-...,Alla Scoperta del Sacro Fiume Gange - India - ...,\n Le Sundarbans sono un ecosistema u...,3.0,2026-05-19 15:08:41.316,1,0
14,1,g3t1,Fiume sacro degli indiani,serp3,https://it.renovables.blog/acqua/il-sacro-fium...,Alla scoperta del Gange: il fiume sacro e inqu...,\n Oltre a essere il fiume più lungo ...,4.0,2026-05-19 15:08:41.317,1,0
15,1,g3t1,Fiume sacro degli indiani,serp3,https://www.skuola.net/geografia-medie/india-d...,"L'India: un viaggio tra cultura, geografia e t...","\n Jun 28, 2014 ... Alla costa indian...",5.0,2026-05-19 15:08:41.319,0,0
16,1,g3t1,Fiume sacro degli indiani,serp3,https://www.focusjunior.it/scuola/storia/chi-s...,"Chi sono gli Indiani d'America, i nativi ameri...","\n Jun 6, 2024 ... Lungo quella terra...",6.0,2026-05-19 15:08:41.320,0,0
17,1,g3t1,Fiume sacro degli indiani,serp3,https://www.focusjunior.it/scuola/storia/le-re...,Quali sono le grandi religioni nel mondo? - Fo...,"\n Da allora, gli ebrei sanno di dove...",7.0,2026-05-19 15:08:41.321,0,0
18,1,g3t1,Fiume sacro degli indiani,serp3,https://www.focusjunior.it/scuola/ricerche-per...,Ricerche per la scuola | L'Arabia Saudita - Fo...,\n ... della Ka-ba . L'importanza spi...,8.0,2026-05-19 15:08:41.322,0,0
19,2,g3t3,Quali sono i animali dall'India,serp4,https://www.focusjunior.it/scuola/storia/il-pi...,Chi ha inventato il pigiama? - FocusJunior.it,\n Ma quali sono le sue origini? DAL ...,1.0,2026-05-19 14:50:23.230,0,0

In [50]:
len(serp_df.loc[pd.isna(serp_df["rank"])])

15

In [51]:
query_df = pd.read_csv("Data/query_df.csv")
serp_df["qid"] = [query_df.loc[query_df["serp_id"]==serp_id]["qid"].values[0] for serp_id in serp_df["serp_id"]]
serp_df = serp_df[["uid", "topic_number", "qid", "query", "serp_id", "url", "title", "snippet", "rank", "relevance_score", "click_count", "timestamp"]]

In [52]:
serp_df.head(1)

,uid,topic_number,qid,query,serp_id,url,title,snippet,rank,relevance_score,click_count,timestamp
0,1,g3t3,q1,Quali sono i cinque animali tipici dell india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,1,2,2026-05-19 14:51:27.687

In [53]:
cleaned_serp_df = serp_df.dropna(subset=["rank"])
cleaned_serp_df["rank"] = cleaned_serp_df["rank"].astype(int)

C:\Users\hrishitachakra\AppData\Local\Temp\ipykernel_29744\193022930.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_serp_df["rank"] = cleaned_serp_df["rank"].astype(int)

In [54]:
len(serp_df), len(cleaned_serp_df)

(945, 930)

In [55]:
serp_df.to_csv("Data/logs_compiled.csv", index=False, encoding='utf8')
cleaned_serp_df.to_csv("Data/results_navigation.csv", index=False, encoding='utf8')

In [56]:
serp_df.loc[serp_df["serp_id"]=="serp119"]

Empty DataFrame
Columns: [uid, topic_number, qid, query, serp_id, url, title, snippet, rank, relevance_score, click_count, timestamp]
Index: []

## information distillation

### automatic scraping

In [ ]:
import pandas as pd
import urllib3
from urllib3 import Retry
from tqdm.notebook import tqdm
import time
from bs4 import BeautifulSoup

serp_df = pd.read_csv("Data/logs_compiled.csv")
len(serp_df["url"].unique())

corpus = []
for idx, url in tqdm(zip(range(len(serp_df["url"].unique())), serp_df["url"].unique()), total = len(serp_df["url"].unique())):
    if idx % 50 == 0 and idx!=0:
        time.sleep(10)
    if pd.notna(url):
        try:
            html = urllib3.request("GET", url, retries=Retry(5), headers={'User-Agent': 'Mozilla/5.0'})
            # html = urllib3.request("GET", url, retries=False)
            if html.status == 200:
                soup = BeautifulSoup(markup = html.data, features='lxml')
                # kill all script and style elements
                for script in soup(["script", "style", "nav", "header", "footer", "aside", "img", "link"]):
                    script.extract() # rip it out
                    # script.decompose() 
                corpus.append(["d"+str(idx), url, str(soup.body), str(soup.body.get_text(separator='\n ', strip=True)), "auto-scraped"])
            else:
                corpus.append(["d"+str(idx), url, None, None, "manual-scraped"])
        except:
            corpus.append(["d"+str(idx), url, None, None, "manual-scraped"])

  0%|          | 0/222 [00:00<?, ?it/s]

In [ ]:
corpus_df = pd.DataFrame(corpus, columns = ["doc_id", "url", "html_content", "text_content", "scraping_source"])
corpus_df.to_excel("Data/corpus.xlsx", index=False)
# corpus_df.to_csv("Data/corpus.tsv", index=False, encoding="utf8", sep="\t")

In [ ]:
corpus_df.head()

,doc_id,url,html_content,text_content,scraping_source
0,d0,https://wwftravel.it/blog/viaggi/india-natura-...,None,None,manual-scraped
1,d1,https://www.terreincognitemagazine.it/natura-s...,"<body class=""single single-post postid-2526 si...",Homepage\n >\n CULTURA\n >\n MOSTRE\n >\n Natu...,auto-scraped
2,d2,https://www.storicang.it/a/civilta-dellindo-i-...,None,None,manual-scraped
3,d3,https://www.focusjunior.it/scuola/storia/chi-s...,"<body><div id=""fb-root""></div>\n<noscript></no...",FocusJunior.it\n Scuola\n Storia\n Chi sono gl...,auto-scraped
4,d4,https://www.focusjunior.it/comportamento/feste...,"<body><div id=""fb-root""></div>\n<noscript></no...",FocusJunior.it\n Comportamento\n Feste\n Festa...,auto-scraped

In [ ]:
len(corpus_df.loc[pd.isna(corpus_df["text_content"])])

11

### manual scraping

In [ ]:
# html_text = """
# <body class="astrofoto-template-default single single-astrofoto postid-33220 wp-embed-responsive herald-boxed herald-v_2_6" data-new-gr-c-s-check-loaded="14.1310.0" data-gr-ext-installed="">



# 	<header id="header" class="herald-site-header">

# 											<div class="header-top hidden-xs hidden-sm">
# 	<div class="container">
# 		<div class="row">
# 			<div class="col-lg-12">
				
								
# 												<div class="hel-r">
# 											<span class="herald-calendar"><i class="fa fa-calendar"></i>13 Luglio 2026</span>									</div>
				
								
# 			</div>
# 		</div>
# 	</div>
# </div>							<div class="header-middle herald-header-wraper hidden-xs hidden-sm">
# 	<div class="container">
# 		<div class="row">
# 				<div class="col-lg-12 hel-el">
				
										
										
													
					
				
# 				</div>
# 		</div>
# 		</div>
# </div>							<div class="header-bottom herald-header-wraper hidden-sm hidden-xs">
# 	<div class="container">
# 		<div class="row">
# 				<div class="col-lg-12 hel-el">
				
										
# 															<div class="hel-c">
# 													<nav class="main-navigation herald-menu">	
# 				<ul id="menu-principale-header" class="menu"><li id="menu-item-38634" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-38634"><a href="https://edu.inaf.it/">Home</a></li><li id="menu-item-3617" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-3617"><a href="#">Didattica</a>
# <ul class="sub-menu">
# 	<li id="menu-item-19133" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-19133"><a href="https://edu.inaf.it/astrodidattica/">Risorse didattiche</a>	</li><li id="menu-item-30675" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-30675"><a href="https://edu.inaf.it/inaf-olimpiadi-astronomia/">Olimpiadi di Astronomia</a>	</li><li id="menu-item-26032" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-26032"><a href="https://edu.inaf.it/didattica-inaf/">Didattica INAF in evidenza</a>	</li><li id="menu-item-19796" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-19796"><a href="https://edu.inaf.it/astroschede/">Schede astronomiche</a>	</li><li id="menu-item-28316" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-28316"><a href="#">Altre proposte didattiche</a>
# 	<ul class="sub-menu">
# 		<li id="menu-item-11987" class="menu-item menu-item-type-post_type menu-item-object-corso_base_brera menu-item-11987"><a href="https://edu.inaf.it/corso_base_brera/introduzione/">Corso base di astronomia</a>		</li><li id="menu-item-3822" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3822"><a href="https://edu.inaf.it/corsi-di-formazione/">Corsi di formazione</a>		</li><li id="menu-item-4177" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4177"><a href="https://edu.inaf.it/rete-irnet/">Rete IRNET</a>	</li></ul>
# </li></ul>
# </li><li id="menu-item-6578" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-6578"><a href="#">Rubriche</a>
# <ul class="sub-menu">
# 	<li id="menu-item-8074" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8074"><a href="https://edu.inaf.it/astronomo-risponde/">L’astronomo risponde</a>	</li><li id="menu-item-15414" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15414"><a href="https://edu.inaf.it/le-costellazioni/">Le costellazioni</a>	</li><li id="menu-item-14150" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-14150"><a href="https://edu.inaf.it/category/rubriche/il-cielo-del-mese/">Il cielo del mese</a>	</li><li id="menu-item-23883" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-23883"><a href="https://edu.inaf.it/category/rubriche/oltre-orizzonte/">Oltre l’orizzonte</a>	</li><li id="menu-item-42356" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-42356"><a href="https://edu.inaf.it/category/rubriche/lo-spazio-tra-le-pagine/">Lo spazio tra le pagine</a>	</li><li id="menu-item-35655" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-35655"><a href="https://edu.inaf.it/category/rubriche/universo-mondo/">Universo Mondo</a>	</li><li id="menu-item-58582" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-58582"><a href="https://edu.inaf.it/category/rubriche/altro-cielo/">Cose dell’altro cielo</a>	</li><li id="menu-item-58580" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-58580"><a href="https://edu.inaf.it/space-jobs/">Space Jobs</a>	</li><li id="menu-item-58581" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-58581"><a href="https://edu.inaf.it/scienza-supereroi/">La scienza con i supereroi</a>	</li><li id="menu-item-38632" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-38632"><a href="https://edu.inaf.it/briciole-spaziali/">Briciole Spaziali</a>	</li><li id="menu-item-28317" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-28317"><a href="https://edu.inaf.it/category/rubriche/risate-spaziali/">Risate spaziali</a>	</li><li id="menu-item-16868" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-16868"><a href="https://edu.inaf.it/astrofoto/">Astrofoto</a></li></ul>
# </li><li id="menu-item-10519" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-10519"><a href="https://edu.inaf.it/category/approfondimenti/">Approfondimenti</a>
# <ul class="sub-menu">
# 	<li id="menu-item-6587" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6587"><a href="https://edu.inaf.it/libri/">Libri e altre recensioni</a>	</li><li id="menu-item-15029" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-15029"><a href="https://edu.inaf.it/category/rubriche/astrografiche/">Astrografiche</a>	</li><li id="menu-item-6573" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-6573"><a href="https://edu.inaf.it/category/approfondimenti/cronache-dalla-scuola/">Cronache dalla scuola</a>	</li><li id="menu-item-49193" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-49193"><a href="https://edu.inaf.it/category/rubriche/prof-spaziali/">Prof Spaziali</a>	</li><li id="menu-item-15030" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-15030"><a href="https://edu.inaf.it/category/approfondimenti/insegnare-astronomia/">Insegnare l’astronomia</a>	</li><li id="menu-item-35654" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-35654"><a href="https://edu.inaf.it/category/rubriche/play-to-learn/">Play to learn | Learn to play</a>	</li><li id="menu-item-15032" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-15032"><a href="https://edu.inaf.it/category/approfondimenti/scoperte/">Scoperte</a>	</li><li id="menu-item-15031" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-15031"><a href="https://edu.inaf.it/category/approfondimenti/personaggi/">Personaggi</a>	</li><li id="menu-item-25034" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-25034"><a href="http://edu.inaf.it/sezioni_sito/speciali/">Speciali</a>	</li><li id="menu-item-22851" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-22851"><a href="https://edu.inaf.it/luoghi-astrofisica-scienze-planetarie/">L’Italia Astrofisica</a></li></ul>
# </li><li id="menu-item-5011" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-5011"><a href="#">In evidenza</a>
# <ul class="sub-menu">
# 	<li id="menu-item-27851" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-27851"><a href="https://edu.inaf.it/diretta/">Dirette</a>	</li><li id="menu-item-30678" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-30678"><a href="https://edu.inaf.it/inaf-arte-letteratura/">Arte e letteratura</a>	</li><li id="menu-item-22182" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-22182"><a href="https://edu.inaf.it/inaf-didattica-inclusiva/">Inclusione</a>	</li><li id="menu-item-22215" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-22215"><a href="https://edu.inaf.it/focus-didattica-innovativa/">Innovazione</a>	</li><li id="menu-item-30708" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-30708"><a href="https://edu.inaf.it/focus-pcto/">PCTO</a>	</li><li id="menu-item-30735" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-30735"><a href="https://edu.inaf.it/focus-realta-virtuale-aumentata/">Realtà&nbsp; virtuale e aumentata</a>	</li><li id="menu-item-16817" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-16817"><a href="https://edu.inaf.it/tour-virtuali/">Visite virtuali all’INAF</a>	</li><li id="menu-item-18322" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-18322"><a href="https://edu.inaf.it/inaf-online-lab/">INAF Online Lab</a>	</li><li id="menu-item-25048" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-25048"><a href="https://edu.inaf.it/donne-e-scienza/">Donne e Scienza</a>	</li><li id="menu-item-26443" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-26443"><a href="https://edu.inaf.it/concorsi/">Concorsi e iniziative</a></li></ul>
# </li><li id="menu-item-3922" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-3922"><a href="#">Eventi</a>
# <ul class="sub-menu">
# 	<li id="menu-item-59494" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-59494"><a href="https://edu.inaf.it/tag/notte-europea-dei-ricercatori/">Notte Europea della Ricerca</a>	</li><li id="menu-item-32536" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-32536"><a href="https://edu.inaf.it/tag/festival-della-scienza-di-genova/">L’INAF al Festival di Genova</a>	</li><li id="menu-item-10520" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-10520"><a href="https://edu.inaf.it/da-zero-a-infinito/">Da zero all’infinito</a>	</li><li id="menu-item-5140" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5140"><a href="https://edu.inaf.it/eventi/settimana-inaf/">Settimana INAF</a></li></ul>
# </li><li id="menu-item-3793" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-3793"><a href="#">Chi siamo</a>
# <ul class="sub-menu">
# 	<li id="menu-item-3800" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3800"><a href="https://edu.inaf.it/edu-inaf/">Cos’è Edu INAF</a>	</li><li id="menu-item-3812" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3812"><a href="https://edu.inaf.it/edu-inaf/la-redazione/">La redazione</a>	</li><li id="menu-item-20052" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-20052"><a href="https://edu.inaf.it/edu-inaf/sedi-inaf/">Sedi INAF</a>	</li><li id="menu-item-19721" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-19721"><a href="https://edu.inaf.it/category/rubriche/editoriali/">Editoriali</a>	</li><li id="menu-item-15860" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15860"><a href="https://edu.inaf.it/contatti/">Contatti</a>	</li><li id="menu-item-15786" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15786"><a href="https://edu.inaf.it/edu-inaf/invio-contributi/">Invia il tuo contributo</a>	</li><li id="menu-item-19722" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-19722"><a href="http://edu.inaf.it/newsletter/">Newsletter</a>	</li><li id="menu-item-32048" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-32048"><a href="http://edu.inaf.it/pubblicazioni">Pubblicazioni</a></li></ul>
# </li></ul>	</nav>													<div class="herald-menu-popup-search">
# <span class="fa fa-search"></span>
# 	<div class="herald-in-popup">
# 		<form class="herald-search-form" action="https://edu.inaf.it/" method="get">
# 	<input name="s" class="herald-search-input" type="text" value="" placeholder="Type here to search..."><button type="submit" class="herald-search-submit"></button>
# </form>	</div>
# </div>											</div>
					
# 															<div class="hel-r">
# 															<ul id="menu-social" class="herald-soc-nav"><li id="menu-item-20613" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20613"><a href="https://twitter.com/edu_inaf"><span class="herald-social-name">Twitter</span></a></li>
# <li id="menu-item-20614" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20614"><a href="https://www.instagram.com/edu_inaf/"><span class="herald-social-name">Instagram</span></a></li>
# <li id="menu-item-20615" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20615"><a href="https://www.facebook.com/EduINAF/"><span class="herald-social-name">Facebook</span></a></li>
# <li id="menu-item-20616" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20616"><a href="https://www.youtube.com/channel/UCNQdg6r8s6kcI0_OFOKh_-w"><span class="herald-social-name">YouTube</span></a></li>
# <li id="menu-item-30950" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-30950"><a href="https://flickr.com/photos/edu_inaf/albums"><span class="herald-social-name">Flickr</span></a></li>
# </ul>											</div>
										
					
				
# 				</div>
# 		</div>
# 		</div>
# </div>					
# 	</header>

# 			<div id="sticky-header" class="herald-header-sticky herald-header-wraper herald-slide hidden-xs hidden-sm">
# 	<div class="container">
# 		<div class="row">
# 				<div class="col-lg-12 hel-el">
				
# 															<div class="hel-l herald-go-hor">
# 													<div class="site-branding mini">
# 		<span class="site-title h1"><a href="https://edu.inaf.it/" rel="home">EduINAF</a></span>
# </div>											</div>
					
										
# 															<div class="hel-r herald-go-hor">
# 													<nav class="main-navigation herald-menu">	
# 				<ul id="menu-principale-header-1" class="menu"><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-38634"><a href="https://edu.inaf.it/">Home</a></li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-3617"><a href="#">Didattica</a>
# <ul class="sub-menu">
# 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-19133"><a href="https://edu.inaf.it/astrodidattica/">Risorse didattiche</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-30675"><a href="https://edu.inaf.it/inaf-olimpiadi-astronomia/">Olimpiadi di Astronomia</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-26032"><a href="https://edu.inaf.it/didattica-inaf/">Didattica INAF in evidenza</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-19796"><a href="https://edu.inaf.it/astroschede/">Schede astronomiche</a>	</li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-28316"><a href="#">Altre proposte didattiche</a>
# 	<ul class="sub-menu">
# 		<li class="menu-item menu-item-type-post_type menu-item-object-corso_base_brera menu-item-11987"><a href="https://edu.inaf.it/corso_base_brera/introduzione/">Corso base di astronomia</a>		</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3822"><a href="https://edu.inaf.it/corsi-di-formazione/">Corsi di formazione</a>		</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4177"><a href="https://edu.inaf.it/rete-irnet/">Rete IRNET</a>	</li></ul>
# </li></ul>
# </li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-6578"><a href="#">Rubriche</a>
# <ul class="sub-menu">
# 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8074"><a href="https://edu.inaf.it/astronomo-risponde/">L’astronomo risponde</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15414"><a href="https://edu.inaf.it/le-costellazioni/">Le costellazioni</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-14150"><a href="https://edu.inaf.it/category/rubriche/il-cielo-del-mese/">Il cielo del mese</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-23883"><a href="https://edu.inaf.it/category/rubriche/oltre-orizzonte/">Oltre l’orizzonte</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-42356"><a href="https://edu.inaf.it/category/rubriche/lo-spazio-tra-le-pagine/">Lo spazio tra le pagine</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-35655"><a href="https://edu.inaf.it/category/rubriche/universo-mondo/">Universo Mondo</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-58582"><a href="https://edu.inaf.it/category/rubriche/altro-cielo/">Cose dell’altro cielo</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-58580"><a href="https://edu.inaf.it/space-jobs/">Space Jobs</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-58581"><a href="https://edu.inaf.it/scienza-supereroi/">La scienza con i supereroi</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-38632"><a href="https://edu.inaf.it/briciole-spaziali/">Briciole Spaziali</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-28317"><a href="https://edu.inaf.it/category/rubriche/risate-spaziali/">Risate spaziali</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-16868"><a href="https://edu.inaf.it/astrofoto/">Astrofoto</a></li></ul>
# </li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-10519"><a href="https://edu.inaf.it/category/approfondimenti/">Approfondimenti</a>
# <ul class="sub-menu">
# 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6587"><a href="https://edu.inaf.it/libri/">Libri e altre recensioni</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-15029"><a href="https://edu.inaf.it/category/rubriche/astrografiche/">Astrografiche</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-6573"><a href="https://edu.inaf.it/category/approfondimenti/cronache-dalla-scuola/">Cronache dalla scuola</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-49193"><a href="https://edu.inaf.it/category/rubriche/prof-spaziali/">Prof Spaziali</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-15030"><a href="https://edu.inaf.it/category/approfondimenti/insegnare-astronomia/">Insegnare l’astronomia</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-35654"><a href="https://edu.inaf.it/category/rubriche/play-to-learn/">Play to learn | Learn to play</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-15032"><a href="https://edu.inaf.it/category/approfondimenti/scoperte/">Scoperte</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-15031"><a href="https://edu.inaf.it/category/approfondimenti/personaggi/">Personaggi</a>	</li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-25034"><a href="http://edu.inaf.it/sezioni_sito/speciali/">Speciali</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-22851"><a href="https://edu.inaf.it/luoghi-astrofisica-scienze-planetarie/">L’Italia Astrofisica</a></li></ul>
# </li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-5011"><a href="#">In evidenza</a>
# <ul class="sub-menu">
# 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-27851"><a href="https://edu.inaf.it/diretta/">Dirette</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-30678"><a href="https://edu.inaf.it/inaf-arte-letteratura/">Arte e letteratura</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-22182"><a href="https://edu.inaf.it/inaf-didattica-inclusiva/">Inclusione</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-22215"><a href="https://edu.inaf.it/focus-didattica-innovativa/">Innovazione</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-30708"><a href="https://edu.inaf.it/focus-pcto/">PCTO</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-30735"><a href="https://edu.inaf.it/focus-realta-virtuale-aumentata/">Realtà&nbsp; virtuale e aumentata</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-16817"><a href="https://edu.inaf.it/tour-virtuali/">Visite virtuali all’INAF</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-18322"><a href="https://edu.inaf.it/inaf-online-lab/">INAF Online Lab</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-25048"><a href="https://edu.inaf.it/donne-e-scienza/">Donne e Scienza</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-26443"><a href="https://edu.inaf.it/concorsi/">Concorsi e iniziative</a></li></ul>
# </li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-3922"><a href="#">Eventi</a>
# <ul class="sub-menu">
# 	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-59494"><a href="https://edu.inaf.it/tag/notte-europea-dei-ricercatori/">Notte Europea della Ricerca</a>	</li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-32536"><a href="https://edu.inaf.it/tag/festival-della-scienza-di-genova/">L’INAF al Festival di Genova</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-10520"><a href="https://edu.inaf.it/da-zero-a-infinito/">Da zero all’infinito</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5140"><a href="https://edu.inaf.it/eventi/settimana-inaf/">Settimana INAF</a></li></ul>
# </li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-3793"><a href="#">Chi siamo</a>
# <ul class="sub-menu">
# 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3800"><a href="https://edu.inaf.it/edu-inaf/">Cos’è Edu INAF</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3812"><a href="https://edu.inaf.it/edu-inaf/la-redazione/">La redazione</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-20052"><a href="https://edu.inaf.it/edu-inaf/sedi-inaf/">Sedi INAF</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-19721"><a href="https://edu.inaf.it/category/rubriche/editoriali/">Editoriali</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15860"><a href="https://edu.inaf.it/contatti/">Contatti</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15786"><a href="https://edu.inaf.it/edu-inaf/invio-contributi/">Invia il tuo contributo</a>	</li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-19722"><a href="http://edu.inaf.it/newsletter/">Newsletter</a>	</li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-32048"><a href="http://edu.inaf.it/pubblicazioni">Pubblicazioni</a></li></ul>
# </li></ul>	</nav>											</div>
										
					
				
# 				</div>
# 		</div>
# 		</div>
# </div>	
# 	<div id="herald-responsive-header" class="herald-responsive-header herald-slide hidden-lg hidden-md">
# 	<div class="container">
# 		<div class="herald-nav-toggle"><i class="fa fa-bars"></i></div>
# 				<div class="site-branding">
# 				<span class="site-title h1"><a href="https://edu.inaf.it/" rel="home">EduINAF</a></span>
# 	</div>

# 												<div class="herald-menu-popup-search">
# <span class="fa fa-search"></span>
# 	<div class="herald-in-popup">
# 		<form class="herald-search-form" action="https://edu.inaf.it/" method="get">
# 	<input name="s" class="herald-search-input" type="text" value="" placeholder="Type here to search..."><button type="submit" class="herald-search-submit"></button>
# </form>	</div>
# </div>					
# 	</div>
# </div>
# <div class="herald-mobile-nav herald-slide hidden-lg hidden-md">
# 	<ul id="menu-principale-header-2" class="herald-mob-nav"><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-38634"><a href="https://edu.inaf.it/">Home</a></li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-3617"><a href="#">Didattica</a>
# <ul class="sub-menu">
# 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-19133"><a href="https://edu.inaf.it/astrodidattica/">Risorse didattiche</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-30675"><a href="https://edu.inaf.it/inaf-olimpiadi-astronomia/">Olimpiadi di Astronomia</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-26032"><a href="https://edu.inaf.it/didattica-inaf/">Didattica INAF in evidenza</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-19796"><a href="https://edu.inaf.it/astroschede/">Schede astronomiche</a>	</li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-28316"><a href="#">Altre proposte didattiche</a>
# 	<ul class="sub-menu">
# 		<li class="menu-item menu-item-type-post_type menu-item-object-corso_base_brera menu-item-11987"><a href="https://edu.inaf.it/corso_base_brera/introduzione/">Corso base di astronomia</a>		</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3822"><a href="https://edu.inaf.it/corsi-di-formazione/">Corsi di formazione</a>		</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4177"><a href="https://edu.inaf.it/rete-irnet/">Rete IRNET</a>	</li></ul>
# <span class="herald-menu-toggler fa fa-caret-down"></span></li></ul>
# <span class="herald-menu-toggler fa fa-caret-down"></span></li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-6578"><a href="#">Rubriche</a>
# <ul class="sub-menu">
# 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8074"><a href="https://edu.inaf.it/astronomo-risponde/">L’astronomo risponde</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15414"><a href="https://edu.inaf.it/le-costellazioni/">Le costellazioni</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-14150"><a href="https://edu.inaf.it/category/rubriche/il-cielo-del-mese/">Il cielo del mese</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-23883"><a href="https://edu.inaf.it/category/rubriche/oltre-orizzonte/">Oltre l’orizzonte</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-42356"><a href="https://edu.inaf.it/category/rubriche/lo-spazio-tra-le-pagine/">Lo spazio tra le pagine</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-35655"><a href="https://edu.inaf.it/category/rubriche/universo-mondo/">Universo Mondo</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-58582"><a href="https://edu.inaf.it/category/rubriche/altro-cielo/">Cose dell’altro cielo</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-58580"><a href="https://edu.inaf.it/space-jobs/">Space Jobs</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-58581"><a href="https://edu.inaf.it/scienza-supereroi/">La scienza con i supereroi</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-38632"><a href="https://edu.inaf.it/briciole-spaziali/">Briciole Spaziali</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-28317"><a href="https://edu.inaf.it/category/rubriche/risate-spaziali/">Risate spaziali</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-16868"><a href="https://edu.inaf.it/astrofoto/">Astrofoto</a></li></ul>
# <span class="herald-menu-toggler fa fa-caret-down"></span></li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-10519"><a href="https://edu.inaf.it/category/approfondimenti/">Approfondimenti</a>
# <ul class="sub-menu">
# 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6587"><a href="https://edu.inaf.it/libri/">Libri e altre recensioni</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-15029"><a href="https://edu.inaf.it/category/rubriche/astrografiche/">Astrografiche</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-6573"><a href="https://edu.inaf.it/category/approfondimenti/cronache-dalla-scuola/">Cronache dalla scuola</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-49193"><a href="https://edu.inaf.it/category/rubriche/prof-spaziali/">Prof Spaziali</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-15030"><a href="https://edu.inaf.it/category/approfondimenti/insegnare-astronomia/">Insegnare l’astronomia</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-35654"><a href="https://edu.inaf.it/category/rubriche/play-to-learn/">Play to learn | Learn to play</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-15032"><a href="https://edu.inaf.it/category/approfondimenti/scoperte/">Scoperte</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-15031"><a href="https://edu.inaf.it/category/approfondimenti/personaggi/">Personaggi</a>	</li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-25034"><a href="http://edu.inaf.it/sezioni_sito/speciali/">Speciali</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-22851"><a href="https://edu.inaf.it/luoghi-astrofisica-scienze-planetarie/">L’Italia Astrofisica</a></li></ul>
# <span class="herald-menu-toggler fa fa-caret-down"></span></li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-5011"><a href="#">In evidenza</a>
# <ul class="sub-menu">
# 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-27851"><a href="https://edu.inaf.it/diretta/">Dirette</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-30678"><a href="https://edu.inaf.it/inaf-arte-letteratura/">Arte e letteratura</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-22182"><a href="https://edu.inaf.it/inaf-didattica-inclusiva/">Inclusione</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-22215"><a href="https://edu.inaf.it/focus-didattica-innovativa/">Innovazione</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-30708"><a href="https://edu.inaf.it/focus-pcto/">PCTO</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-30735"><a href="https://edu.inaf.it/focus-realta-virtuale-aumentata/">Realtà&nbsp; virtuale e aumentata</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-16817"><a href="https://edu.inaf.it/tour-virtuali/">Visite virtuali all’INAF</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-18322"><a href="https://edu.inaf.it/inaf-online-lab/">INAF Online Lab</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-25048"><a href="https://edu.inaf.it/donne-e-scienza/">Donne e Scienza</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-26443"><a href="https://edu.inaf.it/concorsi/">Concorsi e iniziative</a></li></ul>
# <span class="herald-menu-toggler fa fa-caret-down"></span></li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-3922"><a href="#">Eventi</a>
# <ul class="sub-menu">
# 	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-59494"><a href="https://edu.inaf.it/tag/notte-europea-dei-ricercatori/">Notte Europea della Ricerca</a>	</li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-32536"><a href="https://edu.inaf.it/tag/festival-della-scienza-di-genova/">L’INAF al Festival di Genova</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-10520"><a href="https://edu.inaf.it/da-zero-a-infinito/">Da zero all’infinito</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5140"><a href="https://edu.inaf.it/eventi/settimana-inaf/">Settimana INAF</a></li></ul>
# <span class="herald-menu-toggler fa fa-caret-down"></span></li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-3793"><a href="#">Chi siamo</a>
# <ul class="sub-menu">
# 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3800"><a href="https://edu.inaf.it/edu-inaf/">Cos’è Edu INAF</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3812"><a href="https://edu.inaf.it/edu-inaf/la-redazione/">La redazione</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-20052"><a href="https://edu.inaf.it/edu-inaf/sedi-inaf/">Sedi INAF</a>	</li><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-19721"><a href="https://edu.inaf.it/category/rubriche/editoriali/">Editoriali</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15860"><a href="https://edu.inaf.it/contatti/">Contatti</a>	</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15786"><a href="https://edu.inaf.it/edu-inaf/invio-contributi/">Invia il tuo contributo</a>	</li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-19722"><a href="http://edu.inaf.it/newsletter/">Newsletter</a>	</li><li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-32048"><a href="http://edu.inaf.it/pubblicazioni">Pubblicazioni</a></li></ul>
# <span class="herald-menu-toggler fa fa-caret-down"></span></li></ul>	
		
	
	
		
# </div>	
    
# 	<div id="content" class="herald-site-content herald-slide">

	


# <div class="herald-section container ">

# 			<article id="post-33220" class="herald-single post-33220 astrofoto type-astrofoto status-publish has-post-thumbnail hentry tag-europa tag-giove tag-io">
# 			<div class="row">
								
			
# <div class="col-lg-9 col-md-9 col-mod-single col-mod-main">
	
# 	<header class="entry-header">
# 			<span class="meta-category"><a href="https://edu.inaf.it/astrofotografi/roberto-ortu/" class="herald-cat-3436">Roberto Ortu</a></span>
# 		<h1 class="entry-title h1">Giove e i suoi satelliti</h1>			<div class="entry-meta entry-meta-single"><div class="meta-item herald-date"><span class="updated">3 Dicembre 2021</span></div><div class="meta-item herald-rtime">2 Min Read</div></div>
# 	</header>		
# 		<div class="row">

			

# 	<div class="col-lg-2 col-md-2 col-sm-2 hidden-xs herald-left">

				
# 		<div class="entry-meta-wrapper ">

		
		
# 					<div class="entry-meta entry-meta-single"><div class="meta-item herald-comments"><a href="https://edu.inaf.it/astrofoto/giove-satelliti-roberto-ortu/#respond">Add Comment</a></div></div>
		
							
		
# 		</div>

# 	</div>


# 			<div class="col-lg-10 col-md-10 col-sm-10">
# 				<div class="entry-content herald-entry-content">

	
# 			<div class="entry-headline h5">Giove e tre dei suoi satelliti sui cieli di Cabras</div>
	
				
			
# 	<figure id="attachment_33221" aria-describedby="caption-attachment-33221" style="width: 1244px" class="wp-caption aligncenter"><img fetchpriority="high" decoding="async" src="http://edu.inaf.it/wp-content/uploads/2021/11/roberto_ortu-giove_satelliti.jpg" alt="roberto_ortu-giove_satelliti" width="1244" height="918" class="size-full wp-image-33221" srcset="https://edu.inaf.it/wp-content/uploads/2021/11/roberto_ortu-giove_satelliti.jpg 1244w, https://edu.inaf.it/wp-content/uploads/2021/11/roberto_ortu-giove_satelliti-300x221.jpg 300w, https://edu.inaf.it/wp-content/uploads/2021/11/roberto_ortu-giove_satelliti-1024x756.jpg 1024w, https://edu.inaf.it/wp-content/uploads/2021/11/roberto_ortu-giove_satelliti-768x567.jpg 768w, https://edu.inaf.it/wp-content/uploads/2021/11/roberto_ortu-giove_satelliti-74x55.jpg 74w, https://edu.inaf.it/wp-content/uploads/2021/11/roberto_ortu-giove_satelliti-111x83.jpg 111w, https://edu.inaf.it/wp-content/uploads/2021/11/roberto_ortu-giove_satelliti-990x731.jpg 990w" sizes="(max-width: 1244px) 100vw, 1244px"><figcaption id="caption-attachment-33221" class="wp-caption-text">Giove e, partendo da sinistra, i satelliti Ganimede, Europa e Io. Foto di Roberto Ortu</figcaption></figure>
# <p>Quest’anno, dopo anni di osservazione, ho deciso finalmente di iniziare con l’astrofotografia utilizzando una camera per la ripresa dei pianeti. Non potevo quindi non dedicare del tempo a Giove, il pianeta più grande del Sistema Solare. Giove si trova a una distanza media dal Sole di 5,2 UA, ha un diametro equatoriale di quasi 143000 Km e ruota su se stesso in meno di 10 ore. Questa rapida rotazione causa un forte schiacciamento polare ben visibile anche in questa foto. Il pianeta è composto principalmente da idrogeno ed elio ed è classificato come gigante gassoso. I suoi principali satelliti detti “medicei” sono stati scoperti da <strong>Galileo Galilei</strong> nel 1610 e sono: Io, Europa, Ganimede, Callisto. Attualmente ne sono stati scoperti 79.<br>
# Nella foto sono visibili le bande che caratterizzano l’atmosfera esterna del pianeta e la celebre Grande Macchia Rossa, la più grande tempesta del Sistema Solare. Da sinistra a destra sono poi visibili i satelliti Ganimede, Europa e Io.</p>
# <h3>Dati</h3>
# <p>Celestron 114/900 Newton, montatura eq2 con motore AR, camera planetaria QHY5L-II-C<br>
# Barlow 2x Celestron Omni acromatica<br>
# Sharpcap per acquisire un video di 2 minuti<br>
# Pipp, Autostakkert 3 e Registax 6 per elaborare il video<br>
# Registax e Camera Raw per luminosità&nbsp; e contrasto<br>
# Luogo: Cabras (OR)<br>
# Data: 17-10-2021 alle 19:37 UTC (21:37 ora locale)</p>

	
# 			<div class="meta-tags">
# 			<span>Tags</span><a href="https://edu.inaf.it/tag/europa/" rel="tag">Europa</a> <a href="https://edu.inaf.it/tag/giove/" rel="tag">Giove</a> <a href="https://edu.inaf.it/tag/io/" rel="tag">Io</a>		</div>
	
				
# 				</div>			</div>

# 			<div id="extras" class="col-lg-12 col-md-12 col-sm-12">
# 						<div id="related" class="herald-related-wrapper">		
# 		<div class="herald-mod-wrap"><div class="herald-mod-head "><div class="herald-mod-title"><h4 class="h6 herald-mod-h herald-color">You may also like</h4></div></div></div>
# 		<div class="herald-related row row-eq-height">

# 													<article class="herald-lay-f herald-lay-f1 post-60538 post type-post status-publish format-standard has-post-thumbnail hentry category-risate-spaziali tag-carl-friedrich-gauss tag-cerere tag-giuseppe-piazzi tag-heinrich-olbers">
# <div class="herald-ovrld">		
# 			<div class="herald-post-thumbnail">
# 			<a href="https://edu.inaf.it/rubriche/risate-spaziali/storie-travagliate-di-pianeti/" title="Storie travagliate di pianeti"><img width="300" height="200" src="https://edu.inaf.it/wp-content/uploads/2026/07/vignetta_giuseppe_piazzi-evidenza-300x200.jpg" class="attachment-herald-lay-b1 size-herald-lay-b1 wp-post-image" alt="Vignetta giuseppe piazzi evidenza" srcset="https://edu.inaf.it/wp-content/uploads/2026/07/vignetta_giuseppe_piazzi-evidenza-300x200.jpg 300w, https://edu.inaf.it/wp-content/uploads/2026/07/vignetta_giuseppe_piazzi-evidenza-414x276.jpg 414w, https://edu.inaf.it/wp-content/uploads/2026/07/vignetta_giuseppe_piazzi-evidenza-470x313.jpg 470w, https://edu.inaf.it/wp-content/uploads/2026/07/vignetta_giuseppe_piazzi-evidenza-640x426.jpg 640w, https://edu.inaf.it/wp-content/uploads/2026/07/vignetta_giuseppe_piazzi-evidenza-130x86.jpg 130w, https://edu.inaf.it/wp-content/uploads/2026/07/vignetta_giuseppe_piazzi-evidenza-187x124.jpg 187w, https://edu.inaf.it/wp-content/uploads/2026/07/vignetta_giuseppe_piazzi-evidenza-272x182.jpg 272w" sizes="(max-width: 300px) 100vw, 300px"></a>
# 		</div>
	
# 	<div class="entry-header herald-clear-blur">
# 					<span class="meta-category"><a href="https://edu.inaf.it/category/rubriche/risate-spaziali/" class="herald-cat-3006">Risate spaziali</a></span>
		
# 		<h2 class="entry-title h6"><a href="https://edu.inaf.it/rubriche/risate-spaziali/storie-travagliate-di-pianeti/">Storie travagliate di pianeti</a></h2>
# 					<div class="entry-meta"><div class="meta-item herald-date"><span class="updated">9 Luglio 2026</span></div></div>
# 			</div>
# </div>
	
	
# </article>							<article class="herald-lay-f herald-lay-f1 post-60408 post type-post status-publish format-standard has-post-thumbnail hentry category-cronache-dalla-scuola tag-astronomia tag-didattica tag-materia-oscura tag-stage tag-tng">
# <div class="herald-ovrld">		
# 			<div class="herald-post-thumbnail">
# 			<a href="https://edu.inaf.it/approfondimenti/cronache-dalla-scuola/giovani-astronomi-tng-2026-materia-oscura/" title="Giovani astronomi a caccia di materia oscura"><img width="300" height="200" src="https://edu.inaf.it/wp-content/uploads/2026/06/giovani_astronomi_tng-stage2026-evidenza-300x200.jpg" class="attachment-herald-lay-b1 size-herald-lay-b1 wp-post-image" alt="Giovani astronomi tng stage2026 evidenza" srcset="https://edu.inaf.it/wp-content/uploads/2026/06/giovani_astronomi_tng-stage2026-evidenza-300x200.jpg 300w, https://edu.inaf.it/wp-content/uploads/2026/06/giovani_astronomi_tng-stage2026-evidenza-414x276.jpg 414w, https://edu.inaf.it/wp-content/uploads/2026/06/giovani_astronomi_tng-stage2026-evidenza-470x313.jpg 470w, https://edu.inaf.it/wp-content/uploads/2026/06/giovani_astronomi_tng-stage2026-evidenza-640x426.jpg 640w, https://edu.inaf.it/wp-content/uploads/2026/06/giovani_astronomi_tng-stage2026-evidenza-130x86.jpg 130w, https://edu.inaf.it/wp-content/uploads/2026/06/giovani_astronomi_tng-stage2026-evidenza-187x124.jpg 187w, https://edu.inaf.it/wp-content/uploads/2026/06/giovani_astronomi_tng-stage2026-evidenza-272x182.jpg 272w" sizes="(max-width: 300px) 100vw, 300px"></a>
# 		</div>
	
# 	<div class="entry-header herald-clear-blur">
# 					<span class="meta-category"><a href="https://edu.inaf.it/category/approfondimenti/cronache-dalla-scuola/" class="herald-cat-139">Cronache dalla scuola</a></span>
		
# 		<h2 class="entry-title h6"><a href="https://edu.inaf.it/approfondimenti/cronache-dalla-scuola/giovani-astronomi-tng-2026-materia-oscura/">Giovani astronomi a caccia di materia oscura</a></h2>
# 					<div class="entry-meta"><div class="meta-item herald-date"><span class="updated">8 Luglio 2026</span></div></div>
# 			</div>
# </div>
	
	
# </article>							<article class="herald-lay-f herald-lay-f1 post-60427 post type-post status-publish format-standard has-post-thumbnail hentry category-universe-world tag-astronomy tag-eclipse tag-nuria-alvarez-crespo tag-outreach tag-public-engagement tag-social-media tag-sun-eclipse">
# <div class="herald-ovrld">		
# 			<div class="herald-post-thumbnail">
# 			<a href="https://edu.inaf.it/in-english/universe-world/nuria-alvarez-crespo-social-media-outreach/" title="Nothing matches the reach of social media"><img width="300" height="200" src="https://edu.inaf.it/wp-content/uploads/2026/07/nuria_alvarez_crespo-universo_mondo-evidenza-300x200.jpg" class="attachment-herald-lay-b1 size-herald-lay-b1 wp-post-image" alt="Nuria alvarez crespo universo mondo evidenza" loading="lazy" srcset="https://edu.inaf.it/wp-content/uploads/2026/07/nuria_alvarez_crespo-universo_mondo-evidenza-300x200.jpg 300w, https://edu.inaf.it/wp-content/uploads/2026/07/nuria_alvarez_crespo-universo_mondo-evidenza-414x276.jpg 414w, https://edu.inaf.it/wp-content/uploads/2026/07/nuria_alvarez_crespo-universo_mondo-evidenza-470x313.jpg 470w, https://edu.inaf.it/wp-content/uploads/2026/07/nuria_alvarez_crespo-universo_mondo-evidenza-640x426.jpg 640w, https://edu.inaf.it/wp-content/uploads/2026/07/nuria_alvarez_crespo-universo_mondo-evidenza-130x86.jpg 130w, https://edu.inaf.it/wp-content/uploads/2026/07/nuria_alvarez_crespo-universo_mondo-evidenza-187x124.jpg 187w, https://edu.inaf.it/wp-content/uploads/2026/07/nuria_alvarez_crespo-universo_mondo-evidenza-272x182.jpg 272w" sizes="auto, (max-width: 300px) 100vw, 300px"></a>
# 		</div>
	
# 	<div class="entry-header herald-clear-blur">
# 					<span class="meta-category"><a href="https://edu.inaf.it/category/in-english/universe-world/" class="herald-cat-3420">Universe World</a></span>
		
# 		<h2 class="entry-title h6"><a href="https://edu.inaf.it/in-english/universe-world/nuria-alvarez-crespo-social-media-outreach/">Nothing matches the reach of social media</a></h2>
# 					<div class="entry-meta"><div class="meta-item herald-date"><span class="updated">6 Luglio 2026</span></div></div>
# 			</div>
# </div>
	
	
# </article>								</div>
# </div>


	

# 	<div id="comments" class="herald-comments">

# 		<div class="herald-mod-wrap"><div class="herald-mod-head "><div class="herald-mod-title"><h4 class="h6 herald-mod-h herald-color">Add Comment</h4></div></div></div>		
# 					<div class="herald-gray-area"><span class="herald-fake-button herald-comment-form-open">Click here to post a comment</span></div>


# 	<div id="respond" class="comment-respond">
# 		<h3 id="reply-title" class="comment-reply-title"> <small><a rel="nofollow" id="cancel-comment-reply-link" href="/astrofoto/giove-satelliti-roberto-ortu/#respond" style="display:none;">Cancel reply</a></small></h3><form action="https://edu.inaf.it/wp-comments-post.php" method="post" id="commentform" class="comment-form" novalidate=""><p class="comment-form-comment"><label for="comment">Comment</label><textarea id="comment" name="comment" cols="45" rows="8" aria-required="true"></textarea></p><p class="comment-form-author"><label for="author">Nome <span class="required">*</span></label> <input id="author" name="author" type="text" value="" size="30" maxlength="245" autocomplete="name" required=""></p>
# <p class="comment-form-email"><label for="email">Email <span class="required">*</span></label> <input id="email" name="email" type="email" value="" size="30" maxlength="100" autocomplete="email" required=""></p>
# <p class="comment-form-url"><label for="url">Sito web</label> <input id="url" name="url" type="url" value="" size="30" maxlength="200" autocomplete="url"></p>
# <p class="form-submit"><input name="submit" type="submit" id="submit" class="submit" value="Post comment"> <input type="hidden" name="comment_post_ID" value="33220" id="comment_post_ID">
# <input type="hidden" name="comment_parent" id="comment_parent" value="0">
# </p><p style="display: none;"><input type="hidden" id="akismet_comment_nonce" name="akismet_comment_nonce" value="b3f789c146"></p><p style="display: none !important;" class="akismet-fields-container" data-prefix="ak_"><label>Δ<textarea name="ak_hp_textarea" cols="45" rows="8" maxlength="100"></textarea></label><input type="hidden" id="ak_js_1" name="ak_js" value="1783940708829"><script>document.getElementById( "ak_js_1" ).setAttribute( "value", ( new Date() ).getTime() );</script></p></form>	</div><!-- #respond -->
# 	<p class="akismet_comment_form_privacy_notice">Questo sito utilizza Akismet per ridurre lo spam. <a href="https://akismet.com/privacy/" target="_blank" rel="nofollow noopener">Scopri come vengono elaborati i dati derivati dai commenti</a>.</p>		
		
		
# 	</div>


# 	<div id="single-sticky" class="herald-single-sticky herald-single-wraper hidden-xs hidden-sm">
# 	<div class="container">
# 		<div class="row">
# 			<div class="col-lg-12 col-md-12">
				
									
					
										

					
					
				
# 					<div class="herald-sticky-share">
						
						
# 						<a href="https://edu.inaf.it/astrofoto/giove-satelliti-roberto-ortu/#respond" class="herald-comment-action">Comment</a>						
						
																			
# 					</div>

# 			</div>
# 		</div>
# 	</div>					
# </div>			</div>

# 		</div>

# </div>

	

# 	<div class="herald-sidebar col-lg-3 col-md-3 herald-sidebar-right" style="height: auto; min-height: 1px;">

# 					<div align="center"><img src="https://edu.inaf.it/wp-content/uploads/2020/05/astrofoto_avatar-180x180.jpg"></div><p align="center"><strong><a rel="tag" href="https://edu.inaf.it/astrofotografi/roberto-ortu/">Roberto Ortu</a></strong></p><p>Nato a Oristano nel 1985. Sono appassionato di astronomia da quando ero bambino e ricordo molto bene il momento e l'emozione di quando vidi per la prima volta la cometa Hale Bopp del 1997. Alla fine di quell'anno mi fu regalato un binocolo 10x50, tre anni dopo iniziai le osservazioni con il mio primo telescopio che tuttora utilizzo anche per l'astrofotografia amatoriale.</p></div>		
		
# 	</div>


# 			</article><div class="herald-single-sticky herald-single-mobile-sticky hidden-lg hidden-md">
# 	<div class="container">
# 		<div class="row">
# 			<div class="col-lg-12 col-md-12">
				
									
					
										

					
					
				
# 					<div class="herald-sticky-share">
						
						
# 						<a href="https://edu.inaf.it/astrofoto/giove-satelliti-roberto-ortu/#respond" class="herald-comment-action">Comment</a>						
						
																			
# 					</div>

# 			</div>
# 		</div>
# 	</div>					
# </div></div>	
		
# 	</div>


	

    
# 	<footer id="footer" class="herald-site-footer herald-slide">

					
# <div class="footer-widgets container">
# 	<div class="row">
# 					<div class="col-lg-3 col-md-3 col-sm-3">
# 				<div id="text-2" class="widget widget_text">			<div class="textwidget"><p>EduINAF è il magazine di didattica e divulgazione dell'INAF, <a href="http://www.inaf.it/" target="inaf">Istituto Nazionale di Astrofisica</a>.<br>Registrazione n. 45/2020 in data 4 giugno 2020, Tribunale di Roma<br>Direttore responsabile: Livia Giacomini<br><a href="http://edu.inaf.it/edu-inaf/la-redazione/">Redazione</a></p><p>ISSN: <a href="https://portal.issn.org/resource/ISSN/2785-0684" target="issn">2785-0684</a>
# </p></div>
# 		</div>			</div>
# 					<div class="col-lg-3 col-md-3 col-sm-3">
# 				<div id="text-3" class="widget widget_text">			<div class="textwidget"><p>Vuoi usare i contenuti di EduINAF? <a href="http://edu.inaf.it/edu-inaf/copyright/">Leggi i Crediti</a>.</p><p><a href="http://edu.inaf.it/privacy-info/">Informativa sulla Privacy</a><br><a href="http://edu.inaf.it/cookies-info/">Informatva sui Cookie</a></p>
# </div>
# 		</div>			</div>
# 					<div class="col-lg-3 col-md-3 col-sm-3">
# 				<div id="text-4" class="widget widget_text">			<div class="textwidget"><p>Per la rubrica de l'Astronomo risponde, per inviarci le tue foto o i tuoi contributi, scrivici a redazione.edu [chiocciola] inaf.it oppure <a href="http://edu.inaf.it/contatti/">compila il form</a></p>
# </div>
# 		</div>			</div>
# 					<div class="col-lg-3 col-md-3 col-sm-3">
# 				<div id="text-11" class="widget widget_text">			<div class="textwidget"><p>Sei un insegnante? Scarica la nostra <a class="evidenzia" href="http://edu.inaf.it/wp-content/uploads/2021/04/EduINAF-brochure-2025.pdf" target="pdf"><em>brochure</em></a> da distribuire nella tua scuola e…</p>
# </div>
# 		</div><div id="media_image-9" class="widget widget_media_image"><a href="http://edu.inaf.it/questionario/"><img width="300" height="140" src="https://edu.inaf.it/wp-content/uploads/2022/10/questionario_eduinaf-300x140-1.jpg" class="image wp-image-39347  attachment-full size-full" alt="questionario_eduinaf-300x140" style="max-width: 100%; height: auto;" decoding="async" loading="lazy"></a></div>			</div>
# 			</div>
# </div>		
# 					<div class="footer-bottom">
# <div class="container">
# 	<div class="row">
# 		<div class="col-lg-12">
			
# 									<div class="hel-l herald-go-hor">
# 									<div class="herald-copyright">#eduinaf #inaf #astronomyforabetterworld. Theme created by <a href="https://mekshq.com" target="_blank">Meks</a>. Powered by <a href="https://www.wordpress.org" target="_blank">WordPress</a>.</div>
# 							</div>
			
						
						
# 		</div>
# 	</div>
# </div>
# </div>	    
# 	</footer>

	

# <!--googleoff: all--><div id="cookie-law-info-bar" data-nosnippet="true" style="background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); font-family: inherit; bottom: 0px; position: fixed; display: block;"><span>Questo sito utilizza cookie di terze parti necessari per incorporare audio e video, dare la possibilità&nbsp; di condividere un articolo sui social media. Puoi accettare i cookies cliccando sul bottone o, semplicemente, continuando a navigare. Se non li vuoi, basta che abbondoni il sito. <a role="button" data-cli_action="accept" id="cookie_action_close_header" class="medium cli-plugin-button cli-plugin-main-button cookie_action_close_header cli_action_button wt-cli-accept-btn" style="display: inline-block; color: rgb(255, 255, 255); background-color: rgb(0, 0, 0);">Accetto</a> <a role="button" id="cookie_action_close_header_reject" class="medium cli-plugin-button cli-plugin-main-button cookie_action_close_header_reject cli_action_button wt-cli-reject-btn" data-cli_action="reject" style="color: rgb(255, 255, 255); background-color: rgb(0, 0, 0);">Reject</a> <a href="http://edu.inaf.it/index.php/cookies-info/" id="CONSTANT_OPEN_URL" target="_blank" class="cli-plugin-main-link" style="display: inline-block; color: rgb(68, 68, 68);">Leggi di più</a></span></div><div id="cookie-law-info-again" style="display: none; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); position: fixed; font-family: inherit; width: auto; bottom: 0px; right: 100px;" data-nosnippet="true"><span id="cookie_hdr_showagain">Privacy &amp; Cookies Policy</span></div><div class="cli-modal" data-nosnippet="true" id="cliSettingsPopup" tabindex="-1" role="dialog" aria-labelledby="cliSettingsPopup" aria-hidden="true">
#   <div class="cli-modal-dialog" role="document">
# 	<div class="cli-modal-content cli-bar-popup">
# 		  <button type="button" class="cli-modal-close" id="cliModalClose">
# 			<svg class="" viewBox="0 0 24 24"><path d="M19 6.41l-1.41-1.41-5.59 5.59-5.59-5.59-1.41 1.41 5.59 5.59-5.59 5.59 1.41 1.41 5.59-5.59 5.59 5.59 1.41-1.41-5.59-5.59z"></path><path d="M0 0h24v24h-24z" fill="none"></path></svg>
# 			<span class="wt-cli-sr-only">Chiudi</span>
# 		  </button>
# 		  <div class="cli-modal-body">
# 			<div class="cli-container-fluid cli-tab-container">
# 	<div class="cli-row">
# 		<div class="cli-col-12 cli-align-items-stretch cli-px-0">
# 			<div class="cli-privacy-overview">
# 				<h4>Privacy Overview</h4>				<div class="cli-privacy-content">
# 					<div class="cli-privacy-content-text">This website uses cookies to improve your experience while you navigate through the website. Out of these cookies, the cookies that are categorized as necessary are stored on your browser as they are essential for the working of basic functionalities...</div>
# 				</div>
# 				<a class="cli-privacy-readmore" aria-label="Mostra altro" role="button" data-readmore-text="Mostra altro" data-readless-text="Mostra meno"></a>			</div>
# 		</div>
# 		<div class="cli-col-12 cli-align-items-stretch cli-px-0 cli-tab-section-container">
# 												<div class="cli-tab-section">
# 						<div class="cli-tab-header">
# 							<a role="button" tabindex="0" class="cli-nav-link cli-settings-mobile" data-target="necessary" data-toggle="cli-toggle-tab">
# 								Necessary							</a>
# 															<div class="wt-cli-necessary-checkbox">
# 									<input type="checkbox" class="cli-user-preference-checkbox" id="wt-cli-checkbox-necessary" data-id="checkbox-necessary" checked="checked">
# 									<label class="form-check-label" for="wt-cli-checkbox-necessary">Necessary</label>
# 								</div>
# 								<span class="cli-necessary-caption">Sempre abilitato</span>
# 													</div>
# 						<div class="cli-tab-content">
# 							<div class="cli-tab-pane cli-fade" data-id="necessary">
# 								<div class="wt-cli-cookie-description">
# 									Necessary cookies are absolutely essential for the website to function properly. This category only includes cookies that ensures basic functionalities and security features of the website. These cookies do not store any personal information.								</div>
# 							</div>
# 						</div>
# 					</div>
# 																	<div class="cli-tab-section">
# 						<div class="cli-tab-header">
# 							<a role="button" tabindex="0" class="cli-nav-link cli-settings-mobile" data-target="non-necessary" data-toggle="cli-toggle-tab">
# 								Non-necessary							</a>
# 															<div class="cli-switch">
# 									<input type="checkbox" id="wt-cli-checkbox-non-necessary" class="cli-user-preference-checkbox" data-id="checkbox-non-necessary" checked="checked">
# 									<label for="wt-cli-checkbox-non-necessary" class="cli-slider" data-cli-enable="Abilitato" data-cli-disable="Disabilitato"><span class="wt-cli-sr-only">Non-necessary</span></label>
# 								</div>
# 													</div>
# 						<div class="cli-tab-content">
# 							<div class="cli-tab-pane cli-fade" data-id="non-necessary">
# 								<div class="wt-cli-cookie-description">
# 									Any cookies that may not be particularly necessary for the website to function and is used specifically to collect user personal data via analytics, ads, other embedded contents are termed as non-necessary cookies. It is mandatory to procure user consent prior to running these cookies on your website.								</div>
# 							</div>
# 						</div>
# 					</div>
# 										</div>
# 	</div>
# </div>
# 		  </div>
# 		  <div class="cli-modal-footer">
# 			<div class="wt-cli-element cli-container-fluid cli-tab-container">
# 				<div class="cli-row">
# 					<div class="cli-col-12 cli-align-items-stretch cli-px-0">
# 						<div class="cli-tab-footer wt-cli-privacy-overview-actions">
						
# 															<a id="wt-cli-privacy-save-btn" role="button" tabindex="0" data-cli-action="accept" class="wt-cli-privacy-btn cli_setting_save_button wt-cli-privacy-accept-btn cli-btn">ACCETTA E SALVA</a>
# 													</div>
						
# 					</div>
# 				</div>
# 			</div>
# 		</div>
# 	</div>
#   </div>
# </div>
# <div class="cli-modal-backdrop cli-fade cli-settings-overlay"></div>
# <div class="cli-modal-backdrop cli-fade cli-popupbar-overlay"></div>
# <!--googleon: all-->		<script type="text/javascript">
# 			(function() {
# 				let targetObjectName = 'EM';
# 				if ( typeof window[targetObjectName] === 'object' && window[targetObjectName] !== null ) {
# 					Object.assign( window[targetObjectName], []);
# 				} else {
# 					console.warn( 'Could not merge extra data: window.' + targetObjectName + ' not found or not an object.' );
# 				}
# 			})();
# 		</script>
# 		<script type="application/ld+json" id="slim-seo-schema">{"@context":"https://schema.org","@graph":[{"@type":"WebSite","@id":"https://edu.inaf.it/#website","url":"https://edu.inaf.it/","name":"EduINAF","description":"Il magazine di didattica e divulgazione dell&#039;Istituto Nazionale di Astrofisica","inLanguage":"it-IT","potentialAction":{"@id":"https://edu.inaf.it/#searchaction"},"publisher":{"@id":"https://edu.inaf.it/#organization"}},{"@type":"SearchAction","@id":"https://edu.inaf.it/#searchaction","target":"https://edu.inaf.it/?s={search_term_string}","query-input":"required name=search_term_string"},{"@type":"BreadcrumbList","name":"Breadcrumbs","@id":"https://edu.inaf.it/astrofoto/giove-satelliti-roberto-ortu/#breadcrumblist","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://edu.inaf.it/"},{"@type":"ListItem","position":2,"name":"Giove e i suoi satelliti"}]},{"@type":"WebPage","@id":"https://edu.inaf.it/astrofoto/giove-satelliti-roberto-ortu/#webpage","url":"https://edu.inaf.it/astrofoto/giove-satelliti-roberto-ortu/","inLanguage":"it-IT","name":"Giove e i suoi satelliti &#8211; EduINAF","description":"Giove e tre dei suoi satelliti sui cieli di Cabras","datePublished":"2021-12-03T10:00:47+01:00","dateModified":"2021-11-23T10:18:59+01:00","isPartOf":{"@id":"https://edu.inaf.it/#website"},"breadcrumb":{"@id":"https://edu.inaf.it/astrofoto/giove-satelliti-roberto-ortu/#breadcrumblist"},"primaryImageOfPage":{"@id":"https://edu.inaf.it/astrofoto/giove-satelliti-roberto-ortu/#thumbnail"},"image":{"@id":"https://edu.inaf.it/astrofoto/giove-satelliti-roberto-ortu/#thumbnail"}},{"@type":"Organization","@id":"https://edu.inaf.it/#organization","url":"https://edu.inaf.it/","name":"EduINAF"},{"@type":"ImageObject","@id":"https://edu.inaf.it/astrofoto/giove-satelliti-roberto-ortu/#thumbnail","url":"https://edu.inaf.it/wp-content/uploads/2021/11/giove_satelliti-roberto_ortu-astrofoto-evidenza.jpg","contentUrl":"https://edu.inaf.it/wp-content/uploads/2021/11/giove_satelliti-roberto_ortu-astrofoto-evidenza.jpg","width":889,"height":500}]}</script><script type="text/javascript" src="https://edu.inaf.it/wp-includes/js/jquery/ui/tooltip.min.js?ver=1.13.3" id="jquery-ui-tooltip-js"></script>
# <script type="text/javascript" id="ajax-filter-js-extra">
# /* <![CDATA[ */
# var filterPosts = {"nonce":"d993173f49","ajaxUrl":"https:\/\/edu.inaf.it\/wp-admin\/admin-ajax.php","timeoutMessage":"Troppo tempo per caricare i contenuti. Per favore ricarica e prova di nuovo.","serverErrorMessage":"Nessuna risposta. Per favore ricarica e prova di nuovo."};
# /* ]]> */
# </script>
# <script type="text/javascript" src="https://edu.inaf.it/wp-content/plugins/eduinaf-ajax-filter-posts/assets/js/ajax-filter-posts.js?ver=6.7.5" id="ajax-filter-js"></script>
# <script type="text/javascript" id="lsow-frontend-scripts-js-extra">
# /* <![CDATA[ */
# var lsow_settings = {"mobile_width":"780","custom_css":""};
# /* ]]> */
# </script>
# <script type="text/javascript" src="https://edu.inaf.it/wp-content/plugins/livemesh-siteorigin-widgets/assets/js/lsow-frontend.min.js?ver=3.9.2" id="lsow-frontend-scripts-js"></script>
# <script type="text/javascript" src="https://edu.inaf.it/wp-includes/js/comment-reply.min.js?ver=6.7.5" id="comment-reply-js" async="async" data-wp-strategy="async"></script>
# <script type="text/javascript" src="https://edu.inaf.it/wp-includes/js/imagesloaded.min.js?ver=5.0.0" id="imagesloaded-js"></script>
# <script type="text/javascript" id="herald-main-js-extra">
# /* <![CDATA[ */
# var herald_js_settings = {"ajax_url":"https:\/\/edu.inaf.it\/wp-admin\/admin-ajax.php","rtl_mode":"false","header_sticky":"1","header_sticky_offset":"600","header_sticky_up":"","single_sticky_bar":"1","popup_img":"1","logo":"","logo_retina":"","logo_mini":"","logo_mini_retina":"","smooth_scroll":"","trending_columns":"6","responsive_menu_more_link":"","header_ad_responsive":"","header_responsive_breakpoint":"1249"};
# /* ]]> */
# </script>
# <script type="text/javascript" src="https://edu.inaf.it/wp-content/themes/herald/assets/js/min.js?ver=2.6" id="herald-main-js"></script>
# <script defer="" type="text/javascript" src="https://edu.inaf.it/wp-content/plugins/akismet/_inc/akismet-frontend.js?ver=1766050526" id="akismet-frontend-js"></script>


# </body>
# """

In [ ]:
# # corpus_df = pd.read_excel("Data/corpus.xlsx")
# url = "https://edu.inaf.it/astrofoto/giove-satelliti-roberto-ortu/"
# idx = corpus_df.loc[corpus_df["url"]==url].index
# corpus_df.loc[idx, ["html_content"]]

   html_content
99          NaN

In [ ]:
# soup = BeautifulSoup(markup = html_text, features='lxml')
# # kill all script and style elements
# for script in soup(["script", "style", "nav", "header", "footer", "aside", "img", "link"]):
#     script.extract() # rip it out
#     # script.decompose() 
#     corpus_df.loc[idx, ["html_content"]] = str(soup.body)
#     corpus_df.loc[idx, ["text_content"]] = str(soup.body.get_text(separator='\n ', strip=True))

In [ ]:
# corpus_df.loc[idx, ["html_content"]]

                                         html_content
99  <body class="astrofoto-template-default single...

In [ ]:
# corpus_df.to_excel("Data/corpus.xlsx", index=False)

### answer matching

In [57]:
with open("Data/answer_set.json", 'r') as f:
        answer_set = json.load(f)

match_counts = []
for _, row in final_answer_df.iterrows():
        num_matches = 0
        answers = answer_set[row["topic_number"]]
        for answer_key in answers.keys():
                for answer in answers[answer_key]:
                        if answer.lower() in row["answer"].lower():
                        # print(row["answer"], ";", answer)
                                num_matches += 1
                                break
        print(row["uid"], row["topic_number"], row["answer"], num_matches)
        match_counts.append(num_matches)

final_answer_df["num_answer_matches"] = match_counts

1 g3t3 Rinoceronte tigre Leone stambecco cervo 3
1 g3t2 Il simbolo della bandiera rappresenta una ruota 1
1 g3t1 Il fiume gange 1
2 g3t3 Tigre,leone,rinoceronte,barasingha,blackbuck. 5
2 g3t2 Ruota  1
2 g3t1 Fiume gange  1
3 g3t1 Gange 1
3 g3t3 Tigre ,Leone, rinoceronte ,Blackbuck barasingha  5
3 g3t2 Un sole 0
4 g3t2 Ashoka. La ruota della vita buddista 2
4 g3t3 Tigre del bengaline
Leone asiatico
Rinoceronte Indiano
Blackbuck
Barasingha  5
4 g3t1 Gange 1
5 g3t1 Gange, il fiume sacro agli indu e la popolazione indiana 1
5 g3t3 Natura selvaggia tra tigri e leoni terrelncognite magazine 0
5 g3t2 Bandiera indiana significato ashoka chakra simbolo della vita  1
6 g3t1 Gange 1
6 g3t3 Tigress del bengala Leone asiatico rinoceronte INDIANO barasingha blackbuck 5
6 g3t2 La ruota ashoka chakra 2
7 g3t2 E un. Sole blu 0
7 g3t3 Bengala Leone asiatico  rinoceronte indiano barasighna 2
7 g3t1 Gange il fiume sacro again indu e alla popolazione indiana 1
8 g3t3 Tigre elefante pavone rinoceronte scimmie 4
8 g3t2 Ruota con 24 raggi,blu nevy 1
8 g3t1 Gange 1
9 g4t2 Il primo animale  mandato nello spazio è state una cagnietta Di nome Laika  1
9 g4t1 Ganimede e Callisto  2
9 g4t3 Andromeda Triangolo Orsa Minore 3
10 g4t3 Galassia del triangolo galassia del pegaso galassia della fenice 1
10 g4t2 Il primo animale che è andato nello spazio  era il cane Laika 2
10 g4t1 Io Europa ganimede e calisto 3
11 g4t3 Andromeda galassia del triangolo piccola nube di magellano
 3
11 g4t1 Callisto Europa Ganimede  Io 4
11 g4t2 Laika 1
12 g4t1 Io, Ganimede, Europa, Callisto  4
12 g4t2 È stato un cane di nome Laika 2
12 g4t3 Andromeda, galassia del triangolo M31, galassia sombrero M104 3
13 g4t1 Io, Europa, Ganimede e Callisto sono i 4 satelliti di Giove 4
13 g4t3 Le 3 galassie sono NGC3109,galassia di Andromeda galassia del triangolo  3
13 g4t2 Laika è stata il primo animale ed  è un cane  2
14 g4t1 Ganimede Callisto io Europa  4
14 g4t3 Andromeda del triangolo gruppo locale 2
14 g4t2 Un cane di nome Laika 2
15 g4t2 Il primo animale nello spazio è un cane e si chiamava Laika. 2
15 g4t3 Galassia di Andromeda Galassie di Fireworks Galassia del Triangolo 3
15 g4t1 Io Europa Ganimede e Callisto 4
16 g4t1 I satelliti maggiori di Giove si chiamano lune galileiane 1
16 g4t3 Andromeda, Galassia Sombrero ,Galassia del Triangolo
 3
16 g4t2 Il primo animali è stato un cane che si chiamava Laika 2
17 g3t3 Pavone tigre 🐅 scimmia 🐵 leone cobra 5
17 g3t2 Rapreseta la ruota dellavitabhuddista, si chiama ashoka  2
17 g3t1 Il fiume si chiama  gange 1
18 g3t3 Tigre del bengala ,Leone asiatico ,rinoceronte Indiano ,barasingha ,Blackbuck 5
18 g3t2 Sole 0
18 g3t1 Il gange u 1

In [58]:
final_answer_df.to_csv("Data/final_answer_df.csv", index=False, encoding='utf8')

In [59]:
final_answer_df.loc[final_answer_df["topic_number"]=="g3t1"]

,uid,topic_number,prompt,answer,timestamp,num_answer_matches
2,1,g3t1,Come si chiama il fiume sacro agli indiani?,Il fiume gange,2026-05-19 15:10:10.812,1
5,2,g3t1,Come si chiama il fiume sacro agli indiani?,Fiume gange,2026-05-19 15:15:05.518,1
6,3,g3t1,Come si chiama il fiume sacro agli indiani?,Gange,2026-05-19 14:51:32.588,1
11,4,g3t1,Come si chiama il fiume sacro agli indiani?,Gange,2026-05-19 15:21:00.731,1
12,5,g3t1,Come si chiama il fiume sacro agli indiani?,"Gange, il fiume sacro agli indu e la popolazio...",2026-05-19 14:58:33.130,1
15,6,g3t1,Come si chiama il fiume sacro agli indiani?,Gange,2026-05-19 14:52:28.940,1
20,7,g3t1,Come si chiama il fiume sacro agli indiani?,Gange il fiume sacro again indu e alla popolaz...,2026-05-19 15:05:34.776,1
23,8,g3t1,Come si chiama il fiume sacro agli indiani?,Gange,2026-05-19 15:16:38.128,1
50,17,g3t1,Come si chiama il fiume sacro agli indiani?,Il fiume si chiama gange,2026-05-19 15:27:44.380,1
53,18,g3t1,Come si chiama il fiume sacro agli indiani?,Il gange u,2026-05-19 15:17:10.220,1