## Extracting search events from logs

In [272]:
from driver import assign_topic_number
import glob
from tqdm.notebook import tqdm
import json
import pandas as pd

event_mapping = {
    "TaskStarted": "TS", # Task started
    "querySubmitted": "QS", # submitted user formulated query
    "searchResultGenerated": "SG", # serp generated
    "searchNoResults": "N_SG", # no SERP generated
    "clickedDidYouMeanSuggestion": "QC", # submitted SE corrected query
    "resultExposureStarted": "RV", # SERP result viewing
    "clickedResult": "RC", # SERP result clicked
    "OpenedAnswerBox": "AW", # answer writing
    "TaskEnded": "TE", # Task ended
}

event_sequences = []
relevance_df = pd.read_csv("Data/relevance.csv")

for file_name in tqdm(glob.glob("Data/3rd/*_FULL.log"), total=len(glob.glob("Data/3rd/*_FULL.log"))):
    with open(file_name, 'r') as f:
        log_entries = [json.loads(x) for x in f.readlines()]
    
    for entry in log_entries:
        if entry["type"] in list(event_mapping.keys()):
            uid = int(entry["uid"])
            topic_num = assign_topic_number(uid, entry["actual_topic_number"])
            event_type = entry["type"]
            event_key = event_mapping[event_type]
            event_time = entry["timestamp"]
            if (event_key == "RV") or (event_key == "RC"):
                url = entry["url"]
                relevant_resources = relevance_df.loc[relevance_df["topic_number"]==topic_num]["doc"].tolist()
                if url in relevant_resources:
                    event_key = "R_" + event_key
                else:
                    event_key = "NR_" + event_key
            if (event_key == "SG") and (int(entry["rank"]) > 1):
                continue
            event_sequences.append([uid, topic_num, event_type, event_key, event_time])

for file_name in tqdm(glob.glob("Data/4th/*_FULL.log"), total=len(glob.glob("Data/4th/*_FULL.log"))):
    with open(file_name, 'r') as f:
        log_entries = [json.loads(x) for x in f.readlines()]
    
    for entry in log_entries:
        if entry["type"] in list(event_mapping.keys()):
            uid = int(entry["uid"])
            topic_num = assign_topic_number(uid, entry["actual_topic_number"])
            event_type = entry["type"]
            event_key = event_mapping[event_type]
            event_time = entry["timestamp"]
            if (event_key == "RV") or (event_key == "RC"):
                url = entry["url"]
                relevant_resources = relevance_df.loc[relevance_df["topic_number"]==topic_num]["doc"].tolist()
                if url in relevant_resources:
                    event_key = "R_" + event_key
                else:
                    event_key = "NR_" + event_key
            if (event_key == "SG") and (int(entry["rank"]) > 1):
                continue
            event_sequences.append([uid, topic_num, event_type, event_key, event_time])

event_sequences_df = pd.DataFrame(event_sequences, columns=["uid", "topic_number", "action_name", "action_code", "timestamp"])   
event_sequences_df["timestamp"] = pd.to_datetime(event_sequences_df["timestamp"])   
event_sequences_df = event_sequences_df.sort_values(by=["uid", "topic_number", "timestamp"])
event_sequences_df.to_csv("Data/event_sequences_df_final.csv", index=False)

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

In [286]:
df = event_sequences_df.sort_values(
    ["uid", "topic_number", "timestamp"]
).copy()

# Create run IDs for consecutive identical actions
df["run_id"] = (
    df.groupby(["uid", "topic_number"])["action_code"]
      .transform(lambda x: x.ne(x.shift()).cumsum())
)

# Aggregate each run
condensed_df = (
    df.groupby(["uid", "topic_number", "run_id"])
      .agg(
          action_name=("action_name", "first"),
          action_code=("action_code", "first"),
          timestamp=("timestamp", "first"),
          count=("action_code", "size")
      )
      .reset_index()
)

# Append "+" where run length > 1
condensed_df["action_code"] = condensed_df.apply(
    lambda row: f"{row['action_code']}+" if row["count"] > 1 else row["action_code"],
    axis=1
)
condensed_df = condensed_df.drop(columns=["run_id"]).sort_values(by=["uid", "topic_number", "timestamp"])
condensed_df.to_csv("Data/condensed_event_sequences_df_final.csv", index=False)

In [287]:
condensed_df.loc[condensed_df["uid"]==1]

,uid,topic_number,action_name,action_code,timestamp,count
0,1,g3t1,TaskStarted,TS,2026-05-19 15:06:45.708,1
1,1,g3t1,querySubmitted,QS,2026-05-19 15:08:39.525,1
2,1,g3t1,searchResultGenerated,SG,2026-05-19 15:08:41.314,1
3,1,g3t1,resultExposureStarted,R_RV+,2026-05-19 15:08:41.585,2
4,1,g3t1,clickedResult,R_RC,2026-05-19 15:08:58.405,1
5,1,g3t1,resultExposureStarted,R_RV+,2026-05-19 15:09:35.824,2
6,1,g3t1,OpenedAnswerBox,AW,2026-05-19 15:09:38.065,1
7,1,g3t1,TaskEnded,TE,2026-05-19 15:10:10.812,1
8,1,g3t2,TaskStarted,TS,2026-05-19 14:56:45.133,1
9,1,g3t2,querySubmitted,QS+,2026-05-19 14:57:07.106,2
10,1,g3t2,searchResultGenerated,SG,2026-05-19 15:02:42.576,1
11,1,g3t2,resultExposureStarted,R_RV,2026-05-19 15:02:42.844,1
12,1,g3t2,clickedResult,R_RC,2026-05-19 15:02:48.776,1
13,1,g3t2,OpenedAnswerBox,AW+,2026-05-19 15:03:11.207,2
14,1,g3t2,TaskEnded,TE,2026-05-19 15:06:18.848,1
15,1,g3t3,TaskStarted,TS,2026-05-19 14:48:04.522,1
16,1,g3t3,querySubmitted,QS+,2026-05-19 14:48:43.476,2
17,1,g3t3,searchResultGenerated,SG,2026-05-19 14:51:27.687,1
18,1,g3t3,resultExposureStarted,R_RV+,2026-05-19 14:51:27.960,2
19,1,g3t3,resultExposureStarted,NR_RV,2026-05-19 14:51:31.168,1
20,1,g3t3,clickedResult,R_RC,2026-05-19 14:51:43.444,1
21,1,g3t3,resultExposureStarted,R_RV+,2026-05-19 14:53:01.804,2
22,1,g3t3,resultExposureStarted,NR_RV+,2026-05-19 14:53:03.871,11
23,1,g3t3,resultExposureStarted,R_RV+,2026-05-19 14:53:13.441,2
24,1,g3t3,clickedResult,R_RC,2026-05-19 14:53:19.408,1
25,1,g3t3,OpenedAnswerBox,AW,2026-05-19 14:53:52.568,1
26,1,g3t3,TaskEnded,TE,2026-05-19 14:56:19.153,1

In [288]:
event_sequences_df.loc[event_sequences_df["uid"]==1]

,uid,topic_number,action_name,action_code,timestamp
227,1,g3t1,TaskStarted,TS,2026-05-19 15:06:45.708
228,1,g3t1,querySubmitted,QS,2026-05-19 15:08:39.525
229,1,g3t1,searchResultGenerated,SG,2026-05-19 15:08:41.314
230,1,g3t1,resultExposureStarted,R_RV,2026-05-19 15:08:41.585
231,1,g3t1,resultExposureStarted,R_RV,2026-05-19 15:08:41.588
232,1,g3t1,clickedResult,R_RC,2026-05-19 15:08:58.405
233,1,g3t1,resultExposureStarted,R_RV,2026-05-19 15:09:35.824
234,1,g3t1,resultExposureStarted,R_RV,2026-05-19 15:09:35.828
235,1,g3t1,OpenedAnswerBox,AW,2026-05-19 15:09:38.065
236,1,g3t1,TaskEnded,TE,2026-05-19 15:10:10.812
218,1,g3t2,TaskStarted,TS,2026-05-19 14:56:45.133
219,1,g3t2,querySubmitted,QS,2026-05-19 14:57:07.106
220,1,g3t2,querySubmitted,QS,2026-05-19 15:02:41.120
221,1,g3t2,searchResultGenerated,SG,2026-05-19 15:02:42.576
222,1,g3t2,resultExposureStarted,R_RV,2026-05-19 15:02:42.844
223,1,g3t2,clickedResult,R_RC,2026-05-19 15:02:48.776
224,1,g3t2,OpenedAnswerBox,AW,2026-05-19 15:03:11.207
225,1,g3t2,OpenedAnswerBox,AW,2026-05-19 15:03:59.904
226,1,g3t2,TaskEnded,TE,2026-05-19 15:06:18.848
192,1,g3t3,TaskStarted,TS,2026-05-19 14:48:04.522
193,1,g3t3,querySubmitted,QS,2026-05-19 14:48:43.476
194,1,g3t3,querySubmitted,QS,2026-05-19 14:51:26.583
195,1,g3t3,searchResultGenerated,SG,2026-05-19 14:51:27.687
196,1,g3t3,resultExposureStarted,R_RV,2026-05-19 14:51:27.960
197,1,g3t3,resultExposureStarted,R_RV,2026-05-19 14:51:27.966
198,1,g3t3,resultExposureStarted,NR_RV,2026-05-19 14:51:31.168
199,1,g3t3,clickedResult,R_RC,2026-05-19 14:51:43.444
200,1,g3t3,resultExposureStarted,R_RV,2026-05-19 14:53:01.804
201,1,g3t3,resultExposureStarted,R_RV,2026-05-19 14:53:01.814
202,1,g3t3,resultExposureStarted,NR_RV,2026-05-19 14:53:03.871
203,1,g3t3,resultExposureStarted,NR_RV,2026-05-19 14:53:03.975
204,1,g3t3,resultExposureStarted,NR_RV,2026-05-19 14:53:04.062
205,1,g3t3,resultExposureStarted,NR_RV,2026-05-19 14:53:04.181
206,1,g3t3,resultExposureStarted,NR_RV,2026-05-19 14:53:04.350
207,1,g3t3,resultExposureStarted,NR_RV,2026-05-19 14:53:04.575
208,1,g3t3,resultExposureStarted,NR_RV,2026-05-19 14:53:04.985
209,1,g3t3,resultExposureStarted,NR_RV,2026-05-19 14:53:07.005
210,1,g3t3,resultExposureStarted,NR_RV,2026-05-19 14:53:08.097
211,1,g3t3,resultExposureStarted,NR_RV,2026-05-19 14:53:08.795
212,1,g3t3,resultExposureStarted,NR_RV,2026-05-19 14:53:09.000
213,1,g3t3,resultExposureStarted,R_RV,2026-05-19 14:53:13.441
214,1,g3t3,resultExposureStarted,R_RV,2026-05-19 14:53:13.477
215,1,g3t3,clickedResult,R_RC,2026-05-19 14:53:19.408
216,1,g3t3,OpenedAnswerBox,AW,2026-05-19 14:53:52.568
217,1,g3t3,TaskEnded,TE,2026-05-19 14:56:19.153

## Identifying common sequence patterns

In [ ]:
import pandas as pd

event_sequences_df = pd.read_csv("Data/condensed_event_sequences_df_final.csv")
final_answer_df = pd.read_csv("Data/final_answer_df.csv")

In [14]:
event_sequences_df.head()

,uid,topic_number,action_name,action_code,timestamp,count
0,1,g3t1,TaskStarted,TS,2026-05-19 15:06:45.708,1
1,1,g3t1,querySubmitted,QS,2026-05-19 15:08:39.525,1
2,1,g3t1,searchResultGenerated,SG,2026-05-19 15:08:41.314,1
3,1,g3t1,resultExposureStarted,R_RV+,2026-05-19 15:08:41.585,2
4,1,g3t1,clickedResult,R_RC,2026-05-19 15:08:58.405,1

In [15]:
event_sequences_df["uid"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [16]:
action_key_mapping = enumerate(event_sequences_df["action_code"].unique(), start=1)
action_key_mapping = {code: key for key, code in action_key_mapping}
action_key_mapping

{'TS': 1,
 'QS': 2,
 'SG': 3,
 'R_RV+': 4,
 'R_RC': 5,
 'AW': 6,
 'TE': 7,
 'QS+': 8,
 'R_RV': 9,
 'AW+': 10,
 'NR_RV': 11,
 'NR_RV+': 12,
 'TS+': 13,
 'NR_RC': 14,
 'N_SG': 15,
 'QC': 16}

In [17]:
sequence_id_list = []
event_id_list = []
num_events_list = []
action_key_list = []
search_success_list = []

seq_id = 1
for uid in event_sequences_df["uid"].unique():
    user_df = event_sequences_df[event_sequences_df["uid"]==uid]
    for topic_num in user_df["topic_number"].unique():
        answer_match_ratio = final_answer_df[(final_answer_df["uid"]==uid) & (final_answer_df["topic_number"]==topic_num)]["answer_match_ratio"].values[0]
        # print(f"uid: {uid}, topic_num: {topic_num}, answer_match_ratio: {answer_match_ratio}")
        topic_df = user_df[user_df["topic_number"]==topic_num]
        
        evnt_id = 1
        for index, row in topic_df.iterrows():
            sequence_id_list.append(seq_id)
            event_id_list.append(evnt_id)
            num_events_list.append(1)
            action_key_list.append(action_key_mapping[row["action_code"]])
            if answer_match_ratio == 1.0:
                search_success_list.append(1)
            else:
                search_success_list.append(0)
            
            evnt_id+=1
        
        seq_id+=1

event_sequences_df["sequence_id"] = sequence_id_list
event_sequences_df["event_id"] = event_id_list 
event_sequences_df["num_events"] = num_events_list
event_sequences_df["action_key"] = action_key_list
event_sequences_df["search_success"] = search_success_list

event_sequences_df = event_sequences_df[["sequence_id", "uid", "topic_number", "event_id", "num_events", "action_key", "action_name", "action_code", "timestamp", "search_success"]]

In [18]:
success_action_counts = event_sequences_df.loc[event_sequences_df["search_success"]==1].groupby(["uid"])["topic_number"].value_counts().to_frame().reset_index()
fail_action_counts = event_sequences_df.loc[event_sequences_df["search_success"]==0].groupby(["uid"])["topic_number"].value_counts().to_frame().reset_index()

print(f"Avg number of actions for successful searches: {success_action_counts['count'].mean()}", f"Avg number of actions for failed searches: {fail_action_counts['count'].mean()}")

Avg number of actions for successful searches: 23.02777777777778 Avg number of actions for failed searches: 24.61111111111111

In [19]:
event_sequences_df.head()

,sequence_id,uid,topic_number,event_id,num_events,action_key,action_name,action_code,timestamp,search_success
0,1,1,g3t1,1,1,1,TaskStarted,TS,2026-05-19 15:06:45.708,1
1,1,1,g3t1,2,1,2,querySubmitted,QS,2026-05-19 15:08:39.525,1
2,1,1,g3t1,3,1,3,searchResultGenerated,SG,2026-05-19 15:08:41.314,1
3,1,1,g3t1,4,1,4,resultExposureStarted,R_RV+,2026-05-19 15:08:41.585,1
4,1,1,g3t1,5,1,5,clickedResult,R_RC,2026-05-19 15:08:58.405,1

In [20]:
successful_events = event_sequences_df[event_sequences_df["search_success"]==1]
successful_events.to_csv("Data/successful_sessions.txt", sep=" ", header=False, index=False, columns=["sequence_id", "event_id", "num_events", "action_key"])

failed_events = event_sequences_df[event_sequences_df["search_success"]==0]
failed_events.to_csv("Data/failed_sessions.txt", sep=" ", header=False, index=False, columns=["sequence_id", "event_id", "num_events", "action_key"])

In [21]:
from pycspade.helpers import spade, print_result

# To get raw SPADE output
successful_result = spade(filename='Data/successful_sessions.txt', support=0.2, parse=True, maxgap=1)
failed_result = spade(filename='Data/failed_sessions.txt', support=0.2, parse=True, maxgap=1)

In [22]:
print_result(successful_result)

   Occurs     Accum   Support    Confid      Lift                                                                         Sequence
       35        35 0.9722222       N/A       N/A                                                                              (1)
       33        33 0.9166667 0.9428571 0.9697959                                                                         (1)->(2)
       33        33 0.9166667 1.0000000 1.0000000                                                                    (1)->(2)->(3)
       23        23 0.6388889 0.6969697 0.7603306                                                               (1)->(2)->(3)->(4)
       10        10 0.2777778 0.4347826 0.5397301                                                          (1)->(2)->(3)->(4)->(5)
       17        40 0.4722222       N/A       N/A                                                                             (10)
       16        30 0.4444444 0.9411765 0.9411765                                                                        (10)->(7)
       19        43 0.5277778       N/A       N/A                                                                             (11)
       10        10 0.2777778 0.5263158 0.5741627                                                                        (11)->(4)
        9         9 0.2500000 0.4736842 1.0657895                                                                        (11)->(9)
       21        66 0.5833333       N/A       N/A                                                                             (12)
        8         8 0.2222222 0.3809524 1.5238095                                                                       (12)->(14)
        8         8 0.2222222 0.3809524 0.3918367                                                                        (12)->(2)
       17        30 0.4722222 0.8095238 0.8831169                                                                        (12)->(4)
        9        17 0.2500000       N/A       N/A                                                                             (14)
       35        76 0.9722222       N/A       N/A                                                                              (2)
       35        68 0.9722222 1.0000000 1.0000000                                                                         (2)->(3)
       30        53 0.8333333 0.8571429 0.9350649                                                                    (2)->(3)->(4)
        9         9 0.2500000 0.3000000 0.5142857                                                              (2)->(3)->(4)->(12)
       12        22 0.3333333 0.4000000 0.4965517                                                               (2)->(3)->(4)->(5)
       36       104 1.0000000       N/A       N/A                                                                              (3)
        9         9 0.2500000 0.2500000 0.4285714                                                                        (3)->(12)
       31        84 0.8611111 0.8611111 0.9393939                                                                         (3)->(4)
        9        18 0.2500000 0.2903226 0.4976959                                                                   (3)->(4)->(12)
       13        35 0.3611111 0.4193548 0.5205784                                                                    (3)->(4)->(5)
       33       184 0.9166667       N/A       N/A                                                                              (4)
       10        10 0.2777778 0.3030303 0.5741627                                                                        (4)->(11)
       18        36 0.5000000 0.5454545 0.9350649                                                                        (4)->(12)
       13        13 0.3611111 0.7222222 0.7878788                                                                   (4)->(12)->(4)
       23        58 0.6388889 0.6969697 0.8652038                                                                         (4)->(5)
        8         8 0.2222222 0.3478261 0.7365729                                                                   (4)->(5)->(10)
       13        13 0.3611111 0.5652174 0.6166008                                                                    (4)->(5)->(4)
        8         8 0.2222222 0.3478261 0.5444234                                                                    (4)->(5)->(6)
       12        12 0.3333333 0.3636364 0.5691700                                                                         (4)->(6)
        9         9 0.2500000 0.7500000 0.7500000                                                                    (4)->(6)->(7)
       29        87 0.8055556       N/A       N/A                                                                              (5)
       15        23 0.4166667 0.5172414 1.0953347                                                                        (5)->(10)
       14        14 0.3888889 0.9333333 0.9333333                                                                   (5)->(10)->(7)
       14        27 0.3888889 0.4827586 0.5266458                                                                         (5)->(4)
       12        20 0.3333333 0.4137931 0.6476762                                                                         (5)->(6)
       10        10 0.2777778 0.8333333 0.8333333                                                                    (5)->(6)->(7)
       23        55 0.6388889       N/A       N/A                                                                              (6)
       19        38 0.5277778 0.8260870 0.8260870                                                                         (6)->(7)
       36       104 1.0000000       N/A       N/A                                                                              (7)
       16        25 0.4444444       N/A       N/A                                                                              (9)
       14        14 0.3888889 0.8750000 1.6578947                                                                        (9)->(11)

In [23]:
print_result(failed_result)

   Occurs     Accum   Support    Confid      Lift                                                                         Sequence
       18        18 1.0000000       N/A       N/A                                                                              (1)
       15        15 0.8333333 0.8333333 0.9375000                                                                         (1)->(2)
       12        12 0.6666667 0.8000000 0.8000000                                                                    (1)->(2)->(3)
        8         8 0.4444444 0.6666667 0.7058824                                                               (1)->(2)->(3)->(4)
       11        31 0.6111111       N/A       N/A                                                                             (10)
       10        26 0.5555556 0.9090909 0.9090909                                                                        (10)->(7)
       13        52 0.7222222       N/A       N/A                                                                             (11)
        4         4 0.2222222 0.3076923 1.1076923                                                                       (11)->(14)
        4         4 0.2222222 0.3076923 0.3461538                                                                        (11)->(2)
        4         4 0.2222222 1.0000000 1.0000000                                                                   (11)->(2)->(3)
        5        17 0.2777778 0.3846154 0.4072398                                                                        (11)->(4)
        5        10 0.2777778 0.3846154 0.4945055                                                                        (11)->(5)
        7        12 0.3888889 0.5384615 0.9692308                                                                        (11)->(9)
        4         4 0.2222222 0.5714286 0.7346939                                                                   (11)->(9)->(5)
        9        32 0.5000000       N/A       N/A                                                                             (12)
        4         4 0.2222222 0.4444444 1.6000000                                                                       (12)->(14)
        4        12 0.2222222 0.4444444 0.5000000                                                                        (12)->(2)
        4        12 0.2222222 1.0000000 1.0000000                                                                   (12)->(2)->(3)
        7        12 0.3888889 0.7777778 0.8235294                                                                        (12)->(4)
        4         4 0.2222222 0.5714286 0.7346939                                                                   (12)->(4)->(5)
        5        13 0.2777778       N/A       N/A                                                                             (14)
        4         4 0.2222222 0.8000000 0.8470588                                                                        (14)->(4)
        4         4 0.2222222       N/A       N/A                                                                             (15)
        4         4 0.2222222 1.0000000 1.1250000                                                                        (15)->(2)
        4         4 0.2222222 1.0000000 1.0000000                                                                   (15)->(2)->(3)
       16        57 0.8888889       N/A       N/A                                                                              (2)
       16        54 0.8888889 1.0000000 1.0000000                                                                         (2)->(3)
        4         4 0.2222222 0.2500000 0.5000000                                                                   (2)->(3)->(12)
        4         4 0.2222222 1.0000000 1.1250000                                                              (2)->(3)->(12)->(2)
        4         4 0.2222222 1.0000000 1.0000000                                                         (2)->(3)->(12)->(2)->(3)
       15        23 0.8333333 0.9375000 0.9926471                                                                    (2)->(3)->(4)
        4         4 0.2222222 0.2666667 0.4363636                                                              (2)->(3)->(4)->(10)
        4         4 0.2222222 1.0000000 1.0000000                                                         (2)->(3)->(4)->(10)->(7)
        6         6 0.3333333 0.4000000 0.5538462                                                              (2)->(3)->(4)->(11)
        4         4 0.2222222 0.6666667 0.7058824                                                         (2)->(3)->(4)->(11)->(4)
        5         5 0.2777778 0.3333333 0.4285714                                                               (2)->(3)->(4)->(5)
        4         4 0.2222222 0.2500000 0.4500000                                                                    (2)->(3)->(9)
       18        76 1.0000000       N/A       N/A                                                                              (3)
        4         8 0.2222222 0.2222222 0.4444444                                                                        (3)->(12)
        4         8 0.2222222 1.0000000 1.1250000                                                                   (3)->(12)->(2)
        4         8 0.2222222 1.0000000 1.0000000                                                              (3)->(12)->(2)->(3)
       16        39 0.8888889 0.8888889 0.9411765                                                                         (3)->(4)
        4         8 0.2222222 0.2500000 0.4090909                                                                   (3)->(4)->(10)
        4         8 0.2222222 1.0000000 1.0000000                                                              (3)->(4)->(10)->(7)
        9        15 0.5000000 0.5625000 0.7788462                                                                   (3)->(4)->(11)
        4         8 0.2222222 0.4444444 0.4705882                                                              (3)->(4)->(11)->(4)
        5        10 0.2777778 0.3125000 0.4017857                                                                    (3)->(4)->(5)
        6        10 0.3333333 0.3333333 0.6000000                                                                         (3)->(9)
        4         4 0.2222222 0.6666667 0.9230769                                                                   (3)->(9)->(11)
       17       103 0.9444444       N/A       N/A                                                                              (4)
        6        14 0.3333333 0.3529412 0.5775401                                                                        (4)->(10)
        4        12 0.2222222 0.6666667 0.6666667                                                                   (4)->(10)->(7)
       11        30 0.6111111 0.6470588 0.8959276                                                                        (4)->(11)
        4        12 0.2222222 0.3636364 0.3850267                                                                   (4)->(11)->(4)
        5         5 0.2777778 0.4545455 0.5844156                                                                   (4)->(11)->(5)
        5         5 0.2777778 0.4545455 0.8181818                                                                   (4)->(11)->(9)
        7        11 0.3888889 0.4117647 0.8235294                                                                        (4)->(12)
        5         5 0.2777778 0.7142857 0.7563025                                                                   (4)->(12)->(4)
        6         6 0.3333333 0.3529412 0.3970588                                                                         (4)->(2)
        6         6 0.3333333 1.0000000 1.0000000                                                                    (4)->(2)->(3)
       10        24 0.5555556 0.5882353 0.7563025                                                                         (4)->(5)
        6         6 0.3333333 0.6000000 0.6352941                                                                    (4)->(5)->(4)
       14        58 0.7777778       N/A       N/A                                                                              (5)
        6         6 0.3333333 0.4285714 0.7012987                                                                        (5)->(10)
        4         4 0.2222222 0.6666667 0.6666667                                                                   (5)->(10)->(7)
        8        14 0.4444444 0.5714286 0.6050420                                                                         (5)->(4)
        4         4 0.2222222 0.5000000 0.6923077                                                                   (5)->(4)->(11)
        4         4 0.2222222 0.5000000 1.0000000                                                                   (5)->(4)->(12)
        5         5 0.2777778 0.3571429 0.6428571                                                                         (5)->(6)
        5         5 0.2777778 1.0000000 1.0000000                                                                    (5)->(6)->(7)
       10        15 0.5555556       N/A       N/A                                                                              (6)
        8        13 0.4444444 0.8000000 0.8000000                                                                         (6)->(7)
       18        57 1.0000000       N/A       N/A                                                                              (7)
        5         5 0.2777778       N/A       N/A                                                                              (8)
        4         4 0.2222222 0.8000000 0.8000000                                                                         (8)->(3)
       10        32 0.5555556       N/A       N/A                                                                              (9)
        5         9 0.2777778 0.5000000 0.6923077                                                                        (9)->(11)
        4         4 0.2222222 0.4000000 0.8000000                                                                        (9)->(12)
        6        10 0.3333333 0.6000000 0.7714286                                                                         (9)->(5)

In [24]:
import pandas as pd

def is_sublist(sub, main):
    n = len(sub)
    if n == 0:
        return True  # An empty list is always a subset
    return any(main[i : i + n] == sub for i in range(len(main) - n + 1))

def save_extracted_sequences(result, action_key_mapping, prune=False):
    reverse_action_key_mapping = {v: k for k, v in action_key_mapping.items()}
    rows = []

    for line in result["seqstrm"].splitlines():
        if not line.strip():
            continue

        pattern, counts = line.split(" -- ")

        occurs, accum = map(int, counts.split())

        decoded = " -> ".join(
            reverse_action_key_mapping[int(x.strip())]
            for x in pattern.split("->")
        )

        rows.append({
            "Sequence": pattern,
            "Decoded_sequence": decoded,
            "Actions": [int(x.strip()) for x in pattern.split("->")],
            "Num_actions": len(decoded.split("->")),
            "Occurs": occurs, # number of sessions the pattern occurs in
            "Accum": accum, # total number of times the pattern occurs across all sessions
            "Support": occurs / result["nsequences"]
        })

    df = pd.DataFrame(rows)
    # df = df.loc[df["Num_actions"] > 1].reset_index(drop=True)
    
    if prune == True:
        closed = []

        for _, row in df.iterrows():
            actions = row["Actions"]
            num_actions = row["Num_actions"]
            support = row["Support"]

            is_closed_flag = True
            candidate_patterns = df.loc[(df["Support"] == support) & (df["Num_actions"] > num_actions)] # all patterns longer than current pattern with same support

            if len(candidate_patterns) > 0:
                for _, candidate in candidate_patterns.iterrows():
                    # print(len(actions), len(candidate["Actions"]))
                    if is_sublist(actions, candidate["Actions"]):
                        is_closed_flag = False

            closed.append(is_closed_flag)


        df["is_closed"] = closed
        df = df.loc[df["is_closed"]==True].drop(columns=["is_closed"]).reset_index(drop=True)
    df = df.sort_values(by=["Support", "Num_actions"], ascending=False).reset_index(drop=True)
            

    # pruning for closed sequences, i.e., retaining sequences which do not have any supersequence with the same support
    # closed = []

    # for _, row in df.iterrows():

    #     seq = row["Sequence"].split("->")
    #     support = row["Support"]

    #     is_closed_flag = True

    #     candidates = df[
    #         (df["Support"] == support)
    #         & (df["Num_actions"] > len(seq))
    #     ]

    #     for candidate in candidates["Sequence"]:
    #         cand_seq = candidate.split("->")

    #         if is_subsequence(seq, cand_seq):
    #             is_closed_flag = False
    #             break

    #     closed.append(is_closed_flag)

    # df["is_closed"] = closed
    # df = (
    #     df[df["is_closed"]]
    #     .drop(columns=["is_closed"])
    #     .reset_index(drop=True)
    # )

    # for _, row in df.iterrows():
    #     pattern = row["Decoded_sequence"]
    #     super_patterns = df[df["Decoded_sequence"].str.contains(pattern) & (df["Support"] == row["Support"]) & (df["Decoded_sequence"] != pattern)]
    #     # print(pattern)
    #     # print(super_patterns)
    #     if len(super_patterns) > 0:
    #         # print(f"{pattern} is not a closed pattern.")
    #         closed.append(False)
    #     else:
    #         # print(f"{pattern} is a closed pattern.")
    #         closed.append(True)

    # df["is_closed"] = closed
    # df = df.loc[df["is_closed"]==True].drop(columns=["is_closed"]).reset_index(drop=True)
    # df = df.sort_values(by=["Support", "num_actions"], ascending=False).reset_index(drop=True)

    return df

In [25]:
successful_df_pruned = save_extracted_sequences(successful_result, action_key_mapping, prune=True)
successful_df_all = save_extracted_sequences(successful_result, action_key_mapping, prune=False)
failed_df_pruned = save_extracted_sequences(failed_result, action_key_mapping, prune=True)
failed_df_all = save_extracted_sequences(failed_result, action_key_mapping, prune=False)

In [26]:
successful_df_pruned.to_csv("Results/successful_patterns_pruned.csv", index=False)
successful_df_all.to_csv("Results/successful_patterns_all.csv", index=False)
successful_df_pruned

,Sequence,Decoded_sequence,Actions,Num_actions,Occurs,Accum,Support
0,3,SG,[3],1,36,36,1.000000
1,7,TE,[7],1,36,36,1.000000
2,2 -> 3,QS -> SG,"[2, 3]",2,35,35,0.972222
3,1,TS,[1],1,35,35,0.972222
4,1 -> 2 -> 3,TS -> QS -> SG,"[1, 2, 3]",3,33,33,0.916667
5,4,R_RV+,[4],1,33,33,0.916667
6,3 -> 4,SG -> R_RV+,"[3, 4]",2,31,31,0.861111
7,2 -> 3 -> 4,QS -> SG -> R_RV+,"[2, 3, 4]",3,30,30,0.833333
8,5,R_RC,[5],1,29,29,0.805556
9,1 -> 2 -> 3 -> 4,TS -> QS -> SG -> R_RV+,"[1, 2, 3, 4]",4,23,23,0.638889
10,4 -> 5,R_RV+ -> R_RC,"[4, 5]",2,23,23,0.638889
11,6,AW,[6],1,23,23,0.638889
12,12,NR_RV+,[12],1,21,21,0.583333
13,6 -> 7,AW -> TE,"[6, 7]",2,19,19,0.527778
14,11,NR_RV,[11],1,19,19,0.527778
15,4 -> 12,R_RV+ -> NR_RV+,"[4, 12]",2,18,18,0.500000
16,12 -> 4,NR_RV+ -> R_RV+,"[12, 4]",2,17,17,0.472222
17,10,AW+,[10],1,17,17,0.472222
18,10 -> 7,AW+ -> TE,"[10, 7]",2,16,16,0.444444
19,9,R_RV,[9],1,16,16,0.444444
20,5 -> 10,R_RC -> AW+,"[5, 10]",2,15,15,0.416667
21,5 -> 10 -> 7,R_RC -> AW+ -> TE,"[5, 10, 7]",3,14,14,0.388889
22,9 -> 11,R_RV -> NR_RV,"[9, 11]",2,14,14,0.388889
23,5 -> 4,R_RC -> R_RV+,"[5, 4]",2,14,14,0.388889
24,3 -> 4 -> 5,SG -> R_RV+ -> R_RC,"[3, 4, 5]",3,13,13,0.361111
25,4 -> 12 -> 4,R_RV+ -> NR_RV+ -> R_RV+,"[4, 12, 4]",3,13,13,0.361111
26,4 -> 5 -> 4,R_RV+ -> R_RC -> R_RV+,"[4, 5, 4]",3,13,13,0.361111
27,2 -> 3 -> 4 -> 5,QS -> SG -> R_RV+ -> R_RC,"[2, 3, 4, 5]",4,12,12,0.333333
28,4 -> 6,R_RV+ -> AW,"[4, 6]",2,12,12,0.333333
29,5 -> 6,R_RC -> AW,"[5, 6]",2,12,12,0.333333
30,1 -> 2 -> 3 -> 4 -> 5,TS -> QS -> SG -> R_RV+ -> R_RC,"[1, 2, 3, 4, 5]",5,10,10,0.277778
31,5 -> 6 -> 7,R_RC -> AW -> TE,"[5, 6, 7]",3,10,10,0.277778
32,4 -> 11,R_RV+ -> NR_RV,"[4, 11]",2,10,10,0.277778
33,11 -> 4,NR_RV -> R_RV+,"[11, 4]",2,10,10,0.277778
34,2 -> 3 -> 4 -> 12,QS -> SG -> R_RV+ -> NR_RV+,"[2, 3, 4, 12]",4,9,9,0.250000
35,4 -> 6 -> 7,R_RV+ -> AW -> TE,"[4, 6, 7]",3,9,9,0.250000
36,3 -> 12,SG -> NR_RV+,"[3, 12]",2,9,9,0.250000
37,11 -> 9,NR_RV -> R_RV,"[11, 9]",2,9,9,0.250000
38,14,NR_RC,[14],1,9,9,0.250000
39,4 -> 5 -> 10,R_RV+ -> R_RC -> AW+,"[4, 5, 10]",3,8,8,0.222222
40,4 -> 5 -> 6,R_RV+ -> R_RC -> AW,"[4, 5, 6]",3,8,8,0.222222
41,12 -> 14,NR_RV+ -> NR_RC,"[12, 14]",2,8,8,0.222222
42,12 -> 2,NR_RV+ -> QS,"[12, 2]",2,8,8,0.222222

In [27]:
failed_df_pruned.to_csv("Results/failed_patterns_pruned.csv", index=False)
failed_df_all.to_csv("Results/failed_patterns_all.csv", index=False)
failed_df_pruned

,Sequence,Decoded_sequence,Actions,Num_actions,Occurs,Accum,Support
0,1,TS,[1],1,18,18,1.000000
1,3,SG,[3],1,18,18,1.000000
2,7,TE,[7],1,18,18,1.000000
3,4,R_RV+,[4],1,17,17,0.944444
4,3 -> 4,SG -> R_RV+,"[3, 4]",2,16,16,0.888889
5,2 -> 3,QS -> SG,"[2, 3]",2,16,16,0.888889
6,2 -> 3 -> 4,QS -> SG -> R_RV+,"[2, 3, 4]",3,15,15,0.833333
7,1 -> 2,TS -> QS,"[1, 2]",2,15,15,0.833333
8,5,R_RC,[5],1,14,14,0.777778
9,11,NR_RV,[11],1,13,13,0.722222
10,1 -> 2 -> 3,TS -> QS -> SG,"[1, 2, 3]",3,12,12,0.666667
11,4 -> 11,R_RV+ -> NR_RV,"[4, 11]",2,11,11,0.611111
12,10,AW+,[10],1,11,11,0.611111
13,10 -> 7,AW+ -> TE,"[10, 7]",2,10,10,0.555556
14,4 -> 5,R_RV+ -> R_RC,"[4, 5]",2,10,10,0.555556
15,6,AW,[6],1,10,10,0.555556
16,9,R_RV,[9],1,10,10,0.555556
17,3 -> 4 -> 11,SG -> R_RV+ -> NR_RV,"[3, 4, 11]",3,9,9,0.500000
18,12,NR_RV+,[12],1,9,9,0.500000
19,1 -> 2 -> 3 -> 4,TS -> QS -> SG -> R_RV+,"[1, 2, 3, 4]",4,8,8,0.444444
20,6 -> 7,AW -> TE,"[6, 7]",2,8,8,0.444444
21,5 -> 4,R_RC -> R_RV+,"[5, 4]",2,8,8,0.444444
22,4 -> 12,R_RV+ -> NR_RV+,"[4, 12]",2,7,7,0.388889
23,11 -> 9,NR_RV -> R_RV,"[11, 9]",2,7,7,0.388889
24,12 -> 4,NR_RV+ -> R_RV+,"[12, 4]",2,7,7,0.388889
25,2 -> 3 -> 4 -> 11,QS -> SG -> R_RV+ -> NR_RV,"[2, 3, 4, 11]",4,6,6,0.333333
26,4 -> 5 -> 4,R_RV+ -> R_RC -> R_RV+,"[4, 5, 4]",3,6,6,0.333333
27,4 -> 2 -> 3,R_RV+ -> QS -> SG,"[4, 2, 3]",3,6,6,0.333333
28,4 -> 10,R_RV+ -> AW+,"[4, 10]",2,6,6,0.333333
29,5 -> 10,R_RC -> AW+,"[5, 10]",2,6,6,0.333333
30,3 -> 9,SG -> R_RV,"[3, 9]",2,6,6,0.333333
31,9 -> 5,R_RV -> R_RC,"[9, 5]",2,6,6,0.333333
32,2 -> 3 -> 4 -> 5,QS -> SG -> R_RV+ -> R_RC,"[2, 3, 4, 5]",4,5,5,0.277778
33,4 -> 11 -> 9,R_RV+ -> NR_RV -> R_RV,"[4, 11, 9]",3,5,5,0.277778
34,5 -> 6 -> 7,R_RC -> AW -> TE,"[5, 6, 7]",3,5,5,0.277778
35,4 -> 11 -> 5,R_RV+ -> NR_RV -> R_RC,"[4, 11, 5]",3,5,5,0.277778
36,4 -> 12 -> 4,R_RV+ -> NR_RV+ -> R_RV+,"[4, 12, 4]",3,5,5,0.277778
37,9 -> 11,R_RV -> NR_RV,"[9, 11]",2,5,5,0.277778
38,11 -> 4,NR_RV -> R_RV+,"[11, 4]",2,5,5,0.277778
39,8,QS+,[8],1,5,5,0.277778
40,14,NR_RC,[14],1,5,5,0.277778
41,2 -> 3 -> 4 -> 10 -> 7,QS -> SG -> R_RV+ -> AW+ -> TE,"[2, 3, 4, 10, 7]",5,4,4,0.222222
42,2 -> 3 -> 4 -> 11 -> 4,QS -> SG -> R_RV+ -> NR_RV -> R_RV+,"[2, 3, 4, 11, 4]",5,4,4,0.222222
43,2 -> 3 -> 12 -> 2 -> 3,QS -> SG -> NR_RV+ -> QS -> SG,"[2, 3, 12, 2, 3]",5,4,4,0.222222
44,5 -> 4 -> 12,R_RC -> R_RV+ -> NR_RV+,"[5, 4, 12]",3,4,4,0.222222
45,3 -> 9 -> 11,SG -> R_RV -> NR_RV,"[3, 9, 11]",3,4,4,0.222222
46,5 -> 4 -> 11,R_RC -> R_RV+ -> NR_RV,"[5, 4, 11]",3,4,4,0.222222
47,2 -> 3 -> 9,QS -> SG -> R_RV,"[2, 3, 9]",3,4,4,0.222222
48,5 -> 10 -> 7,R_RC -> AW+ -> TE,"[5, 10, 7]",3,4,4,0.222222
49,11 -> 9 -> 5,NR_RV -> R_RV -> R_RC,"[11, 9, 5]",3,4,4,0.222222
50,12 -> 4 -> 5,NR_RV+ -> R_RV+ -> R_RC,"[12, 4, 5]",3,4,4,0.222222
51,11 -> 2 -> 3,NR_RV -> QS -> SG,"[11, 2, 3]",3,4,4,0.222222
52,15 -> 2 -> 3,N_SG -> QS -> SG,"[15, 2, 3]",3,4,4,0.222222
53,11 -> 14,NR_RV -> NR_RC,"[11, 14]",2,4,4,0.222222
54,12 -> 14,NR_RV+ -> NR_RC,"[12, 14]",2,4,4,0.222222
55,9 -> 12,R_RV -> NR_RV+,"[9, 12]",2,4,4,0.222222
56,14 -> 4,NR_RC -> R_RV+,"[14, 4]",2,4,4,0.222222
57,8 -> 3,QS+ -> SG,"[8, 3]",2,4,4,0.222222

In [28]:
events = []

for _, row in successful_df_pruned.iterrows():
    sequence = row["Decoded_sequence"]
    success_support = row["Support"]
    success_accum = row["Accum"]
    failed_row = failed_df_all[failed_df_all["Decoded_sequence"]==sequence]
    if len(failed_row) == 0:
        failed_support = 0
        failed_accum = 0
    elif len(failed_row) == 1:
        failed_support = failed_row["Support"].values[0]
        failed_accum = failed_row["Accum"].values[0]
    else:
        print(sequence, failed_row)
    events.append({
        "sequence": sequence,
        "successful_support": success_support,
        "successul_accum": success_accum,
        "failed_support": failed_support,
        "failed_accum": failed_accum
    })

for _, row in failed_df_pruned.iterrows():
    sequence = row["Decoded_sequence"]
    failed_support = row["Support"]
    failed_accum = row["Accum"]
    success_row = successful_df_all[successful_df_all["Decoded_sequence"]==sequence]
    
    if len(success_row) == 0:
        success_support = 0
        success_accum = 0
    elif len(success_row) == 1:
        success_support = success_row["Support"].values[0]
        success_accum = success_row["Accum"].values[0]
    else:
        print(sequence, success_row)
    events.append({
        "sequence": sequence,
        "successful_support": success_support,
        "successul_accum": success_accum,
        "failed_support": failed_support,
        "failed_accum": failed_accum
    })

events_df = pd.DataFrame(events)
events_df.drop_duplicates(subset=["sequence"], inplace=True)
events_df = events_df.sort_values(by=["failed_support"], ascending=False).reset_index(drop=True)
events_df.to_csv("Results/patterns_combined.csv", index=False)

In [29]:
events_df

,sequence,successful_support,successul_accum,failed_support,failed_accum
0,SG,1.000000,36,1.000000,18
1,TE,1.000000,36,1.000000,18
2,TS,0.972222,35,1.000000,18
3,R_RV+,0.916667,33,0.944444,17
4,QS -> SG,0.972222,35,0.888889,16
...,...,...,...,...,...
63,TS -> QS -> SG -> R_RV+ -> R_RC,0.277778,10,0.000000,0
64,R_RV+ -> AW -> TE,0.250000,9,0.000000,0
65,QS -> SG -> R_RV+ -> NR_RV+,0.250000,9,0.000000,0
66,R_RV+ -> R_RC -> AW+,0.222222,8,0.000000,0
67,R_RV+ -> R_RC -> AW,0.222222,8,0.000000,0

## Miscelaneous

In [3]:
# successful_sessions = final_answer_df.loc[final_answer_df["answer_match_ratio"]==1.0]
# failed_sessions = final_answer_df.loc[final_answer_df["answer_match_ratio"]<1.0]

successful_transactions = []
failed_transactions = []

for _, row in final_answer_df.iterrows():
    uid = row["uid"]
    topic_num = row["topic_number"]
    session_actions = event_sequences_df.loc[(event_sequences_df["uid"]==uid) & (event_sequences_df["topic_number"]==topic_num)]
    if row["answer_match_ratio"] == 1.0:
        successful_transactions.append(session_actions["event_key"].tolist())
    else:
        failed_transactions.append(session_actions["event_key"].tolist())

In [4]:
successful_transactions_lengths = [int(len(event_seq)) for event_seq in successful_transactions]
sum(successful_transactions_lengths)/len(successful_transactions_lengths)

41.30555555555556

In [5]:
failed_transactions_lengths = [int(len(event_seq)) for event_seq in failed_transactions]
sum(failed_transactions_lengths)/len(failed_transactions_lengths)

42.388888888888886

In [ ]:
from gsppy.gsp import GSP
from prefixspan import PrefixSpan


# transactions = [
#     ["Bread", "Milk"],
#     ["Bread", "Diaper", "Beer", "Eggs"],
#     ["Milk", "Diaper", "Beer", "Coke"],
# ]

# patterns = GSP(successful_transactions).search(min_support=0.3, verbose=True)
# for level, freq_patterns in enumerate(patterns, start=1):
#     print(f"Level {level}: {freq_patterns}")

ps = PrefixSpan(successful_transactions)
patterns = ps.frequent(0.3*len(successful_transactions), closed=True) # all closed patterns occuring even once
patterns = sorted(patterns, reverse=True)
for sup, patt in patterns:
    print(f"{sup}: {' -> '.join(patt)}")

In [19]:
ps = PrefixSpan(failed_transactions)
patterns = ps.frequent(0.3*len(failed_transactions), closed=True) # all closed patterns occuring even once
patterns = sorted(patterns, reverse=True)
for sup, patt in patterns:
    print(f"{sup}: {' -> '.join(patt)}")

18: TS -> TH -> QS -> SG -> R_RV -> AW -> TE
18: TS -> TH -> QF -> R_RV -> AW -> TE
18: TS -> TH -> QF -> QS -> SG -> R_RV -> AW -> TE
18: TS -> TH -> QF -> AW -> TE
17: TS -> TH -> TH -> QS -> SG -> R_RV -> AW -> TE
17: TS -> TH -> TH -> QF -> R_RV -> AW -> TE
17: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> AW -> TE
17: TS -> TH -> TH -> QF -> AW -> TE
17: TS -> TH -> QS -> SG -> R_RV -> R_RV -> AW -> TE
17: TS -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> AW -> TE
17: TS -> TH -> QF -> QF -> R_RV -> AW -> TE
17: TS -> TH -> QF -> QF -> QS -> SG -> R_RV -> AW -> TE
17: TS -> TH -> QF -> QF -> AW -> TE
16: TS -> TH -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
16: TS -> TH -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> AW -> TE
16: TS -> TH -> TH -> QS -> SG -> R_RV -> R_RV -> AW -> TE
16: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
16: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> AW -> TE
16: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> AW -> TE
16: TS -> TH -> TH -> QF -> QF -> QS -> SG -> R_RV -> AW -> TE
16: TS -> TH -> TH -> QF -> QF -> AW -> TE
16: TS -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> AW -> TE
16: TS -> QS -> QS -> SG -> R_RV -> AW -> TE
16: TS -> QF -> TH -> QS -> SG -> R_RV -> AW -> TE
15: TS -> TH -> TH -> QS -> SG -> NR_RV -> AW -> TE
15: TS -> TH -> TH -> QF -> SG -> NR_RV -> AW -> TE
15: TS -> TH -> TH -> QF -> QS -> SG -> NR_RV -> AW -> TE
15: TS -> TH -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> AW -> TE
15: TS -> TH -> TH -> QF -> NR_RV -> AW -> TE
15: TS -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
15: TS -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> NR_RV -> AW -> TE
15: TS -> TH -> QS -> SG -> R_RV -> NR_RV -> AW -> TE
15: TS -> TH -> QS -> QS -> SG -> R_RV -> AW -> TE
15: TS -> TH -> QF -> TH -> QS -> SG -> R_RV -> AW -> TE
15: TS -> TH -> QF -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
15: TS -> TH -> QF -> R_RV -> NR_RV -> AW -> TE
15: TS -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
15: TS -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> NR_RV -> AW -> TE
15: TS -> TH -> QF -> QS -> SG -> R_RV -> NR_RV -> AW -> TE
15: TS -> TH -> QF -> QF -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
15: TS -> TH -> QF -> QF -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
15: TS -> TH -> QF -> QF -> R_RV -> R_RV -> R_RV -> AW -> TE
15: TS -> TH -> QF -> QF -> R_RV -> NR_RV -> AW -> TE
15: TS -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
15: TS -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> AW -> TE
15: TS -> TH -> QF -> QF -> QS -> SG -> NR_RV -> AW -> TE
15: TS -> TH -> QF -> QF -> NR_RV -> AW -> TE
15: TS -> QS -> QS -> SG -> R_RV -> R_RV -> AW -> TE
15: TS -> QS -> QF -> AW -> TE
15: TS -> QF -> TH -> QS -> SG -> R_RV -> R_RV -> AW -> TE
15: TS -> QF -> TH -> QF -> R_RV -> AW -> TE
15: TS -> QF -> TH -> QF -> QS -> SG -> R_RV -> AW -> TE
15: TS -> QF -> TH -> QF -> AW -> TE
15: TS -> QF -> QS -> QS -> SG -> R_RV -> AW -> TE
15: TS -> QF -> QF -> TH -> QS -> SG -> R_RV -> AW -> TE
14: TS -> TH -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
14: TS -> TH -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> NR_RV -> AW -> TE
14: TS -> TH -> TH -> QS -> SG -> R_RV -> R_RC -> AW -> TE
14: TS -> TH -> TH -> QS -> SG -> R_RV -> NR_RV -> AW -> TE
14: TS -> TH -> TH -> QS -> SG -> NR_RV -> R_RV -> AW -> TE
14: TS -> TH -> TH -> QF -> TH -> QS -> SG -> R_RV -> AW -> TE
14: TS -> TH -> TH -> QF -> SG -> QS -> SG -> R_RV -> R_RV -> AW -> TE
14: TS -> TH -> TH -> QF -> SG -> QS -> SG -> R_RV -> AW -> TE
14: TS -> TH -> TH -> QF -> SG -> NR_RV -> R_RV -> AW -> TE
14: TS -> TH -> TH -> QF -> R_RV -> NR_RV -> AW -> TE
14: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
14: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> NR_RV -> AW -> TE
14: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> R_RC -> AW -> TE
14: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> NR_RV -> AW -> TE
14: TS -> TH -> TH -> QF -> QS -> SG -> NR_RV -> R_RV -> AW -> TE
14: TS -> TH -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
14: TS -> TH -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> AW -> TE
14: TS -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
14: TS -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> NR_RV -> R_RV -> AW -> TE
14: TS -> TH -> QS -> SG -> R_RV -> R_RV -> NR_RV -> R_RV -> AW -> TE
14: TS -> TH -> QS -> SG -> R_RV -> NR_RV -> R_RV -> AW -> TE
14: TS -> TH -> QS -> QS -> SG -> R_RV -> R_RV -> AW -> TE
14: TS -> TH -> QS -> QF -> AW -> TE
14: TS -> TH -> QF -> TH -> QS -> SG -> R_RV -> R_RV -> AW -> TE
14: TS -> TH -> QF -> TH -> QF -> QS -> SG -> R_RV -> AW -> TE
14: TS -> TH -> QF -> TH -> QF -> AW -> TE
14: TS -> TH -> QF -> R_RV -> QS -> SG -> R_RV -> R_RV -> AW -> TE
14: TS -> TH -> QF -> R_RV -> QS -> SG -> R_RV -> AW -> TE
14: TS -> TH -> QF -> R_RV -> NR_RV -> R_RV -> AW -> TE
14: TS -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
14: TS -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> NR_RV -> R_RV -> AW -> TE
14: TS -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> NR_RV -> R_RV -> AW -> TE
14: TS -> TH -> QF -> QS -> SG -> R_RV -> NR_RV -> R_RV -> AW -> TE
14: TS -> TH -> QF -> QF -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
14: TS -> TH -> QF -> QF -> R_RV -> R_RV -> R_RV -> NR_RV -> AW -> TE
14: TS -> TH -> QF -> QF -> R_RV -> NR_RV -> R_RV -> AW -> TE
14: TS -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
14: TS -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RC -> AW -> TE
14: TS -> TH -> QF -> QF -> QS -> SG -> R_RV -> NR_RV -> AW -> TE
14: TS -> TH -> QF -> QF -> QS -> SG -> NR_RV -> R_RV -> AW -> TE
14: TS -> QS -> QF -> R_RV -> AW -> TE
14: TS -> QS -> QF -> QS -> SG -> R_RV -> AW -> TE
14: TS -> QF -> TH -> TH -> QS -> SG -> R_RV -> AW -> TE
14: TS -> QF -> TH -> TH -> QF -> R_RV -> AW -> TE
14: TS -> QF -> TH -> TH -> QF -> QS -> SG -> R_RV -> AW -> TE
14: TS -> QF -> TH -> TH -> QF -> AW -> TE
14: TS -> QF -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
14: TS -> QF -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> AW -> TE
14: TS -> QF -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
14: TS -> QF -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> AW -> TE
14: TS -> QF -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> AW -> TE
14: TS -> QF -> TH -> QF -> QF -> QS -> SG -> R_RV -> AW -> TE
14: TS -> QF -> QS -> SG -> R_RV -> QS -> SG -> R_RV -> R_RV -> AW -> TE
14: TS -> QF -> QS -> SG -> R_RV -> QS -> SG -> R_RV -> AW -> TE
14: TS -> QF -> QS -> SG -> QS -> SG -> R_RV -> R_RV -> AW -> TE
14: TS -> QF -> QS -> SG -> QS -> SG -> R_RV -> AW -> TE
14: TS -> QF -> QS -> QS -> SG -> R_RV -> R_RV -> AW -> TE
14: TS -> QF -> QS -> QF -> AW -> TE
14: TS -> QF -> QF -> TH -> QS -> SG -> R_RV -> R_RV -> AW -> TE
14: TS -> QF -> QF -> TH -> QF -> R_RV -> AW -> TE
14: TS -> QF -> QF -> TH -> QF -> QS -> SG -> R_RV -> AW -> TE
14: TS -> QF -> QF -> TH -> QF -> QF -> AW -> TE
14: TS -> QF -> QF -> TH -> QF -> AW -> TE
14: TS -> QF -> QF -> QF -> QS -> SG -> R_RV -> AW -> TE
14: TS -> QF -> QF -> QF -> QF -> AW -> TE
13: TS -> TH -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RC -> AW -> TE
13: TS -> TH -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> NR_RV -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QS -> SG -> R_RV -> R_RV -> R_RC -> AW -> TE
13: TS -> TH -> TH -> QS -> SG -> R_RV -> R_RV -> NR_RV -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QS -> SG -> R_RV -> NR_RV -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QS -> SG -> R_RV -> BC -> R_RV -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QF -> TH -> QS -> SG -> R_RV -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QF -> TH -> QF -> QS -> SG -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QF -> TH -> QF -> AW -> TE
13: TS -> TH -> TH -> QF -> SG -> QF -> AW -> TE
13: TS -> TH -> TH -> QF -> R_RV -> QS -> SG -> R_RV -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QF -> R_RV -> QS -> SG -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RC -> AW -> TE
13: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> NR_RV -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RC -> AW -> TE
13: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> NR_RV -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> NR_RV -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> BC -> R_RV -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QF -> QS -> SG -> QS -> SG -> R_RV -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QF -> QS -> SG -> QS -> SG -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QF -> QS -> QS -> SG -> R_RV -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> TH -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RC -> AW -> TE
13: TS -> TH -> TH -> QF -> QF -> QS -> SG -> R_RV -> NR_RV -> AW -> TE
13: TS -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> NR_RV -> AW -> TE
13: TS -> TH -> QS -> QF -> R_RV -> AW -> TE
13: TS -> TH -> QS -> QF -> QS -> SG -> R_RV -> AW -> TE
13: TS -> TH -> QF -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> TH -> QF -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> TH -> QF -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> TH -> QF -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> TH -> QF -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> AW -> TE
13: TS -> TH -> QF -> TH -> QF -> QF -> QS -> SG -> R_RV -> AW -> TE
13: TS -> TH -> QF -> TH -> QF -> QF -> AW -> TE
13: TS -> TH -> QF -> R_RV -> R_RV -> R_RV -> R_RV -> NR_RV -> AW -> TE
13: TS -> TH -> QF -> R_RV -> R_RV -> QS -> SG -> R_RV -> R_RV -> AW -> TE
13: TS -> TH -> QF -> R_RV -> R_RV -> QS -> SG -> R_RV -> AW -> TE
13: TS -> TH -> QF -> R_RV -> QF -> AW -> TE
13: TS -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> NR_RV -> AW -> TE
13: TS -> TH -> QF -> QS -> SG -> R_RV -> QS -> SG -> R_RV -> R_RV -> AW -> TE
13: TS -> TH -> QF -> QS -> SG -> R_RV -> QS -> SG -> R_RV -> AW -> TE
13: TS -> TH -> QF -> QF -> TH -> QS -> SG -> R_RV -> AW -> TE
13: TS -> TH -> QF -> QF -> R_RV -> R_RV -> R_RV -> R_RV -> NR_RV -> AW -> TE
13: TS -> TH -> QF -> QF -> R_RV -> R_RV -> R_RV -> NR_RV -> R_RV -> AW -> TE
13: TS -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> NR_RV -> AW -> TE
13: TS -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> R_RC -> AW -> TE
13: TS -> TH -> QF -> QF -> QS -> SG -> R_RV -> NR_RV -> R_RV -> AW -> TE
13: TS -> TH -> QF -> QF -> QF -> QS -> SG -> R_RV -> AW -> TE
13: TS -> TH -> QF -> QF -> QF -> AW -> TE
13: TS -> QS -> TH -> QS -> SG -> R_RV -> AW -> TE
13: TS -> QS -> QF -> QS -> SG -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> TH -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> TH -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> TH -> TH -> QS -> SG -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> TH -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> TH -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> TH -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> TH -> QS -> SG -> R_RV -> R_RC -> AW -> TE
13: TS -> QF -> TH -> QS -> SG -> NR_RV -> AW -> TE
13: TS -> QF -> TH -> QF -> TH -> QS -> SG -> R_RV -> AW -> TE
13: TS -> QF -> TH -> QF -> TH -> QF -> QS -> SG -> R_RV -> AW -> TE
13: TS -> QF -> TH -> QF -> TH -> QF -> AW -> TE
13: TS -> QF -> TH -> QF -> SG -> NR_RV -> AW -> TE
13: TS -> QF -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> TH -> QF -> QS -> SG -> R_RV -> R_RC -> AW -> TE
13: TS -> QF -> TH -> QF -> QS -> SG -> NR_RV -> AW -> TE
13: TS -> QF -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> TH -> QF -> NR_RV -> AW -> TE
13: TS -> QF -> QS -> SG -> R_RV -> R_RV -> QS -> SG -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> QS -> SG -> R_RV -> R_RV -> QS -> SG -> R_RV -> AW -> TE
13: TS -> QF -> QS -> SG -> R_RV -> QF -> AW -> TE
13: TS -> QF -> QS -> SG -> QF -> AW -> TE
13: TS -> QF -> QS -> QF -> R_RV -> AW -> TE
13: TS -> QF -> QS -> QF -> QS -> SG -> R_RV -> AW -> TE
13: TS -> QF -> QF -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> QF -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> QF -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> QF -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> QF -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> QF -> TH -> QF -> QF -> QS -> SG -> R_RV -> AW -> TE
13: TS -> QF -> QF -> R_RV -> QS -> SG -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> QF -> R_RV -> QS -> SG -> R_RV -> AW -> TE
13: TS -> QF -> QF -> QS -> SG -> QS -> SG -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> QF -> QS -> SG -> QS -> SG -> R_RV -> AW -> TE
13: TS -> QF -> QF -> QS -> QS -> SG -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> AW -> TE
13: TS -> QF -> QF -> QF -> QF -> R_RV -> AW -> TE
13: TS -> QF -> QF -> QF -> QF -> QS -> SG -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RC -> AW -> TE
12: TS -> TH -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> NR_RV -> AW -> TE
12: TS -> TH -> TH -> QS -> SG -> R_RV -> R_RV -> BC -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QS -> SG -> NR_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QS -> SG -> NR_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QS -> SG -> NR_RV -> NR_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> SG -> QF -> QS -> SG -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> SG -> NR_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> SG -> NR_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> SG -> NR_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> SG -> NR_RV -> NR_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> R_RV -> R_RV -> QS -> SG -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> R_RV -> R_RV -> QS -> SG -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> R_RV -> QF -> AW -> TE
12: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RC -> AW -> TE
12: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> NR_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> BC -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> QS -> SG -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> QS -> SG -> R_RV -> QS -> SG -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> QS -> SG -> QF -> AW -> TE
12: TS -> TH -> TH -> QF -> QS -> SG -> NR_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> QS -> SG -> NR_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> QS -> SG -> NR_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> QS -> SG -> NR_RV -> NR_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> QS -> QF -> AW -> TE
12: TS -> TH -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> NR_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> R_RC -> AW -> TE
12: TS -> TH -> TH -> QF -> QF -> QS -> SG -> R_RV -> NR_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> QF -> QS -> SG -> NR_RV -> R_RV -> AW -> TE
12: TS -> TH -> TH -> QF -> QF -> QF -> AW -> TE
12: TS -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> NR_RV -> R_RV -> AW -> TE
12: TS -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> NR_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> QS -> SG -> R_RV -> R_RV -> NR_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> QS -> SG -> R_RV -> NR_RV -> NR_RV -> AW -> TE
12: TS -> TH -> QS -> SG -> R_RV -> AW -> AW -> TE
12: TS -> TH -> QS -> QF -> QS -> SG -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> QF -> TH -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> QF -> TH -> QS -> SG -> R_RV -> R_RC -> AW -> TE
12: TS -> TH -> QF -> TH -> QS -> SG -> NR_RV -> AW -> TE
12: TS -> TH -> QF -> TH -> QF -> TH -> QS -> SG -> R_RV -> AW -> TE
12: TS -> TH -> QF -> TH -> QF -> TH -> QF -> QS -> SG -> R_RV -> AW -> TE
12: TS -> TH -> QF -> TH -> QF -> TH -> QF -> AW -> TE
12: TS -> TH -> QF -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> QF -> TH -> QF -> QS -> SG -> R_RV -> R_RC -> AW -> TE
12: TS -> TH -> QF -> TH -> QF -> QS -> SG -> NR_RV -> AW -> TE
12: TS -> TH -> QF -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> QF -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> QF -> TH -> QF -> QF -> QS -> SG -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> QF -> R_RV -> R_RV -> R_RV -> R_RV -> NR_RV -> R_RV -> AW -> TE
12: TS -> TH -> QF -> R_RV -> QF -> R_RV -> AW -> TE
12: TS -> TH -> QF -> R_RV -> QF -> QS -> SG -> R_RV -> AW -> TE
12: TS -> TH -> QF -> R_RV -> NR_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> QF -> R_RV -> NR_RV -> NR_RV -> AW -> TE
12: TS -> TH -> QF -> R_RV -> AW -> AW -> TE
12: TS -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> R_RV -> NR_RV -> R_RV -> AW -> TE
12: TS -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> R_RV -> NR_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> QS -> SG -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> QS -> SG -> R_RV -> AW -> TE
12: TS -> TH -> QF -> QS -> SG -> R_RV -> R_RV -> NR_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> QF -> QS -> SG -> R_RV -> QF -> AW -> TE
12: TS -> TH -> QF -> QS -> SG -> R_RV -> NR_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> QF -> QS -> SG -> R_RV -> NR_RV -> NR_RV -> AW -> TE
12: TS -> TH -> QF -> QS -> SG -> R_RV -> AW -> AW -> TE
12: TS -> TH -> QF -> QF -> TH -> QS -> SG -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> QF -> QF -> TH -> QF -> QS -> SG -> R_RV -> AW -> TE
12: TS -> TH -> QF -> QF -> TH -> QF -> QF -> AW -> TE
12: TS -> TH -> QF -> QF -> TH -> QF -> AW -> TE
12: TS -> TH -> QF -> QF -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> R_RV -> AW -> TE
12: TS -> TH -> QF -> QF -> R_RV -> R_RV -> R_RV -> R_RV -> NR_RV -> R_RV -> AW -> TE