In [4]:
import json
import pandas as pd
import glob

In [ ]:
# global topic number: g<grade>t<topic_num>

def assign_topic_number(uid, topic_num):
    if int(uid) <=  8 or int(uid) >= 17:
        grade = "3"
    return "g"+grade+"t"+str(topic_num)

In [5]:
def get_query_actions(log_entries):
    query_actions = []
    for entry in log_entries:
        if entry["type"] == "querySubmitted":
            query_actions.append([entry["uid"], entry["actual_topic_number"], entry["rawQuery"], "UserFormulated", entry["timestamp"]])
        elif entry["type"] == "choseAutoCompleteSuggestion":
            query_actions.append([entry["uid"], entry["actual_topic_number"], entry["selectedSuggestion"], "AutoCompleteSuggestion", entry["timestamp"]])
        elif entry["type"] == "clickedDidYouMeanSuggestion":
            query_actions.append([int(entry["uid"]), entry["actual_topic_number"], entry["suggested query"], "QueryCorrection", entry["timestamp"]])
        elif entry["type"] == "taskQuestionHelpClicked":
            query_actions.append([int(entry["uid"]), entry["actual_topic_number"], None, "TaskQuestionHelp", entry["timestamp"]])


    query_actions_df = pd.DataFrame(query_actions, columns = ["uid", "topic_number", "query", "query_source", "timestamp"])
    return query_actions_df

In [ ]:
def get_generated_serps(log_entries):
    generated_serps = []
    for entry in log_entries:
        if entry["type"] == "searchResultGenerated":
            generated_serps.append([int(entry["uid"]), entry["actual_topic_number"], entry["query"], entry["url"], entry["title"], entry["snippet"], entry["rank"], entry["page"], entry["timestamp"]])
        elif entry["type"] == "searchNoResults":
            generated_serps.append([int(entry["uid"]), entry["actual_topic_number"], entry["query"], None, None, None, None, None, entry["timestamp"]])

    generated_serp_df = pd.DataFrame(generated_serps, columns = ["uid", "topic_number", "query", "url", "title", "snippet", "page_rank", "page_number", "timestamp"])
    return generated_serp_df

In [7]:
def get_clicked_results(log_entries):
    clicked_results = []
    for entry in log_entries:
        if entry["type"] == "clickedResult":
            clicked_results.append([int(entry["uid"]), entry["actual_topic_number"], entry["query"], entry["url"], entry["rank"], entry["page"], entry["timestamp"]])

    clicked_results_df = pd.DataFrame(clicked_results, columns = ["uid", "topic_number", "query", "url", "page_rank", "page_number", "timestamp"])
    return clicked_results_df

In [8]:
query_actions_df = pd.DataFrame() 
generated_serp_df = pd.DataFrame()
clicked_results_df = pd.DataFrame()

for file_name in glob.glob("Data/trial/*.log"):
    # print(file_name)
    with open(file_name, 'r') as f:
        result = [json.loads(x) for x in f.readlines()]
    
    # query actions
    query_temp_df = get_query_actions(result)
    query_actions_df = pd.concat([query_actions_df, query_temp_df], ignore_index=True)

    # SERPs generated
    serp_temp_df = get_generated_serps(result)
    generated_serp_df = pd.concat([generated_serp_df, serp_temp_df], ignore_index=True)

    # Clicked results
    clicked_temp_df = get_clicked_results(result)
    clicked_results_df = pd.concat([clicked_results_df, clicked_temp_df], ignore_index=True)

In [9]:
generated_serp_df.head()

,uid,topic_number,query,url,title,snippet,page_rank,page_number,timestamp
0,10,3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.focusjunior.it/scienza/spazio/stel...,10 cose (+3) che forse non sai sulle stelle - ...,"\n Informazioni scientifiche, miti e ...",1,1,2026-05-19T10:44:36.488
1,10,3,Quali sono i nomi di altre 3 galassie oltre la...,https://123stella.astronomiamo.it/Fase.aspx?Ar...,Cosa sono le galassie - 123Stella,"\n Oct 19, 2015 ... IL NOME DELLA VIA...",2,1,2026-05-19T10:44:36.489
2,10,3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.castfvg.it/galassie/gruppo_locale/...,Il Gruppo Locale,\n Le altre galassie del gruppo di M ...,3,1,2026-05-19T10:44:36.491
3,10,3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.focusjunior.it/content/uploads/sit...,"SP ""Aldo Moro"" - Focus Junior","\n May 30, 2016 ... Le stelle sono og...",4,1,2026-05-19T10:44:36.492
4,10,3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.focusjunior.it/scienza/spazio/mari...,Mari spaziali: come sono gli oceani sugli altr...,"\n Giusta distanza dal Sole, gravità,...",5,1,2026-05-19T10:44:36.493

### Exploring data

In [7]:
query_actions_df

,uid,topic_number,query,query_source,timestamp
0,10,3,Quali sono i nomi di altre 3 galassie oltre la...,UserFormulated,2026-05-19T10:44:35.207
1,10,2,qual è,AutoCompleteSuggestion,2026-05-19T10:53:50.940
2,10,2,qual'è stato il primo animale nello spazio,AutoCompleteSuggestion,2026-05-19T10:55:02.986
3,10,2,qual'è stato il primo animale nello spazio e c...,UserFormulated,2026-05-19T10:55:57.938
4,10,1,Come si chiamano i satelliti maggiori di Giove,UserFormulated,2026-05-19T11:02:08.749
5,10,1,Come si chiamano i satelliti maggiori di Giove,UserFormulated,2026-05-19T11:04:29.983
6,2,3,Quali sono i animali dall'India,UserFormulated,2026-05-19T14:50:22.081
7,2,3,Quali sono i 5 animali tipici dall'India,UserFormulated,2026-05-19T14:51:20.189
8,2,2,Qual è il nome del simbolo al centro della ban...,UserFormulated,2026-05-19T15:05:41.521
9,2,2,Qual è il nome del simbolo al centro della b...,UserFormulated,2026-05-19T15:09:06.317
10,2,1,Come si chiama il fiume sacro agli indiani,UserFormulated,2026-05-19T15:14:10.201
11,5,1,Come si chiama il fiume,UserFormulated,2026-05-19T14:50:30.668
12,5,1,come si chiama il fiume sacro agli indianischen,AutoCompleteSuggestion,2026-05-19T14:52:30.697
13,5,1,come si chiama il fiume sacro agli indianischen,UserFormulated,2026-05-19T14:52:33.886
14,5,1,come si chiama il fiume sacro agli indianischen,UserFormulated,2026-05-19T14:52:45.184
15,5,1,come si chiama il fiume sacro agli indiani,AutoCompleteSuggestion,2026-05-19T14:52:56.688
16,5,1,come si chiama il fiume sacro agli indiani,UserFormulated,2026-05-19T14:52:58.725
17,5,1,come si chiama il fiume sacro agli indiani,UserFormulated,2026-05-19T14:54:34.881
18,5,3,Qali sono 5 animali tipici dell india,UserFormulated,2026-05-19T15:01:42.366
19,5,3,Qali sono 5 animali tipici dell india,UserFormulated,2026-05-19T15:01:46.525
20,5,3,Qali sono 5 animali tipici dell india,UserFormulated,2026-05-19T15:01:56.495
21,5,3,Quali sono 5 animali tipici dell india,UserFormulated,2026-05-19T15:02:30.582
22,5,3,,UserFormulated,2026-05-19T15:05:12.374
23,5,3,,UserFormulated,2026-05-19T15:06:34.504
24,5,3,Quali sono 5 animali tipici dell india,UserFormulated,2026-05-19T15:08:15.219
25,5,2,,UserFormulated,2026-05-19T15:14:19.389
26,5,2,Qal e il,UserFormulated,2026-05-19T15:15:42.116
27,5,2,Qual eil simbolo della bandiera india,UserFormulated,2026-05-19T15:19:12.025
28,5,2,Qual eil simbolo della bandiera india,UserFormulated,2026-05-19T15:20:59.385
29,5,2,Bandiera,UserFormulated,2026-05-19T15:21:16.565
30,9,2,Quale è il primo animale nello spazio e come s...,UserFormulated,2026-05-19T10:43:38.559
31,9,1,Come si chiamano i satteliti maggiori di Giove,UserFormulated,2026-05-19T10:52:20.605
32,9,1,Come si chiamano i satelliti maggiori di Giove,UserFormulated,2026-05-19T10:55:54.544
33,9,3,Quali sono i nomi di altre 3 galassie oltre la...,UserFormulated,2026-05-19T11:02:48.217
34,9,3,3 galassie oly,UserFormulated,2026-05-19T11:09:40.426
35,9,3,3 galassie oltre la nostra,UserFormulated,2026-05-19T11:09:50.595

In [8]:
list(query_actions_df["uid"].unique())

['10', '2', '5', '9']

In [9]:
user_topics = pd.read_csv("Data/user_topics.csv")
user_topics = user_topics[["uid", "topic1_question", "topic2_question", "topic3_question"]]
user_topics = user_topics.rename(columns={"topic1_question": "topic1", "topic2_question": "topic2", "topic3_question": "topic3"})
user_topics = user_topics.astype({"uid":"str"})
user_topics.dtypes

uid       object
topic1    object
topic2    object
topic3    object
dtype: object

In [10]:
selected_user_topics = user_topics.loc[user_topics["uid"].isin(list(query_actions_df["uid"].unique()))]

In [11]:
for uid, topic_num in zip(query_actions_df["uid"], query_actions_df["topic_number"]):
    prompt = user_topics.loc[user_topics["uid"]==uid]["topic"+str(topic_num)]
    print(prompt.values[0])

Quali sono i nomi di altre 3 galassie oltre la nostra?
Qual è stato il primo animale nello spazio e come si chiamava?
Qual è stato il primo animale nello spazio e come si chiamava?
Qual è stato il primo animale nello spazio e come si chiamava?
Come si chiamano i satelliti maggiori di Giove?
Come si chiamano i satelliti maggiori di Giove?
Quali sono 5 animali tipici dell'India?
Quali sono 5 animali tipici dell'India?
Qual è il nome del simbolo al centro della bandiera dell'India, e che cosa rappresenta?
Qual è il nome del simbolo al centro della bandiera dell'India, e che cosa rappresenta?
Come si chiama il fiume sacro agli indiani?
Come si chiama il fiume sacro agli indiani?
Come si chiama il fiume sacro agli indiani?
Come si chiama il fiume sacro agli indiani?
Come si chiama il fiume sacro agli indiani?
Come si chiama il fiume sacro agli indiani?
Come si chiama il fiume sacro agli indiani?
Come si chiama il fiume sacro agli indiani?
Quali sono 5 animali tipici dell'India?
Quali sono 5 animali tipici dell'India?
Quali sono 5 animali tipici dell'India?
Quali sono 5 animali tipici dell'India?
Quali sono 5 animali tipici dell'India?
Quali sono 5 animali tipici dell'India?
Quali sono 5 animali tipici dell'India?
Qual è il nome del simbolo al centro della bandiera dell'India, e che cosa rappresenta?
Qual è il nome del simbolo al centro della bandiera dell'India, e che cosa rappresenta?
Qual è il nome del simbolo al centro della bandiera dell'India, e che cosa rappresenta?
Qual è il nome del simbolo al centro della bandiera dell'India, e che cosa rappresenta?
Qual è il nome del simbolo al centro della bandiera dell'India, e che cosa rappresenta?
Qual è stato il primo animale nello spazio e come si chiamava?
Come si chiamano i satelliti maggiori di Giove?
Come si chiamano i satelliti maggiori di Giove?
Quali sono i nomi di altre 3 galassie oltre la nostra?
Quali sono i nomi di altre 3 galassie oltre la nostra?
Quali sono i nomi di altre 3 galassie oltre la nostra?

In [12]:
query_actions_df["prompt"] = [user_topics.loc[user_topics["uid"]==uid]["topic"+str(topic_num)].values[0] for uid, topic_num in zip(query_actions_df["uid"], query_actions_df["topic_number"])]
query_actions_df

,uid,topic_number,query,query_source,timestamp,prompt
0,10,3,Quali sono i nomi di altre 3 galassie oltre la...,UserFormulated,2026-05-19T10:44:35.207,Quali sono i nomi di altre 3 galassie oltre la...
1,10,2,qual è,AutoCompleteSuggestion,2026-05-19T10:53:50.940,Qual è stato il primo animale nello spazio e c...
2,10,2,qual'è stato il primo animale nello spazio,AutoCompleteSuggestion,2026-05-19T10:55:02.986,Qual è stato il primo animale nello spazio e c...
3,10,2,qual'è stato il primo animale nello spazio e c...,UserFormulated,2026-05-19T10:55:57.938,Qual è stato il primo animale nello spazio e c...
4,10,1,Come si chiamano i satelliti maggiori di Giove,UserFormulated,2026-05-19T11:02:08.749,Come si chiamano i satelliti maggiori di Giove?
5,10,1,Come si chiamano i satelliti maggiori di Giove,UserFormulated,2026-05-19T11:04:29.983,Come si chiamano i satelliti maggiori di Giove?
6,2,3,Quali sono i animali dall'India,UserFormulated,2026-05-19T14:50:22.081,Quali sono 5 animali tipici dell'India?
7,2,3,Quali sono i 5 animali tipici dall'India,UserFormulated,2026-05-19T14:51:20.189,Quali sono 5 animali tipici dell'India?
8,2,2,Qual è il nome del simbolo al centro della ban...,UserFormulated,2026-05-19T15:05:41.521,Qual è il nome del simbolo al centro della ban...
9,2,2,Qual è il nome del simbolo al centro della b...,UserFormulated,2026-05-19T15:09:06.317,Qual è il nome del simbolo al centro della ban...
10,2,1,Come si chiama il fiume sacro agli indiani,UserFormulated,2026-05-19T15:14:10.201,Come si chiama il fiume sacro agli indiani?
11,5,1,Come si chiama il fiume,UserFormulated,2026-05-19T14:50:30.668,Come si chiama il fiume sacro agli indiani?
12,5,1,come si chiama il fiume sacro agli indianischen,AutoCompleteSuggestion,2026-05-19T14:52:30.697,Come si chiama il fiume sacro agli indiani?
13,5,1,come si chiama il fiume sacro agli indianischen,UserFormulated,2026-05-19T14:52:33.886,Come si chiama il fiume sacro agli indiani?
14,5,1,come si chiama il fiume sacro agli indianischen,UserFormulated,2026-05-19T14:52:45.184,Come si chiama il fiume sacro agli indiani?
15,5,1,come si chiama il fiume sacro agli indiani,AutoCompleteSuggestion,2026-05-19T14:52:56.688,Come si chiama il fiume sacro agli indiani?
16,5,1,come si chiama il fiume sacro agli indiani,UserFormulated,2026-05-19T14:52:58.725,Come si chiama il fiume sacro agli indiani?
17,5,1,come si chiama il fiume sacro agli indiani,UserFormulated,2026-05-19T14:54:34.881,Come si chiama il fiume sacro agli indiani?
18,5,3,Qali sono 5 animali tipici dell india,UserFormulated,2026-05-19T15:01:42.366,Quali sono 5 animali tipici dell'India?
19,5,3,Qali sono 5 animali tipici dell india,UserFormulated,2026-05-19T15:01:46.525,Quali sono 5 animali tipici dell'India?
20,5,3,Qali sono 5 animali tipici dell india,UserFormulated,2026-05-19T15:01:56.495,Quali sono 5 animali tipici dell'India?
21,5,3,Quali sono 5 animali tipici dell india,UserFormulated,2026-05-19T15:02:30.582,Quali sono 5 animali tipici dell'India?
22,5,3,,UserFormulated,2026-05-19T15:05:12.374,Quali sono 5 animali tipici dell'India?
23,5,3,,UserFormulated,2026-05-19T15:06:34.504,Quali sono 5 animali tipici dell'India?
24,5,3,Quali sono 5 animali tipici dell india,UserFormulated,2026-05-19T15:08:15.219,Quali sono 5 animali tipici dell'India?
25,5,2,,UserFormulated,2026-05-19T15:14:19.389,Qual è il nome del simbolo al centro della ban...
26,5,2,Qal e il,UserFormulated,2026-05-19T15:15:42.116,Qual è il nome del simbolo al centro della ban...
27,5,2,Qual eil simbolo della bandiera india,UserFormulated,2026-05-19T15:19:12.025,Qual è il nome del simbolo al centro della ban...
28,5,2,Qual eil simbolo della bandiera india,UserFormulated,2026-05-19T15:20:59.385,Qual è il nome del simbolo al centro della ban...
29,5,2,Bandiera,UserFormulated,2026-05-19T15:21:16.565,Qual è il nome del simbolo al centro della ban...
30,9,2,Quale è il primo animale nello spazio e come s...,UserFormulated,2026-05-19T10:43:38.559,Qual è stato il primo animale nello spazio e c...
31,9,1,Come si chiamano i satteliti maggiori di Giove,UserFormulated,2026-05-19T10:52:20.605,Come si chiamano i satelliti maggiori di Giove?
32,9,1,Come si chiamano i satelliti maggiori di Giove,UserFormulated,2026-05-19T10:55:54.544,Come si chiamano i satelliti maggiori di Giove?
33,9,3,Quali sono i nomi di altre 3 galassie oltre la...,UserFormulated,2026-05-19T11:02:48.217,Quali sono i nomi di altre 3 galassie oltre la...
34,9,3,3 galassie oly,UserFormulated,2026-05-19T11:09:40.426,Quali sono i nomi di altre 3 galassie oltre la...
35,9,3,3 galassie oltre la nostra,UserFormulated,2026-05-19T11:09:50.595,Quali sono i nomi di altre 3 galassie oltre la...

In [13]:
query_actions_df["query_source"].value_counts()

query_source
UserFormulated            32
AutoCompleteSuggestion     4
Name: count, dtype: int64

In [14]:
clicked_results_df

,uid,topic_number,query,url,page_rank,page_number,timestamp
0,10,3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.focusjunior.it/news/i-musei-scient...,10,1,2026-05-19T10:45:07.398
1,10,3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.focusjunior.it/scienza/spazio/stel...,1,1,2026-05-19T10:46:34.863
2,10,3,Quali sono i nomi di altre 3 galassie oltre la...,https://123stella.astronomiamo.it/Fase.aspx?Ar...,2,1,2026-05-19T10:47:32.166
3,10,3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.castfvg.it/galassie/gruppo_locale/...,3,1,2026-05-19T10:48:27.880
4,10,2,qual'è stato il primo animale nello spazio e c...,https://www.storicang.it/foto-del-giorno/laika...,1,1,2026-05-19T10:56:19.184
5,10,2,qual'è stato il primo animale nello spazio e c...,https://www.storicang.it/foto-del-giorno/laika...,1,1,2026-05-19T10:57:54.624
6,2,3,Quali sono i 5 animali tipici dall'India,https://wwftravel.it/blog/viaggi/india-natura-...,1,1,2026-05-19T14:52:53.759
7,2,2,Qual è il nome del simbolo al centro della b...,https://sullestradedelmondo.it/bandiera-indiana/,3,1,2026-05-19T15:09:25.575
8,2,1,Come si chiama il fiume sacro agli indiani,https://www.consciousjourneys.com/it/approfond...,1,1,2026-05-19T15:14:18.095
9,5,3,Quali sono 5 animali tipici dell india,https://www.terreincognitemagazine.it/natura-s...,2,1,2026-05-19T15:08:18.588
10,5,2,Qual eil simbolo della bandiera india,https://sullestradedelmondo.it/bandiera-indiana/,1,1,2026-05-19T15:19:29.861
11,9,2,Quale è il primo animale nello spazio e come s...,https://www.focusjunior.it/scienza/spazio/laik...,2,1,2026-05-19T10:43:58.958
12,9,2,Quale è il primo animale nello spazio e come s...,https://www.nationalgeographic.it/spazio/2021/...,3,1,2026-05-19T10:44:41.360
13,9,2,Quale è il primo animale nello spazio e come s...,https://www.focusjunior.it/scienza/spazio/stel...,6,1,2026-05-19T10:45:32.387
14,9,2,Quale è il primo animale nello spazio e come s...,https://www.storicang.it/foto-del-giorno/laika...,1,1,2026-05-19T10:46:16.185
15,9,2,Quale è il primo animale nello spazio e come s...,https://www.focusjunior.it/scienza/spazio/laik...,2,1,2026-05-19T10:46:57.627
16,9,1,Come si chiamano i satteliti maggiori di Giove,https://www.astronomitaly.com/blog/astronomy-p...,1,1,2026-05-19T10:52:26.337
17,9,1,Come si chiamano i satteliti maggiori di Giove,https://www.astronomitaly.com/blog/astronomy-p...,1,1,2026-05-19T10:52:26.495
18,9,1,Come si chiamano i satteliti maggiori di Giove,https://starwalk.space/it/news/jupiter-galilea...,2,1,2026-05-19T10:53:18.182
19,9,1,Come si chiamano i satteliti maggiori di Giove,https://edu.inaf.it/astrofoto/giove-satelliti-...,3,1,2026-05-19T10:53:42.819
20,9,1,Come si chiamano i satteliti maggiori di Giove,https://www.focusjunior.it/news/news-e-curiosi...,4,1,2026-05-19T10:54:25.155
21,9,1,Come si chiamano i satelliti maggiori di Giove,https://www.astronomitaly.com/blog/astronomy-p...,1,1,2026-05-19T10:56:01.873
22,9,1,Come si chiamano i satelliti maggiori di Giove,https://www.astronomitaly.com/blog/astronomy-p...,1,1,2026-05-19T10:56:39.796
23,9,1,Come si chiamano i satelliti maggiori di Giove,https://www.focusjunior.it/news/lallineamento-...,5,1,2026-05-19T10:57:32.698
24,9,1,Come si chiamano i satelliti maggiori di Giove,https://edu.inaf.it/astrofoto/giove-satelliti-...,3,1,2026-05-19T10:58:05.587
25,9,1,Come si chiamano i satelliti maggiori di Giove,https://www.astronomitaly.com/blog/astronomy-p...,1,1,2026-05-19T10:58:48.575
26,9,3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.focusjunior.it/scienza/spazio/stel...,1,1,2026-05-19T11:03:22.373
27,9,3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.castfvg.it/galassie/gruppo_locale/...,3,1,2026-05-19T11:04:28.011
28,9,3,Quali sono i nomi di altre 3 galassie oltre la...,https://123stella.astronomiamo.it/Fase.aspx?Ar...,2,1,2026-05-19T11:04:55.643
29,9,3,Quali sono i nomi di altre 3 galassie oltre la...,https://123stella.astronomiamo.it/Fase.aspx?Ar...,2,1,2026-05-19T11:05:22.754
30,9,3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.castfvg.it/galassie/gruppo_locale/...,3,1,2026-05-19T11:05:36.905
31,9,3,Quali sono i nomi di altre 3 galassie oltre la...,https://123stella.astronomiamo.it/Fase.aspx?Ar...,2,1,2026-05-19T11:06:07.472
32,9,3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.focusjunior.it/content/uploads/sit...,4,1,2026-05-19T11:07:15.094
33,9,3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.focusjunior.it/scienza/spazio/stel...,1,1,2026-05-19T11:07:20.975
34,9,3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.focusjunior.it/content/uploads/sit...,4,1,2026-05-19T11:08:14.999
35,9,3,3 galassie oltre la nostra,https://www.focusjunior.it/scienza/spazio/univ...,7,1,2026-05-19T11:10:14.279
36,9,3,3 galassie oltre la nostra,https://www.castfvg.it/galassie/gruppo_locale/...,5,1,2026-05-19T11:11:43.196
37,9,3,3 galassie oltre la nostra,https://www.focusjunior.it/scienza/spazio/stel...,9,1,2026-05-19T11:12:12.633
38,9,3,3 galassie oltre la nostra,https://spaziotempo.altervista.org/gruppo-locale/,7,1,2026-05-19T11:14:04.823
39,9,3,3 galassie oltre la nostra,https://www.media.inaf.it/2014/03/12/un-consig...,1,1,2026-05-19T11:15:07.153
40,9,3,3 galassie oltre la nostra,https://www.focus.it/scienza/spazio/hubble-nel...,4,1,2026-05-19T11:15:22.861
41,9,3,3 galassie oltre la nostra,https://www.focus.it/scienza/spazio/la-via-lat...,2,1,2026-05-19T11:15:39.675
42,9,3,3 galassie oltre la nostra,https://www.focusjunior.it/scienza/spazio/stel...,9,1,2026-05-19T11:16:17.601
43,9,3,3 galassie oltre la nostra,https://www.focusjunior.it/scienza/spazio/stel...,9,1,2026-05-19T11:16:30.795

In [15]:
clicked_results_df["page_number"].value_counts()

page_number
1    44
Name: count, dtype: int64

In [16]:
print(generated_serp_df.loc[generated_serp_df["uid"]==5])

     uid topic_number                    query  \
71     5            1  Come si chiama il fiume
72     5            1  Come si chiama il fiume
73     5            1  Come si chiama il fiume
74     5            1  Come si chiama il fiume
75     5            1  Come si chiama il fiume
..   ...          ...                      ...
147    5            2                 Bandiera
148    5            2                 Bandiera
149    5            2                 Bandiera
150    5            2                 Bandiera
151    5            2                 Bandiera

                                                   url  \
71   https://www.goasia.it/la-religione-gange-fiume...
72   https://www.focusjunior.it/scuola/storia/dove-...
73   https://www.beyondthetrip.net/2019/04/03/fiume...
74   https://www.consciousjourneys.com/it/approfond...
75   https://isha.sadhguru.org/mahashivratri/it/shi...
..                                                 ...
147  https://www.focusjunior.it/news/perche-nelle-p...
148  https://www.focusjunior.it/scuola/storia/unita...
149  https://www.focusjunior.it/scuola/geografia/qu...
150   https://sullestradedelmondo.it/bandiera-indiana/
151  https://www.focusjunior.it/news/news-e-curiosi...

                                                 title  \
71   La religione e il Gange, il fiume sacro dell'I...
72   Dove si trova la Mesopotamia di preciso? - Foc...
73   Fiume Gange: tutte le informazioni e le curios...
74   Gange, il fiume sacro agli indù e alla popolaz...
75   Shiva e il Gange - La Leggenda e il suo Signif...
..                                                 ...
147  Perché nelle proteste in Nepal compare la band...
148  Italia | Ecco alcuni fatti storici che devi co...
149  Bandiere del mondo: 10 curiosità che forse non...
150  Bandiera Indiana: significato, storia e curiosità
151  Come sarà la bandiera di Marte? Ecco le ipotes...

                                               snippet page_rank page_number  \
71   \n          ... si dice possa curare anche i m...         1           1
72   \n          Mar 4, 2025 ... ... si chiama più ...         2           1
73   \n          Apr 3, 2019 ... Gli indù lo venera...         3           1
74   \n          le famose scalinate che scendono s...         4           1
75   \n          Come sappiamo molte culture si son...         5           1
..                                                 ...       ...         ...
147  \n          Sep 16, 2025 ... La bandiera di On...         6           1
148  \n          Nov 7, 2016 ... Vi siete mai chies...         7           1
149  \n          La bandiera russa trae ispirazione...         8           1
150  \n          May 21, 2022 ... La bandiera india...         9           1
151  \n          Dec 18, 2025 ... Anche Marte avrà ...        10           1

                   timestamp
71   2026-05-19T14:50:32.173
72   2026-05-19T14:50:32.175
73   2026-05-19T14:50:32.180
74   2026-05-19T14:50:32.181
75   2026-05-19T14:50:32.183
..                       ...
147  2026-05-19T15:21:18.073
148  2026-05-19T15:21:18.075
149  2026-05-19T15:21:18.081
150  2026-05-19T15:21:18.083
151  2026-05-19T15:21:18.084

[81 rows x 9 columns]

In [17]:
generated_serp_df.loc[generated_serp_df["uid"]==5].to_csv("Data/u5_SERPS.csv", index=False)

In [25]:
generated_serp_df.loc[generated_serp_df["page_rank"].isin(["1", None])]

,uid,topic_number,query,url,title,snippet,page_rank,page_number,timestamp
0,10,3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.focusjunior.it/scienza/spazio/stel...,10 cose (+3) che forse non sai sulle stelle - ...,"\n Informazioni scientifiche, miti e ...",1,1,2026-05-19T10:44:36.488
10,10,2,qual'è stato il primo animale nello spazio e c...,https://www.storicang.it/foto-del-giorno/laika...,"Laika, il primo animale nello spazio - Storica...","\n Nov 3, 2022 ... È probabilmente la...",1,1,2026-05-19T10:55:58.959
20,10,1,Come si chiamano i satelliti maggiori di Giove,https://www.astronomitaly.com/blog/astronomy-p...,"Io, Europa, Ganimede e Callisto: guida ai 4 sa...","\n Mar 19, 2024 ... Io, Europa, Ganim...",1,1,2026-05-19T11:02:09.754
26,10,1,Come si chiamano i satelliti maggiori di Giove,https://www.astronomitaly.com/blog/astronomy-p...,"Io, Europa, Ganimede e Callisto: guida ai 4 sa...","\n Mar 19, 2024 ... Io, Europa, Ganim...",1,1,2026-05-19T11:04:31.470
32,2,3,Quali sono i animali dall'India,https://www.focusjunior.it/scuola/storia/il-pi...,Chi ha inventato il pigiama? - FocusJunior.it,\n Ma quali sono le sue origini? DAL ...,1,1,2026-05-19T14:50:23.230
42,2,3,Quali sono i 5 animali tipici dall'India,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1,1,2026-05-19T14:51:21.413
52,2,2,Qual è il nome del simbolo al centro della ban...,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... ... e le interazi...",1,1,2026-05-19T15:05:43.123
58,2,2,Qual è il nome del simbolo al centro della b...,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1,1,2026-05-19T15:09:07.969
64,2,1,Come si chiama il fiume sacro agli indiani,https://www.consciousjourneys.com/it/approfond...,"Gange, il fiume sacro agli indù e alla popolaz...","\n È altresì importante per la pesca,...",1,1,2026-05-19T15:14:11.974
71,5,1,Come si chiama il fiume,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n ... si dice possa curare anche i m...,1,1,2026-05-19T14:50:32.173
81,5,1,come si chiama il fiume sacro agli indianischen,None,None,None,None,None,2026-05-19T14:52:35.518
82,5,1,come si chiama il fiume sacro agli indianischen,None,None,None,None,None,2026-05-19T14:52:46.904
83,5,1,come si chiama il fiume sacro agli indiani,https://www.consciousjourneys.com/it/approfond...,"Gange, il fiume sacro agli indù e alla popolaz...","\n È altresì importante per la pesca,...",1,1,2026-05-19T14:53:00.313
90,5,1,come si chiama il fiume sacro agli indiani,https://www.consciousjourneys.com/it/approfond...,"Gange, il fiume sacro agli indù e alla popolaz...","\n È altresì importante per la pesca,...",1,1,2026-05-19T14:54:36.969
97,5,3,Qali sono 5 animali tipici dell india,None,None,None,None,None,2026-05-19T15:01:44.186
98,5,3,Qali sono 5 animali tipici dell india,None,None,None,None,None,2026-05-19T15:01:47.876
99,5,3,Qali sono 5 animali tipici dell india,None,None,None,None,None,2026-05-19T15:01:58.337
100,5,3,Quali sono 5 animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1,1,2026-05-19T15:02:31.643
110,5,3,Quali sono 5 animali tipici dell india,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1,1,2026-05-19T15:03:04.692
120,5,2,Qal e il,None,None,None,None,None,2026-05-19T15:15:44.081
121,5,2,Qual eil simbolo della bandiera india,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... I 24 raggi della ...",1,1,2026-05-19T15:19:13.407
131,5,2,Qual eil simbolo della bandiera india,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... I 24 raggi della ...",1,1,2026-05-19T15:21:01.262
141,5,2,Qal e il,None,None,None,None,None,2026-05-19T15:21:02.658
142,5,2,Bandiera,https://www.focusjunior.it/scienza/ambiente/ch...,Che cos'è la Bandiera Blu? - FocusJunior.it,\n In altre parole la Bandiera Blu in...,1,1,2026-05-19T15:21:18.057
152,9,2,Quale è il primo animale nello spazio e come s...,https://www.storicang.it/foto-del-giorno/laika...,"Laika, il primo animale nello spazio - Storica...","\n Nov 3, 2022 ... È probabilmente la...",1,1,2026-05-19T10:43:39.628
162,9,1,Come si chiamano i satteliti maggiori di Giove,https://www.astronomitaly.com/blog/astronomy-p...,"Io, Europa, Ganimede e Callisto: guida ai 4 sa...","\n Mar 19, 2024 ... ... dei Medici, e...",1,1,2026-05-19T10:52:22.321
168,9,1,Come si chiamano i satteliti maggiori di Giove,https://www.astronomitaly.com/blog/astronomy-p...,"Io, Europa, Ganimede e Callisto: guida ai 4 sa...","\n Mar 19, 2024 ... ... dei Medici, e...",1,1,2026-05-19T10:53:13.348
174,9,1,Come si chiamano i satelliti maggiori di Giove,https://www.astronomitaly.com/blog/astronomy-p...,"Io, Europa, Ganimede e Callisto: guida ai 4 sa...","\n Mar 19, 2024 ... Io, Europa, Ganim...",1,1,2026-05-19T10:55:55.513
180,9,3,Quali sono i nomi di altre 3 galassie oltre la...,https://www.focusjunior.it/scienza/spazio/stel...,10 cose (+3) che forse non sai sulle stelle - ...,"\n Informazioni scientifiche, miti e ...",1,1,2026-05-19T11:02:49.295
190,9,3,3 galassie oly,None,None,None,None,None,2026-05-19T11:09:41.822
191,9,3,3 galassie oltre la nostra,https://www.media.inaf.it/2014/03/12/un-consig...,Un Consiglio dei Giganti per il Gruppo Locale ...,"\n Mar 12, 2014 ... “Tutte le galassi...",1,1,2026-05-19T11:09:51.577