In [ ]:
import pandas as pd
import json
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
query_df = pd.read_csv("Data/query_formulation_df.csv")
query_df.head(10)

,uid,tid,serp_id,query,precision@10
0,17,g3t3,serp1,Quali sono i 5 animali tipici del india,0.5
1,18,g3t2,serp10,Quale il nome del simbolo al centro della band...,0.3
2,15,g4t2,serp100,Qual è stato il primo animale nello spazio e c...,0.0
3,15,g4t2,serp101,Qual è stato il primo animale nello spazio e c...,0.0
4,15,g4t2,serp102,Qual è stato il primo animale nello spazio e c...,0.0
5,15,g4t3,serp104,Quali sono i nomi di altre 3 galassie oltre la...,0.1
6,15,g4t3,serp105,Quali sono i nomi di altre 3 galassie oltre la...,0.1
7,15,g4t3,serp107,Nomi di altre galassie,0.1
8,15,g4t1,serp108,Come si chiamano i satelliti maggiori di Giove,0.2
9,16,g4t1,serp109,Come si chiamano i satelliti d,0.4

In [ ]:
ineffective_queries = query_df.loc[query_df["precision@10"]<0.8]
effective_queries = query_df.loc[query_df["precision@10"]<0.8]

,uid,tid,serp_id,query,precision@10
0,17,g3t3,serp1,Quali sono i 5 animali tipici del india,0.5
1,18,g3t2,serp10,Quale il nome del simbolo al centro della band...,0.3
2,15,g4t2,serp100,Qual è stato il primo animale nello spazio e c...,0.0
3,15,g4t2,serp101,Qual è stato il primo animale nello spazio e c...,0.0
4,15,g4t2,serp102,Qual è stato il primo animale nello spazio e c...,0.0

In [ ]:
import spacy
nlp = spacy.load("it_core_news_sm")
for query in