In [ ]:
import json
import pandas as pd
import glob
import numpy as np
import driver

In [ ]:
query_df = pd.DataFrame()
query_actions_df = pd.DataFrame() 
serp_df = pd.DataFrame()
clicked_results_df = pd.DataFrame()

for file_name in glob.glob("Data/3rd/*_FULL.log"):
    # print(file_name)
    with open(file_name, 'r') as f:
        result = [json.loads(x) for x in f.readlines()]
    
    # query actions
    query_temp_df = driver.get_queries(result)
    query_df = pd.concat([query_df, query_temp_df], ignore_index=True)

    # query actions
    query_actions_temp_df = driver.get_query_actions(result)
    query_actions_df = pd.concat([query_actions_df, query_actions_temp_df], ignore_index=True)

    # SERPs generated
    serp_temp_df = driver.get_generated_serps(result)
    serp_df = pd.concat([serp_df, serp_temp_df], ignore_index=True)

    # Clicked results
    clicked_results_temp_df = driver.get_clicked_results(result)
    clicked_results_df = pd.concat([clicked_results_df, clicked_results_temp_df], ignore_index=True)

for file_name in glob.glob("Data/4th/*_FULL.log"):
    # print(file_name)
    with open(file_name, 'r') as f:
        result = [json.loads(x) for x in f.readlines()]
    
    # query actions
    query_temp_df = driver.get_queries(result)
    query_df = pd.concat([query_df, query_temp_df], ignore_index=True)

    # query actions
    query_actions_temp_df = driver.get_query_actions(result)
    query_actions_df = pd.concat([query_actions_df, query_actions_temp_df], ignore_index=True)

    # SERPs generated
    serp_temp_df = driver.get_generated_serps(result)
    serp_df = pd.concat([serp_df, serp_temp_df], ignore_index=True)

    # Clicked results
    clicked_results_temp_df = driver.get_clicked_results(result)
    clicked_results_df = pd.concat([clicked_results_df, clicked_results_temp_df], ignore_index=True)


## assigning qid
query_df["qid"] = ["q"+str(i) for i in range(1, len(query_df)+1)]
query_df = query_df[["uid", "topic_number", "qid", "query", "timestamp"]]


## assigning serp id
serp_num = 0
serp_id_list = []

for _, row in serp_df.iterrows():
    if row["rank"]==1 or pd.isna(row["rank"]):
        serp_num += 1
    serp_id_list.append("serp"+str(serp_num))

serp_df["serp_id"] = serp_id_list
serp_df = serp_df[["uid", "topic_number", "query", "serp_id", "url", "title", "snippet", "rank", "timestamp"]]

In [120]:
query_df.head()

,uid,topic_number,qid,query,timestamp
0,17,g3t3,q1,Quali sono i 5 animali tipici del india,2026-05-19T14:50:53.443
1,17,g3t2,q2,Quale il simbolo del la bandiera del india,2026-05-19T15:00:09.059
2,17,g3t2,q3,qual e la bandiera dell india,2026-05-19T15:07:43.639
3,17,g3t2,q4,Quale ilsimbolo al centro della bandiera dell ...,2026-05-19T15:12:24.264
4,17,g3t1,q5,Il nome del fiume sacro,2026-05-19T15:26:21.050

In [121]:
serp_df.head()

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
0,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19T14:50:54.636
1,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.terreincognitemagazine.it/natura-s...,"Natura selvaggia in India, tra tigri e leoni -...","\n Feb 17, 2017 ... O dei Giganti, vi...",2.0,2026-05-19T14:50:54.638
2,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://animalia.bio/it/india-animals,India - Animalia,"\n Flora e fauna ... L'India, ufficia...",3.0,2026-05-19T14:50:54.640
3,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.focusjunior.it/news/news-e-curiosi...,Quali sono gli sport più seguiti e praticati a...,"\n Il cricket è seguito da circa 2,5 ...",4.0,2026-05-19T14:50:54.644
4,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://www.goasia.it/geografia-natura-e-clima...,"Geografia, natura e clima dell'India - Go Asia",\n Molteplici varietà di animali sono...,5.0,2026-05-19T14:50:54.645

In [122]:
serp_df.loc[serp_df["rank"].isna()]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
267,5,g3t1,come si chiama il fiume sacro agli indianischen,serp33,None,None,None,NaN,2026-05-19T14:52:35.518
268,5,g3t1,come si chiama il fiume sacro agli indianischen,serp34,None,None,None,NaN,2026-05-19T14:52:46.904
283,5,g3t3,Qali sono 5 animali tipici dell india,serp37,None,None,None,NaN,2026-05-19T15:01:44.186
284,5,g3t3,Qali sono 5 animali tipici dell india,serp38,None,None,None,NaN,2026-05-19T15:01:47.876
285,5,g3t3,Qali sono 5 animali tipici dell india,serp39,None,None,None,NaN,2026-05-19T15:01:58.337
306,5,g3t2,Qal e il,serp42,None,None,None,NaN,2026-05-19T15:15:44.081
327,5,g3t2,Qal e il,serp45,None,None,None,NaN,2026-05-19T15:21:02.658
451,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp61,None,None,None,NaN,2026-05-19T15:04:52.511
452,8,g3t2,Come si chiama il nome dell disegno nell centr...,serp62,None,None,None,NaN,2026-05-19T15:05:05.152
453,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp63,None,None,None,NaN,2026-05-19T15:08:36.757
454,8,g3t2,Come si chiama il nome del disegno nel centro ...,serp64,None,None,None,NaN,2026-05-19T15:09:48.390
642,12,g4t3,3 galassie olt4e la nostra,serp84,None,None,None,NaN,2026-05-19T11:16:50.790
643,12,g4t3,3 galassie olt4e la nostra,serp85,None,None,None,NaN,2026-05-19T11:16:54.735
809,15,g4t3,qualifiche f1,serp102,None,None,None,NaN,2026-05-19T10:55:32.846
831,15,g4t3,Nomi di alre galassie,serp105,None,None,None,NaN,2026-05-19T11:06:11.428
951,9,g4t3,3 galassie oly,serp120,None,None,None,NaN,2026-05-19T11:09:41.822

In [123]:
df = pd.DataFrame(serp_df.loc[(serp_df["rank"]==1)|(serp_df["rank"].isna())].groupby(["uid", "topic_number"])["query"].value_counts()).reset_index()
df.loc[df["count"]>1]

    uid topic_number                                              query  count
13    4         g3t2  Che cosa rappresenta l'imagine del simbolo ban...      3
14    4         g3t2                        Quale il simbolo dell'India      2
16    5         g3t1         come si chiama il fiume sacro agli indiani      2
17    5         g3t1    come si chiama il fiume sacro agli indianischen      2
19    5         g3t2                                           Qal e il      2
20    5         g3t2              Qual eil simbolo della bandiera india      2
22    5         g3t3              Qali sono 5 animali tipici dell india      3
23    5         g3t3             Quali sono 5 animali tipici dell india      2
25    6         g3t2                              Simbolo andiera India      2
31    7         g3t2           il simbolo della baniera dell dell'india      2
33    8         g3t1                                  Fiume sacro India      2
34    8         g3t2  Come si chiama il nome dell disegno nell centr...      2
39    8         g3t3                    Quali sono 5 animali dell India      2
41    9         g4t1     Come si chiamano i satteliti maggiori di Giove      2
47   10         g4t1    Come  si chiamano i satelliti maggiori di Giove      2
59   12         g4t3                         3 galassie olt4e la nostra      2
67   14         g4t1              come si chiamano i satelliti di giove      2
76   15         g4t2  Qual è stato il primo animale nello spazio e c...      2
82   16         g4t1    Come si chiamano i satelliti  maggiori di Giove      2
85   16         g4t3  Quali sono altre nomi di tre galassie in oltre...      2
88   17         g3t2         Quale il simbolo del la bandiera del india      2
91   17         g3t3            Quali sono i 5 animali tipici del india      2

In [124]:
q_df = pd.DataFrame(query_df.groupby(["uid", "topic_number"])["query"].value_counts()).reset_index()
q_df.loc[q_df["count"]>1]

    uid topic_number                                              query  count
13    4         g3t2  Che cosa rappresenta l'imagine del simbolo ban...      2
14    4         g3t2                        Quale il simbolo dell'India      2
16    5         g3t1         come si chiama il fiume sacro agli indiani      2
17    5         g3t1    come si chiama il fiume sacro agli indianischen      2
19    5         g3t2              Qual eil simbolo della bandiera india      2
22    5         g3t3              Qali sono 5 animali tipici dell india      3
23    5         g3t3             Quali sono 5 animali tipici dell india      2
29    7         g3t2           il simbolo della baniera dell dell'india      2
31    8         g3t1                                  Fiume sacro India      2
32    8         g3t2  Come si chiama il nome dell disegno nell centr...      2
45   10         g4t1    Come  si chiamano i satelliti maggiori di Giove      2
49   11         g4t2  Qual è stato il primo animale nello spazio e c...      2
57   12         g4t3                         3 galassie olt4e la nostra      2
74   15         g4t2  Qual è stato il primo animale nello spazio e c...      3
75   15         g4t3  Quali sono i nomi di altre 3 galassie oltre la...      2
79   16         g4t1    Come si chiamano i satelliti  maggiori di Giove      2
82   16         g4t3  Quali sono altre nomi di tre galassie in oltre...      2

In [125]:
q_df.loc[q_df["count"]==3]["query"].tolist()

['Qali sono 5 animali tipici dell india',
 'Qual è stato il primo animale nello spazio e come si chiamava']

In [126]:
query_df.loc[query_df["uid"]==15]

,uid,topic_number,qid,query,timestamp
91,15,g4t2,q92,Qual è stato il primo animale nello spazio e c...,2026-05-19T10:44:45.385
92,15,g4t2,q93,Qual è stato il primo animale nello spazio e c...,2026-05-19T10:46:43.174
93,15,g4t2,q94,Qual è stato il primo animale nello spazio e c...,2026-05-19T10:51:12.928
94,15,g4t3,q95,qualifiche f1,2026-05-19T10:55:31.771
95,15,g4t3,q96,Quali sono i nomi di altre 3 galassie oltre la...,2026-05-19T10:57:32.254
96,15,g4t3,q97,Quali sono i nomi di altre 3 galassie oltre la...,2026-05-19T11:03:56.641
97,15,g4t3,q98,Quali sono i nomi di altre 3 galassie oltre la...,2026-05-19T11:04:18.615
98,15,g4t3,q99,Nomi di alre galassie,2026-05-19T11:06:09.998
99,15,g4t1,q100,Come si chiamano i satelliti maggiori di Giove,2026-05-19T11:15:45.762

In [127]:
serp_df["uid"].unique()

array([17, 18,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16,
        9])

In [128]:
query_df.loc[query_df["uid"]==4]

,uid,topic_number,qid,query,timestamp
22,4,g3t2,q23,Che cosa rappresenta l'imagine del simbolo ban...,2026-05-19T14:54:57.981
23,4,g3t2,q24,Che cosa rappresenta l'imagine del simbolo ban...,2026-05-19T14:59:35.687
24,4,g3t2,q25,Quale il simbolo dell'India,2026-05-19T15:03:52.949
25,4,g3t2,q26,Quale il simbolo dell'India,2026-05-19T15:05:57.147
26,4,g3t3,q27,5 animali tipici dell'India,2026-05-19T15:14:08.813
27,4,g3t1,q28,Fiume sacro indiano,2026-05-19T15:20:20.872

In [129]:
serp_df.loc[(serp_df["uid"]==4) & (serp_df["query"]=="Che cosa rappresenta l'imagine del simbolo banderia dell'India")]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
178,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19T14:54:59.384
179,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... La storia della b...",2.0,2026-05-19T14:54:59.386
180,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focus.it/ambiente/animali/8-cose-c...,8 cose che (forse) non sai sulle vacche sacre ...,"\n Mar 31, 2019 ... Per molti indù, c...",3.0,2026-05-19T14:54:59.387
181,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focusjunior.it/news/holi-festival-...,"Holi festival, la festa dei colori - FocusJuni...","\n Mar 23, 2024 ... Si chiama Holi ed...",4.0,2026-05-19T14:54:59.392
182,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focusjunior.it/scuola/geografia/le...,Quali sono le 10 Nazioni più popolate del mond...,"\n Apr 16, 2017 ... Il Pakistan , che...",5.0,2026-05-19T14:54:59.394
183,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focusjunior.it/scuola/geografia/10...,10 cose che (forse) non sai sull'Europa - Focu...,"\n Dal nome, alla bandiera passando p...",6.0,2026-05-19T14:54:59.396
184,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://it.gov-civ-guarda.pt/flag-india,"Bandiera dell'India | Storia, design e signifi...",\n ... simbolo distintivo che potesse...,7.0,2026-05-19T14:54:59.398
185,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focusjunior.it/news/plogging-corre...,"Plogging, cos'è e perché aiuta il pianeta - Fo...",\n L'amore per l'ambiente ha portato ...,8.0,2026-05-19T14:54:59.399
186,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focusjunior.it/scuola/storia/rivol...,"Rivoluzione: quando il popolo si ribella, la s...","\n May 20, 2019 ... Il 22 settembre 1...",9.0,2026-05-19T14:54:59.401
187,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focusjunior.it/scuola/storia/chi-s...,Chi sono i curdi? - FocusJunior.it,"\n La bandiera curda, che oggi svento...",10.0,2026-05-19T14:54:59.403
188,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19T14:59:37.155
189,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... La storia della b...",2.0,2026-05-19T14:59:37.157
190,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://www.focus.it/ambiente/animali/8-cose-c...,8 cose che (forse) non sai sulle vacche sacre ...,"\n Mar 31, 2019 ... Per molti indù, c...",3.0,2026-05-19T14:59:37.160
191,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://www.focusjunior.it/news/holi-festival-...,"Holi festival, la festa dei colori - FocusJuni...","\n Mar 23, 2024 ... Si chiama Holi ed...",4.0,2026-05-19T14:59:37.162
192,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://www.focusjunior.it/scuola/geografia/le...,Quali sono le 10 Nazioni più popolate del mond...,"\n Apr 16, 2017 ... Il Pakistan , che...",5.0,2026-05-19T14:59:37.165
193,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://www.focusjunior.it/scuola/geografia/10...,10 cose che (forse) non sai sull'Europa - Focu...,"\n Dal nome, alla bandiera passando p...",6.0,2026-05-19T14:59:37.173
194,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://it.gov-civ-guarda.pt/flag-india,"Bandiera dell'India | Storia, design e signifi...",\n ... simbolo distintivo che potesse...,7.0,2026-05-19T14:59:37.175
195,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://www.focusjunior.it/news/plogging-corre...,"Plogging, cos'è e perché aiuta il pianeta - Fo...",\n L'amore per l'ambiente ha portato ...,8.0,2026-05-19T14:59:37.178
196,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://www.focusjunior.it/scuola/storia/rivol...,"Rivoluzione: quando il popolo si ribella, la s...","\n May 20, 2019 ... Il 22 settembre 1...",9.0,2026-05-19T14:59:37.180
197,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp26,https://www.focusjunior.it/scuola/storia/chi-s...,Chi sono i curdi? - FocusJunior.it,"\n La bandiera curda, che oggi svento...",10.0,2026-05-19T14:59:37.182
218,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19T15:10:33.501
219,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... La storia della b...",2.0,2026-05-19T15:10:33.507
220,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://www.focus.it/ambiente/animali/8-cose-c...,8 cose che (forse) non sai sulle vacche sacre ...,"\n Mar 31, 2019 ... Per molti indù, c...",3.0,2026-05-19T15:10:33.519
221,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://www.focusjunior.it/news/holi-festival-...,"Holi festival, la festa dei colori - FocusJuni...","\n Mar 23, 2024 ... Si chiama Holi ed...",4.0,2026-05-19T15:10:33.523
222,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://www.focusjunior.it/scuola/geografia/le...,Quali sono le 10 Nazioni più popolate del mond...,"\n Apr 16, 2017 ... Il Pakistan , che...",5.0,2026-05-19T15:10:33.526
223,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://www.focusjunior.it/scuola/geografia/10...,10 cose che (forse) non sai sull'Europa - Focu...,"\n Dal nome, alla bandiera passando p...",6.0,2026-05-19T15:10:33.530
224,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://it.gov-civ-guarda.pt/flag-india,"Bandiera dell'India | Storia, design e signifi...",\n ... simbolo distintivo che potesse...,7.0,2026-05-19T15:10:33.535
225,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://www.focusjunior.it/news/plogging-corre...,"Plogging, cos'è e perché aiuta il pianeta - Fo...",\n L'amore per l'ambiente ha portato ...,8.0,2026-05-19T15:10:33.540
226,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://www.focusjunior.it/scuola/storia/rivol...,"Rivoluzione: quando il popolo si ribella, la s...","\n May 20, 2019 ... Il 22 settembre 1...",9.0,2026-05-19T15:10:33.545
227,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp29,https://www.focusjunior.it/scuola/storia/chi-s...,Chi sono i curdi? - FocusJunior.it,"\n La bandiera curda, che oggi svento...",10.0,2026-05-19T15:10:33.551

In [130]:
serp_df.loc[(serp_df["uid"]==4)]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp
178,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... L'elemento più im...",1.0,2026-05-19T14:54:59.384
179,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://sullestradedelmondo.it/bandiera-indiana/,"Bandiera Indiana: significato, storia e curiosità","\n May 21, 2022 ... La storia della b...",2.0,2026-05-19T14:54:59.386
180,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focus.it/ambiente/animali/8-cose-c...,8 cose che (forse) non sai sulle vacche sacre ...,"\n Mar 31, 2019 ... Per molti indù, c...",3.0,2026-05-19T14:54:59.387
181,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focusjunior.it/news/holi-festival-...,"Holi festival, la festa dei colori - FocusJuni...","\n Mar 23, 2024 ... Si chiama Holi ed...",4.0,2026-05-19T14:54:59.392
182,4,g3t2,Che cosa rappresenta l'imagine del simbolo ban...,serp25,https://www.focusjunior.it/scuola/geografia/le...,Quali sono le 10 Nazioni più popolate del mond...,"\n Apr 16, 2017 ... Il Pakistan , che...",5.0,2026-05-19T14:54:59.394
...,...,...,...,...,...,...,...,...,...
252,4,g3t1,Fiume sacro indiano,serp31,https://it.renovables.blog/acqua/il-sacro-fium...,Alla scoperta del Gange: il fiume sacro e inqu...,"\n La sorgente del fiume Gange, noto ...",6.0,2026-05-19T15:20:22.204
253,4,g3t1,Fiume sacro indiano,serp31,https://www.consciousjourneys.com/it/approfond...,"Varanasi, la città sacra per gli induisti sul ...",\n Varanasi è un'importante città ind...,7.0,2026-05-19T15:20:22.204
254,4,g3t1,Fiume sacro indiano,serp31,https://www.cinziamalaguti.it/fiumi-sacri-il-g...,Fiumi sacri: il Gange - Esperienziando Vitae,\n Il Gange scorre nel Nord dell'Indi...,8.0,2026-05-19T15:20:22.205
255,4,g3t1,Fiume sacro indiano,serp31,https://www.skuola.net/geografia-medie/india-d...,"L'India: un viaggio tra cultura, geografia e t...","\n Jun 28, 2014 ... Alla costa indian...",9.0,2026-05-19T15:20:22.206
256,4,g3t1,Fiume sacro indiano,serp31,https://www.focusjunior.it/animali/enciclopedi...,"Il gruccione, poco conosciuto ma davvero bello...","\n Mar 25, 2014 ... ... India e Sri L...",10.0,2026-05-19T15:20:22.207

In [131]:
relevance = pd.read_csv("Data/relevance.csv")
relevance_score = []

for _, row in serp_df.iterrows():
    relevant_docs = relevance.loc[relevance["tid"]==row["topic_number"]]["doc"].tolist()
    if row["url"] in relevant_docs:
        relevance_score.append(1)
    else:
        relevance_score.append(0)

serp_df["relevance_score"] = relevance_score

In [132]:
temp = serp_df.loc[serp_df["rank"]<=10].groupby(["serp_id"])["relevance_score"].sum()/10
df = pd.DataFrame(temp).reset_index()
df.columns = ["serp_id", "precision@10"]

In [133]:
effective_query = df.loc[df["precision@10"]>=0.8]["serp_id"].tolist() # above 3rd quartile

In [134]:
serp_df["effective_query"] = [int(serp_id in effective_query) for serp_id in serp_df["serp_id"]]

In [135]:
serp_df.loc[(serp_df["effective_query"]==0)&((serp_df["rank"]==1) | (serp_df["rank"].isna()))]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,relevance_score,effective_query
0,17,g3t3,Quali sono i 5 animali tipici del india,serp1,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19T14:50:54.636,1,0
10,17,g3t3,Quali sono i 5 animali tipici del india,serp2,https://wwftravel.it/blog/viaggi/india-natura-...,"India naturalistica, 5 animali da non perdere ...","\n Oct 31, 2023 ... La fauna selvatic...",1.0,2026-05-19T14:52:45.059,1,0
20,17,g3t2,Quale il simbolo del la bandiera del india,serp3,https://liceoberchet.edu.it/ricerche/geo4d_03/...,India Britannica,\n Bandiera di stato a terra dal 2 ag...,1.0,2026-05-19T15:00:11.086,1,0
27,17,g3t2,Quale il simbolo del la bandiera del india,serp4,https://liceoberchet.edu.it/ricerche/geo4d_03/...,India Britannica,\n Bandiera di stato a terra dal 2 ag...,1.0,2026-05-19T15:01:27.269,1,0
34,17,g3t2,qual e la bandiera dell india,serp5,https://mastroviaggiatore.it/saree/blog/lindia...,"L'INDIA A COLORI, I COLORI DELL'INDIA - MASTRO...","\n Feb 14, 2025 ... ... le persone e ...",1.0,2026-05-19T15:07:44.856,1,0
...,...,...,...,...,...,...,...,...,...,...,...
929,9,g4t1,Come si chiamano i satteliti maggiori di Giove,serp117,https://www.astronomitaly.com/blog/astronomy-p...,"Io, Europa, Ganimede e Callisto: guida ai 4 sa...","\n Mar 19, 2024 ... ... dei Medici, e...",1.0,2026-05-19T10:53:13.348,0,0
935,9,g4t1,Come si chiamano i satelliti maggiori di Giove,serp118,https://www.astronomitaly.com/blog/astronomy-p...,"Io, Europa, Ganimede e Callisto: guida ai 4 sa...","\n Mar 19, 2024 ... Io, Europa, Ganim...",1.0,2026-05-19T10:55:55.513,0,0
941,9,g4t3,Quali sono i nomi di altre 3 galassie oltre la...,serp119,https://www.focusjunior.it/scienza/spazio/stel...,10 cose (+3) che forse non sai sulle stelle - ...,"\n Informazioni scientifiche, miti e ...",1.0,2026-05-19T11:02:49.295,0,0
951,9,g4t3,3 galassie oly,serp120,None,None,None,NaN,2026-05-19T11:09:41.822,0,0
952,9,g4t3,3 galassie oltre la nostra,serp121,https://www.media.inaf.it/2014/03/12/un-consig...,Un Consiglio dei Giganti per il Gruppo Locale ...,"\n Mar 12, 2014 ... “Tutte le galassi...",1.0,2026-05-19T11:09:51.577,0,0

In [136]:
serp_df.loc[(serp_df["effective_query"]==1)&((serp_df["rank"]==1) | (serp_df["rank"].isna()))]

,uid,topic_number,query,serp_id,url,title,snippet,rank,timestamp,relevance_score,effective_query
247,4,g3t1,Fiume sacro indiano,serp31,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Il Gange è un grande fiume del sub...,1.0,2026-05-19T15:20:22.199,1,1
475,8,g3t1,Fiume sacro India,serp67,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Secondo gli indù questo fiume è sa...,1.0,2026-05-19T15:16:03.549,1,1
485,8,g3t1,Fiume sacro India,serp68,https://www.goasia.it/la-religione-gange-fiume...,"La religione e il Gange, il fiume sacro dell'I...",\n Secondo gli indù questo fiume è sa...,1.0,2026-05-19T15:16:18.583,1,1